package org.opennur.tahsin.ui

import android.speech.SpeechRecognizer

import org.opennur.tahsin.util.AppLanguage

/**
 * Katalog teks UI per bahasa (tanpa resource Android — cukup untuk 2 bahasa).
 * Tambahkan bahasa baru = buat instance baru di [AppStrings.of].
 */
data class Strings(
    val appTitle: String,
    val subtitle: String,
    /** Subjudul portal (layar utama). */
    val homeSubtitle: String,
    /** Label kartu menu "Tahsin" di portal. */
    val menuTahsin: String,
    /** Label kartu menu "Pengaturan" di portal. */
    val menuSettings: String,
    val legendCorrect: String,
    val legendWrong: String,
    val legendReading: String,
    val legendNotReached: String,
    val ayahWord: String,
    val ayahLabel: String,
    val loadingSurah: String,
    val detectedPrefix: String,
    val issueDetected: String,
    val downloadingLabel: String,
    val noTajwidRule: String,
    val issuesTitle: String,
    val micHint: String,
    val listeningHint: String,
    val listen: String,
    val stop: String,
    val playWord: String,
    val settingsTitle: String,
    val settingTajwid: String,
    val settingFlow: String,
    val flowHint: String,
    val settingDarkMode: String,
    val settingLanguage: String,
    val languageNameId: String,
    val languageNameEn: String,
    val sectionAppearance: String,
    val sectionMenu: String,
    val sectionReciter: String,
    val sectionSpeed: String,
    val audioReciterLabel: String,
    val sectionDaily: String,
    val sectionStreakReminder: String,
    val menuStats: String,
    val menuQuiz: String,
    val menuAudio: String,
    val menuDownloadAll: String,
    val swipeHint: String,
    val credit: String,
    val downloadNoticeTitle: String,
    val downloadNoticeBody: String,
    val gotIt: String,
    val bgPromptTitle: String,
    val bgPromptBody: String,
    val bgAllow: String,
    val bgDeny: String,
    val loadingMushaf: String,
    // Pesan ViewModel
    val msgMicPermission: String,
    val msgCheckConnection: String,
    val msgSurahLoadFailed: String,
    val msgMushafLoading: String,
    val msgMushafLoadFailed: String,
    val msgRetry: String,
    val msgAyahDone: String,
    val msgSurahDone: String,
    val msgMurojaahDone: String,
    val msgDownloadFailed: String,
    val msgAudioUnavailable: String,
    val msgWordUnavailable: String,
    val msgDownloadAllPartial: String,
    val msgDownloadAllDone: String,
    // Manajer audio
    val audioManagerTitle: String,
    val audioManagerSubtitle: String,
    val audioStatusComplete: String,
    val audioStatusIncomplete: String,
    val audioMissingNote: String,
    val audioDeleteTitle: String,
    val audioDeleteAllTitle: String,
    val audioDeleteBody: String,
    val audioDeleteAllBody: String,
    val audioCancel: String,
    val audioDelete: String,
    val audioDeleteAll: String,
    val audioBack: String,
    val audioSize: String,
    val audioAyat: String,
    val audioKata: String,
    val audioNoDownload: String,
    val audioDownloadAllCta: String,
    val audioLoading: String,
    // Statistik & riwayat kesalahan
    val statsTitle: String,
    val statsSubtitle: String,
    val statsTotalSessions: String,
    val statsBestScoreLabel: String,
    val statsTotalRounds: String,
    val statsWordsMastered: String,
    val statsTahsinLine: String,
    val statsDreamBigLine: String,
    val statsLughohLine: String,
    val statsVocabLine: String,
    val statsNoData: String,
    val statsLoading: String,
    val statsInline: String,
    // Pencarian ayat
    val searchTitle: String,
    val searchHint: String,
    val searchNoQuery: String,
    val searchIndexing: String,
    val searchSearching: String,
    val searchNoResults: String,
    val searchResultsCount: String,
    // Kuis tajwid
    val quizTitle: String,
    val quizScore: String,
    val quizQuestion: String,
    val quizNext: String,
    val quizCorrect: String,
    val quizWrong: String,
    val quizRuleLabel: String,
    val quizLoading: String,
    val quizNoData: String,
    // Kuis Ayat (Lengkapi Ayat & Tebak Surah)
    val menuAyatQuiz: String,
    val ayatQuizTitle: String,
    val ayatQuizModeComplete: String,
    val ayatQuizModeSurah: String,
    val ayatQuizCompleteQuestion: String,
    val ayatQuizSurahQuestion: String,
    val ayatQuizWrong: String,
    // Kosa kata
    val menuVocab: String,
    // Materi Dream BIG
    val menuDreamBig: String,
    val dreamBigTitle: String,
    val dreamBigSubtitle: String,
    val dreamBigLoading: String,
    val gameBestScore: String,
    val gameQuestionProgress: String,
    val gameScoreLabel: String,
    val gameStreakLabel: String,
    val gameCorrect: String,
    val gameWrong: String,
    val gameNext: String,
    val gameResultTitle: String,
    val gameResultScore: String,
    val gameResultStreak: String,
    val gameRepeat: String,
    val gameStart: String,
    val gameRoundsPlayed: String,
    val gameBackHome: String,
    val vocabTitle: String,
    val vocabSubtitle: String,
    val vocabModeCards: String,
    val vocabModeQuiz: String,
    val vocabFlipHint: String,
    val vocabMeaning: String,
    val vocabRoot: String,
    val vocabExample: String,
    val vocabPlayAudio: String,
    val vocabRemember: String,
    val vocabForgot: String,
    val vocabLearned: String,
    val vocabDue: String,
    val vocabSessionDone: String,
    val vocabStartQuiz: String,
    val vocabEmpty: String,
    val vocabQuizQuestionWord: String,
    val vocabQuizQuestionMeaning: String,
    val vocabQuizScore: String,
    val vocabQuizCorrect: String,
    val vocabQuizWrong: String,
    val vocabQuizNext: String,
    val vocabQuizDone: String,
    val vocabQuizAgain: String,
    val vocabOpenExample: String,
    val vocabAudioUnavailable: String,
    val vocabLoading: String,
    // Belajar Arab (Durusul Lughoh style)
    val menuLughoh: String,
    val lughohSubtitle: String,
    val lughohLoading: String,
    val lughohEmpty: String,
    val lughohStartRandom: String,
    val lughohBestScore: String,
    val lughohSessionsPlayed: String,
    val lughohMaterialTitle: String,
    val lughohSectionMuhadatsah: String,
    val lughohSectionMufrodat: String,
    val lughohSectionQawaid: String,
    val lughohExercisesTitle: String,
    val lughohProgressLabel: String,
    val lughohCheck: String,
    val lughohNext: String,
    val lughohCorrect: String,
    val lughohWrong: String,
    val lughohResultTitle: String,
    val lughohScore: String,
    val lughohRestart: String,
    val lughohBackToHome: String,
    // Penghargaan (badge)
    val menuBadges: String,
    val badgesTitle: String,
    val badgesSubtitle: String,
    val badgesLoading: String,
    val badgesCount: String,
    val badgesLocked: String,
    val badgesEarned: String,
    val badgesTierLabel: String,
    // Gamification header (Home & ringkasan statistik)
    val homeLevelLine: String,
    val homeStreakLine: String,
    val homeBadgeLabel: String,
    val homeGoalLine: String,
    val levelLabel: String,
    // Perayaan gamification
    val celebrateLevelUpTitle: String,
    val celebrateLevelUpBody: String,
    val celebrateStreakTitle: String,
    val celebrateStreakBody: String,
    val celebrateBadgeTitle: String,
    val celebrateBadgeBody: String,
)

object AppStrings {

    fun of(lang: AppLanguage): Strings = when (lang) {
        AppLanguage.ID -> Indonesian
        AppLanguage.EN -> English
    }

    val Indonesian = Strings(
        appTitle = "Tahsin Qur'an",
        subtitle = "Setiap kata dicek langsung.",
        homeSubtitle = "Pilih menu untuk mulai belajar.",
        menuTahsin = "🕌 Tahsin",
        menuSettings = "⚙️ Pengaturan",
        legendCorrect = "benar",
        legendWrong = "salah",
        legendReading = "dibaca",
        legendNotReached = "belum",
        ayahWord = "ayat",
        ayahLabel = "Ayat",
        loadingSurah = "Memuat surah…",
        detectedPrefix = "🎙️ Terdeteksi:",
        issueDetected = "Terdeteksi:",
        downloadingLabel = "Mengunduh audio…",
        noTajwidRule = "Tidak ada aturan tajwid khusus pada kata ini.",
        issuesTitle = "Kesalahan terdeteksi",
        micHint = "Tekan 🎙️\nlalu bacalah",
        listeningHint = "Membaca… tekan ⏹ untuk berhenti",
        listen = "▶ Dengar",
        stop = "⏹ Stop",
        playWord = "▶ Kata",
        settingsTitle = "Pengaturan",
        settingTajwid = "Warna Tajwid",
        settingFlow = "Mode Flow",
        flowHint = "Lanjut otomatis ke ayat berikutnya saat selesai.",
        settingDarkMode = "Mode Gelap",
        settingLanguage = "Bahasa",
        languageNameId = "Indonesia",
        languageNameEn = "Inggris",
        sectionAppearance = "Tampilan",
        sectionMenu = "Menu",
        sectionReciter = "Qari' (Perawi)",
        sectionSpeed = "Kecepatan Audio",
        audioReciterLabel = "Qari'",
        sectionDaily = "Ayat Hari Ini",
        sectionStreakReminder = "Pengingat Streak",
        menuStats = "📊 Statistik",
        menuQuiz = "📝 Kuis",
        menuAudio = "🎵 Kelola Audio",
        menuDownloadAll = "📥 Unduh Semua Audio",
        swipeHint = "Geser layar ke kiri/kanan untuk ganti ayat",
        credit = "Dibuat dengan ❤️ oleh OpenNur Project (FOSS)",
        downloadNoticeTitle = "Mengunduh audio…",
        downloadNoticeBody = "Audio surah ini belum diunduh. Unduhan dimulai otomatis — " +
            "ikuti progres di atas tombol. Bacaan contoh akan diputar setelah unduhan selesai.",
        gotIt = "Mengerti",
        bgPromptTitle = "Unduhan latar belakang?",
        bgPromptBody = "Izinkan unduhan terus berjalan saat layar mati / aplikasi di latar " +
            "belakang? Unduhan besar (mis. Al-Baqarah ≈ 440 MB) bisa gagal kalau tidak.",
        bgAllow = "Izinkan",
        bgDeny = "Tidak, cukup saat aplikasi terbuka",
        loadingMushaf = "Memuat mushaf…",
        msgMicPermission = "Izin mikrofon diperlukan untuk mendeteksi bacaan.",
        msgCheckConnection = "periksa koneksi",
        msgSurahLoadFailed = "Gagal memuat surah",
        msgMushafLoading = "Memuat mushaf…",
        msgMushafLoadFailed = "Gagal memuat mushaf.",
        msgRetry = "🔄 Coba Lagi",
        msgAyahDone = "✅ Ayat selesai — lanjut ke ayat berikutnya",
        msgSurahDone = "✅ Surah selesai — lanjut ke surah berikutnya",
        msgMurojaahDone = "🎉 Selesai muroja'ah — seluruh Al-Qur'an dibaca benar!",
        msgDownloadFailed = "Gagal mengunduh",
        msgAudioUnavailable = "Audio belum tersedia. Cek koneksi lalu coba lagi.",
        msgWordUnavailable = "Audio kata belum tersedia. Cek koneksi lalu coba lagi.",
        msgDownloadAllPartial = "Unduh selesai: %d surah gagal.",
        msgDownloadAllDone = "Semua audio berhasil diunduh ✓",
        audioManagerTitle = "Audio Terunduh",
        audioManagerSubtitle = "Kelola audio yang sudah diunduh per surah.",
        audioStatusComplete = "✓ Lengkap",
        audioStatusIncomplete = "Belum lengkap",
        audioMissingNote = "%d audio tak tersedia di server",
        audioDeleteTitle = "Hapus audio surah ini?",
        audioDeleteAllTitle = "Hapus semua audio?",
        audioDeleteBody = "Audio surah ini akan dihapus dari perangkat.",
        audioDeleteAllBody = "Semua audio terunduh akan dihapus dari perangkat.",
        audioCancel = "Batal",
        audioDelete = "Hapus",
        audioDeleteAll = "Hapus Semua",
        audioBack = "←",
        audioSize = "%d,%.2f MB",
        audioAyat = "Ayat",
        audioKata = "Kata",
        audioNoDownload = "Belum ada audio terunduh. Buka surah dan tekan Dengar untuk mengunduh.",
        audioDownloadAllCta = "📥 Unduh Semua — %s",
        audioLoading = "Memuat audio…",
        statsTitle = "📊 Statistik & Riwayat",
        statsSubtitle = "Ringkasan semua aktivitas belajarmu dalam satu layar.",
        statsTotalSessions = "Total Sesi",
        statsBestScoreLabel = "Skor Terbaik",
        statsTotalRounds = "Total Ronde",
        statsWordsMastered = "Kata Dikuasai",
        statsTahsinLine = "Tahsin: %d percobaan",
        statsDreamBigLine = "Dream BIG: %d ronde • skor terbaik %d/%d",
        statsLughohLine = "Belajar Arab: %d sesi • skor terbaik %d/%d",
        statsVocabLine = "Kosakata: %d kata dikuasai",
        statsNoData = "Belum ada aktivitas. Mulai dari Tahsin, Dream BIG, Belajar Arab, atau Kosakata!",
        statsLoading = "Memuat statistik…",
        statsInline = "📊 %d× dicoba · skor terbaik %d%%",
        searchTitle = "🔍 Cari Ayat",
        searchHint = "Kata Arab / kata kunci terjemahan (ID/EN)…",
        searchNoQuery = "Ketik kata kunci untuk mencari ayat di seluruh Al-Qur'an.",
        searchIndexing = "Menyiapkan indeks pencarian…",
        searchSearching = "Mencari…",
        searchNoResults = "Tidak ada ayat yang cocok.",
        searchResultsCount = "%d hasil",
        quizTitle = "📝 Kuis Tajwid",
        quizScore = "Skor: %d/%d",
        quizQuestion = "Hukum apa pada kata ini?",
        quizNext = "Soal berikutnya →",
        quizCorrect = "✓ Benar!",
        quizWrong = "✗ Belum tepat.",
        quizRuleLabel = "Hukum",
        quizLoading = "Menyiapkan soal…",
        quizNoData = "Gagal menyiapkan soal. Coba lagi.",
        menuAyatQuiz = "🎯 Kuis Ayat",
        ayatQuizTitle = "🎯 Kuis Ayat",
        ayatQuizModeComplete = "Lengkapi Ayat",
        ayatQuizModeSurah = "Tebak Surah",
        ayatQuizCompleteQuestion = "Kata mana yang melengkapi ayat ini?",
        ayatQuizSurahQuestion = "Ayat ini dari surah apa?",
        ayatQuizWrong = "✗ Belum tepat. Jawabannya: %s",
        menuVocab = "📖 Kosakata",
        menuDreamBig = "🎬 Dream BIG",
        dreamBigTitle = "🎬 Dream BIG",
        dreamBigSubtitle = "Kuis kosakata Qur'an acak — main terus, kejar skor terbaikmu!",
        dreamBigLoading = "Memuat game…",
        gameBestScore = "Skor terbaik: %d/%d",
        gameQuestionProgress = "Soal %d/%d",
        gameScoreLabel = "Skor %d",
        gameStreakLabel = "🔥 %d",
        gameCorrect = "✓ Benar!",
        gameWrong = "✗ Belum tepat.",
        gameNext = "Soal berikutnya →",
        gameResultTitle = "Ronde selesai",
        gameResultScore = "Skor: %d/%d",
        gameResultStreak = "Streak terbaik: %d",
        gameRepeat = "🔄 Main Lagi",
        gameStart = "▶ Main",
        gameRoundsPlayed = "Ronde dimainkan: %d",
        gameBackHome = "← Kembali",
        vocabTitle = "📖 Kosakata",
        vocabSubtitle = "Kata-kata terpenting Al-Qur'an — diurutkan dari yang paling sering muncul.",
        vocabModeCards = "📇 Kartu",
        vocabModeQuiz = "📝 Kuis",
        vocabFlipHint = "Ketuk kartu untuk melihat arti.",
        vocabMeaning = "Arti",
        vocabRoot = "Akar",
        vocabExample = "Contoh ayat",
        vocabPlayAudio = "▶ Dengar",
        vocabRemember = "✓ Ingat",
        vocabForgot = "✗ Lupa",
        vocabLearned = "%d kata dikuasai",
        vocabDue = "%d untuk diulang",
        vocabSessionDone = "Sesi kartu selesai ✓",
        vocabStartQuiz = "Coba Kuis",
        vocabEmpty = "Belum ada kata untuk dipelajari. Kembali lagi nanti — atau coba Kuis!",
        vocabQuizQuestionWord = "Apa arti kata ini?",
        vocabQuizQuestionMeaning = "Kata mana yang artinya:",
        vocabQuizScore = "Skor: %d/%d",
        vocabQuizCorrect = "✓ Benar!",
        vocabQuizWrong = "✗ Belum tepat. Jawabannya: %s",
        vocabQuizNext = "Lanjut →",
        vocabQuizDone = "Kuis selesai! Skor: %d/%d",
        vocabQuizAgain = "Kuis Lagi",
        vocabOpenExample = "Buka di mushaf ▸",
        vocabAudioUnavailable = "Audio belum tersedia. Cek koneksi lalu coba lagi.",
        vocabLoading = "Menyiapkan kosa kata…",
        // Belajar Arab
        menuLughoh = "📚 Belajar Arab",
        lughohSubtitle = "Metode ala Durusul Lughoh: percakapan, kosakata, tata bahasa — latihan acak tak terbatas untuk pemula.",
        lughohLoading = "Memuat pelajaran…",
        lughohEmpty = "Belum ada materi.",
        lughohStartRandom = "🎮 Latihan Acak",
        lughohBestScore = "Skor terbaik: %d/%d",
        lughohSessionsPlayed = "Sesi dimainkan: %d",
        lughohMaterialTitle = "📖 Materi",
        lughohSectionMuhadatsah = "1. Muhadatsah — Percakapan",
        lughohSectionMufrodat = "2. Mufrodat — Kosakata",
        lughohSectionQawaid = "3. Qawa'id — Tata Bahasa",
        lughohExercisesTitle = "Tadribat",
        lughohProgressLabel = "Latihan %d/%d",
        lughohCheck = "✓ Periksa",
        lughohNext = "Lanjut →",
        lughohCorrect = "✓ Benar!",
        lughohWrong = "✗ Belum tepat.",
        lughohResultTitle = "Sesi selesai!",
        lughohScore = "Skor: %d/%d",
        lughohRestart = "🔄 Sesi Baru",
        lughohBackToHome = "← Kembali",
        // Penghargaan (badge)
        menuBadges = "🏅 Penghargaan",
        badgesTitle = "🏅 Penghargaan",
        badgesSubtitle = "Raih lencana dengan rutin berlatih — setiap aktivitas bernilai XP.",
        badgesLoading = "Memeriksa lencana…",
        badgesCount = "%d/%d lencana diraih",
        badgesLocked = "Terkunci",
        badgesEarned = "Diraih",
        badgesTierLabel = "Tingkat %d",
        homeLevelLine = "Level %d · %d XP",
        homeStreakLine = "🔥 %d hari beruntun",
        homeBadgeLabel = "Badge terbaru:",
        homeGoalLine = "🎯 Target harian: %d/%d XP",
        levelLabel = "Level",
        celebrateLevelUpTitle = "🎉 Naik Level!",
        celebrateLevelUpBody = "Selamat! Kamu sekarang di Level %d.",
        celebrateStreakTitle = "🔥 Streak!",
        celebrateStreakBody = "%d hari beruntun — pertahankan!",
        celebrateBadgeTitle = "🏅 Badge Baru!",
        celebrateBadgeBody = "Badge %s mencapai tingkat %d.",
    )

    val English = Strings(
        appTitle = "Tahsin Qur'an",
        subtitle = "Every word is checked live.",
        homeSubtitle = "Choose a menu to start learning.",
        menuTahsin = "🕌 Tahsin",
        menuSettings = "⚙️ Settings",
        legendCorrect = "correct",
        legendWrong = "wrong",
        legendReading = "reading",
        legendNotReached = "not yet",
        ayahWord = "ayah",
        ayahLabel = "Ayah",
        loadingSurah = "Loading surah…",
        detectedPrefix = "🎙️ Detected:",
        issueDetected = "Heard:",
        downloadingLabel = "Downloading audio…",
        noTajwidRule = "No specific tajweed rule detected for this word.",
        issuesTitle = "Reading issues",
        micHint = "Tap 🎙️\nthen recite",
        listeningHint = "Listening… tap ⏹ to stop",
        listen = "▶ Listen",
        stop = "⏹ Stop",
        playWord = "▶ Word",
        settingsTitle = "Settings",
        settingTajwid = "Tajweed Color",
        settingFlow = "Flow Mode",
        flowHint = "Automatically continues to the next ayah when finished.",
        settingDarkMode = "Dark Mode",
        settingLanguage = "Language",
        languageNameId = "Indonesian",
        languageNameEn = "English",
        sectionAppearance = "Appearance",
        sectionMenu = "Menu",
        sectionReciter = "Reciter",
        sectionSpeed = "Audio Speed",
        audioReciterLabel = "Reciter",
        sectionDaily = "Ayah of the Day",
        sectionStreakReminder = "Streak Reminder",
        menuStats = "📊 Stats",
        menuQuiz = "📝 Quiz",
        menuAudio = "🎵 Audio",
        menuDownloadAll = "📥 Download All Audio",
        swipeHint = "Swipe the screen left/right to change ayah",
        credit = "Made with ❤️ by OpenNur Project (FOSS)",
        downloadNoticeTitle = "Downloading audio…",
        downloadNoticeBody = "This surah's audio is not downloaded yet. The download starts " +
            "automatically — follow the progress above the buttons. The example recitation " +
            "will play once the download finishes.",
        gotIt = "Got it",
        bgPromptTitle = "Background download?",
        bgPromptBody = "Allow downloads to continue while the screen is off / the app is in " +
            "the background? Large downloads (e.g. Al-Baqarah ≈ 440 MB) may fail otherwise.",
        bgAllow = "Allow",
        bgDeny = "No, only while the app is open",
        loadingMushaf = "Loading mushaf…",
        msgMicPermission = "Microphone permission is required to check your recitation.",
        msgCheckConnection = "check connection",
        msgSurahLoadFailed = "Failed to load surah",
        msgMushafLoading = "Loading mushaf…",
        msgMushafLoadFailed = "Failed to load mushaf.",
        msgRetry = "🔄 Try Again",
        msgAyahDone = "✅ Ayah complete — moving to the next ayah",
        msgSurahDone = "✅ Surah complete — moving to the next surah",
        msgMurojaahDone = "🎉 Muraja'ah complete — the whole Qur'an read correctly!",
        msgDownloadFailed = "Failed to download",
        msgAudioUnavailable = "Audio not available. Check your connection and try again.",
        msgWordUnavailable = "Word audio not available. Check your connection and try again.",
        msgDownloadAllPartial = "Download finished: %d surahs failed.",
        msgDownloadAllDone = "All audio downloaded successfully ✓",
        audioManagerTitle = "Downloaded Audio",
        audioManagerSubtitle = "Manage audio downloaded per surah.",
        audioStatusComplete = "✓ Complete",
        audioStatusIncomplete = "Incomplete",
        audioMissingNote = "%d audio unavailable on server",
        audioDeleteTitle = "Delete this surah's audio?",
        audioDeleteAllTitle = "Delete all audio?",
        audioDeleteBody = "This surah's audio will be removed from the device.",
        audioDeleteAllBody = "All downloaded audio will be removed from the device.",
        audioCancel = "Cancel",
        audioDelete = "Delete",
        audioDeleteAll = "Delete All",
        audioBack = "←",
        audioSize = "%d,%.2f MB",
        audioAyat = "Ayah",
        audioKata = "Word",
        audioNoDownload = "No audio downloaded yet. Open a surah and tap Listen to download.",
        audioDownloadAllCta = "📥 Download All — %s",
        audioLoading = "Loading audio…",
        statsTitle = "📊 Statistics",
        statsSubtitle = "A summary of all your learning activity in one screen.",
        statsTotalSessions = "Total Sessions",
        statsBestScoreLabel = "Best Score",
        statsTotalRounds = "Total Rounds",
        statsWordsMastered = "Words Mastered",
        statsTahsinLine = "Tahsin: %d attempts",
        statsDreamBigLine = "Dream BIG: %d rounds • best score %d/%d",
        statsLughohLine = "Learn Arabic: %d sessions • best score %d/%d",
        statsVocabLine = "Vocabulary: %d words mastered",
        statsNoData = "No activity yet. Start with Tahsin, Dream BIG, Learn Arabic, or Vocabulary!",
        statsLoading = "Loading statistics…",
        statsInline = "📊 %d× attempted · best score %d%%",
        searchTitle = "🔍 Search Ayah",
        searchHint = "Arabic word / translation keyword (ID/EN)…",
        searchNoQuery = "Type a keyword to search ayahs across the whole Qur'an.",
        searchIndexing = "Preparing search index…",
        searchSearching = "Searching…",
        searchNoResults = "No matching ayahs.",
        searchResultsCount = "%d results",
        quizTitle = "📝 Tajweed Quiz",
        quizScore = "Score: %d/%d",
        quizQuestion = "What rule applies to this word?",
        quizNext = "Next question →",
        quizCorrect = "✓ Correct!",
        quizWrong = "✗ Not quite.",
        quizRuleLabel = "Rule",
        quizLoading = "Preparing question…",
        quizNoData = "Failed to prepare a question. Try again.",
        menuAyatQuiz = "🎯 Ayah Quiz",
        ayatQuizTitle = "🎯 Ayah Quiz",
        ayatQuizModeComplete = "Complete",
        ayatQuizModeSurah = "Guess Surah",
        ayatQuizCompleteQuestion = "Which word completes this ayah?",
        ayatQuizSurahQuestion = "Which surah is this ayah from?",
        ayatQuizWrong = "✗ Not quite. The answer: %s",
        menuVocab = "📖 Vocabulary",
        menuDreamBig = "🎬 Dream BIG",
        dreamBigTitle = "🎬 Dream BIG",
        dreamBigSubtitle = "Random Qur'anic vocabulary quiz — keep playing, chase your best score!",
        dreamBigLoading = "Loading game…",
        gameBestScore = "Best score: %d/%d",
        gameQuestionProgress = "Question %d/%d",
        gameScoreLabel = "Score %d",
        gameStreakLabel = "🔥 %d",
        gameCorrect = "✓ Correct!",
        gameWrong = "✗ Not quite.",
        gameNext = "Next question →",
        gameResultTitle = "Round complete",
        gameResultScore = "Score: %d/%d",
        gameResultStreak = "Best streak: %d",
        gameRepeat = "🔄 Play Again",
        gameStart = "▶ Play",
        gameRoundsPlayed = "Rounds played: %d",
        gameBackHome = "← Back",
        vocabTitle = "📖 Vocabulary",
        vocabSubtitle = "The most important words of the Qur'an — ordered by frequency.",
        vocabModeCards = "📇 Cards",
        vocabModeQuiz = "📝 Quiz",
        vocabFlipHint = "Tap the card to reveal the meaning.",
        vocabMeaning = "Meaning",
        vocabRoot = "Root",
        vocabExample = "Example verse",
        vocabPlayAudio = "▶ Hear",
        vocabRemember = "✓ Remember",
        vocabForgot = "✗ Forgot",
        vocabLearned = "%d words mastered",
        vocabDue = "%d to review",
        vocabSessionDone = "Card session done ✓",
        vocabStartQuiz = "Try Quiz",
        vocabEmpty = "No words to study right now. Come back later — or try the Quiz!",
        vocabQuizQuestionWord = "What does this word mean?",
        vocabQuizQuestionMeaning = "Which word means:",
        vocabQuizScore = "Score: %d/%d",
        vocabQuizCorrect = "✓ Correct!",
        vocabQuizWrong = "✗ Not quite. The answer: %s",
        vocabQuizNext = "Next →",
        vocabQuizDone = "Quiz complete! Score: %d/%d",
        vocabQuizAgain = "Quiz Again",
        vocabOpenExample = "Open in mushaf ▸",
        vocabAudioUnavailable = "Audio not available yet. Check your connection and try again.",
        vocabLoading = "Preparing vocabulary…",
        // Learn Arabic
        menuLughoh = "📚 Learn Arabic",
        lughohSubtitle = "Durusul Lughoh-style method: conversation, vocabulary, grammar — unlimited random practice for beginners.",
        lughohLoading = "Loading lessons…",
        lughohEmpty = "No material yet.",
        lughohStartRandom = "🎮 Random Practice",
        lughohBestScore = "Best score: %d/%d",
        lughohSessionsPlayed = "Sessions played: %d",
        lughohMaterialTitle = "📖 Material",
        lughohSectionMuhadatsah = "1. Muhadatsah — Conversation",
        lughohSectionMufrodat = "2. Mufrodat — Vocabulary",
        lughohSectionQawaid = "3. Qawa'id — Grammar",
        lughohExercisesTitle = "Tadribat",
        lughohProgressLabel = "Exercise %d/%d",
        lughohCheck = "✓ Check",
        lughohNext = "Next →",
        lughohCorrect = "✓ Correct!",
        lughohWrong = "✗ Not quite.",
        lughohResultTitle = "Session done!",
        lughohScore = "Score: %d/%d",
        lughohRestart = "🔄 New Session",
        lughohBackToHome = "← Back",
        // Penghargaan (badge)
        menuBadges = "🏅 Badges",
        badgesTitle = "🏅 Badges",
        badgesSubtitle = "Earn badges by practicing regularly — every activity is worth XP.",
        badgesLoading = "Checking badges…",
        badgesCount = "%d/%d badges earned",
        badgesLocked = "Locked",
        badgesEarned = "Earned",
        badgesTierLabel = "Tier %d",
        homeLevelLine = "Level %d · %d XP",
        homeStreakLine = "🔥 %d-day streak",
        homeBadgeLabel = "Latest badge:",
        homeGoalLine = "🎯 Daily goal: %d/%d XP",
        levelLabel = "Level",
        celebrateLevelUpTitle = "🎉 Level Up!",
        celebrateLevelUpBody = "Congrats! You're now Level %d.",
        celebrateStreakTitle = "🔥 Streak!",
        celebrateStreakBody = "%d-day streak — keep it up!",
        celebrateBadgeTitle = "🏅 New Badge!",
        celebrateBadgeBody = "Badge %s reached tier %d.",
    )

    /** Judul badge terjemahan — key = [org.opennur.tahsin.util.BadgeDef.key]. */
    fun badgeTitle(key: String, lang: AppLanguage): String = when (lang) {
        AppLanguage.ID -> when (key) {
            "xp" -> "Pencari Ilmu"
            "streak" -> "Konsisten"
            "tahsin" -> "Tekun Berlatih"
            "tahsin-perfect" -> "Bacaan Sempurna"
            "vocab" -> "Pengumpul Kata"
            "dream" -> "Mimpi Besar"
            "lughoh" -> "Poliglot Pemula"
            "surah" -> "Penuntas Surah"
            else -> key
        }
        AppLanguage.EN -> when (key) {
            "xp" -> "Knowledge Seeker"
            "streak" -> "Consistent"
            "tahsin" -> "Dedicated Reciter"
            "tahsin-perfect" -> "Perfect Recitation"
            "vocab" -> "Word Collector"
            "dream" -> "Big Dreamer"
            "lughoh" -> "Budding Polyglot"
            "surah" -> "Surah Finisher"
            else -> key
        }
    }

    /** Deskripsi badge terjemahan — key = [org.opennur.tahsin.util.BadgeDef.key]. */
    fun badgeDesc(key: String, lang: AppLanguage): String = when (lang) {
        AppLanguage.ID -> when (key) {
            "xp" -> "Kumpulkan XP untuk naik level."
            "streak" -> "Pertahankan streak hari beruntun."
            "tahsin" -> "Selesaikan percobaan bacaan Tahsin."
            "tahsin-perfect" -> "Baca ayat dengan skor 90+."
            "vocab" -> "Kuasai kata kosakata."
            "dream" -> "Mainkan ronde Dream BIG."
            "lughoh" -> "Selesaikan sesi Belajar Arab."
            "surah" -> "Tamatkan surah: semua ayatnya pernah dibaca."
            else -> ""
        }
        AppLanguage.EN -> when (key) {
            "xp" -> "Earn XP to level up."
            "streak" -> "Keep your daily streak alive."
            "tahsin" -> "Complete Tahsin recitation attempts."
            "tahsin-perfect" -> "Recite ayahs with a 90+ score."
            "vocab" -> "Master vocabulary words."
            "dream" -> "Play Dream BIG rounds."
            "lughoh" -> "Finish Learn Arabic sessions."
            "surah" -> "Complete a surah: every ayah read at least once."
            else -> ""
        }
    }

    /**
     * Pesan error STT terjemahan dari kode [SpeechRecognizer] — pembungkus
     * STT tetap netral bahasa (hanya mengirim kode mentah).
     */
    fun sttErrorMessage(error: Int, lang: AppLanguage): String {
        val id = lang == AppLanguage.ID
        return when (error) {
            SpeechRecognizer.ERROR_NO_MATCH ->
                if (id) "Tidak ada yang cocok terdeteksi — coba baca lebih pelan dan jelas."
                else "Nothing matched — try reciting slower and clearer."
            SpeechRecognizer.ERROR_SPEECH_TIMEOUT ->
                if (id) "Tidak ada suara terdeteksi (timeout)."
                else "No speech detected (timeout)."
            SpeechRecognizer.ERROR_INSUFFICIENT_PERMISSIONS ->
                if (id) "Izin mikrofon belum diberikan."
                else "Microphone permission not granted."
            SpeechRecognizer.ERROR_NETWORK, SpeechRecognizer.ERROR_NETWORK_TIMEOUT ->
                if (id) "STT butuh internet (atau pasang paket bahasa Arab offline di pengaturan HP)."
                else "Speech recognition needs internet (or install the offline Arabic pack in device settings)."
            SpeechRecognizer.ERROR_RECOGNIZER_BUSY ->
                if (id) "SpeechRecognizer sedang sibuk — coba lagi."
                else "Speech recognizer is busy — try again."
            else ->
                if (id) "Error speech recognition (kode $error)."
                else "Speech recognition error (code $error)."
        }
    }
}
