package org.opennur.tahsin.ui

import android.speech.SpeechRecognizer

import org.opennur.tahsin.util.AppLanguage

/** New learning copy is grouped to keep the JVM constructor below its 255-slot limit. */
data class LearningStrings(
    val settingLearningPlan: String,
    val statsPlanLine: String,
    val menuMemorization: String,
    val todayTitle: String,
    val todaySubtitle: String,
    val todayProgress: String,
    val todayComplete: String,
    val todayTaskStart: String,
    val todayTaskDone: String,
    val todayExplore: String,
    val goalRecitation: String,
    val goalUnderstanding: String,
    val goalMemorization: String,
    val goalArabic: String,
    val taskRecite: String,
    val taskTajwid: String,
    val taskVocabulary: String,
    val taskUnderstand: String,
    val taskArabic: String,
    val taskMemorization: String,
    val onboardingTitle: String,
    val onboardingSubtitle: String,
    val onboardingGoalQuestion: String,
    val onboardingTimeQuestion: String,
    val onboardingMinutes: String,
    val onboardingStart: String,
    val memorizationTitle: String,
    val memorizationSubtitle: String,
    val memorizationLoading: String,
    val memorizationDue: String,
    val memorizationHidden: String,
    val memorizationReveal: String,
    val memorizationReview: String,
    val memorizationRemembered: String,
    val memorizationOpenTahsin: String,
    val memorizationError: String,
    // STT recitation
    val memorizationRecite: String,
    val memorizationSttListening: String,
    val memorizationSttScore: String,
    val memorizationSttPass: String,
    val memorizationSttFail: String,
    // Target selection
    val memorizationTargetSurah: String,
    val memorizationTargetJuz: String,
    val memorizationApply: String,
)

/**
 * Katalog teks UI per bahasa (tanpa resource Android — cukup untuk 2 bahasa).
 * Tambahkan bahasa baru = buat instance baru di [AppStrings.of].
 */
data class Strings(
    val appTitle: String,
    val subtitle: String,
    /** Subjudul portal (layar utama). */
    val homeSubtitle: String,
    /** Label kartu menu "Tahsin" di portal. */
    val menuTahsin: String,
    /** Label kartu menu "Pengaturan" di portal. */
    val menuSettings: String,
    val legendCorrect: String,
    val legendWrong: String,
    val legendReading: String,
    val legendNotReached: String,
    val ayahWord: String,
    val ayahLabel: String,
    val loadingSurah: String,
    val detectedPrefix: String,
    val issueDetected: String,
    val downloadingLabel: String,
    val noTajwidRule: String,
    val issuesTitle: String,
    val micHint: String,
    val listeningHint: String,
    val listen: String,
    val stop: String,
    val playWord: String,
    val settingsTitle: String,
    val settingTajwid: String,
    val settingFlow: String,
    val flowHint: String,
    val settingDarkMode: String,
    val settingLanguage: String,
    val languageNameId: String,
    val languageNameEn: String,
    val sectionAppearance: String,
    val sectionMenu: String,
    val sectionReciter: String,
    val sectionSpeed: String,
    val audioReciterLabel: String,
    val sectionDaily: String,
    val sectionStreakReminder: String,
    val menuStats: String,
    val menuQuiz: String,
    val menuAudio: String,
    val menuDownloadAll: String,
    val swipeHint: String,
    val credit: String,
    val downloadNoticeTitle: String,
    val downloadNoticeBody: String,
    val gotIt: String,
    val bgPromptTitle: String,
    val bgPromptBody: String,
    val bgAllow: String,
    val bgDeny: String,
    val loadingMushaf: String,
    // Pesan ViewModel
    val msgMicPermission: String,
    val msgCheckConnection: String,
    val msgSurahLoadFailed: String,
    val msgMushafLoading: String,
    val msgMushafLoadFailed: String,
    val msgRetry: String,
    val msgAyahDone: String,
    val msgSurahDone: String,
    val msgMurojaahDone: String,
    val msgDownloadFailed: String,
    val msgAudioUnavailable: String,
    val msgWordUnavailable: String,
    val msgDownloadAllPartial: String,
    val msgDownloadAllDone: String,
    // Manajer audio
    val audioManagerTitle: String,
    val audioManagerSubtitle: String,
    val audioStatusComplete: String,
    val audioStatusIncomplete: String,
    val audioMissingNote: String,
    val audioDeleteTitle: String,
    val audioDeleteAllTitle: String,
    val audioDeleteBody: String,
    val audioDeleteAllBody: String,
    val audioCancel: String,
    val audioDelete: String,
    val audioDeleteAll: String,
    val audioBack: String,
    val audioSize: String,
    val audioAyat: String,
    val audioKata: String,
    val audioNoDownload: String,
    val audioDownloadAllCta: String,
    val audioLoading: String,
    // Statistik & riwayat kesalahan
    val statsTitle: String,
    val statsHistoryTitle: String,
    val statsHistoryEmpty: String,
    val statsSubtitle: String,
    val statsTotalSessions: String,
    val statsBestScoreLabel: String,
    val statsTotalRounds: String,
    val statsWordsMastered: String,
    val statsTahsinLine: String,
    val statsDreamBigLine: String,
    val statsLughohLine: String,
    val statsVocabLine: String,
    val statsNoData: String,
    val statsLoading: String,
    val statsInline: String,
    val issueFallback: String,
    // Mushaf halaman (Tahsin)
    val tahsinPage: String,
    val tahsinJuz: String,
    val tahsinTranslation: String,
    val tahsinAyah: String,
    val tahsinAudioSingle: String,
    val tahsinAudioContinuous: String,
    val tahsinAudioRepeat: String,
    // Pencarian ayat
    val searchTitle: String,
    val searchHint: String,
    val searchNoQuery: String,
    val searchIndexing: String,
    val searchSearching: String,
    val searchNoResults: String,
    val searchResultsCount: String,
    // Kuis tajwid
    val quizTitle: String,
    val quizScore: String,
    val quizQuestion: String,
    val quizNext: String,
    val quizCorrect: String,
    val quizWrong: String,
    val quizRuleLabel: String,
    val quizLoading: String,
    val quizNoData: String,
    // Kuis Ayat (Lengkapi Ayat & Tebak Surah)
    val menuAyatQuiz: String,
    val ayatQuizTitle: String,
    val ayatQuizModeComplete: String,
    val ayatQuizModeSurah: String,
    val ayatQuizCompleteQuestion: String,
    val ayatQuizSurahQuestion: String,
    val ayatQuizWrong: String,
    // Kosa kata
    val menuVocab: String,
    // Materi Dream BIG
    val menuDreamBig: String,
    val dreamBigTitle: String,
    val dreamBigSubtitle: String,
    val dreamBigLoading: String,
    val gameBestScore: String,
    val gameQuestionProgress: String,
    val gameScoreLabel: String,
    val gameStreakLabel: String,
    val gameCorrect: String,
    val gameWrong: String,
    val gameNext: String,
    val gameResultTitle: String,
    val gameResultScore: String,
    val gameResultStreak: String,
    val gameRepeat: String,
    val gameStart: String,
    val gameRoundsPlayed: String,
    val gameBackHome: String,
    val vocabTitle: String,
    val vocabSubtitle: String,
    val vocabModeCards: String,
    val vocabModeQuiz: String,
    val vocabFlipHint: String,
    val vocabMeaning: String,
    val vocabRoot: String,
    val vocabExample: String,
    val vocabPlayAudio: String,
    val vocabRemember: String,
    val vocabForgot: String,
    val vocabLearned: String,
    val vocabDue: String,
    val vocabSessionDone: String,
    val vocabStartQuiz: String,
    val vocabEmpty: String,
    val vocabQuizQuestionWord: String,
    val vocabQuizQuestionMeaning: String,
    val vocabQuizScore: String,
    val vocabQuizCorrect: String,
    val vocabQuizWrong: String,
    val vocabQuizNext: String,
    val vocabQuizDone: String,
    val vocabQuizAgain: String,
    val vocabOpenExample: String,
    val vocabAudioUnavailable: String,
    val vocabLoading: String,
    // Morfologi / Akar Kata
    val morphRoot: String,
    val morphRelatedLabel: String,
    val morphNoRoot: String,
    val morphViewAll: String,
    // Belajar Arab (Durusul Lughoh style)
    val menuLughoh: String,
    val lughohSubtitle: String,
    val lughohLoading: String,
    val lughohEmpty: String,
    val lughohStartRandom: String,
    val lughohBestScore: String,
    val lughohSessionsPlayed: String,
    val lughohMaterialTitle: String,
    val lughohSectionMuhadatsah: String,
    val lughohSectionMufrodat: String,
    val lughohSectionQawaid: String,
    val lughohExercisesTitle: String,
    val lughohProgressLabel: String,
    val lughohCheck: String,
    val lughohNext: String,
    val lughohCorrect: String,
    val lughohWrong: String,
    val lughohResultTitle: String,
    val lughohScore: String,
    val lughohRestart: String,
    val lughohBackToHome: String,
    // Penghargaan (badge)
    val menuBadges: String,
    val badgesTitle: String,
    val badgesSubtitle: String,
    val badgesLoading: String,
    val badgesCount: String,
    val badgesLocked: String,
    val badgesEarned: String,
    val badgesTierLabel: String,
    // Gamification header (Home & ringkasan statistik)
    val homeLevelLine: String,
    val homeStreakLine: String,
    val homeBadgeLabel: String,
    val homeGoalLine: String,
    val levelLabel: String,
    // Perayaan gamification
    val celebrateLevelUpTitle: String,
    val celebrateLevelUpBody: String,
    val celebrateStreakTitle: String,
    val celebrateStreakBody: String,
    val celebrateBadgeTitle: String,
    val celebrateBadgeBody: String,
    // Menu Studi Coherence (nazm) & Ayat Favorit
    val menuCoherence: String,
    val menuFavorites: String,
    val coherenceTitle: String,
    val coherenceSubtitle: String,
    val coherenceSource: String,
    val coherenceCentralTheme: String,
    val coherenceGroupLabel: String,
    val coherenceNazmLabel: String,
    val coherenceMethodology: String,
    // Arti kata di tooltip mushaf
    val wordMeaningLabel: String,
    val favoritesTitle: String,
    val favoritesSubtitle: String,
    val favoritesEmpty: String,
    val favoritesLoading: String,
    val favoritesOpenHint: String,
    val learning: LearningStrings,
) {
    val settingLearningPlan get() = learning.settingLearningPlan
    val statsPlanLine get() = learning.statsPlanLine
    val menuMemorization get() = learning.menuMemorization
    val todayTitle get() = learning.todayTitle
    val todaySubtitle get() = learning.todaySubtitle
    val todayProgress get() = learning.todayProgress
    val todayComplete get() = learning.todayComplete
    val todayTaskStart get() = learning.todayTaskStart
    val todayTaskDone get() = learning.todayTaskDone
    val todayExplore get() = learning.todayExplore
    val goalRecitation get() = learning.goalRecitation
    val goalUnderstanding get() = learning.goalUnderstanding
    val goalMemorization get() = learning.goalMemorization
    val goalArabic get() = learning.goalArabic
    val taskRecite get() = learning.taskRecite
    val taskTajwid get() = learning.taskTajwid
    val taskVocabulary get() = learning.taskVocabulary
    val taskUnderstand get() = learning.taskUnderstand
    val taskArabic get() = learning.taskArabic
    val taskMemorization get() = learning.taskMemorization
    val onboardingTitle get() = learning.onboardingTitle
    val onboardingSubtitle get() = learning.onboardingSubtitle
    val onboardingGoalQuestion get() = learning.onboardingGoalQuestion
    val onboardingTimeQuestion get() = learning.onboardingTimeQuestion
    val onboardingMinutes get() = learning.onboardingMinutes
    val onboardingStart get() = learning.onboardingStart
    val memorizationTitle get() = learning.memorizationTitle
    val memorizationSubtitle get() = learning.memorizationSubtitle
    val memorizationLoading get() = learning.memorizationLoading
    val memorizationDue get() = learning.memorizationDue
    val memorizationHidden get() = learning.memorizationHidden
    val memorizationReveal get() = learning.memorizationReveal
    val memorizationReview get() = learning.memorizationReview
    val memorizationRemembered get() = learning.memorizationRemembered
    val memorizationOpenTahsin get() = learning.memorizationOpenTahsin
    val memorizationError get() = learning.memorizationError
    val memorizationRecite get() = learning.memorizationRecite
    val memorizationSttListening get() = learning.memorizationSttListening
    val memorizationSttScore get() = learning.memorizationSttScore
    val memorizationSttPass get() = learning.memorizationSttPass
    val memorizationSttFail get() = learning.memorizationSttFail
    val memorizationTargetSurah get() = learning.memorizationTargetSurah
    val memorizationTargetJuz get() = learning.memorizationTargetJuz
    val memorizationApply get() = learning.memorizationApply
}

object AppStrings {

    fun of(lang: AppLanguage): Strings = when (lang) {
        AppLanguage.ID -> Indonesian
        AppLanguage.EN -> English
    }

    val Indonesian = Strings(
        appTitle = "Tahsin Qur'an",
        subtitle = "Setiap kata dicek langsung.",
        homeSubtitle = "Pilih menu untuk mulai belajar.",
        menuTahsin = "🕌 Tahsin",
        menuSettings = "⚙️ Pengaturan",
        legendCorrect = "benar",
        legendWrong = "salah",
        legendReading = "dibaca",
        legendNotReached = "belum",
        ayahWord = "ayat",
        ayahLabel = "Ayat",
        loadingSurah = "Memuat surah…",
        detectedPrefix = "🎙️ Terdeteksi:",
        issueDetected = "Terdeteksi:",
        downloadingLabel = "Mengunduh audio…",
        noTajwidRule = "Tidak ada aturan tajwid khusus pada kata ini.",
        issuesTitle = "Kesalahan terdeteksi",
        micHint = "🎙️ lalu bacalah",
        listeningHint = "Membaca… ⏹ stop",
        listen = "▶ Dengar",
        stop = "⏹ Stop",
        playWord = "▶ Dengar Kata",
        settingsTitle = "Pengaturan",
        settingTajwid = "Warna Tajwid",
        settingFlow = "Mode Flow",
        flowHint = "Lanjut otomatis ke ayat berikutnya saat selesai.",
        settingDarkMode = "Mode Gelap",
        settingLanguage = "Bahasa",
        languageNameId = "Indonesia",
        languageNameEn = "Inggris",
        sectionAppearance = "Tampilan",
        sectionMenu = "Menu",
        sectionReciter = "Qari' (Perawi)",
        sectionSpeed = "Kecepatan Audio",
        audioReciterLabel = "Qari'",
        sectionDaily = "Ayat Hari Ini",
        sectionStreakReminder = "Pengingat Streak",
        menuStats = "📊 Statistik",
        menuQuiz = "📝 Kuis",
        menuAudio = "🎵 Kelola Audio",
        menuDownloadAll = "📥 Unduh Semua Audio",
        swipeHint = "Geser layar ke kiri/kanan untuk ganti ayat",
        credit = "Dibuat dengan ❤️ oleh OpenNur Project (FOSS)",
        downloadNoticeTitle = "Mengunduh audio…",
        downloadNoticeBody = "Audio surah ini belum diunduh. Unduhan dimulai otomatis — " +
            "ikuti progres di atas tombol. Bacaan contoh akan diputar setelah unduhan selesai.",
        gotIt = "Mengerti",
        bgPromptTitle = "Unduhan latar belakang?",
        bgPromptBody = "Izinkan unduhan terus berjalan saat layar mati / aplikasi di latar " +
            "belakang? Unduhan besar (mis. Al-Baqarah ≈ 440 MB) bisa gagal kalau tidak.",
        bgAllow = "Izinkan",
        bgDeny = "Tidak, cukup saat aplikasi terbuka",
        loadingMushaf = "Memuat mushaf…",
        msgMicPermission = "Izin mikrofon diperlukan untuk mendeteksi bacaan.",
        msgCheckConnection = "periksa koneksi",
        msgSurahLoadFailed = "Gagal memuat surah",
        msgMushafLoading = "Memuat mushaf…",
        msgMushafLoadFailed = "Gagal memuat mushaf.",
        msgRetry = "🔄 Coba Lagi",
        msgAyahDone = "✅ Ayat selesai — lanjut ke ayat berikutnya",
        msgSurahDone = "✅ Surah selesai — lanjut ke surah berikutnya",
        msgMurojaahDone = "🎉 Selesai muroja'ah — seluruh Al-Qur'an dibaca benar!",
        msgDownloadFailed = "Gagal mengunduh",
        msgAudioUnavailable = "Audio belum tersedia. Cek koneksi lalu coba lagi.",
        msgWordUnavailable = "Audio kata belum tersedia. Cek koneksi lalu coba lagi.",
        msgDownloadAllPartial = "Unduh selesai: %d surah gagal.",
        msgDownloadAllDone = "Semua audio berhasil diunduh ✓",
        audioManagerTitle = "Audio Terunduh",
        audioManagerSubtitle = "Kelola audio yang sudah diunduh per surah.",
        audioStatusComplete = "✓ Lengkap",
        audioStatusIncomplete = "Belum lengkap",
        audioMissingNote = "%d audio tak tersedia di server",
        audioDeleteTitle = "Hapus audio surah ini?",
        audioDeleteAllTitle = "Hapus semua audio?",
        audioDeleteBody = "Audio surah ini akan dihapus dari perangkat.",
        audioDeleteAllBody = "Semua audio terunduh akan dihapus dari perangkat.",
        audioCancel = "Batal",
        audioDelete = "Hapus",
        audioDeleteAll = "Hapus Semua",
        audioBack = "←",
        audioSize = "%d,%.2f MB",
        audioAyat = "Ayat",
        audioKata = "Kata",
        audioNoDownload = "Belum ada audio terunduh. Buka surah dan tekan Dengar untuk mengunduh.",
        audioDownloadAllCta = "📥 Unduh Semua — %s",
        audioLoading = "Memuat audio…",
        statsTitle = "📊 Statistik & Riwayat",
        statsHistoryTitle = "🕘 Riwayat Baca",
        statsHistoryEmpty = "Belum ada riwayat baca. Buka beberapa ayat di layar Tahsin — nanti muncul di sini.",
        statsSubtitle = "Ringkasan semua aktivitas belajarmu dalam satu layar.",
        statsTotalSessions = "Total Sesi",
        statsBestScoreLabel = "Skor Terbaik",
        statsTotalRounds = "Total Ronde",
        statsWordsMastered = "Kata Dikuasai",
        statsTahsinLine = "Tahsin: %d percobaan",
        statsDreamBigLine = "Dream BIG: %d ronde • skor terbaik %d/%d",
        statsLughohLine = "Belajar Arab: %d sesi • skor terbaik %d/%d",
        statsVocabLine = "Kosakata: %d kata dikuasai",
        statsNoData = "Belum ada aktivitas. Mulai dari Tahsin, Dream BIG, Belajar Arab, atau Kosakata!",
        statsLoading = "Memuat statistik…",
        statsInline = "📊 %d× dicoba · skor terbaik %d%%",
        issueFallback = "Bacalah kata ini sesuai teks mushaf (huruf & harakat).",
        tahsinPage = "Halaman",
        tahsinJuz = "Juz",
        tahsinTranslation = "Terjemahan",
        tahsinAyah = "Ayat",
        tahsinAudioSingle = "Ayat ini saja",
        tahsinAudioContinuous = "Lanjut ayat berikutnya",
        tahsinAudioRepeat = "Ulang terus ayat ini",
        searchTitle = "🔍 Cari Ayat",
        searchHint = "Kata Arab / kata kunci terjemahan (ID/EN)…",
        searchNoQuery = "Ketik kata kunci untuk mencari ayat di seluruh Al-Qur'an.",
        searchIndexing = "Menyiapkan indeks pencarian…",
        searchSearching = "Mencari…",
        searchNoResults = "Tidak ada ayat yang cocok.",
        searchResultsCount = "%d hasil",
        quizTitle = "📝 Kuis Tajwid",
        quizScore = "Skor: %d/%d",
        quizQuestion = "Hukum apa pada kata ini?",
        quizNext = "Soal berikutnya →",
        quizCorrect = "✓ Benar!",
        quizWrong = "✗ Belum tepat.",
        quizRuleLabel = "Hukum",
        quizLoading = "Menyiapkan soal…",
        quizNoData = "Gagal menyiapkan soal. Coba lagi.",
        menuAyatQuiz = "🎯 Kuis Ayat",
        ayatQuizTitle = "🎯 Kuis Ayat",
        ayatQuizModeComplete = "Lengkapi Ayat",
        ayatQuizModeSurah = "Tebak Surah",
        ayatQuizCompleteQuestion = "Kata mana yang melengkapi ayat ini?",
        ayatQuizSurahQuestion = "Ayat ini dari surah apa?",
        ayatQuizWrong = "✗ Belum tepat. Jawabannya: %s",
        menuVocab = "📖 Kosakata",
        menuDreamBig = "🎬 Dream BIG",
        dreamBigTitle = "🎬 Dream BIG",
        dreamBigSubtitle = "Kuis kosakata Qur'an acak — main terus, kejar skor terbaikmu!",
        dreamBigLoading = "Memuat game…",
        gameBestScore = "Skor terbaik: %d/%d",
        gameQuestionProgress = "Soal %d/%d",
        gameScoreLabel = "Skor %d",
        gameStreakLabel = "🔥 %d",
        gameCorrect = "✓ Benar!",
        gameWrong = "✗ Belum tepat.",
        gameNext = "Soal berikutnya →",
        gameResultTitle = "Ronde selesai",
        gameResultScore = "Skor: %d/%d",
        gameResultStreak = "Streak terbaik: %d",
        gameRepeat = "🔄 Main Lagi",
        gameStart = "▶ Main",
        gameRoundsPlayed = "Ronde dimainkan: %d",
        gameBackHome = "← Kembali",
        vocabTitle = "📖 Kosakata",
        vocabSubtitle = "Kata-kata terpenting Al-Qur'an — diurutkan dari yang paling sering muncul.",
        vocabModeCards = "📇 Kartu",
        vocabModeQuiz = "📝 Kuis",
        vocabFlipHint = "Ketuk kartu untuk melihat arti.",
        vocabMeaning = "Arti",
        vocabRoot = "Akar",
        vocabExample = "Contoh ayat",
        vocabPlayAudio = "▶ Dengar",
        vocabRemember = "✓ Ingat",
        vocabForgot = "✗ Lupa",
        vocabLearned = "%d kata dikuasai",
        vocabDue = "%d untuk diulang",
        vocabSessionDone = "Sesi kartu selesai ✓",
        vocabStartQuiz = "Coba Kuis",
        vocabEmpty = "Belum ada kata untuk dipelajari. Kembali lagi nanti — atau coba Kuis!",
        vocabQuizQuestionWord = "Apa arti kata ini?",
        vocabQuizQuestionMeaning = "Kata mana yang artinya:",
        vocabQuizScore = "Skor: %d/%d",
        vocabQuizCorrect = "✓ Benar!",
        vocabQuizWrong = "✗ Belum tepat. Jawabannya: %s",
        vocabQuizNext = "Lanjut →",
        vocabQuizDone = "Kuis selesai! Skor: %d/%d",
        vocabQuizAgain = "Kuis Lagi",
        vocabOpenExample = "Buka di mushaf ▸",
        vocabAudioUnavailable = "Audio belum tersedia. Cek koneksi lalu coba lagi.",
        vocabLoading = "Menyiapkan kosa kata…",
        // Morfologi / Akar Kata
        morphRoot = "Akar Kata",
        morphRelatedLabel = "Kata lain dengan akar yang sama",
        morphNoRoot = "Tidak ditemukan akar",
        morphViewAll = "Lihat Semua",
        // Belajar Arab
        menuLughoh = "📚 Belajar Arab",
        lughohSubtitle = "Metode ala Durusul Lughoh: percakapan, kosakata, tata bahasa — latihan acak tak terbatas untuk pemula.",
        lughohLoading = "Memuat pelajaran…",
        lughohEmpty = "Belum ada materi.",
        lughohStartRandom = "🎮 Latihan Acak",
        lughohBestScore = "Skor terbaik: %d/%d",
        lughohSessionsPlayed = "Sesi dimainkan: %d",
        lughohMaterialTitle = "📖 Materi",
        lughohSectionMuhadatsah = "1. Muhadatsah — Percakapan",
        lughohSectionMufrodat = "2. Mufrodat — Kosakata",
        lughohSectionQawaid = "3. Qawa'id — Tata Bahasa",
        lughohExercisesTitle = "Tadribat",
        lughohProgressLabel = "Latihan %d/%d",
        lughohCheck = "✓ Periksa",
        lughohNext = "Lanjut →",
        lughohCorrect = "✓ Benar!",
        lughohWrong = "✗ Belum tepat.",
        lughohResultTitle = "Sesi selesai!",
        lughohScore = "Skor: %d/%d",
        lughohRestart = "🔄 Sesi Baru",
        lughohBackToHome = "← Kembali",
        // Penghargaan (badge)
        menuBadges = "🏅 Penghargaan",
        badgesTitle = "🏅 Penghargaan",
        badgesSubtitle = "Raih lencana dengan rutin berlatih — setiap aktivitas bernilai XP.",
        badgesLoading = "Memeriksa lencana…",
        badgesCount = "%d/%d lencana diraih",
        badgesLocked = "Terkunci",
        badgesEarned = "Diraih",
        badgesTierLabel = "Tingkat %d",
        homeLevelLine = "Level %d · %d XP",
        homeStreakLine = "🔥 %d hari beruntun",
        homeBadgeLabel = "Badge terbaru:",
        homeGoalLine = "🎯 Target harian: %d/%d XP",
        levelLabel = "Level",
        celebrateLevelUpTitle = "🎉 Naik Level!",
        celebrateLevelUpBody = "Selamat! Kamu sekarang di Level %d.",
        celebrateStreakTitle = "🔥 Streak!",
        celebrateStreakBody = "%d hari beruntun — pertahankan!",
        celebrateBadgeTitle = "🏅 Badge Baru!",
        celebrateBadgeBody = "Badge %s mencapai tingkat %d.",
        menuCoherence = "📖 Studi Coherence Al-Qur'an",
        menuFavorites = "⭐ Ayat Favorit",
        coherenceTitle = "Studi Coherence (Nazm) Al-Qur'an",
        coherenceSubtitle = "Topik utama tiap surah dan keterkaitan antar surah menurut mazhab nazm — Farahi, Islahi, dan Mustansir Mir.",
        coherenceSource = "Sumber",
        coherenceCentralTheme = "Tema Pusat Al-Qur'an",
        coherenceGroupLabel = "Kelompok %d",
        coherenceNazmLabel = "Keterkaitan (nazm)",
        coherenceMethodology = "Ringkasan pembacaan mazhab nazm (bukan kutipan harfiah); ini salah satu kerangka tafsir akademis, bukan satu-satunya cara membaca Al-Qur'an.",
        wordMeaningLabel = "📖 Arti:",
        favoritesTitle = "Ayat Favorit",
        favoritesSubtitle = "Ayat yang kamu tandai dengan ★ di layar Tahsin.",
        favoritesEmpty = "Belum ada ayat favorit.\nBuka layar Tahsin, pilih satu ayat, lalu ketuk ★ di header.",
        favoritesLoading = "Memuat ayat favorit…",
        favoritesOpenHint = "Ketuk untuk membuka di mushaf",
        learning = LearningStrings(
            settingLearningPlan = "Ubah rencana belajar",
            statsPlanLine = "Rencana hari ini: %d/%d aktivitas selesai",
            menuMemorization = "🧠 Hafalan & Muraja'ah",
            todayTitle = "Rencana hari ini",
            todaySubtitle = "%d menit yang terarah, sedikit demi sedikit.",
            todayProgress = "%d/%d aktivitas selesai",
            todayComplete = "Rencana hari ini selesai ✓",
            todayTaskStart = "Mulai",
            todayTaskDone = "Selesai",
            todayExplore = "Jelajahi semua fitur",
            goalRecitation = "🕌 Memperbaiki bacaan",
            goalUnderstanding = "📖 Memahami makna",
            goalMemorization = "🧠 Menghafal dan muraja'ah",
            goalArabic = "📚 Belajar bahasa Arab",
            taskRecite = "Baca dan latih satu ayat",
            taskTajwid = "Kenali satu hukum tajwid",
            taskVocabulary = "Ulangi kosakata Qur'an",
            taskUnderstand = "Pelajari coherence Al-Qur'an",
            taskArabic = "Latihan pelajaran bahasa Arab",
            taskMemorization = "Latihan hafalan dengan mushaf",
            onboardingTitle = "Mulai perjalanan belajarmu",
            onboardingSubtitle = "Pilih arah utama. Kamu tetap bisa membuka semua fitur kapan saja.",
            onboardingGoalQuestion = "Apa fokus utamamu?",
            onboardingTimeQuestion = "Berapa waktu yang ingin kamu sisihkan setiap hari?",
            onboardingMinutes = "%d mnt",
            onboardingStart = "Mulai belajar",
            memorizationTitle = "🧠 Hafalan & Muraja'ah",
            memorizationSubtitle = "Uji ingatanmu, lalu jadwalkan ayat untuk diulang lagi. " +
                "Ini alat bantu latihan, bukan penilaian guru.",
            memorizationLoading = "Menyiapkan antrean hafalan…",
            memorizationDue = "%d dari %d ayat perlu diulang",
            memorizationHidden = "Coba baca dari ingatan sebelum membuka ayat.",
            memorizationReveal = "Buka ayat",
            memorizationReview = "Perlu diulang",
            memorizationRemembered = "Saya ingat",
            memorizationOpenTahsin = "Latih di Tahsin ▸",
            memorizationError = "Antrean hafalan belum dapat dimuat. Coba lagi nanti.",
            memorizationRecite = "🎤 Bacakan dari Hafalan",
            memorizationSttListening = "Mendengarkan hafalanmu…",
            memorizationSttScore = "Skor: %d%%",
            memorizationSttPass = "✓ Bagus! Lanjutkan ke ayat berikutnya.",
            memorizationSttFail = "✗ Perlu latihan lagi. Coba baca lebih pelan.",
            memorizationTargetSurah = "Surah",
            memorizationTargetJuz = "Juz",
            memorizationApply = "Terapkan",
        ),
    )

    val English = Strings(
        appTitle = "Tahsin Qur'an",
        subtitle = "Every word is checked live.",
        homeSubtitle = "Choose a menu to start learning.",
        menuTahsin = "🕌 Tahsin",
        menuSettings = "⚙️ Settings",
        legendCorrect = "correct",
        legendWrong = "wrong",
        legendReading = "reading",
        legendNotReached = "not yet",
        ayahWord = "ayah",
        ayahLabel = "Ayah",
        loadingSurah = "Loading surah…",
        detectedPrefix = "🎙️ Detected:",
        issueDetected = "Heard:",
        downloadingLabel = "Downloading audio…",
        noTajwidRule = "No specific tajweed rule detected for this word.",
        issuesTitle = "Reading issues",
        micHint = "🎙️ then recite",
        listeningHint = "Reading… ⏹ stop",
        listen = "▶ Listen",
        stop = "⏹ Stop",
        playWord = "▶ Play Word",
        settingsTitle = "Settings",
        settingTajwid = "Tajweed Color",
        settingFlow = "Flow Mode",
        flowHint = "Automatically continues to the next ayah when finished.",
        settingDarkMode = "Dark Mode",
        settingLanguage = "Language",
        languageNameId = "Indonesian",
        languageNameEn = "English",
        sectionAppearance = "Appearance",
        sectionMenu = "Menu",
        sectionReciter = "Reciter",
        sectionSpeed = "Audio Speed",
        audioReciterLabel = "Reciter",
        sectionDaily = "Ayah of the Day",
        sectionStreakReminder = "Streak Reminder",
        menuStats = "📊 Stats",
        menuQuiz = "📝 Quiz",
        menuAudio = "🎵 Audio",
        menuDownloadAll = "📥 Download All Audio",
        swipeHint = "Swipe the screen left/right to change ayah",
        credit = "Made with ❤️ by OpenNur Project (FOSS)",
        downloadNoticeTitle = "Downloading audio…",
        downloadNoticeBody = "This surah's audio is not downloaded yet. The download starts " +
            "automatically — follow the progress above the buttons. The example recitation " +
            "will play once the download finishes.",
        gotIt = "Got it",
        bgPromptTitle = "Background download?",
        bgPromptBody = "Allow downloads to continue while the screen is off / the app is in " +
            "the background? Large downloads (e.g. Al-Baqarah ≈ 440 MB) may fail otherwise.",
        bgAllow = "Allow",
        bgDeny = "No, only while the app is open",
        loadingMushaf = "Loading mushaf…",
        msgMicPermission = "Microphone permission is required to check your recitation.",
        msgCheckConnection = "check connection",
        msgSurahLoadFailed = "Failed to load surah",
        msgMushafLoading = "Loading mushaf…",
        msgMushafLoadFailed = "Failed to load mushaf.",
        msgRetry = "🔄 Try Again",
        msgAyahDone = "✅ Ayah complete — moving to the next ayah",
        msgSurahDone = "✅ Surah complete — moving to the next surah",
        msgMurojaahDone = "🎉 Muraja'ah complete — the whole Qur'an read correctly!",
        msgDownloadFailed = "Failed to download",
        msgAudioUnavailable = "Audio not available. Check your connection and try again.",
        msgWordUnavailable = "Word audio not available. Check your connection and try again.",
        msgDownloadAllPartial = "Download finished: %d surahs failed.",
        msgDownloadAllDone = "All audio downloaded successfully ✓",
        audioManagerTitle = "Downloaded Audio",
        audioManagerSubtitle = "Manage audio downloaded per surah.",
        audioStatusComplete = "✓ Complete",
        audioStatusIncomplete = "Incomplete",
        audioMissingNote = "%d audio unavailable on server",
        audioDeleteTitle = "Delete this surah's audio?",
        audioDeleteAllTitle = "Delete all audio?",
        audioDeleteBody = "This surah's audio will be removed from the device.",
        audioDeleteAllBody = "All downloaded audio will be removed from the device.",
        audioCancel = "Cancel",
        audioDelete = "Delete",
        audioDeleteAll = "Delete All",
        audioBack = "←",
        audioSize = "%d,%.2f MB",
        audioAyat = "Ayah",
        audioKata = "Word",
        audioNoDownload = "No audio downloaded yet. Open a surah and tap Listen to download.",
        audioDownloadAllCta = "📥 Download All — %s",
        audioLoading = "Loading audio…",
        statsTitle = "📊 Statistics",
        statsHistoryTitle = "🕘 Reading History",
        statsHistoryEmpty = "No reading history yet. Open a few ayahs on the Tahsin screen — they will appear here.",
        statsSubtitle = "A summary of all your learning activity in one screen.",
        statsTotalSessions = "Total Sessions",
        statsBestScoreLabel = "Best Score",
        statsTotalRounds = "Total Rounds",
        statsWordsMastered = "Words Mastered",
        statsTahsinLine = "Tahsin: %d attempts",
        statsDreamBigLine = "Dream BIG: %d rounds • best score %d/%d",
        statsLughohLine = "Learn Arabic: %d sessions • best score %d/%d",
        statsVocabLine = "Vocabulary: %d words mastered",
        statsNoData = "No activity yet. Start with Tahsin, Dream BIG, Learn Arabic, or Vocabulary!",
        statsLoading = "Loading statistics…",
        statsInline = "📊 %d× attempted · best score %d%%",
        issueFallback = "Read this word exactly as written in the mushaf (letters & harakat).",
        tahsinPage = "Page",
        tahsinJuz = "Juz",
        tahsinTranslation = "Translation",
        tahsinAyah = "Ayah",
        tahsinAudioSingle = "This ayah only",
        tahsinAudioContinuous = "Continue to next ayah",
        tahsinAudioRepeat = "Repeat this ayah",
        searchTitle = "🔍 Search Ayah",
        searchHint = "Arabic word / translation keyword (ID/EN)…",
        searchNoQuery = "Type a keyword to search ayahs across the whole Qur'an.",
        searchIndexing = "Preparing search index…",
        searchSearching = "Searching…",
        searchNoResults = "No matching ayahs.",
        searchResultsCount = "%d results",
        quizTitle = "📝 Tajweed Quiz",
        quizScore = "Score: %d/%d",
        quizQuestion = "What rule applies to this word?",
        quizNext = "Next question →",
        quizCorrect = "✓ Correct!",
        quizWrong = "✗ Not quite.",
        quizRuleLabel = "Rule",
        quizLoading = "Preparing question…",
        quizNoData = "Failed to prepare a question. Try again.",
        menuAyatQuiz = "🎯 Ayah Quiz",
        ayatQuizTitle = "🎯 Ayah Quiz",
        ayatQuizModeComplete = "Complete",
        ayatQuizModeSurah = "Guess Surah",
        ayatQuizCompleteQuestion = "Which word completes this ayah?",
        ayatQuizSurahQuestion = "Which surah is this ayah from?",
        ayatQuizWrong = "✗ Not quite. The answer: %s",
        menuVocab = "📖 Vocabulary",
        menuDreamBig = "🎬 Dream BIG",
        dreamBigTitle = "🎬 Dream BIG",
        dreamBigSubtitle = "Random Qur'anic vocabulary quiz — keep playing, chase your best score!",
        dreamBigLoading = "Loading game…",
        gameBestScore = "Best score: %d/%d",
        gameQuestionProgress = "Question %d/%d",
        gameScoreLabel = "Score %d",
        gameStreakLabel = "🔥 %d",
        gameCorrect = "✓ Correct!",
        gameWrong = "✗ Not quite.",
        gameNext = "Next question →",
        gameResultTitle = "Round complete",
        gameResultScore = "Score: %d/%d",
        gameResultStreak = "Best streak: %d",
        gameRepeat = "🔄 Play Again",
        gameStart = "▶ Play",
        gameRoundsPlayed = "Rounds played: %d",
        gameBackHome = "← Back",
        vocabTitle = "📖 Vocabulary",
        vocabSubtitle = "The most important words of the Qur'an — ordered by frequency.",
        vocabModeCards = "📇 Cards",
        vocabModeQuiz = "📝 Quiz",
        vocabFlipHint = "Tap the card to reveal the meaning.",
        vocabMeaning = "Meaning",
        vocabRoot = "Root",
        vocabExample = "Example verse",
        vocabPlayAudio = "▶ Hear",
        vocabRemember = "✓ Remember",
        vocabForgot = "✗ Forgot",
        vocabLearned = "%d words mastered",
        vocabDue = "%d to review",
        vocabSessionDone = "Card session done ✓",
        vocabStartQuiz = "Try Quiz",
        vocabEmpty = "No words to study right now. Come back later — or try the Quiz!",
        vocabQuizQuestionWord = "What does this word mean?",
        vocabQuizQuestionMeaning = "Which word means:",
        vocabQuizScore = "Score: %d/%d",
        vocabQuizCorrect = "✓ Correct!",
        vocabQuizWrong = "✗ Not quite. The answer: %s",
        vocabQuizNext = "Next →",
        vocabQuizDone = "Quiz complete! Score: %d/%d",
        vocabQuizAgain = "Quiz Again",
        vocabOpenExample = "Open in mushaf ▸",
        vocabAudioUnavailable = "Audio not available yet. Check your connection and try again.",
        vocabLoading = "Preparing vocabulary…",
        // Morphology / Root Word
        morphRoot = "Root Word",
        morphRelatedLabel = "Other words with same root",
        morphNoRoot = "No root found",
        morphViewAll = "View All",
        // Learn Arabic
        menuLughoh = "📚 Learn Arabic",
        lughohSubtitle = "Durusul Lughoh-style method: conversation, vocabulary, grammar — unlimited random practice for beginners.",
        lughohLoading = "Loading lessons…",
        lughohEmpty = "No material yet.",
        lughohStartRandom = "🎮 Random Practice",
        lughohBestScore = "Best score: %d/%d",
        lughohSessionsPlayed = "Sessions played: %d",
        lughohMaterialTitle = "📖 Material",
        lughohSectionMuhadatsah = "1. Muhadatsah — Conversation",
        lughohSectionMufrodat = "2. Mufrodat — Vocabulary",
        lughohSectionQawaid = "3. Qawa'id — Grammar",
        lughohExercisesTitle = "Tadribat",
        lughohProgressLabel = "Exercise %d/%d",
        lughohCheck = "✓ Check",
        lughohNext = "Next →",
        lughohCorrect = "✓ Correct!",
        lughohWrong = "✗ Not quite.",
        lughohResultTitle = "Session done!",
        lughohScore = "Score: %d/%d",
        lughohRestart = "🔄 New Session",
        lughohBackToHome = "← Back",
        // Penghargaan (badge)
        menuBadges = "🏅 Badges",
        badgesTitle = "🏅 Badges",
        badgesSubtitle = "Earn badges by practicing regularly — every activity is worth XP.",
        badgesLoading = "Checking badges…",
        badgesCount = "%d/%d badges earned",
        badgesLocked = "Locked",
        badgesEarned = "Earned",
        badgesTierLabel = "Tier %d",
        homeLevelLine = "Level %d · %d XP",
        homeStreakLine = "🔥 %d-day streak",
        homeBadgeLabel = "Latest badge:",
        homeGoalLine = "🎯 Daily goal: %d/%d XP",
        levelLabel = "Level",
        celebrateLevelUpTitle = "🎉 Level Up!",
        celebrateLevelUpBody = "Congrats! You're now Level %d.",
        celebrateStreakTitle = "🔥 Streak!",
        celebrateStreakBody = "%d-day streak — keep it up!",
        celebrateBadgeTitle = "🏅 New Badge!",
        celebrateBadgeBody = "Badge %s reached tier %d.",
        menuCoherence = "📖 Qur'an Coherence Study",
        menuFavorites = "⭐ Favorite Ayahs",
        coherenceTitle = "Qur'an Coherence Study (Nazm)",
        coherenceSubtitle = "The main theme of every surah and the connections between surahs according to the nazm school — Farahi, Islahi, and Mustansir Mir.",
        coherenceSource = "Source",
        coherenceCentralTheme = "The Qur'an's Central Theme",
        coherenceGroupLabel = "Group %d",
        coherenceNazmLabel = "Connection (nazm)",
        coherenceMethodology = "A summary of the nazm-school reading (not a literal quotation); it is one academic interpretive framework, not the only way to read the Qur'an.",
        wordMeaningLabel = "📖 Meaning:",
        favoritesTitle = "Favorite Ayahs",
        favoritesSubtitle = "Ayahs you marked with ★ on the Tahsin screen.",
        favoritesEmpty = "No favorite ayahs yet.\nOpen the Tahsin screen, pick an ayah, then tap ★ in the header.",
        favoritesLoading = "Loading favorite ayahs…",
        favoritesOpenHint = "Tap to open in the mushaf",
        learning = LearningStrings(
            settingLearningPlan = "Edit learning plan",
            statsPlanLine = "Today's plan: %d/%d activities complete",
            menuMemorization = "🧠 Memorization & Murajaah",
            todayTitle = "Today's plan",
            todaySubtitle = "%d focused minutes, one step at a time.",
            todayProgress = "%d/%d activities complete",
            todayComplete = "Today's plan complete ✓",
            todayTaskStart = "Start",
            todayTaskDone = "Done",
            todayExplore = "Explore all features",
            goalRecitation = "🕌 Improve recitation",
            goalUnderstanding = "📖 Understand meaning",
            goalMemorization = "🧠 Memorize and review",
            goalArabic = "📚 Learn Arabic",
            taskRecite = "Read and practice one ayah",
            taskTajwid = "Learn one tajweed rule",
            taskVocabulary = "Review Qur'anic vocabulary",
            taskUnderstand = "Study Qur'an coherence",
            taskArabic = "Practice an Arabic lesson",
            taskMemorization = "Practice memorization with the mushaf",
            onboardingTitle = "Start your learning journey",
            onboardingSubtitle = "Choose a primary direction. You can still open every feature at any time.",
            onboardingGoalQuestion = "What is your main focus?",
            onboardingTimeQuestion = "How much time would you like to set aside each day?",
            onboardingMinutes = "%d min",
            onboardingStart = "Start learning",
            memorizationTitle = "🧠 Memorization & Murajaah",
            memorizationSubtitle = "Test your memory, then schedule the ayah for review. " +
                "This is a practice aid, not a teacher assessment.",
            memorizationLoading = "Preparing your memorization queue…",
            memorizationDue = "%d of %d ayahs due for review",
            memorizationHidden = "Try reciting from memory before revealing the ayah.",
            memorizationReveal = "Reveal ayah",
            memorizationReview = "Review again",
            memorizationRemembered = "I remembered",
            memorizationOpenTahsin = "Practice in Tahsin ▸",
            memorizationError = "The memorization queue could not be loaded. Try again later.",
            memorizationRecite = "🎤 Recite from Memory",
            memorizationSttListening = "Listening to your recitation…",
            memorizationSttScore = "Score: %d%%",
            memorizationSttPass = "✓ Great! Move on to the next ayah.",
            memorizationSttFail = "✗ Needs more practice. Try reading slower.",
            memorizationTargetSurah = "Surah",
            memorizationTargetJuz = "Juz",
            memorizationApply = "Apply",
        ),
    )

    /** Judul badge terjemahan — key = [org.opennur.tahsin.util.BadgeDef.key]. */
    fun badgeTitle(key: String, lang: AppLanguage): String = when (lang) {
        AppLanguage.ID -> when (key) {
            "xp" -> "Pencari Ilmu"
            "streak" -> "Konsisten"
            "tahsin" -> "Tekun Berlatih"
            "tahsin-perfect" -> "Bacaan Sempurna"
            "vocab" -> "Pengumpul Kata"
            "dream" -> "Mimpi Besar"
            "lughoh" -> "Poliglot Pemula"
            "surah" -> "Penuntas Surah"
            else -> key
        }
        AppLanguage.EN -> when (key) {
            "xp" -> "Knowledge Seeker"
            "streak" -> "Consistent"
            "tahsin" -> "Dedicated Reciter"
            "tahsin-perfect" -> "Perfect Recitation"
            "vocab" -> "Word Collector"
            "dream" -> "Big Dreamer"
            "lughoh" -> "Budding Polyglot"
            "surah" -> "Surah Finisher"
            else -> key
        }
    }

    /** Deskripsi badge terjemahan — key = [org.opennur.tahsin.util.BadgeDef.key]. */
    fun badgeDesc(key: String, lang: AppLanguage): String = when (lang) {
        AppLanguage.ID -> when (key) {
            "xp" -> "Kumpulkan XP untuk naik level."
            "streak" -> "Pertahankan streak hari beruntun."
            "tahsin" -> "Selesaikan percobaan bacaan Tahsin."
            "tahsin-perfect" -> "Baca ayat dengan skor 90+."
            "vocab" -> "Kuasai kata kosakata."
            "dream" -> "Mainkan ronde Dream BIG."
            "lughoh" -> "Selesaikan sesi Belajar Arab."
            "surah" -> "Tamatkan surah: semua ayatnya pernah dibaca."
            else -> ""
        }
        AppLanguage.EN -> when (key) {
            "xp" -> "Earn XP to level up."
            "streak" -> "Keep your daily streak alive."
            "tahsin" -> "Complete Tahsin recitation attempts."
            "tahsin-perfect" -> "Recite ayahs with a 90+ score."
            "vocab" -> "Master vocabulary words."
            "dream" -> "Play Dream BIG rounds."
            "lughoh" -> "Finish Learn Arabic sessions."
            "surah" -> "Complete a surah: every ayah read at least once."
            else -> ""
        }
    }

    /**
     * Pesan error STT terjemahan dari kode [SpeechRecognizer] — pembungkus
     * STT tetap netral bahasa (hanya mengirim kode mentah).
     */
    fun sttErrorMessage(error: Int, lang: AppLanguage): String {
        val id = lang == AppLanguage.ID
        return when (error) {
            SpeechRecognizer.ERROR_NO_MATCH ->
                if (id) "Tidak ada yang cocok terdeteksi — coba baca lebih pelan dan jelas."
                else "Nothing matched — try reciting slower and clearer."
            SpeechRecognizer.ERROR_SPEECH_TIMEOUT ->
                if (id) "Tidak ada suara terdeteksi (timeout)."
                else "No speech detected (timeout)."
            SpeechRecognizer.ERROR_INSUFFICIENT_PERMISSIONS ->
                if (id) "Izin mikrofon belum diberikan."
                else "Microphone permission not granted."
            SpeechRecognizer.ERROR_NETWORK, SpeechRecognizer.ERROR_NETWORK_TIMEOUT ->
                if (id) "STT butuh internet (atau pasang paket bahasa Arab offline di pengaturan HP)."
                else "Speech recognition needs internet (or install the offline Arabic pack in device settings)."
            SpeechRecognizer.ERROR_RECOGNIZER_BUSY ->
                if (id) "SpeechRecognizer sedang sibuk — coba lagi."
                else "Speech recognizer is busy — try again."
            else ->
                if (id) "Error speech recognition (kode $error)."
                else "Speech recognition error (code $error)."
        }
    }
}
