package org.opennur.tahsin.ui

/**
 * Konten layar "Studi Coherence (Nazm) Al-Qur'an".
 *
 * Ringkasan pembacaan nazm (keteraturan/keterkaitan antar surah) ala
 * Hamiduddin Farahi, Amin Ahsan Islahi (Tadabbur-i-Qur'an), dan Mustansir Mir
 * (Coherence in the Qur'an, 1986). Setiap surah punya SATU tema pusat (amud),
 * surah-surah berpasangan saling melengkapi, dan seluruh Qur'an terbagi dalam
 * 7 kelompok yang masing-masing memuat fase dakwah. Ini SATU kerangka
 * tafsir akademis (mazhab nazm) — bukan satu-satunya cara membaca Al-Qur'an,
 * dan ringkasan ini bukan kutipan harfiah dari kitab-kitab tersebut.
 */

/** Satu surah: tema pusat (amud) + keterkaitan nazm, ID + EN. */
data class CoherenceSurah(
    val number: Int,
    val name: String,
    val group: Int,
    val amudId: String,
    val amudEn: String,
    val nazmId: String,
    val nazmEn: String,
)

/** Satu kelompok surah dalam struktur 7-grup Islahi. */
data class CoherenceGroup(
    val number: Int,
    val rangeId: String,
    val rangeEn: String,
    val themeId: String,
    val themeEn: String,
)

/** Konten statis Studi Coherence (dua bahasa). */
object CoherenceContent {

    /** Tema pusat seluruh Al-Qur'an menurut mazhab nazm (ringkasan, bukan kutipan). */
    val centralThemeId: String =
        "Menurut Farahi–Islahi, Al-Qur'an adalah satu kitab yang utuh dengan satu " +
            "tema pusat: kehidupan manusia adalah ibadah kepada Allah semata, di atas " +
            "tiga pilar — tauhid, risalah (kenabian), dan akhirat."
    val centralThemeEn: String =
        "According to Farahi–Islahi, the Qur'an is one unified book with a single " +
            "central theme: human life is servitude ('ibadah) to God alone, resting on " +
            "three pillars — tawhid, risalah (prophethood), and the Hereafter."

    /** Struktur 7 kelompok (diverifikasi: situs resmi Islahi, Mir 1986, Oxford Dict. of Islam). */
    val groups: List<CoherenceGroup> = listOf(
        CoherenceGroup(1, "1–5", "1–5", "Hukum Islam", "Islamic law"),
        CoherenceGroup(2, "6–9", "6–9", "Akibat penolakan terhadap Nabi bagi kaum musyrik Makkah", "Consequences of denying the Prophet for the Makkan polytheists"),
        CoherenceGroup(3, "10–24", "10–24", "Kabar gembira akan kemenangan Nabi", "Glad tidings of the Prophet's dominance"),
        CoherenceGroup(4, "25–33", "25–33", "Argumentasi kenabian Muhammad ﷺ dan tuntutan iman kepadanya", "Arguments for the prophethood of Muhammad ﷺ and the requirements of faith in him"),
        CoherenceGroup(5, "34–49", "34–49", "Argumentasi tauhid dan tuntutan iman kepadanya", "Arguments for tawhid and the requirements of faith in it"),
        CoherenceGroup(6, "50–66", "50–66", "Argumentasi akhirat dan tuntutan iman kepadanya", "Arguments for the Hereafter and the requirements of faith in it"),
        CoherenceGroup(7, "67–114", "67–114", "Peringatan kepada Quraisy tentang nasib mereka di dunia dan akhirat", "Admonition to the Quraysh about their fate here and hereafter"),
    )

    val surahs: List<CoherenceSurah> = listOf(
        CoherenceSurah(1, "Al-Fatihah", 1,
            "Pembuka seluruh Al-Qur'an: pujian kepada Allah dan permohonan petunjuk.",
            "Introduction to the whole Qur'an: praise of God and the petition for guidance.",
            "Pembukaan bagi seluruh kitab dan kelompok pertama; tidak berpasangan.",
            "Preface to the whole book and to the first group; unpaired."),
        CoherenceSurah(2, "Al-Baqarah", 1,
            "Al-Qur'an sebagai petunjuk; ajakan kepada Ahli Kitab (Yahudi).",
            "The Book as guidance; a summons to the People of the Book (the Jews).",
            "Berpasangan dengan Ali 'Imran: keduanya berbicara kepada Ahli Kitab.",
            "Paired with Ali 'Imran: both address the People of the Book."),
        CoherenceSurah(3, "Ali 'Imran", 1,
            "Lanjutan tema: keluarga 'Imran dan dialog dengan kaum Nasrani.",
            "Same theme continued: the family of 'Imran and dialogue with the Christians.",
            "Pasangan Al-Baqarah: hukum & dakwah → contoh keluarga Nabi.",
            "Pair of Al-Baqarah: law & da'wah → the example of the prophet's family."),
        CoherenceSurah(4, "An-Nisa'", 1,
            "Hak dan kewajiban perempuan, keluarga, dan masyarakat.",
            "Rights and obligations of women, the family, and society.",
            "Berpasangan dengan Al-Ma'idah: hukum keluarga → penyempurnaan agama.",
            "Paired with Al-Ma'idah: family law → the completion of religion."),
        CoherenceSurah(5, "Al-Ma'idah", 1,
            "Perjanjian-perjanjian; penyempurnaan agama; hukum Islam.",
            "Covenants; the completion of religion; Islamic law.",
            "Pasangan An-Nisa': penutup hukum → nikmat sempurna bagi umat.",
            "Pair of An-Nisa': the close of legislation → the completed blessing."),
        CoherenceSurah(6, "Al-An'am", 2,
            "Argumentasi tauhid dan bantahan terhadap syirik.",
            "Arguments for tawhid and the refutation of shirk.",
            "Berpasangan dengan Al-A'raf: tauhid → nasib bangsa-bangsa.",
            "Paired with Al-A'raf: tawhid → the fate of nations."),
        CoherenceSurah(7, "Al-A'raf", 2,
            "Nasib bangsa yang menolak para nabi; penghuni A'raf.",
            "The fate of nations that rejected the prophets; the people of the Heights.",
            "Pasangan Al-An'am: bukti tauhid → peringatan lewat sejarah.",
            "Pair of Al-An'am: proofs of tawhid → warnings from history."),
        CoherenceSurah(8, "Al-Anfal", 2,
            "Perang Badar; pertahanan dan harta rampasan umat.",
            "Badr; the community's defense and the spoils of war.",
            "Berpasangan dengan At-Taubah: perang pembelaan → pemutusan dengan musyrik.",
            "Paired with At-Taubah: defensive war → disavowal of the polytheists."),
        CoherenceSurah(9, "At-Taubah", 2,
            "Pembebasan (bara'ah); Tabuk; perang terhadap kaum musyrik.",
            "Disavowal (bara'ah); Tabuk; war against the polytheists.",
            "Pasangan Al-Anfal: jihad → keputusan akhir atas kaum musyrik.",
            "Pair of Al-Anfal: jihad → the final ruling on the polytheists."),
        CoherenceSurah(10, "Yunus", 3,
            "Nasib bangsa yang mendustakan para rasul; tanda-tanda Allah.",
            "The fate of nations that denied their messengers; God's signs.",
            "Berpasangan dengan Hud: rasul dan nasib kaumnya.",
            "Paired with Hud: the messenger and the fate of his people."),
        CoherenceSurah(11, "Hud", 3,
            "Kisah 'Ad, Tsamud, dan Nuh; kesabaran para nabi.",
            "The stories of 'Ad, Thamud, and Nuh; the patience of the prophets.",
            "Pasangan Yunus: kabar gembira & ancaman dalam kisah umat.",
            "Pair of Yunus: glad tidings and warnings in the stories of nations."),
        CoherenceSurah(12, "Yusuf", 3,
            "Kenabian yang bekerja dalam kehidupan keluarga dan masyarakat.",
            "Prophethood at work within family and community life.",
            "Berpasangan dengan Ar-Ra'd: kisah indah → kebenaran wahyu.",
            "Paired with Ar-Ra'd: the beautiful story → the truth of revelation."),
        CoherenceSurah(13, "Ar-Ra'd", 3,
            "Kebenaran wahyu; guruh dan kekuasaan Allah di alam.",
            "The truth of revelation; thunder and God's power in nature.",
            "Pasangan Yusuf: kisah → tanda-tanda di alam semesta.",
            "Pair of Yusuf: story → signs in the cosmos."),
        CoherenceSurah(14, "Ibrahim", 3,
            "Misi Ibrahim: tauhid, doa, dan warisan para nabi.",
            "Abraham's mission: tawhid, prayer, and the legacy of the prophets.",
            "Berpasangan dengan Al-Hijr: bapak para nabi → nasib kaum yang dimusnahkan.",
            "Paired with Al-Hijr: the father of prophets → the fate of the destroyed nations."),
        CoherenceSurah(15, "Al-Hijr", 3,
            "Nasib orang-orang yang mendustakan; penjagaan Allah atas Al-Qur'an.",
            "The fate of the deniers; God's protection of the Qur'an.",
            "Pasangan Ibrahim: doa bapak para nabi → ancaman bagi pendusta.",
            "Pair of Ibrahim: the patriarch's prayer → warning to the deniers."),
        CoherenceSurah(16, "An-Nahl", 3,
            "Nikmat Allah di alam sebagai bukti tauhid.",
            "God's bounties in creation as proofs of tawhid.",
            "Berpasangan dengan Al-Isra': bukti-bukti Allah → kisah Bani Israil.",
            "Paired with Al-Isra': proofs of God → the story of the Children of Israel."),
        CoherenceSurah(17, "Al-Isra'", 3,
            "Bani Israil; peristiwa Isra' dan perjalanan malam.",
            "The Children of Israel; the Isra' (night journey).",
            "Pasangan An-Nahl: tanda di alam → sejarah Bani Israil.",
            "Pair of An-Nahl: signs in nature → the history of Israel's children."),
        CoherenceSurah(18, "Al-Kahf", 3,
            "Ujian iman: harta, ilmu, kekuasaan, dan penganiayaan.",
            "Trials of faith: wealth, knowledge, power, and persecution.",
            "Berpasangan dengan Maryam: perlindungan saat ujian → rahmat Allah bagi para nabi.",
            "Paired with Maryam: protection through trial → God's mercy to His prophets."),
        CoherenceSurah(19, "Maryam", 3,
            "Maryam dan 'Isa; rahmat Allah kepada para nabi.",
            "Mary and Jesus; God's mercy to His prophets.",
            "Pasangan Al-Kahf: ujian → kisah keluarga yang saleh.",
            "Pair of Al-Kahf: trials → the stories of the righteous families."),
        CoherenceSurah(20, "Taha", 3,
            "Misi Musa; Al-Qur'an sebagai peringatan.",
            "Moses' mission; the Qur'an as a reminder.",
            "Berpasangan dengan Al-Anbiya: satu kisah nabi → para nabi sebagai satu umat.",
            "Paired with Al-Anbiya: one prophet's story → the prophets as one community."),
        CoherenceSurah(21, "Al-Anbiya", 3,
            "Para nabi: satu agama, satu perjuangan.",
            "The prophets: one religion, one struggle.",
            "Pasangan Taha: kisah Musa → kesatuan risalah seluruh nabi.",
            "Pair of Taha: Moses' story → the unity of all prophetic missions."),
        CoherenceSurah(22, "Al-Hajj", 3,
            "Rumah Allah (Ka'bah) dan perjuangan di jalan-Nya.",
            "The House of God (the Kaaba) and striving in His way.",
            "Berpasangan dengan Al-Mu'minun: ibadah di Rumah-Nya → karakter mukmin.",
            "Paired with Al-Mu'minun: worship at His House → the character of the believers."),
        CoherenceSurah(23, "Al-Mu'minun", 3,
            "Sifat-sifat orang beriman: iman, salat, dan keberuntungan (falah).",
            "The believers: faith, prayer, and success (falah).",
            "Pasangan Al-Hajj: simbol umat → akhlak umat.",
            "Pair of Al-Hajj: the ummah's symbol → the ummah's character."),
        CoherenceSurah(24, "An-Nur", 3,
            "Cahaya (nur) Allah; kesucian masyarakat (kisah ifk).",
            "The Light; the purity of society (the story of the slander).",
            "Berpasangan dengan Al-Furqan: cahaya → pembeda hak dan batil.",
            "Paired with Al-Furqan: the Light → the Criterion of truth and falsehood."),
        CoherenceSurah(25, "Al-Furqan", 4,
            "Al-Furqan: pembeda antara kebenaran dan kebatilan.",
            "Al-Furqan: the Criterion between truth and falsehood.",
            "Pasangan An-Nur: cahaya masyarakat → standar kebenaran.",
            "Pair of An-Nur: society's light → the standard of truth."),
        CoherenceSurah(26, "Asy-Syu'ara", 4,
            "Para rasul dan kaumnya; dakwah yang ditolak.",
            "The messengers and their peoples; rejected calls.",
            "Berpasangan dengan An-Naml: pesan para nabi → kerajaan para nabi.",
            "Paired with An-Naml: the prophets' message → the prophets' kingdoms."),
        CoherenceSurah(27, "An-Naml", 4,
            "Para nabi (Sulaiman, Musa); tanda-tanda kekuasaan Allah.",
            "The prophets (Solomon, Moses); signs of God's power.",
            "Pasangan Asy-Syu'ara: dakwah → kerajaan yang adil.",
            "Pair of Ash-Shu'ara: da'wah → a just kingdom."),
        CoherenceSurah(28, "Al-Qasas", 4,
            "Kisah Musa yang lengkap; awal hingga akhir misinya.",
            "The full story of Moses; from the beginning to the end of his mission.",
            "Berpasangan dengan Al-'Ankabut: kisah Musa → ujian orang beriman.",
            "Paired with Al-'Ankabut: Moses' story → the trials of the believers."),
        CoherenceSurah(29, "Al-'Ankabut", 4,
            "Ujian iman; rumah laba-laba sebagai perumpamaan.",
            "Trials of faith; the spider's house as a parable.",
            "Pasangan Al-Qasas: kisah nabi → ujian para pengikutnya.",
            "Pair of Al-Qasas: the prophet's story → the trials of his followers."),
        CoherenceSurah(30, "Ar-Rum", 4,
            "Bangkit dan runtuhnya bangsa-bangsa (kemenangan Romawi).",
            "The rise and fall of nations (the Byzantine victory).",
            "Berpasangan dengan Luqman: nasib bangsa → hikmah individu.",
            "Paired with Luqman: nations' fortunes → individual wisdom."),
        CoherenceSurah(31, "Luqman", 4,
            "Hikmah; nasihat Luqman kepada anaknya.",
            "Wisdom; Luqman's counsel to his son.",
            "Pasangan Ar-Rum: sejarah bangsa → pelajaran untuk keluarga.",
            "Pair of Ar-Rum: history of nations → lessons for the family."),
        CoherenceSurah(32, "As-Sajdah", 4,
            "Penciptaan dan kebangkitan.",
            "Creation and resurrection.",
            "Berpasangan dengan Al-Ahzab: ciptaan & kebangkitan → konspirasi musuh.",
            "Paired with Al-Ahzab: creation & resurrection → the conspirators' plot."),
        CoherenceSurah(33, "Al-Ahzab", 4,
            "Perang Ahzab; rumah tangga Nabi.",
            "The Confederates; the Prophet's household.",
            "Pasangan As-Sajdah: ketetapan Allah → kemenangan atas persekutuan musuh.",
            "Pair of As-Sajdah: God's decree → victory over the confederacy."),
        CoherenceSurah(34, "Saba'", 5,
            "Negeri Saba': kemakmuran, syukur, dan kehancuran.",
            "Sheba: prosperity, gratitude, and decline.",
            "Berpasangan dengan Fatir: jatuh-bangun bangsa → tanda Sang Pencipta.",
            "Paired with Fatir: a nation's rise and fall → the Creator's signs."),
        CoherenceSurah(35, "Fatir", 5,
            "Sang Pencipta; penciptaan sebagai bukti tauhid.",
            "The Creator; creation as proof of tawhid.",
            "Pasangan Saba': pelajaran sejarah → dalil tauhid.",
            "Pair of Saba': lessons of history → the proofs of tawhid."),
        CoherenceSurah(36, "Ya-Sin", 5,
            "Al-Qur'an dan misi Nabi; \"jantung Al-Qur'an\".",
            "The Qur'an and the Prophet's mission; the \"heart of the Qur'an\".",
            "Berpasangan dengan As-Saffat: pesan → para utusan dalam barisan.",
            "Paired with As-Saffat: the message → the messengers in ranks."),
        CoherenceSurah(37, "As-Saffat", 5,
            "Para malaikat dan rasul dalam barisan; nasib para pendusta.",
            "Angels and messengers in ranks; the fate of the deniers.",
            "Pasangan Ya-Sin: seruan → barisan penegak kebenaran.",
            "Pair of Ya-Sin: the call → the ranks upholding truth."),
        CoherenceSurah(38, "Sad", 5,
            "Kedurhakaan para penentang; kisah Dawud, Sulaiman, Ayyub.",
            "The defiance of the rejecters; the stories of David, Solomon, Job.",
            "Berpasangan dengan Az-Zumar: penentang → dua golongan di hari kiamat.",
            "Paired with Az-Zumar: the defiant → the two groups on the Day."),
        CoherenceSurah(39, "Az-Zumar", 5,
            "Golongan-golongan (zumar): mukmin vs. pendusta.",
            "The groups (zumar): believers vs. rejecters.",
            "Pasangan Sad: kesombongan penentang → keputusan hari kiamat.",
            "Pair of Sad: the deniers' pride → the verdict of the Day."),
        CoherenceSurah(40, "Ghafir", 5,
            "Iman dan penolakan; mukmin keluarga Fir'aun.",
            "Faith and rejection; the believer of Pharaoh's household.",
            "Berpasangan dengan Fussilat: iman yang dibela → ayat yang diperinci.",
            "Paired with Fussilat: faith defended → revelation detailed."),
        CoherenceSurah(41, "Fussilat", 5,
            "Ayat-ayat yang diperinci; Al-Qur'an sebagai pembeda.",
            "The detailed signs; the Qur'an as the discrimination.",
            "Pasangan Ghafir: pengikut Fir'aun → dalil yang gamblang.",
            "Pair of Ghafir: Pharaoh's follower → the clear evidence."),
        CoherenceSurah(42, "Asy-Syura", 5,
            "Musyawarah; wahyu sebagai perintah Allah.",
            "Consultation; revelation as God's command.",
            "Berpasangan dengan Az-Zukhruf: wahyu yang dibenarkan → hiasan dunia.",
            "Paired with Az-Zukhruf: the confirmed revelation → worldly ornament."),
        CoherenceSurah(43, "Az-Zukhruf", 5,
            "Perhiasan dunia vs. Kitab Allah.",
            "Worldly ornament vs. the Book of God.",
            "Pasangan Asy-Syura: keputusan wahyu → tipuan kemewahan.",
            "Pair of Ash-Shura: revelation's verdict → the lure of luxury."),
        CoherenceSurah(44, "Ad-Dukhan", 5,
            "Peringatan yang jelas; kabut (dukhan).",
            "The clear warning; the smoke (dukhan).",
            "Berpasangan dengan Al-Jasiyah: peringatan → bangsa-bangsa berlutut.",
            "Paired with Al-Jathiyah: the warning → the nations kneeling."),
        CoherenceSurah(45, "Al-Jasiyah", 5,
            "Bangsa-bangsa berlutut di hadapan Allah.",
            "The nations kneeling before God.",
            "Pasangan Ad-Dukhan: azab yang dijanjikan → kesaksian di hadapan Allah.",
            "Pair of Ad-Dukhan: the promised punishment → testimony before God."),
        CoherenceSurah(46, "Al-Ahqaf", 5,
            "Kaum 'Ad; Nabi di tengah kaumnya.",
            "The people of 'Ad; the Messenger among his people.",
            "Berpasangan dengan Muhammad: nasib 'Ad → perjuangan Nabi sendiri.",
            "Paired with Muhammad: the fate of 'Ad → the Prophet's own struggle."),
        CoherenceSurah(47, "Muhammad", 5,
            "Orang beriman vs. kafir; perang Nabi.",
            "The believers vs. the disbelievers; the Prophet's war.",
            "Pasangan Al-Ahqaf: pelajaran kaum terdahulu → perintah berperang.",
            "Pair of Al-Ahqaf: lessons of past nations → the command to fight."),
        CoherenceSurah(48, "Al-Fath", 5,
            "Kemenangan; perjanjian Hudaibiyah.",
            "The victory; the treaty of Hudaybiyyah.",
            "Berpasangan dengan Al-Hujurat: kemenangan tanpa perang → etika sosial mukmin.",
            "Paired with Al-Hujurat: victory without battle → the believers' social ethics."),
        CoherenceSurah(49, "Al-Hujurat", 5,
            "Adab dan etika bermasyarakat bagi orang beriman.",
            "Manners and community ethics for the believers.",
            "Pasangan Al-Fath: kemenangan → adab pemenang.",
            "Pair of Al-Fath: victory → the etiquette of the victors."),
        CoherenceSurah(50, "Qaf", 6,
            "Kebangkitan; pengingkaran para pendusta.",
            "Resurrection; the denial of the rejecters.",
            "Berpasangan dengan Az-Zariyat: kebangkitan → tanda-tanda di alam.",
            "Paired with Adh-Dhariyat: resurrection → signs in creation."),
        CoherenceSurah(51, "Az-Zariyat", 6,
            "Angin yang menerbangkan; tanda-tanda kekuasaan Allah.",
            "The winnowing winds; God's signs in creation.",
            "Pasangan Qaf: kepastian hari akhir → bukti dari alam.",
            "Pair of Qaf: the certainty of the Last Day → proofs from nature."),
        CoherenceSurah(52, "At-Tur", 6,
            "Gunung Tur; ancaman azab yang dijanjikan.",
            "Mount Sinai; the threatened punishment.",
            "Berpasangan dengan An-Najm: perjanjian → wahyu (bintang).",
            "Paired with An-Najm: the covenant → the revelation (the star)."),
        CoherenceSurah(53, "An-Najm", 6,
            "Bintang; wahyu dan perjalanan naik Nabi.",
            "The star; revelation and the Prophet's ascent.",
            "Pasangan At-Tur: ancaman → bukti wahyu yang nyata.",
            "Pair of At-Tur: the threat → the manifest proof of revelation."),
        CoherenceSurah(54, "Al-Qamar", 6,
            "Bulan; peringatan yang telah terbukti.",
            "The moon; the fulfilled warning.",
            "Berpasangan dengan Ar-Rahman: peringatan → rahmat yang luas.",
            "Paired with Ar-Rahman: the warning → the all-embracing mercy."),
        CoherenceSurah(55, "Ar-Rahman", 6,
            "Sang Maha Pemurah; nikmat-nikmat-Nya (dua surga).",
            "The Merciful; His blessings (the two gardens).",
            "Pasangan Al-Qamar: azab bagi pendusta → nikmat bagi yang bersyukur.",
            "Pair of Al-Qamar: punishment for deniers → blessings for the grateful."),
        CoherenceSurah(56, "Al-Waqi'ah", 6,
            "Hari Kiamat; tiga golongan manusia.",
            "The Inevitable; the three groups of people on the Day.",
            "Berpasangan dengan Al-Hadid: nasib di hari akhir → dunia materi (besi).",
            "Paired with Al-Hadid: the Day's outcome → the material world (iron)."),
        CoherenceSurah(57, "Al-Hadid", 6,
            "Besi; dunia materi dan akhirat.",
            "Iron; the material world and the Hereafter.",
            "Pasangan Al-Waqi'ah: hari akhir → perbekalan di dunia.",
            "Pair of Al-Waqi'ah: the Last Day → provision in this world."),
        CoherenceSurah(58, "Al-Mujadalah", 6,
            "Perempuan yang bersengketa; adab berdiskusi.",
            "The woman who disputed; the etiquette of discourse.",
            "Berpasangan dengan Al-Hasyr: aturan diskusi → pengusiran Bani Nadir.",
            "Paired with Al-Hashr: rules of discourse → the exile of Banu Nadir."),
        CoherenceSurah(59, "Al-Hasyr", 6,
            "Pengusiran (Bani Nadir); akhirat sebagai tujuan.",
            "The exile; the Hereafter as the goal.",
            "Pasangan Al-Mujadalah: sengketa internal → hukuman bagi pengkhianat.",
            "Pair of Al-Mujadalah: internal disputes → punishment for the traitors."),
        CoherenceSurah(60, "Al-Mumtahanah", 6,
            "Perempuan yang diuji; batas hubungan dengan non-muslim.",
            "The examined woman; boundaries of relations with non-Muslims.",
            "Berpasangan dengan As-Saff: batas loyalitas → persatuan mukmin.",
            "Paired with As-Saff: limits of loyalty → the unity of the believers."),
        CoherenceSurah(61, "As-Saff", 6,
            "Barisan; persatuan orang beriman.",
            "The ranks; the unity of the believers.",
            "Pasangan Al-Mumtahanah: pemisahan dari musuh → kesatuan barisan.",
            "Pair of Al-Mumtahanah: separation from enemies → unity in ranks."),
        CoherenceSurah(62, "Al-Jumu'ah", 6,
            "Hari Jumat; prioritas jamaah.",
            "Friday; the congregation's priorities.",
            "Berpasangan dengan Al-Munafiqun: jamaah sejati → kaum munafik.",
            "Paired with Al-Munafiqun: the true congregation → the hypocrites."),
        CoherenceSurah(63, "Al-Munafiqun", 6,
            "Orang-orang munafik.",
            "The hypocrites.",
            "Pasangan Al-Jumu'ah: panggilan salat → yang meninggalkan jamaah.",
            "Pair of Al-Jumu'ah: the call to prayer → those who abandon the congregation."),
        CoherenceSurah(64, "At-Taghabun", 6,
            "Kerugian timbal-balik pada hari kiamat.",
            "Mutual loss on the Day of Judgment.",
            "Berpasangan dengan At-Talaq: kerugian hari akhir → hukum keluarga.",
            "Paired with At-Talaq: the Day's loss → family law."),
        CoherenceSurah(65, "At-Talaq", 6,
            "Talak; hukum keluarga.",
            "Divorce; family law.",
            "Pasangan At-Taghabun: hisab akhir → ketakwaan dalam keluarga.",
            "Pair of At-Taghabun: the final reckoning → taqwa within the family."),
        CoherenceSurah(66, "At-Tahrim", 6,
            "Larangan; rumah tangga Nabi.",
            "The prohibition; the Prophet's household.",
            "Jembatan ke kelompok 7: rumah tangga Nabi → kekuasaan Allah (Al-Mulk).",
            "Bridge to group 7: the Prophet's household → God's sovereignty (Al-Mulk)."),
        CoherenceSurah(67, "Al-Mulk", 7,
            "Kerajaan Allah; kekuasaan-Nya atas segala sesuatu.",
            "The Sovereignty; God's dominion over all things.",
            "Pasangan At-Tahrim: pembuka kelompok akhir → peringatan kepada Quraisy.",
            "Pair of At-Tahrim: opening the final group → the warning to the Quraysh."),
        CoherenceSurah(68, "Al-Qalam", 7,
            "Pena; akhlak Nabi yang agung.",
            "The Pen; the Prophet's noble character.",
            "Berpasangan dengan Al-Haqqah: akhlak Nabi → hari kiamat yang pasti.",
            "Paired with Al-Haqqah: the Prophet's character → the sure Reality."),
        CoherenceSurah(69, "Al-Haqqah", 7,
            "Hari Kiamat yang pasti terjadi.",
            "The Inevitable Reality; the Day.",
            "Pasangan Al-Qalam: tuduhan gila pada Nabi → kebenaran hari akhir.",
            "Pair of Al-Qalam: the charge of madness → the truth of the Last Day."),
        CoherenceSurah(70, "Al-Ma'arij", 7,
            "Tempat-tempat naik; orang yang tergesa-gesa.",
            "The Ascents; the impatient man.",
            "Berpasangan dengan Nuh: jalan naik → misi Nuh.",
            "Paired with Nuh: the ways of ascent → Noah's mission."),
        CoherenceSurah(71, "Nuh", 7,
            "Misi Nabi Nuh kepada kaumnya.",
            "Noah's mission to his people.",
            "Pasangan Al-Ma'arij: jalan menuju Allah → dakwah yang panjang.",
            "Pair of Al-Ma'arij: the path to God → the long da'wah."),
        CoherenceSurah(72, "Al-Jinn", 7,
            "Jin yang mendengar Al-Qur'an.",
            "The jinn hearing the Qur'an.",
            "Berpasangan dengan Al-Muzzammil: pendengar gaib → Nabi yang salat malam.",
            "Paired with Al-Muzzammil: unseen listeners → the Prophet praying at night."),
        CoherenceSurah(73, "Al-Muzzammil", 7,
            "Orang yang berselimut; salat malam.",
            "The enfolded one; night prayer.",
            "Pasangan Al-Jinn: keteguhan iman → persiapan menghadapi dakwah berat.",
            "Pair of Al-Jinn: firm faith → preparation for the heavy call."),
        CoherenceSurah(74, "Al-Muddassir", 7,
            "Orang yang berselimut; peringatan.",
            "The wrapped one; the warning.",
            "Berpasangan dengan Al-Qiyamah: peringatan → kebangkitan.",
            "Paired with Al-Qiyamah: the warning → the resurrection."),
        CoherenceSurah(75, "Al-Qiyamah", 7,
            "Kebangkitan ditegaskan lewat hati nurani manusia.",
            "Resurrection affirmed through the human conscience.",
            "Pasangan Al-Muddassir: seruan peringatan → hari yang pasti.",
            "Pair of Al-Muddaththir: the call to warn → the certain Day."),
        CoherenceSurah(76, "Al-Insan", 7,
            "Manusia; balasan bagi orang-orang yang berbakti (abrar).",
            "The human being; the reward of the righteous (abrar).",
            "Berpasangan dengan Al-Mursalat: pilihan manusia → utusan-utusan hari akhir.",
            "Paired with Al-Mursalat: man's choice → the emissaries of the Day."),
        CoherenceSurah(77, "Al-Mursalat", 7,
            "Utusan-utusan; hari kiamat.",
            "The emissaries; the Day.",
            "Pasangan Al-Insan: kebaikan yang dipilih → kepastian pembalasan.",
            "Pair of Al-Insan: the good one chooses → the certainty of recompense."),
        CoherenceSurah(78, "An-Naba", 7,
            "Berita besar; kebangkitan.",
            "The Great News; resurrection.",
            "Berpasangan dengan An-Nazi'at: berita kebangkitan → malaikat pencabut nyawa.",
            "Paired with An-Nazi'at: the news of resurrection → the angels of death."),
        CoherenceSurah(79, "An-Nazi'at", 7,
            "Malaikat yang mencabut; dahsyatnya hari kiamat.",
            "The pluckers; the terror of the Day.",
            "Pasangan An-Naba: kabar gembira bagi mukmin → dahsyat bagi pendusta.",
            "Pair of An-Naba: good news for believers → terror for the deniers."),
        CoherenceSurah(80, "'Abasa", 7,
            "Ia bermuka masam; Nabi dan sahabat tunanetra.",
            "He frowned; the Prophet and the blind companion.",
            "Berpasangan dengan At-Takwir: adab Nabi → tergulungnya alam semesta.",
            "Paired with At-Takwir: the Prophet's conduct → the folding up of the cosmos."),
        CoherenceSurah(81, "At-Takwir", 7,
            "Penggulungan; akhir dunia.",
            "The folding up; the end of the world.",
            "Pasangan 'Abasa: peringatan kepada manusia → kebenaran wahyu.",
            "Pair of 'Abasa: warning to man → the truth of revelation."),
        CoherenceSurah(82, "Al-Infitar", 7,
            "Terbelahnya langit; hari hisab.",
            "The cleaving; the Day of Reckoning.",
            "Berpasangan dengan Al-Mutaffifin: hari hisab → para pengurangan takaran.",
            "Paired with Al-Mutaffifin: the Reckoning → the defrauders."),
        CoherenceSurah(83, "Al-Mutaffifin", 7,
            "Para pengurangan takaran; catatan yang tersegel.",
            "The defrauders; the sealed record.",
            "Pasangan Al-Infitar: hisab umum → kecurangan dalam timbangan.",
            "Pair of Al-Infitar: the general reckoning → cheating in the scales."),
        CoherenceSurah(84, "Al-Insyiqaq", 7,
            "Terbelahnya langit; hari pembalasan.",
            "The splitting; the Day.",
            "Berpasangan dengan Al-Buruj: hari yang terbuka → para saksi (bintang-bintang).",
            "Paired with Al-Buruj: the opened Day → the witnesses (constellations)."),
        CoherenceSurah(85, "Al-Buruj", 7,
            "Gugusan bintang; para penggali parit.",
            "The constellations; the people of the ditch.",
            "Pasangan Al-Insyiqaq: ketetapan Allah → ujian para mukmin terdahulu.",
            "Pair of Al-Inshiqaq: God's decree → the trials of earlier believers."),
        CoherenceSurah(86, "At-Tariq", 7,
            "Bintang yang datang di malam; penjaga setiap jiwa.",
            "The night-comer; a guardian over every soul.",
            "Berpasangan dengan Al-A'la: bintang penembus → pengingat Yang Maha Tinggi.",
            "Paired with Al-A'la: the piercing star → the reminder of the Most High."),
        CoherenceSurah(87, "Al-A'la", 7,
            "Yang Maha Tinggi; peringatan yang mudah.",
            "The Most High; the easy reminder.",
            "Pasangan At-Tariq: penjagaan jiwa → jalan penyucian.",
            "Pair of At-Tariq: the guarding of the soul → the path of purification."),
        CoherenceSurah(88, "Al-Gasyiyah", 7,
            "Hari yang meliputi; wajah-wajah di hari itu.",
            "The Overwhelming; the faces on that Day.",
            "Berpasangan dengan Al-Fajr: hari yang meliputi → azab bangsa terdahulu.",
            "Paired with Al-Fajr: the overwhelming Day → the doom of past nations."),
        CoherenceSurah(89, "Al-Fajr", 7,
            "Fajar; 'Ad, Tsamud, dan Fir'aun.",
            "The Dawn; 'Ad, Thamud, and Pharaoh.",
            "Pasangan Al-Gasyiyah: peringatan bagi kaum → umat yang durhaka.",
            "Pair of Al-Ghashiyah: warning to the tribe → the disobedient nations."),
        CoherenceSurah(90, "Al-Balad", 7,
            "Negeri (Makkah); perjuangan manusia.",
            "The City (Makkah); the human struggle.",
            "Berpasangan dengan Asy-Syams: kota Nabi → matahari penyucian jiwa.",
            "Paired with Ash-Shams: the Prophet's city → the sun of soul-purification."),
        CoherenceSurah(91, "Asy-Syams", 7,
            "Matahari; penyucian jiwa.",
            "The Sun; purification of the soul.",
            "Pasangan Al-Balad: kesulitan hidup → kunci keselamatan jiwa.",
            "Pair of Al-Balad: life's hardship → the key to the soul's salvation."),
        CoherenceSurah(92, "Al-Lail", 7,
            "Malam; dua jalan hidup.",
            "The Night; the two ways.",
            "Berpasangan dengan Ad-Duha: dua jalan → penghiburan di pagi hari.",
            "Paired with Ad-Duha: the two ways → consolation in the forenoon."),
        CoherenceSurah(93, "Ad-Duha", 7,
            "Waktu dhuha; penghiburan bagi Nabi.",
            "The Forenoon; consolation for the Prophet.",
            "Pasangan Al-Lail: kegelapan malam → cahaya pagi bagi Nabi.",
            "Pair of Al-Layl: the dark night → morning light for the Prophet."),
        CoherenceSurah(94, "Al-Insyirah", 7,
            "Kelapangan dada Nabi.",
            "The expansion of the Prophet's breast.",
            "Berpasangan dengan At-Tin: kelapangan → fitrah manusia.",
            "Paired with At-Tin: relief → the human constitution."),
        CoherenceSurah(95, "At-Tin", 7,
            "Buah tin; fitrah manusia.",
            "The Fig; the human's nature.",
            "Pasangan Al-Insyirah: kemudahan setelah kesulitan → keadilan hari akhir.",
            "Pair of Al-Inshirah: ease after hardship → the justice of the Last Day."),
        CoherenceSurah(96, "Al-'Alaq", 7,
            "Segumpal darah; wahyu pertama (iqra').",
            "The Clot; the first revelation (iqra').",
            "Berpasangan dengan Al-Qadr: wahyu pertama → malam Lailatul Qadar.",
            "Paired with Al-Qadr: the first revelation → the Night of Power."),
        CoherenceSurah(97, "Al-Qadr", 7,
            "Lailatul Qadar; malam kemuliaan.",
            "The Night of Power; the night of honour.",
            "Pasangan Al-'Alaq: awal wahyu → malam diturunkannya wahyu.",
            "Pair of Al-'Alaq: the start of revelation → the night it was sent down."),
        CoherenceSurah(98, "Al-Bayyinah", 7,
            "Bukti yang nyata; Ahli Kitab dan kaum musyrik.",
            "The Clear Proof; the People of the Book and the polytheists.",
            "Berpasangan dengan Az-Zalzalah: bukti → gempa hari kiamat.",
            "Paired with Az-Zalzalah: the proof → the earthquake of the Day."),
        CoherenceSurah(99, "Az-Zalzalah", 7,
            "Gempa bumi; ditimbangnya amal.",
            "The Earthquake; the weighing of deeds.",
            "Pasangan Al-Bayyinah: seruan beriman → hisab yang detail.",
            "Pair of Al-Bayyinah: the call to faith → the detailed reckoning."),
        CoherenceSurah(100, "Al-'Adiyat", 7,
            "Kuda perang; kebakhilan manusia.",
            "The Chargers; human ingratitude.",
            "Berpasangan dengan Al-Qari'ah: kuda perang → hari yang mengguncang.",
            "Paired with Al-Qari'ah: the war horses → the Calamity."),
        CoherenceSurah(101, "Al-Qari'ah", 7,
            "Hari yang menggebrak; timbangan amal.",
            "The Calamity; the scales.",
            "Pasangan Al-'Adiyat: kesibukan dunia → hari perhitungan.",
            "Pair of Al-'Adiyat: worldly bustle → the Day of account."),
        CoherenceSurah(102, "At-Takasur", 7,
            "Bermegah-megahan; kubur.",
            "Rivalry in abundance; the grave.",
            "Berpasangan dengan Al-'Asr: kesibukan dunia → waktu yang merugikan.",
            "Paired with Al-'Asr: worldly rivalry → time that brings loss."),
        CoherenceSurah(103, "Al-'Asr", 7,
            "Waktu; empat syarat keselamatan.",
            "Time; the four conditions of salvation.",
            "Pasangan At-Takasur: peringatan dunia → jalan selamat.",
            "Pair of At-Takathur: the warning → the way of salvation."),
        CoherenceSurah(104, "Al-Humazah", 7,
            "Pengumpat; api yang menghancurkan.",
            "The Slanderer; the crushing fire.",
            "Berpasangan dengan Al-Fil: harta pengumpat → pembelaan Allah atas Rumah-Nya.",
            "Paired with Al-Fil: the slanderer's wealth → God's defense of His House."),
        CoherenceSurah(105, "Al-Fil", 7,
            "Gajah; pasukan yang dihancurkan.",
            "The Elephant; the army destroyed.",
            "Pasangan Al-Humazah: kesombongan harta → kekuasaan Allah yang mutlak.",
            "Pair of Al-Humazah: pride in wealth → God's absolute power."),
        CoherenceSurah(106, "Quraisy", 7,
            "Keamanan kaum Quraisy.",
            "The security of the Quraysh.",
            "Berpasangan dengan Al-Ma'un: keamanan suku → penolakan kebaikan kecil.",
            "Paired with Al-Ma'un: the tribe's security → the denial of small kindnesses."),
        CoherenceSurah(107, "Al-Ma'un", 7,
            "Kebaikan-kebaikan kecil; agama orang munafik.",
            "Small kindnesses; the religion of the hypocrite.",
            "Pasangan Quraisy: nikmat keamanan → kewajiban berbagi.",
            "Pair of Quraysh: the blessing of security → the duty to share."),
        CoherenceSurah(108, "Al-Kausar", 7,
            "Nikmat yang banyak; karunia bagi Nabi.",
            "Abundance; the Prophet's gift.",
            "Berpasangan dengan Al-Kafirun: karunia Allah → penolakan kaum kafir.",
            "Paired with Al-Kafirun: God's bounty → the disbelievers' rejection."),
        CoherenceSurah(109, "Al-Kafirun", 7,
            "Orang-orang kafir; pemisahan agama.",
            "The Disbelievers; the separation of religion.",
            "Pasangan Al-Kausar: nikmat Nabi → sikap tegas terhadap kemusyrikan.",
            "Pair of Al-Kawthar: the Prophet's gift → firmness against shirk."),
        CoherenceSurah(110, "An-Nasr", 7,
            "Pertolongan Allah; kemenangan dan akhir misi.",
            "The Help; victory and the end of the mission.",
            "Berpasangan dengan Al-Lahab: kemenangan Nabi → azab Abu Lahab.",
            "Paired with Al-Masad: the Prophet's victory → Abu Lahab's doom."),
        CoherenceSurah(111, "Al-Lahab", 7,
            "Sabut; nasib Abu Lahab.",
            "The Palm Fiber; Abu Lahab's fate.",
            "Pasangan An-Nasr: kemenangan dakwah → kerugian para penentang.",
            "Pair of An-Nasr: the victory of the call → the loss of its opponents."),
        CoherenceSurah(112, "Al-Ikhlas", 7,
            "Tauhid murni.",
            "Pure monotheism.",
            "Berpasangan dengan Al-Falaq: inti tauhid → permohonan perlindungan.",
            "Paired with Al-Falaq: the core of tawhid → the plea for refuge."),
        CoherenceSurah(113, "Al-Falaq", 7,
            "Waktu subuh; perlindungan dari keburukan.",
            "The Daybreak; refuge from evil.",
            "Pasangan Al-Ikhlas: tauhid → doa perlindungan.",
            "Pair of Al-Ikhlas: tawhid → the prayer of refuge."),
        CoherenceSurah(114, "An-Nas", 7,
            "Manusia; berlindung kepada Allah — penutup Al-Qur'an.",
            "Mankind; seeking refuge in God — the seal of the Qur'an.",
            "Penutup seluruh kitab, menggenapkan perlindungan yang dimulai Al-Falaq; tidak berpasangan.",
            "The closing of the whole book, completing the refuge begun in Al-Falaq; unpaired."),
    )
}
