package com.tahsin.app.ui

import com.tahsin.app.util.AppLanguage

/**
 * Katalog teks UI per bahasa (tanpa resource Android — cukup untuk 2 bahasa).
 * Tambahkan bahasa baru = buat instance baru di [AppStrings.of].
 */
data class Strings(
    val appTitle: String,
    val subtitle: String,
    /** Subjudul portal (layar utama). */
    val homeSubtitle: String,
    /** Label kartu menu "Tahsin" di portal. */
    val menuTahsin: String,
    /** Label kartu menu "Pengaturan" di portal. */
    val menuSettings: String,
    val legendCorrect: String,
    val legendWrong: String,
    val legendReading: String,
    val legendNotReached: String,
    val ayahWord: String,
    val ayahLabel: String,
    val loadingSurah: String,
    val detectedPrefix: String,
    val issueDetected: String,
    val downloadingLabel: String,
    val noTajwidRule: String,
    val issuesTitle: String,
    val micHint: String,
    val listeningHint: String,
    val listen: String,
    val stop: String,
    val playWord: String,
    val settingsTitle: String,
    val settingTajwid: String,
    val settingFlow: String,
    val flowHint: String,
    val settingDarkMode: String,
    val settingLanguage: String,
    val languageNameId: String,
    val languageNameEn: String,
    val sectionAppearance: String,
    val sectionMenu: String,
    val sectionReciter: String,
    val sectionSpeed: String,
    val audioReciterLabel: String,
    val sectionDaily: String,
    val menuStats: String,
    val menuQuiz: String,
    val menuAudio: String,
    val menuDownloadAll: String,
    val swipeHint: String,
    val credit: String,
    val downloadNoticeTitle: String,
    val downloadNoticeBody: String,
    val gotIt: String,
    val bgPromptTitle: String,
    val bgPromptBody: String,
    val bgAllow: String,
    val bgDeny: String,
    val loadingMushaf: String,
    // Pesan ViewModel
    val msgMicPermission: String,
    val msgSurahLoadFailed: String,
    val msgAyahDone: String,
    val msgSurahDone: String,
    val msgMurojaahDone: String,
    val msgDownloadFailed: String,
    val msgAudioUnavailable: String,
    val msgWordUnavailable: String,
    val msgDownloadAllPartial: String,
    val msgDownloadAllDone: String,
    // Manajer audio
    val audioManagerTitle: String,
    val audioManagerSubtitle: String,
    val audioStatusComplete: String,
    val audioStatusIncomplete: String,
    val audioMissingNote: String,
    val audioDeleteTitle: String,
    val audioDeleteAllTitle: String,
    val audioDeleteBody: String,
    val audioDeleteAllBody: String,
    val audioCancel: String,
    val audioDelete: String,
    val audioDeleteAll: String,
    val audioBack: String,
    val audioSize: String,
    val audioAyat: String,
    val audioKata: String,
    val audioNoDownload: String,
    val audioLoading: String,
    // Statistik & riwayat kesalahan
    val statsTitle: String,
    val statsSubtitle: String,
    val statsTotalAttempts: String,
    val statsAvgScore: String,
    val statsBestScore: String,
    val statsAyahsPracticed: String,
    val statsSurahSection: String,
    val statsFrequentWords: String,
    val statsWrongCount: String,
    val statsNoData: String,
    val statsClear: String,
    val statsClearTitle: String,
    val statsClearBody: String,
    val statsCancel: String,
    val statsInline: String,
    val statsEmptySurah: String,
    val statsLoading: String,
    // Pencarian ayat
    val searchTitle: String,
    val searchHint: String,
    val searchNoQuery: String,
    val searchIndexing: String,
    val searchSearching: String,
    val searchNoResults: String,
    val searchResultsCount: String,
    // Kuis tajwid
    val quizTitle: String,
    val quizScore: String,
    val quizQuestion: String,
    val quizNext: String,
    val quizCorrect: String,
    val quizWrong: String,
    val quizRuleLabel: String,
    val quizLoading: String,
    val quizNoData: String,
    // Kosa kata
    val menuVocab: String,
    // Materi Dream BIG
    val menuDreamBig: String,
    val dreamBigTitle: String,
    val dreamBigSubtitle: String,
    val dreamBigLoading: String,
    val dreamBigOpenYouTube: String,
    // Game Dream BIG
    val gameLocked: String,
    val gameBestScore: String,
    val gameQuestionProgress: String,
    val gameScoreLabel: String,
    val gameStreakLabel: String,
    val gameCorrect: String,
    val gameWrong: String,
    val gameNext: String,
    val gameResultTitle: String,
    val gameResultScore: String,
    val gameResultStreak: String,
    val gamePass: String,
    val gameFail: String,
    val gameRepeat: String,
    val gameNextLevel: String,
    val gameMateri: String,
    val gameMateriToday: String,
    val gameBackToMap: String,
    val gameEmpty: String,
    val gameNoVideo: String,
    val vocabTitle: String,
    val vocabSubtitle: String,
    val vocabModeCards: String,
    val vocabModeQuiz: String,
    val vocabFlipHint: String,
    val vocabMeaning: String,
    val vocabRoot: String,
    val vocabExample: String,
    val vocabPlayAudio: String,
    val vocabRemember: String,
    val vocabForgot: String,
    val vocabLearned: String,
    val vocabDue: String,
    val vocabSessionDone: String,
    val vocabStartQuiz: String,
    val vocabEmpty: String,
    val vocabQuizQuestionWord: String,
    val vocabQuizQuestionMeaning: String,
    val vocabQuizScore: String,
    val vocabQuizCorrect: String,
    val vocabQuizWrong: String,
    val vocabQuizNext: String,
    val vocabQuizDone: String,
    val vocabQuizAgain: String,
    val vocabOpenExample: String,
    val vocabAudioUnavailable: String,
    val vocabLoading: String,
)

object AppStrings {

    fun of(lang: AppLanguage): Strings = when (lang) {
        AppLanguage.ID -> Indonesian
        AppLanguage.EN -> English
    }

    val Indonesian = Strings(
        appTitle = "Tahsin Qur'an",
        subtitle = "Setiap kata dicek langsung.",
        homeSubtitle = "Pilih menu untuk mulai belajar.",
        menuTahsin = "🕌 Tahsin",
        menuSettings = "⚙️ Pengaturan",
        legendCorrect = "benar",
        legendWrong = "salah",
        legendReading = "dibaca",
        legendNotReached = "belum",
        ayahWord = "ayat",
        ayahLabel = "Ayat",
        loadingSurah = "Memuat surah…",
        detectedPrefix = "🎙️ Terdeteksi:",
        issueDetected = "Terdeteksi:",
        downloadingLabel = "Mengunduh audio…",
        noTajwidRule = "Tidak ada aturan tajwid khusus pada kata ini.",
        issuesTitle = "Kesalahan terdeteksi",
        micHint = "Tekan 🎙️\nlalu bacalah",
        listeningHint = "Membaca… tekan ⏹ untuk berhenti",
        listen = "▶ Dengar",
        stop = "⏹ Stop",
        playWord = "▶ Kata",
        settingsTitle = "Pengaturan",
        settingTajwid = "Warna Tajwid",
        settingFlow = "Mode Flow",
        flowHint = "Lanjut otomatis ke ayat berikutnya saat selesai.",
        settingDarkMode = "Mode Gelap",
        settingLanguage = "Bahasa",
        languageNameId = "Indonesia",
        languageNameEn = "Inggris",
        sectionAppearance = "Tampilan",
        sectionMenu = "Menu",
        sectionReciter = "Qari' (Perawi)",
        sectionSpeed = "Kecepatan Audio",
        audioReciterLabel = "Qari'",
        sectionDaily = "Ayah of the Day",
        menuStats = "📊 Statistik",
        menuQuiz = "📝 Kuis",
        menuAudio = "🎵 Kelola Audio",
        menuDownloadAll = "📥 Unduh Semua",
        swipeHint = "Geser layar ke kiri/kanan untuk ganti ayat",
        credit = "Made with ❤️ by OpenNur Project (FOSS)",
        downloadNoticeTitle = "Mengunduh audio…",
        downloadNoticeBody = "Audio surah ini belum diunduh. Unduhan dimulai otomatis — " +
            "ikuti progres di atas tombol. Bacaan contoh akan diputar setelah unduhan selesai.",
        gotIt = "Mengerti",
        bgPromptTitle = "Unduhan latar belakang?",
        bgPromptBody = "Izinkan unduhan terus berjalan saat layar mati / aplikasi di latar " +
            "belakang? Unduhan besar (mis. Al-Baqarah ≈ 440 MB) bisa gagal kalau tidak.",
        bgAllow = "Izinkan",
        bgDeny = "Tidak, cukup saat aplikasi terbuka",
        loadingMushaf = "Memuat mushaf…",
        msgMicPermission = "Izin mikrofon diperlukan untuk mendeteksi bacaan.",
        msgSurahLoadFailed = "Gagal memuat surah",
        msgAyahDone = "✅ Ayat selesai — lanjut ke ayat berikutnya",
        msgSurahDone = "✅ Surah selesai — lanjut ke surah berikutnya",
        msgMurojaahDone = "🎉 Selesai muroja'ah — seluruh Al-Qur'an dibaca benar!",
        msgDownloadFailed = "Gagal mengunduh",
        msgAudioUnavailable = "Audio belum tersedia. Cek koneksi lalu coba lagi.",
        msgWordUnavailable = "Audio kata belum tersedia. Cek koneksi lalu coba lagi.",
        msgDownloadAllPartial = "Unduh selesai: %d surah gagal.",
        msgDownloadAllDone = "Semua audio berhasil diunduh ✓",
        audioManagerTitle = "Audio Terunduh",
        audioManagerSubtitle = "Kelola audio yang sudah diunduh per surah.",
        audioStatusComplete = "✓ Lengkap",
        audioStatusIncomplete = "Belum lengkap",
        audioMissingNote = "%d audio tak tersedia di server",
        audioDeleteTitle = "Hapus audio surah ini?",
        audioDeleteAllTitle = "Hapus semua audio?",
        audioDeleteBody = "Audio surah ini akan dihapus dari perangkat.",
        audioDeleteAllBody = "Semua audio terunduh akan dihapus dari perangkat.",
        audioCancel = "Batal",
        audioDelete = "Hapus",
        audioDeleteAll = "Hapus Semua",
        audioBack = "←",
        audioSize = "%d,%.2f MB",
        audioAyat = "Ayat",
        audioKata = "Kata",
        audioNoDownload = "Belum ada audio terunduh. Buka surah dan tekan Dengar untuk mengunduh.",
        audioLoading = "Memuat audio…",
        statsTitle = "📊 Statistik & Riwayat",
        statsSubtitle = "Kata yang sering salah per surah — tahu persis yang harus diperbaiki.",
        statsTotalAttempts = "Total percobaan",
        statsAvgScore = "Rata-rata skor",
        statsBestScore = "Skor terbaik",
        statsAyahsPracticed = "Ayat dilatih",
        statsSurahSection = "Surah",
        statsFrequentWords = "Kata yang sering salah",
        statsWrongCount = "%d× salah/terlewat",
        statsNoData = "Belum ada riwayat bacaan. Bacalah beberapa ayat ke mikrofon untuk mulai melihat statistik.",
        statsClear = "🗑 Hapus riwayat",
        statsClearTitle = "Hapus riwayat bacaan?",
        statsClearBody = "Semua skor dan riwayat kesalahan akan dihapus permanen.",
        statsCancel = "Batal",
        statsInline = "📊 %d× dicoba · skor terbaik %d%%",
        statsEmptySurah = "Belum ada kata yang sering salah di surah ini. 👍",
        statsLoading = "Memuat statistik…",
        searchTitle = "🔍 Cari Ayat",
        searchHint = "Kata Arab / kata kunci terjemahan (ID/EN)…",
        searchNoQuery = "Ketik kata kunci untuk mencari ayat di seluruh Al-Qur'an.",
        searchIndexing = "Menyiapkan indeks pencarian…",
        searchSearching = "Mencari…",
        searchNoResults = "Tidak ada ayat yang cocok.",
        searchResultsCount = "%d hasil",
        quizTitle = "📝 Kuis Tajwid",
        quizScore = "Skor: %d/%d",
        quizQuestion = "Hukum apa pada kata ini?",
        quizNext = "Soal berikutnya →",
        quizCorrect = "✓ Benar!",
        quizWrong = "✗ Belum tepat.",
        quizRuleLabel = "Hukum",
        quizLoading = "Menyiapkan soal…",
        quizNoData = "Gagal menyiapkan soal. Coba lagi.",
        menuVocab = "📖 Kosakata",
        menuDreamBig = "🎬 Dream BIG",
        dreamBigTitle = "🎬 Materi Dream BIG",
        dreamBigSubtitle = "Belajar kosakata Qur'an lewat 10 level kuis — terinspirasi challenge Dream BIG.",
        dreamBigLoading = "Memuat game…",
        dreamBigOpenYouTube = "▶ Buka di YouTube",
        gameLocked = "🔒 Terkunci — selesaikan Day %d",
        gameBestScore = "Skor terbaik: %d/%d",
        gameQuestionProgress = "Soal %d/%d",
        gameScoreLabel = "Skor %d",
        gameStreakLabel = "🔥 %d",
        gameCorrect = "✓ Benar!",
        gameWrong = "✗ Belum tepat.",
        gameNext = "Soal berikutnya →",
        gameResultTitle = "Ronde selesai",
        gameResultScore = "Skor: %d/%d",
        gameResultStreak = "Streak terbaik: %d",
        gamePass = "Lulus! 🎉",
        gameFail = "Belum lulus — skor minimal %d untuk membuka level berikutnya.",
        gameRepeat = "🔄 Ulangi",
        gameNextLevel = "➡ Level Berikutnya",
        gameMateri = "📖 Materi",
        gameMateriToday = "📖 Materi Hari Ini",
        gameBackToMap = "🗺 Peta Level",
        gameEmpty = "Belum ada level.",
        gameNoVideo = "Tidak ada transkrip untuk hari ini.",
        vocabTitle = "📖 Kosakata",
        vocabSubtitle = "Kata-kata terpenting Al-Qur'an — diurutkan dari yang paling sering muncul.",
        vocabModeCards = "📇 Kartu",
        vocabModeQuiz = "📝 Kuis",
        vocabFlipHint = "Ketuk kartu untuk melihat arti.",
        vocabMeaning = "Arti",
        vocabRoot = "Akar",
        vocabExample = "Contoh ayat",
        vocabPlayAudio = "▶ Dengar",
        vocabRemember = "✓ Ingat",
        vocabForgot = "✗ Lupa",
        vocabLearned = "%d kata dikuasai",
        vocabDue = "%d untuk diulang",
        vocabSessionDone = "Sesi kartu selesai ✓",
        vocabStartQuiz = "Coba Kuis",
        vocabEmpty = "Belum ada kata untuk dipelajari. Kembali lagi nanti — atau coba Kuis!",
        vocabQuizQuestionWord = "Apa arti kata ini?",
        vocabQuizQuestionMeaning = "Kata mana yang artinya:",
        vocabQuizScore = "Skor: %d/%d",
        vocabQuizCorrect = "✓ Benar!",
        vocabQuizWrong = "✗ Belum tepat. Jawabannya: %s",
        vocabQuizNext = "Lanjut →",
        vocabQuizDone = "Kuis selesai! Skor: %d/%d",
        vocabQuizAgain = "Kuis Lagi",
        vocabOpenExample = "Buka di mushaf ▸",
        vocabAudioUnavailable = "Audio belum tersedia. Cek koneksi lalu coba lagi.",
        vocabLoading = "Menyiapkan kosa kata…",
    )

    val English = Strings(
        appTitle = "Tahsin Qur'an",
        subtitle = "Every word is checked live.",
        homeSubtitle = "Choose a menu to start learning.",
        menuTahsin = "🕌 Tahsin",
        menuSettings = "⚙️ Settings",
        legendCorrect = "correct",
        legendWrong = "wrong",
        legendReading = "reading",
        legendNotReached = "not yet",
        ayahWord = "ayah",
        ayahLabel = "Ayah",
        loadingSurah = "Loading surah…",
        detectedPrefix = "🎙️ Detected:",
        issueDetected = "Heard:",
        downloadingLabel = "Downloading audio…",
        noTajwidRule = "No specific tajweed rule detected for this word.",
        issuesTitle = "Reading issues",
        micHint = "Tap 🎙️\nthen recite",
        listeningHint = "Listening… tap ⏹ to stop",
        listen = "▶ Listen",
        stop = "⏹ Stop",
        playWord = "▶ Word",
        settingsTitle = "Settings",
        settingTajwid = "Tajweed Color",
        settingFlow = "Flow Mode",
        flowHint = "Automatically continues to the next ayah when finished.",
        settingDarkMode = "Dark Mode",
        settingLanguage = "Language",
        languageNameId = "Indonesian",
        languageNameEn = "English",
        sectionAppearance = "Appearance",
        sectionMenu = "Menu",
        sectionReciter = "Reciter",
        sectionSpeed = "Audio Speed",
        audioReciterLabel = "Reciter",
        sectionDaily = "Ayah of the Day",
        menuStats = "📊 Stats",
        menuQuiz = "📝 Quiz",
        menuAudio = "🎵 Audio",
        menuDownloadAll = "📥 Download All",
        swipeHint = "Swipe the screen left/right to change ayah",
        credit = "Made with ❤️ by OpenNur Project (FOSS)",
        downloadNoticeTitle = "Downloading audio…",
        downloadNoticeBody = "This surah's audio is not downloaded yet. The download starts " +
            "automatically — follow the progress above the buttons. The example recitation " +
            "will play once the download finishes.",
        gotIt = "Got it",
        bgPromptTitle = "Background download?",
        bgPromptBody = "Allow downloads to continue while the screen is off / the app is in " +
            "the background? Large downloads (e.g. Al-Baqarah ≈ 440 MB) may fail otherwise.",
        bgAllow = "Allow",
        bgDeny = "No, only while the app is open",
        loadingMushaf = "Loading mushaf…",
        msgMicPermission = "Microphone permission is required to check your recitation.",
        msgSurahLoadFailed = "Failed to load surah",
        msgAyahDone = "✅ Ayah complete — moving to the next ayah",
        msgSurahDone = "✅ Surah complete — moving to the next surah",
        msgMurojaahDone = "🎉 Muraja'ah complete — the whole Qur'an read correctly!",
        msgDownloadFailed = "Failed to download",
        msgAudioUnavailable = "Audio not available. Check your connection and try again.",
        msgWordUnavailable = "Word audio not available. Check your connection and try again.",
        msgDownloadAllPartial = "Download finished: %d surahs failed.",
        msgDownloadAllDone = "All audio downloaded successfully ✓",
        audioManagerTitle = "Downloaded Audio",
        audioManagerSubtitle = "Manage audio downloaded per surah.",
        audioStatusComplete = "✓ Complete",
        audioStatusIncomplete = "Incomplete",
        audioMissingNote = "%d audio unavailable on server",
        audioDeleteTitle = "Delete this surah's audio?",
        audioDeleteAllTitle = "Delete all audio?",
        audioDeleteBody = "This surah's audio will be removed from the device.",
        audioDeleteAllBody = "All downloaded audio will be removed from the device.",
        audioCancel = "Cancel",
        audioDelete = "Delete",
        audioDeleteAll = "Delete All",
        audioBack = "←",
        audioSize = "%d,%.2f MB",
        audioAyat = "Ayah",
        audioKata = "Word",
        audioNoDownload = "No audio downloaded yet. Open a surah and tap Listen to download.",
        audioLoading = "Loading audio…",
        statsTitle = "📊 Statistics & History",
        statsSubtitle = "Frequently wrong words per surah — know exactly what to fix.",
        statsTotalAttempts = "Total attempts",
        statsAvgScore = "Average score",
        statsBestScore = "Best score",
        statsAyahsPracticed = "Ayahs practiced",
        statsSurahSection = "Surah",
        statsFrequentWords = "Frequently wrong words",
        statsWrongCount = "%d× wrong/missed",
        statsNoData = "No reading history yet. Recite a few ayahs into the microphone to start seeing statistics.",
        statsClear = "🗑 Clear history",
        statsClearTitle = "Clear reading history?",
        statsClearBody = "All scores and error history will be permanently deleted.",
        statsCancel = "Cancel",
        statsInline = "📊 %d× attempted · best score %d%%",
        statsEmptySurah = "No frequently wrong words in this surah yet. 👍",
        statsLoading = "Loading statistics…",
        searchTitle = "🔍 Search Ayah",
        searchHint = "Arabic word / translation keyword (ID/EN)…",
        searchNoQuery = "Type a keyword to search ayahs across the whole Qur'an.",
        searchIndexing = "Preparing search index…",
        searchSearching = "Searching…",
        searchNoResults = "No matching ayahs.",
        searchResultsCount = "%d results",
        quizTitle = "📝 Tajweed Quiz",
        quizScore = "Score: %d/%d",
        quizQuestion = "What rule applies to this word?",
        quizNext = "Next question →",
        quizCorrect = "✓ Correct!",
        quizWrong = "✗ Not quite.",
        quizRuleLabel = "Rule",
        quizLoading = "Preparing question…",
        quizNoData = "Failed to prepare a question. Try again.",
        menuVocab = "📖 Vocabulary",
        menuDreamBig = "🎬 Dream BIG",
        dreamBigTitle = "🎬 Dream BIG Materials",
        dreamBigSubtitle = "Learn Qur'anic vocabulary through 10 quiz levels — inspired by the Dream BIG intensive.",
        dreamBigLoading = "Loading game…",
        dreamBigOpenYouTube = "▶ Open on YouTube",
        gameLocked = "🔒 Locked — finish Day %d",
        gameBestScore = "Best score: %d/%d",
        gameQuestionProgress = "Question %d/%d",
        gameScoreLabel = "Score %d",
        gameStreakLabel = "🔥 %d",
        gameCorrect = "✓ Correct!",
        gameWrong = "✗ Not quite.",
        gameNext = "Next question →",
        gameResultTitle = "Round complete",
        gameResultScore = "Score: %d/%d",
        gameResultStreak = "Best streak: %d",
        gamePass = "Passed! 🎉",
        gameFail = "Not passed — need at least %d to unlock the next level.",
        gameRepeat = "🔄 Repeat",
        gameNextLevel = "➡ Next Level",
        gameMateri = "📖 Material",
        gameMateriToday = "📖 Today's Material",
        gameBackToMap = "🗺 Level Map",
        gameEmpty = "No levels yet.",
        gameNoVideo = "No transcript for this day.",
        vocabTitle = "📖 Vocabulary",
        vocabSubtitle = "The most important words of the Qur'an — ordered by frequency.",
        vocabModeCards = "📇 Cards",
        vocabModeQuiz = "📝 Quiz",
        vocabFlipHint = "Tap the card to reveal the meaning.",
        vocabMeaning = "Meaning",
        vocabRoot = "Root",
        vocabExample = "Example verse",
        vocabPlayAudio = "▶ Hear",
        vocabRemember = "✓ Remember",
        vocabForgot = "✗ Forgot",
        vocabLearned = "%d words mastered",
        vocabDue = "%d to review",
        vocabSessionDone = "Card session done ✓",
        vocabStartQuiz = "Try Quiz",
        vocabEmpty = "No words to study right now. Come back later — or try the Quiz!",
        vocabQuizQuestionWord = "What does this word mean?",
        vocabQuizQuestionMeaning = "Which word means:",
        vocabQuizScore = "Score: %d/%d",
        vocabQuizCorrect = "✓ Correct!",
        vocabQuizWrong = "✗ Not quite. The answer: %s",
        vocabQuizNext = "Next →",
        vocabQuizDone = "Quiz complete! Score: %d/%d",
        vocabQuizAgain = "Quiz Again",
        vocabOpenExample = "Open in mushaf ▸",
        vocabAudioUnavailable = "Audio not available yet. Check your connection and try again.",
        vocabLoading = "Preparing vocabulary…",
    )
}
