package com.tahsin.app.ui

import com.tahsin.app.util.AppLanguage

/**
 * Katalog teks UI per bahasa (tanpa resource Android — cukup untuk 2 bahasa).
 * Tambahkan bahasa baru = buat instance baru di [AppStrings.of].
 */
data class Strings(
    val appTitle: String,
    val subtitle: String,
    val legendCorrect: String,
    val legendWrong: String,
    val legendReading: String,
    val legendNotReached: String,
    val ayahWord: String,
    val ayahLabel: String,
    val loadingSurah: String,
    val detectedPrefix: String,
    val issueDetected: String,
    val downloadingLabel: String,
    val noTajwidRule: String,
    val issuesTitle: String,
    val micHint: String,
    val listeningHint: String,
    val listen: String,
    val stop: String,
    val playWord: String,
    val settingsTitle: String,
    val sectionTajwid: String,
    val tajwidOn: String,
    val tajwidOff: String,
    val sectionMurojaah: String,
    val flowOn: String,
    val flowOff: String,
    val flowHintOn: String,
    val flowHintOff: String,
    val sectionStorage: String,
    val downloadAll: String,
    val manageAudio: String,
    val sectionDaily: String,
    val dailyOn: String,
    val dailyOff: String,
    val closeDrawerHint: String,
    val swipeHint: String,
    val credit: String,
    val downloadNoticeTitle: String,
    val downloadNoticeBody: String,
    val gotIt: String,
    val bgPromptTitle: String,
    val bgPromptBody: String,
    val bgAllow: String,
    val bgDeny: String,
    val loadingMushaf: String,
    // Pesan ViewModel
    val msgMicPermission: String,
    val msgSurahLoadFailed: String,
    val msgAyahDone: String,
    val msgSurahDone: String,
    val msgMurojaahDone: String,
    val msgDownloadFailed: String,
    val msgAudioUnavailable: String,
    val msgWordUnavailable: String,
    val msgDownloadAllPartial: String,
    val msgDownloadAllDone: String,
    // Manajer audio
    val audioManagerTitle: String,
    val audioManagerSubtitle: String,
    val audioStatusComplete: String,
    val audioStatusIncomplete: String,
    val audioMissingNote: String,
    val audioDeleteTitle: String,
    val audioDeleteAllTitle: String,
    val audioDeleteBody: String,
    val audioDeleteAllBody: String,
    val audioCancel: String,
    val audioDelete: String,
    val audioDeleteAll: String,
    val audioBack: String,
    val audioSize: String,
    val audioAyat: String,
    val audioKata: String,
    val audioNoDownload: String,
    val audioLoading: String,
)

object AppStrings {

    fun of(lang: AppLanguage): Strings = when (lang) {
        AppLanguage.ID -> Indonesian
        AppLanguage.EN -> English
    }

    val Indonesian = Strings(
        appTitle = "Tahsin Qur'an",
        subtitle = "Setiap kata dicek langsung.",
        legendCorrect = "benar",
        legendWrong = "salah",
        legendReading = "dibaca",
        legendNotReached = "belum",
        ayahWord = "ayat",
        ayahLabel = "Ayat",
        loadingSurah = "Memuat surah…",
        detectedPrefix = "🎙️ Terdeteksi:",
        issueDetected = "Terdeteksi:",
        downloadingLabel = "Mengunduh audio…",
        noTajwidRule = "Tidak ada aturan tajwid khusus pada kata ini.",
        issuesTitle = "Kesalahan terdeteksi",
        micHint = "Tekan 🎙️\nlalu bacalah",
        listeningHint = "Membaca… tekan ⏹ untuk berhenti",
        listen = "▶ Dengar",
        stop = "⏹ Stop",
        playWord = "▶ Kata",
        settingsTitle = "Pengaturan",
        sectionTajwid = "Tajwid",
        tajwidOn = "🎨 Warna Tajwid: Nyala",
        tajwidOff = "🎨 Warna Tajwid: Mati",
        sectionMurojaah = "Muroja'ah",
        flowOn = "🔁 Mode Flow: Nyala",
        flowOff = "🔁 Mode Flow: Mati",
        flowHintOn = "Lanjut otomatis ke ayat berikutnya saat semua kata benar.",
        flowHintOff = "Lanjut otomatis antar-ayat untuk muroja'ah.",
        sectionStorage = "Penyimpanan",
        downloadAll = "📥 Unduh semua audio",
        manageAudio = "🎵 Kelola audio terunduh",
        sectionDaily = "Ayah of the Day",
        dailyOn = "🗓️ Notifikasi Harian: Nyala",
        dailyOff = "🗓️ Notifikasi Harian: Mati",
        closeDrawerHint = "Ketuk di luar drawer untuk menutup.",
        swipeHint = "Geser layar ke kiri/kanan untuk ganti ayat",
        credit = "Made with ❤️ by Lutfian Dwi Cahyono",
        downloadNoticeTitle = "Mengunduh audio…",
        downloadNoticeBody = "Audio surah ini belum diunduh. Unduhan dimulai otomatis — " +
            "ikuti progres di atas tombol. Bacaan contoh akan diputar setelah unduhan selesai.",
        gotIt = "Mengerti",
        bgPromptTitle = "Unduhan latar belakang?",
        bgPromptBody = "Izinkan unduhan terus berjalan saat layar mati / aplikasi di latar " +
            "belakang? Unduhan besar (mis. Al-Baqarah ≈ 440 MB) bisa gagal kalau tidak.",
        bgAllow = "Izinkan",
        bgDeny = "Tidak, cukup saat aplikasi terbuka",
        loadingMushaf = "Memuat mushaf…",
        msgMicPermission = "Izin mikrofon diperlukan untuk mendeteksi bacaan.",
        msgSurahLoadFailed = "Gagal memuat surah",
        msgAyahDone = "✅ Ayat selesai — lanjut ke ayat berikutnya",
        msgSurahDone = "✅ Surah selesai — lanjut ke surah berikutnya",
        msgMurojaahDone = "🎉 Selesai muroja'ah — seluruh Al-Qur'an dibaca benar!",
        msgDownloadFailed = "Gagal mengunduh",
        msgAudioUnavailable = "Audio belum tersedia. Cek koneksi lalu coba lagi.",
        msgWordUnavailable = "Audio kata belum tersedia. Cek koneksi lalu coba lagi.",
        msgDownloadAllPartial = "Unduh selesai: %d surah gagal.",
        msgDownloadAllDone = "Semua audio berhasil diunduh ✓",
        audioManagerTitle = "Audio Terunduh",
        audioManagerSubtitle = "Kelola audio yang sudah diunduh per surah.",
        audioStatusComplete = "✓ Lengkap",
        audioStatusIncomplete = "Belum lengkap",
        audioMissingNote = "%d audio tak tersedia di server",
        audioDeleteTitle = "Hapus audio surah ini?",
        audioDeleteAllTitle = "Hapus semua audio?",
        audioDeleteBody = "Audio surah ini akan dihapus dari perangkat.",
        audioDeleteAllBody = "Semua audio terunduh akan dihapus dari perangkat.",
        audioCancel = "Batal",
        audioDelete = "Hapus",
        audioDeleteAll = "Hapus Semua",
        audioBack = "←",
        audioSize = "%d,%.2f MB",
        audioAyat = "Ayat",
        audioKata = "Kata",
        audioNoDownload = "Belum ada audio terunduh. Buka surah dan tekan Dengar untuk mengunduh.",
        audioLoading = "Memuat audio…",
    )

    val English = Strings(
        appTitle = "Tahsin Qur'an",
        subtitle = "Every word is checked live.",
        legendCorrect = "correct",
        legendWrong = "wrong",
        legendReading = "reading",
        legendNotReached = "not yet",
        ayahWord = "ayah",
        ayahLabel = "Ayah",
        loadingSurah = "Loading surah…",
        detectedPrefix = "🎙️ Detected:",
        issueDetected = "Heard:",
        downloadingLabel = "Downloading audio…",
        noTajwidRule = "No specific tajweed rule detected for this word.",
        issuesTitle = "Reading issues",
        micHint = "Tap 🎙️\nthen recite",
        listeningHint = "Listening… tap ⏹ to stop",
        listen = "▶ Listen",
        stop = "⏹ Stop",
        playWord = "▶ Word",
        settingsTitle = "Settings",
        sectionTajwid = "Tajweed",
        tajwidOn = "🎨 Tajweed Color: On",
        tajwidOff = "🎨 Tajweed Color: Off",
        sectionMurojaah = "Muraja'ah",
        flowOn = "🔁 Flow Mode: On",
        flowOff = "🔁 Flow Mode: Off",
        flowHintOn = "Automatically continue to the next ayah when every word is correct.",
        flowHintOff = "Continue automatically across ayahs for muraja'ah.",
        sectionStorage = "Storage",
        downloadAll = "📥 Download all audio",
        manageAudio = "🎵 Manage downloaded audio",
        sectionDaily = "Ayah of the Day",
        dailyOn = "🗓️ Daily Notification: On",
        dailyOff = "🗓️ Daily Notification: Off",
        closeDrawerHint = "Tap outside the drawer to close.",
        swipeHint = "Swipe the screen left/right to change ayah",
        credit = "Made with ❤️ by Lutfian Dwi Cahyono",
        downloadNoticeTitle = "Downloading audio…",
        downloadNoticeBody = "This surah's audio is not downloaded yet. The download starts " +
            "automatically — follow the progress above the buttons. The example recitation " +
            "will play once the download finishes.",
        gotIt = "Got it",
        bgPromptTitle = "Background download?",
        bgPromptBody = "Allow downloads to continue while the screen is off / the app is in " +
            "the background? Large downloads (e.g. Al-Baqarah ≈ 440 MB) may fail otherwise.",
        bgAllow = "Allow",
        bgDeny = "No, only while the app is open",
        loadingMushaf = "Loading mushaf…",
        msgMicPermission = "Microphone permission is required to check your recitation.",
        msgSurahLoadFailed = "Failed to load surah",
        msgAyahDone = "✅ Ayah complete — moving to the next ayah",
        msgSurahDone = "✅ Surah complete — moving to the next surah",
        msgMurojaahDone = "🎉 Muraja'ah complete — the whole Qur'an read correctly!",
        msgDownloadFailed = "Failed to download",
        msgAudioUnavailable = "Audio not available. Check your connection and try again.",
        msgWordUnavailable = "Word audio not available. Check your connection and try again.",
        msgDownloadAllPartial = "Download finished: %d surahs failed.",
        msgDownloadAllDone = "All audio downloaded successfully ✓",
        audioManagerTitle = "Downloaded Audio",
        audioManagerSubtitle = "Manage audio downloaded per surah.",
        audioStatusComplete = "✓ Complete",
        audioStatusIncomplete = "Incomplete",
        audioMissingNote = "%d audio unavailable on server",
        audioDeleteTitle = "Delete this surah's audio?",
        audioDeleteAllTitle = "Delete all audio?",
        audioDeleteBody = "This surah's audio will be removed from the device.",
        audioDeleteAllBody = "All downloaded audio will be removed from the device.",
        audioCancel = "Cancel",
        audioDelete = "Delete",
        audioDeleteAll = "Delete All",
        audioBack = "←",
        audioSize = "%d,%.2f MB",
        audioAyat = "Ayah",
        audioKata = "Word",
        audioNoDownload = "No audio downloaded yet. Open a surah and tap Listen to download.",
        audioLoading = "Loading audio…",
    )
}
