#!/usr/bin/env python3
"""
Kurasi arti kosa kata → isi `assets/quran/vocab.json`.

Daftar arti di bawah (kunci ternormalisasi → transliterasi, arti ID, arti EN)
ditulis manual untuk kata-kata paling sering (target ±150–200 entri; ~80%
kemunculan kata di Al-Qur'an). Entri yang belum dikurasi dibiarkan kosong
dan TIDAK tampil di aplikasi (VocabularyRepository menyaringnya).

Pakai:  python3 tools/curate_vocab.py
Setelah menambah arti baru, jalankan ulang — skrip hanya mengisi field yang
kosong, tidak menimpa yang sudah ada.
"""

import json
import os

from vocab_extra import VOCAB_EXTRA
from vocab_roots import ROOTS, ROOT_MEANINGS

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
VOCAB = os.path.join(ROOT, "app", "src", "main", "assets", "quran", "vocab.json")

# key → (translit, meaningId, meaningEn)
CURATED = {
    "من": ("min", "dari", "from"),
    "الله": ("allāh", "Allah", "Allah"),
    "ان": ("inna", "sesungguhnya", "indeed"),
    "في": ("fī", "di dalam", "in"),
    "ما": ("mā", "apa; yang; tidak", "what; that; not"),
    "الذين": ("alladhīna", "orang-orang yang", "those who"),
    "لا": ("lā", "tidak", "no; not"),
    "الا": ("illā", "kecuali", "except"),
    "علي": ("'alā", "di atas", "upon; on"),
    "ولا": ("wa lā", "dan tidak", "and not"),
    "وما": ("wa mā", "dan apa; dan tidak", "and what; and not"),
    "الي": ("ilā", "ke; kepada", "to"),
    "قال": ("qāla", "dia berkata", "he said"),
    "لهم": ("lahum", "bagi mereka", "for them"),
    "ومن": ("wa min", "dan dari", "and from"),
    "ثم": ("thumma", "kemudian", "then"),
    "لكم": ("lakum", "bagi kalian", "for you"),
    "كان": ("kāna", "dia adalah", "he was"),
    "به": ("bihī", "dengannya", "with it"),
    "وان": ("wa in", "dan jika", "and if"),
    "بما": ("bimā", "dengan apa; dengan yang", "with what; with that"),
    "قل": ("qul", "katakanlah", "say!"),
    "الارض": ("al-arḍ", "bumi", "the earth"),
    "او": ("aw", "atau", "or"),
    "ذلك": ("dhālika", "itu", "that"),
    "الذي": ("alladhī", "yang", "who; which"),
    "هو": ("huwa", "dia (laki-laki)", "he; it"),
    "امنوا": ("āmanū", "mereka beriman", "they believed"),
    "هم": ("hum", "mereka", "they; them"),
    "قالوا": ("qālū", "mereka berkata", "they said"),
    "كل": ("kull", "setiap; seluruh", "every; all"),
    "لهٗ": ("lahū", "baginya", "for him"),
    "فيها": ("fīhā", "di dalamnya", "in it"),
    "والله": ("wa-llāhu", "dan Allah", "and Allah"),
    "انا": ("innā", "sesungguhnya kami", "indeed we"),
    "اذا": ("idhā", "apabila", "when"),
    "كانوا": ("kānū", "mereka adalah", "they were"),
    "عن": ("'an", "dari; tentang", "from; about"),
    "ربك": ("rabbuka", "Tuhanmu", "your Lord"),
    "يوم": ("yawm", "hari", "day"),
    "عليهم": ("'alayhim", "atas mereka", "upon them"),
    "شي": ("shay'", "sesuatu", "something"),
    "هذا": ("hādhā", "ini", "this"),
    "كفروا": ("kafarū", "mereka kafir", "they disbelieved"),
    "كنتم": ("kuntum", "kalian adalah", "you were"),
    "السموت": ("as-samāwāt", "langit-langit", "the heavens"),
    "الناس": ("an-nās", "manusia", "mankind"),
    "لم": ("lam", "tidak (lampau)", "not (past)"),
    "فان": ("fa-in", "maka jika", "then if"),
    "وهو": ("wa huwa", "dan dia", "and he"),
    "اذ": ("idh", "ketika (dulu)", "when (past)"),
    "عليكم": ("'alaykum", "atas kalian", "upon you"),
    "والذين": ("wa-lladhīna", "dan orang-orang yang", "and those who"),
    "الكتب": ("al-kitāb", "kitab", "the Book"),
    "انهٗ": ("innahū", "sesungguhnya dia", "indeed he"),
    "اني": ("innī", "sesungguhnya aku", "indeed I"),
    "والارض": ("wa-l-arḍ", "dan bumi", "and the earth"),
    "فلا": ("fa-lā", "maka tidak", "so not"),
    "منهم": ("minhum", "dari mereka", "from them"),
    "عذاب": ("'adhāb", "azab; siksaan", "punishment"),
    "بعد": ("ba'd", "sesudah", "after"),
    "عليه": ("'alayhi", "atasnya", "upon him"),
    "حتي": ("ḥattā", "sehingga; sampai", "until"),
    "يايها": ("yā ayyuhā", "wahai", "O (vocative)"),
    "بالله": ("bi-llāhi", "demi Allah", "by Allah"),
    "وهم": ("wa hum", "dan mereka", "and they"),
    "واذا": ("wa idhā", "dan apabila", "and when"),
    "اوليك": ("ulā'ika", "mereka itu", "those"),
    "انما": ("innamā", "hanyalah", "only; indeed"),
    "ام": ("am", "ataukah", "or"),
    "رب": ("rabb", "Tuhan", "Lord"),
    "ولقد": ("wa laqad", "dan sungguh", "and indeed"),
    "بل": ("bal", "bahkan; sebaliknya", "rather; nay"),
    "فيه": ("fīhi", "di dalamnya", "in it"),
    "قد": ("qad", "sungguh", "indeed (perfective)"),
    "يشا": ("yashā'", "dia menghendaki", "He wills"),
    "عند": ("'inda", "di sisi", "with; near"),
    "قبل": ("qabl", "sebelum", "before"),
    "خير": ("khayr", "lebih baik; kebaikan", "better; goodness"),
    "لله": ("li-llāhi", "bagi Allah", "for Allah"),
    "الدنيا": ("ad-dunyā", "dunia", "the world"),
    "ولكن": ("wa lākin", "akan tetapi", "but"),
    "ربهم": ("rabbuhum", "Tuhan mereka", "their Lord"),
    "ولو": ("wa law", "dan kalaulah", "and if only"),
    "مما": ("mimmā", "dari apa", "from what"),
    "الحق": ("al-ḥaqq", "kebenaran", "the truth"),
    "السما": ("as-samā'", "langit", "the sky"),
    "منكم": ("minkum", "dari kalian", "from you"),
    "ربنا": ("rabbanā", "Tuhan kami", "our Lord"),
    "عليم": ("'alīm", "Maha Mengetahui", "All-Knowing"),
    "موسي": ("mūsā", "Musa", "Moses"),
    "انهم": ("innahum", "sesungguhnya mereka", "indeed they"),
    "النار": ("an-nār", "neraka", "the Fire"),
    "ربكم": ("rabbukum", "Tuhan kalian", "your Lord"),
    "فلما": ("fa-lammā", "maka ketika", "and when"),
    "انزل": ("unzila", "diturunkan", "was revealed"),
    "ربي": ("rabbī", "Tuhanku", "my Lord"),
    "لمن": ("la-man", "sungguh bagi yang", "indeed for who"),
    "دون": ("dūn", "selain", "besides; without"),
    "فمن": ("fa-man", "maka siapa", "then who"),
    "منه": ("minhu", "darinya", "from him"),
    "سبيل": ("sabīl", "jalan", "path; way"),
    "فاذا": ("fa-idhā", "maka apabila", "then when"),
    "فما": ("fa-mā", "maka apa; maka tidak", "then what; then not"),
    "كذلك": ("ka-dhālika", "demikianlah", "thus"),
    "منها": ("minhā", "darinya", "from it"),
    "يؤمنون": ("yu'minūn", "mereka beriman", "they believe"),
    "العذاب": ("al-'adhāb", "azab", "the punishment"),
    "وقال": ("wa qāla", "dan dia berkata", "and he said"),
    "الم": ("alif lām mīm", "Alif Lam Mim", "Alif-Lam-Meem"),
    "مبين": ("mubīn", "jelas; nyata", "clear; evident"),
    "وكان": ("wa kāna", "dan dia adalah", "and he was"),
    "انتم": ("antum", "kalian", "you (pl.)"),
    "تعملون": ("ta'malūn", "kalian mengerjakan", "you do"),
    "خلق": ("khalaqa", "dia menciptakan", "He created"),
    "لنا": ("lanā", "bagi kami", "for us"),
    "يعلمون": ("ya'lamūn", "mereka mengetahui", "they know"),
    "بين": ("bayna", "antara; di antara", "between; among"),
    "للذين": ("li-lladhīna", "bagi orang-orang yang", "for those who"),
    "بها": ("bihā", "dengannya", "with it"),
    "قوم": ("qawm", "kaum", "people; nation"),
    "المؤمنين": ("al-mu'minīn", "orang-orang beriman", "the believers"),
    "لو": ("law", "kalaulah; seandainya", "if; if only"),
    "اله": ("ilāh", "tuhan; sembahan", "god"),
    "اليك": ("ilayka", "kepadamu", "to you"),
    "شيا": ("shay'an", "sesuatu", "a thing"),
    "اليه": ("ilayhi", "kepadanya", "to him"),
    "عنهم": ("'anhum", "dari mereka", "from them"),
    "بالحق": ("bil-ḥaqq", "dengan kebenaran", "with the truth"),
    "لما": ("li-mā", "untuk apa; untuk yang", "for what"),
    "انفسهم": ("anfusahum", "diri mereka", "themselves"),
    "جهنم": ("jahannam", "Jahanam; neraka", "Hell"),
    "واذ": ("wa idh", "dan ketika", "and when"),
    "الاخره": ("al-ākhirah", "akhirat", "the Hereafter"),
    "القيمه": ("al-qiyāmah", "hari kiamat", "the Resurrection"),
    "لك": ("laka", "bagimu", "for you"),
    "يعلم": ("ya'lam", "dia mengetahui", "he knows"),
    "علم": ("'ilm", "ilmu", "knowledge"),
    "غير": ("ghayr", "selain; bukan", "other than"),
    "هل": ("hal", "apakah", "is; do (question)"),
    "كتب": ("kitāb", "kitab", "a Book"),
    "التي": ("allatī", "yang (perempuan)", "which; that (fem.)"),
    "فرعون": ("fir'awn", "Firaun", "Pharaoh"),
    "قلوبهم": ("qulūbuhum", "hati mereka", "their hearts"),
    "نحن": ("naḥnu", "kami", "we"),
    "يوميذ": ("yawma-idhin", "hari itu", "that day"),
    "الظلمين": ("aẓ-ẓālimīn", "orang-orang zalim", "the wrongdoers"),
    "العزيز": ("al-'azīz", "Yang Maha Perkasa", "the Almighty"),
    "الحيوه": ("al-ḥayāh", "kehidupan", "life"),
    "الشيطن": ("ash-shayṭān", "setan", "Satan; the devil"),
    "كنا": ("kunnā", "kami adalah", "we were"),
    "لي": ("lī", "bagiku", "for me"),
    "اصحب": ("aṣḥāb", "penghuni; para sahabat", "companions; dwellers"),
    "القوم": ("al-qawm", "kaum itu", "the people"),
    "جنت": ("jannāt", "surga-surga", "gardens (of Paradise)"),
    "كيف": ("kayfa", "bagaimana", "how"),
    "الصلحت": ("aṣ-ṣāliḥāt", "amal saleh", "righteous deeds"),
    "العلمين": ("al-'ālamīn", "semesta alam", "the worlds"),
    "بعض": ("ba'ḍ", "sebagian", "some"),
    "رحيم": ("raḥīm", "Maha Penyayang", "Most Merciful"),
    "كما": ("kamā", "sebagaimana", "just as"),
    "اليم": ("alīm", "pedih", "painful"),
    "اليل": ("al-layl", "malam", "the night"),
    "لعلكم": ("la'allakum", "agar kalian", "so that you may"),
    "لن": ("lan", "tidak akan", "will never"),
    "الانسان": ("al-insān", "manusia", "mankind"),
    "الصلوه": ("aṣ-ṣalāh", "salat", "the prayer"),
    "بينهم": ("baynahum", "di antara mereka", "among them"),
    "مع": ("ma'a", "bersama", "with"),
    "انت": ("anta", "kamu (laki-laki)", "you (masc.)"),
    "جا": ("jā'a", "dia datang", "he came"),
    "عليك": ("'alayka", "atasmu", "upon you"),
    "فقد": ("fa-qad", "maka sungguh", "then indeed"),
    "الجنه": ("al-jannah", "surga", "Paradise"),
    "تعلمون": ("ta'lamūn", "kalian mengetahui", "you know"),
    "شا": ("shā'a", "dia menghendaki", "He wills"),
    "اعلم": ("a'lam", "aku lebih tahu", "I know best"),
    "انك": ("innaka", "sesungguhnya kamu", "indeed you"),
    "قليلا": ("qalīlan", "sedikit", "a little"),
    "يعملون": ("ya'malūn", "mereka mengerjakan", "they do"),
    "لقد": ("laqad", "sungguh", "indeed"),
    "وعملوا": ("wa 'amilū", "dan mereka mengerjakan", "and they did"),
    "الكفرين": ("al-kāfirīn", "orang-orang kafir", "the disbelievers"),
    "ايت": ("āyāt", "ayat-ayat; tanda-tanda", "signs; verses"),
    "رسول": ("rasūl", "rasul; utusan", "messenger"),
    "غفور": ("ghafūr", "Maha Pengampun", "Oft-Forgiving"),
    "ارسلنا": ("arsalnā", "kami mengutus", "We sent"),
    "كنت": ("kunta", "kamu adalah", "you were"),
    "امه": ("ummah", "umat", "a nation; community"),
    "ايه": ("āyah", "ayat; tanda", "a sign; verse"),
    "عظيم": ("'aẓīm", "agung; besar", "great; mighty"),
    "الدين": ("ad-dīn", "agama", "the religion; the Day of Judgement"),
    "ليس": ("laysa", "bukan; tidak ada", "is not"),
    "مثل": ("mithl", "seperti; perumpamaan", "like; example"),
    "نفس": ("nafs", "jiwa; diri", "soul; self"),
    "هي": ("hiya", "dia (perempuan)", "she; it"),
    "كثيرا": ("kathīran", "banyak", "much; many"),
    "هذه": ("hādhihi", "ini (perempuan)", "this (fem.)"),
    "الرحمن": ("ar-raḥmān", "Yang Maha Pengasih", "the Most Gracious"),
    "الرسول": ("ar-rasūl", "rasul itu", "the Messenger"),
    "جعل": ("ja'ala", "dia menjadikan", "He made"),
    "خلدين": ("khālidīn", "kekal", "abiding forever"),
}


def main():
    with open(VOCAB, encoding="utf-8") as f:
        data = json.load(f)
    # Gabung kurasi gelombang kedua & ketiga (ketiga menang kalau bentrok).
    merged = {**CURATED_EXTRA, **CURATED, **VOCAB_EXTRA}
    filled = 0
    for e in data["entries"]:
        key = e["key"]
        if key in merged:
            translit, meaning_id, meaning_en = merged[key]
            e["translit"] = translit
            e["meaningId"] = meaning_id
            e["meaningEn"] = meaning_en
            filled += 1
    apply_roots(data["entries"])
    with open(VOCAB, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=1)
        f.write("\n")
    total = len(data["entries"])
    print(f"Terkurasi: {filled} / {total} entri ({filled * 100 // total}%)")


# Awalan kata yang bisa dilepas untuk mencari akar (و/ف/ب/ل/ك).
PREFIXES = ("و", "ف", "ب", "ل", "ك")


def apply_roots(entries):
    """Isi `root` (+ rootMeaningId/En) tiap entri.

    Aturan:
    1. `vocab_roots.ROOTS[key]` kalau ada.
    2. Awalan و/ف/ب/ل/ك dilepas dulu, sisa dicari di ROOTS (mis. "وقال" → قول).
    3. Fallback: kunci itu sendiri (kata tugas/fungsi tidak punya keluarga).
    Arti akar: override `ROOT_MEANINGS[root]`, atau diturunkan dari anggota
    keluarga pertama (paling sering) yang sudah terkurasi.
    """
    root_meaning = {}  # root -> (meaningId, meaningEn) turunan pertama
    for e in entries:
        key = e["key"]
        root = ROOTS.get(key)
        if root is None:
            for p in PREFIXES:
                if key.startswith(p):
                    rest = key[len(p):]
                    if rest in ROOTS:
                        root = ROOTS[rest]
                        break
        if root is None:
            root = key
        e["root"] = root

        override = ROOT_MEANINGS.get(root)
        if override is not None:
            e["rootMeaningId"], e["rootMeaningEn"] = override
        elif root in root_meaning:
            e["rootMeaningId"], e["rootMeaningEn"] = root_meaning[root]
        elif e["meaningId"]:
            e["rootMeaningId"], e["rootMeaningEn"] = e["meaningId"], e["meaningEn"]
            root_meaning[root] = (e["meaningId"], e["meaningEn"])
        else:
            e["rootMeaningId"], e["rootMeaningEn"] = "", ""


# ---- Perluasan gelombang kedua (top-600): ±390 arti baru ----
CURATED_EXTRA = {
    "عما": ("'ammā", "tentang apa; dari apa", "about what"),
    "ولم": ("wa lam", "dan tidak", "and not"),
    "عليها": ("'alayhā", "atasnya", "upon it"),
    "فاوليك": ("fa-ulā'ika", "maka mereka itu", "then those"),
    "افلا": ("a-fa-lā", "maka tidakkah", "then do they not ...?"),
    "انكم": ("innakum", "sesungguhnya kalian", "indeed you"),
    "وانتم": ("wa antum", "dan kalian", "and you"),
    "ذلكم": ("dhālikum", "itu; itulah", "that"),
    "ربه": ("rabbahū", "Tuhannya", "his Lord"),
    "ويوم": ("wa yawm", "dan hari", "and the day"),
    "يهدي": ("yahdī", "Dia memberi petunjuk", "He guides"),
    "ابرهيم": ("ibrāhīm", "Ibrahim", "Abraham"),
    "الانهر": ("al-anhār", "sungai-sungai", "rivers"),
    "القران": ("al-qur'ān", "Al-Qur'an", "the Qur'an"),
    "اهل": ("ahl", "keluarga; penduduk", "family; people of"),
    "كذبوا": ("kadhdhabū", "mereka mendustakan", "they denied"),
    "ولهم": ("wa lahum", "dan bagi mereka", "and for them"),
    "يقوم": ("yā qawmi", "wahai kaumku", "O my people"),
    "اسرايل": ("isrā'īl", "Israel", "Israel"),
    "الحكيم": ("al-ḥakīm", "Yang Maha Bijaksana", "the All-Wise"),
    "ظلموا": ("ẓalamū", "mereka berbuat zalim", "they wronged"),
    "واتقوا": ("wa-ttaqū", "dan bertakwalah", "and be mindful (of Allah)"),
    "ورسولهٗ": ("wa rasūlihī", "dan rasul-Nya", "and His Messenger"),
    "وقد": ("wa qad", "dan sungguh", "and indeed"),
    "اليوم": ("al-yawm", "hari ini", "this day"),
    "امر": ("amara", "dia memerintahkan", "He commanded"),
    "بهم": ("bihim", "dengan mereka", "with them"),
    "جاهم": ("jā'ahum", "datang kepada mereka", "came to them"),
    "فهم": ("fa-hum", "maka mereka", "then they"),
    "لعلهم": ("la'allahum", "semoga mereka", "so that they may"),
    "لها": ("lahā", "baginya (perempuan)", "for it; for her"),
    "هؤلا": ("hā'ulā'", "mereka ini", "these"),
    "واما": ("wa ammā", "dan adapun", "and as for"),
    "اليهم": ("ilayhim", "kepada mereka", "to them"),
    "بغير": ("bi-ghayr", "dengan tanpa", "without"),
    "قوما": ("qawman", "suatu kaum", "a people"),
    "امن": ("āmana", "dia beriman", "he believed"),
    "هدي": ("hudan", "petunjuk", "guidance"),
    "وعلي": ("wa 'alā", "dan di atas", "and upon"),
    "يحب": ("yuḥibbu", "Dia mencintai", "He loves"),
    "يقول": ("yaqūlu", "dia berkata", "he says"),
    "اكثرهم": ("aktharuhum", "kebanyakan mereka", "most of them"),
    "المليكه": ("al-malā'ikah", "para malaikat", "the angels"),
    "امنا": ("āmannā", "kami beriman", "we believed"),
    "انفسكم": ("anfusakum", "diri kalian", "yourselves"),
    "حكيم": ("ḥakīm", "bijaksana", "wise"),
    "دونه": ("dūnihī", "selain-Nya", "besides Him"),
    "ذكر": ("dhikr", "peringatan; mengingat", "reminder; remembrance"),
    "عذابا": ("'adhāban", "azab", "a punishment"),
    "كلا": ("kullan", "seluruhnya", "all of it"),
    "وعد": ("wa'ada", "Dia menjanjikan", "He promised"),
    "وكذلك": ("wa ka-dhālika", "dan demikianlah", "and likewise"),
    "يريد": ("yurīdu", "Dia menghendaki", "He wants"),
    "بكم": ("bukmun", "bisu", "dumb; mute"),
    "خيرا": ("khayran", "kebaikan", "good"),
    "عنه": ("'anhu", "daripadanya", "from him"),
    "قدير": ("qadīr", "Maha Kuasa", "All-Powerful"),
    "لولا": ("lawlā", "kalaulah tidak", "if not for"),
    "وانهٗ": ("wa innahū", "dan sesungguhnya dia", "and indeed he"),
    "وجعلنا": ("wa ja'alnā", "dan Kami menjadikan", "and We made"),
    "العظيم": ("al-'aẓīm", "Yang Maha Agung", "the Almighty"),
    "تحتها": ("taḥtahā", "di bawahnya", "beneath it"),
    "الساعه": ("as-sā'ah", "hari kiamat", "the Hour"),
    "الموت": ("al-mawt", "kematian", "death"),
    "اولم": ("a-wa-lam", "tidakkah", "did not ...?"),
    "شديد": ("shadīd", "keras; dahsyat", "severe"),
    "فباي": ("fa-bi-ayyi", "maka dengan yang mana", "then with which"),
    "منا": ("minnā", "dari kami", "from us"),
    "وكانوا": ("wa kānū", "dan mereka adalah", "and they were"),
    "يكون": ("yakūnu", "dia ada; terjadi", "he is; happens"),
    "اوليا": ("awliyā'", "pelindung-pelindung", "allies; protectors"),
    "بايت": ("bi-āyāt", "dengan ayat-ayat", "with the signs"),
    "بكل": ("bi-kulli", "dengan segala", "with every"),
    "رحمه": ("raḥmah", "rahmat", "mercy"),
    "قيل": ("qīla", "dikatakan", "it was said"),
    "مؤمنين": ("mu'minīn", "orang-orang beriman", "believers"),
    "ايتنا": ("āyātinā", "ayat-ayat Kami", "Our signs"),
    "ايديهم": ("aydīhim", "tangan-tangan mereka", "their hands"),
    "بعضهم": ("ba'ḍuhum", "sebagian mereka", "some of them"),
    "حق": ("ḥaqq", "benar; hak", "truth; right"),
    "ربكما": ("rabbukumā", "Tuhan kalian berdua", "the Lord of you two"),
    "قبلك": ("qablaka", "sebelummu", "before you"),
    "له": ("lahū", "baginya", "for him"),
    "ملك": ("māliki", "pemilik; penguasa", "owner; Master"),
    "ولين": ("wa la-in", "dan sesungguhnya jika", "and indeed if"),
    "اجر": ("ajr", "upah; pahala", "reward"),
    "احسن": ("aḥsanu", "lebih baik", "better"),
    "الامر": ("al-amr", "urusan; perintah", "the matter; command"),
    "الاولين": ("al-awwalīn", "orang-orang terdahulu", "the former ones"),
    "العليم": ("al-'alīm", "Yang Maha Mengetahui", "the All-Knowing"),
    "اليكم": ("ilaykum", "kepada kalian", "to you"),
    "اوتوا": ("ūtū", "mereka diberi", "they were given"),
    "سوا": ("sawā'", "sama", "equal"),
    "صراط": ("ṣirāṭ", "jalan", "path"),
    "وفي": ("wa fī", "dan di dalam", "and in"),
    "ولما": ("wa lammā", "dan ketika", "and when"),
    "يكن": ("yakun", "dia ada (subjungtif)", "he is (subj.)"),
    "اكثر": ("akthar", "kebanyakan; lebih banyak", "most; more"),
    "الايت": ("al-āyāt", "ayat-ayat", "the signs"),
    "بني": ("banī", "anak-anak", "children of"),
    "بينهما": ("baynahumā", "di antara keduanya", "between them both"),
    "تر": ("tara", "kamu melihat", "you see"),
    "تكذبن": ("tukadhdhibān", "kalian berdua mendustakan", "you two deny"),
    "صالحا": ("ṣāliḥan", "saleh", "righteous"),
    "صدقين": ("ṣādiqīn", "orang-orang benar", "the truthful"),
    "فضل": ("faḍl", "karunia", "bounty"),
    "معهٗ": ("ma'ahū", "bersamanya", "with him"),
    "ممن": ("mimman", "dari orang yang", "from those who"),
    "احد": ("aḥad", "seorang pun; satu", "anyone; one"),
    "المحسنين": ("al-muḥsinīn", "orang-orang berbuat baik", "the doers of good"),
    "النبي": ("an-nabī", "nabi", "the Prophet"),
    "سو": ("sū'", "keburukan", "evil"),
    "فانما": ("fa-innamā", "maka hanyalah", "then only"),
    "والي": ("wa ilā", "dan kepada", "and to"),
    "اتقوا": ("ittaqū", "bertakwalah", "be mindful (of Allah)"),
    "الاخر": ("al-ākhir", "yang akhir", "the Last"),
    "بينكم": ("baynakum", "di antara kalian", "among you"),
    "جعلنا": ("ja'alnā", "Kami menjadikan", "We made"),
    "حيث": ("ḥaythu", "di tempat", "where"),
    "حين": ("ḥīn", "waktu", "time"),
    "ربهٗ": ("rabbuhū", "Tuhannya", "his Lord"),
    "سبيلا": ("sabīlan", "jalan", "a path"),
    "فاما": ("fa-ammā", "maka adapun", "then as for"),
    "قالت": ("qālat", "dia (perempuan) berkata", "she said"),
    "لايت": ("la-āyāt", "sungguh tanda-tanda", "surely signs"),
    "لفي": ("la-fī", "sungguh di dalam", "surely in"),
    "نذير": ("nadhīr", "pemberi peringatan", "a warner"),
    "نوح": ("nūḥ", "Nuh", "Noah"),
    "واحده": ("wāḥidah", "satu", "one (fem.)"),
    "وجعل": ("wa ja'ala", "dan Dia menjadikan", "and He made"),
    "ابدا": ("abadan", "selama-lamanya", "forever"),
    "ابن": ("ibn", "anak laki-laki", "son"),
    "اشد": ("ashadd", "lebih keras", "severer"),
    "السبيل": ("as-sabīl", "jalan", "the path"),
    "العلم": ("al-'ilm", "ilmu", "knowledge"),
    "الغيب": ("al-ghayb", "yang gaib", "the unseen"),
    "القول": ("al-qawl", "ucapan", "the saying"),
    "الملك": ("al-mulk", "kerajaan", "the dominion"),
    "تلك": ("tilka", "itu (perempuan)", "that (fem.)"),
    "جزا": ("jazā'", "balasan", "recompense"),
    "فهو": ("fa-huwa", "maka dia", "then he"),
    "كانت": ("kānat", "dia (perempuan) adalah", "it was"),
    "لين": ("la-in", "sesungguhnya jika", "indeed if"),
    "مريم": ("maryam", "Maryam; Mary", "Mary"),
    "ويقولون": ("wa yaqūlūn", "dan mereka berkata", "and they say"),
    "يظلمون": ("yaẓlimūn", "mereka berbuat zalim", "they wrong"),
    "اعمالهم": ("a'māluhum", "amal perbuatan mereka", "their deeds"),
    "ايته": ("āyātuhū", "ayat-ayat-Nya", "His signs"),
    "بصير": ("baṣīr", "Maha Melihat", "All-Seeing"),
    "ضلل": ("ḍalāl", "kesesatan", "misguidance"),
    "عاقبه": ("'āqibah", "akibat; kesudahan", "end; outcome"),
    "فقال": ("fa-qāla", "maka dia berkata", "then he said"),
    "قومه": ("qawmuhū", "kaumnya", "his people"),
    "لكل": ("li-kulli", "bagi setiap", "for every"),
    "ولله": ("wa li-llāhi", "dan bagi Allah", "and to Allah"),
    "يؤمن": ("yu'min", "dia beriman", "he believes"),
    "يدعون": ("yad'ūn", "mereka menyeru", "they call"),
    "يروا": ("yaraw", "mereka melihat", "they see"),
    "الحمد": ("al-ḥamd", "segala puji", "all praise"),
    "الزكوه": ("az-zakāh", "zakat", "the alms"),
    "الهدي": ("al-hudā", "petunjuk", "the guidance"),
    "جناح": ("junāḥ", "dosa; keberatan", "sin; blame"),
    "فسوف": ("fa-sawfa", "maka kelak", "then soon"),
    "فضله": ("faḍlihī", "karunia-Nya", "His bounty"),
    "كذب": ("kudhdhiba", "didustakan", "was denied"),
    "مستقيم": ("mustaqīm", "lurus", "straight"),
    "معكم": ("ma'akum", "bersama kalian", "with you"),
    "والنهار": ("wa-n-nahār", "dan siang", "and the day"),
    "ولي": ("waliyy", "pelindung", "protector; ally"),
    "ومنهم": ("wa minhum", "dan dari mereka", "and among them"),
    "النهار": ("an-nahār", "siang", "the daylight"),
    "انزلنا": ("anzalnā", "Kami menurunkan", "We sent down"),
    "بانهم": ("bi-annahum", "karena sesungguhnya mereka", "because they"),
    "تكون": ("takūnu", "kamu ada; terjadi", "you be; happens"),
    "جاكم": ("jā'akum", "datang kepada kalian", "came to you"),
    "خبير": ("khabīr", "Maha Mengetahui", "All-Aware"),
    "ذو": ("dhū", "pemilik", "possessor of"),
    "واوليك": ("wa ulā'ika", "dan mereka itu", "and those"),
    "ينظرون": ("yanẓurūn", "mereka melihat", "they look"),
    "الجبال": ("al-jibāl", "gunung-gunung", "the mountains"),
    "الظلمون": ("aẓ-ẓālimūn", "orang-orang zalim", "the wrongdoers"),
    "المرسلين": ("al-mursalīn", "para rasul", "the messengers"),
    "المشركين": ("al-mushrikīn", "orang-orang musyrik", "the polytheists"),
    "النسا": ("an-nisā'", "wanita-wanita", "the women"),
    "بالبينت": ("bil-bayyināt", "dengan bukti-bukti nyata", "with clear proofs"),
    "تعقلون": ("ta'qilūn", "kalian memahami", "you understand"),
    "خلدون": ("khālidūn", "kekal", "abiding forever"),
    "عنكم": ("'ankum", "dari kalian", "from you"),
    "عنها": ("'anhā", "daripadanya", "from it"),
    "فيما": ("fīmā", "di dalam apa", "in what"),
    "ورحمه": ("wa raḥmah", "dan rahmat", "and mercy"),
    "ورسوله": ("wa rasūlihī", "dan rasul-Nya", "and His Messenger"),
    "ولولا": ("wa lawlā", "dan kalaulah tidak", "and if not for"),
    "يموسي": ("yā mūsā", "wahai Musa", "O Moses"),
    "اجل": ("ajal", "batas waktu", "appointed term"),
    "اجمعين": ("ajma'īn", "seluruhnya", "all together"),
    "ال": ("āl", "keluarga", "family of"),
    "البحر": ("al-baḥr", "laut", "the sea"),
    "الجحيم": ("al-jaḥīm", "neraka Jahim", "the Blazing Fire"),
    "الحرام": ("al-ḥarām", "yang suci; diharamkan", "the Sacred; forbidden"),
    "المتقين": ("al-muttaqīn", "orang-orang bertakwa", "the God-fearing"),
    "المصير": ("al-maṣīr", "tempat kembali", "the destination"),
    "باذن": ("bi-idhni", "dengan izin", "by permission"),
    "تولوا": ("tawallaw", "mereka berpaling", "they turned away"),
    "حسنا": ("ḥusnan", "kebaikan", "goodness"),
    "رسولا": ("rasūlan", "seorang rasul", "a messenger"),
    "عباده": ("'ibādihī", "hamba-hamba-Nya", "His servants"),
    "عدو": ("'aduww", "musuh", "enemy"),
    "عزيز": ("'azīz", "perkasa; mulia", "mighty; honored"),
    "فتنه": ("fitnah", "cobaan; fitnah", "trial; persecution"),
    "فهل": ("fa-hal", "maka apakah", "then is ...?"),
    "قريه": ("qaryah", "kampung; negeri", "a town"),
    "للكفرين": ("lil-kāfirīn", "bagi orang-orang kafir", "for the disbelievers"),
    "واليوم": ("wa-l-yawm", "dan hari", "and the day"),
    "اتينا": ("ātainā", "Kami berikan", "We gave"),
    "اجرا": ("ajran", "pahala; upah", "a reward"),
    "المؤمنون": ("al-mu'minūn", "orang-orang beriman", "the believers"),
    "المبين": ("al-mubīn", "yang jelas", "the clear"),
    "بشر": ("bashar", "manusia", "a human being"),
    "بلي": ("balā", "ya; bahkan", "yes indeed"),
    "عظيما": ("'aẓīman", "agung", "great"),
    "عليما": ("'alīman", "mengetahui", "knowing"),
    "فلن": ("fa-lan", "maka tidak akan", "then will never"),
    "ماذا": ("mādhā", "apa", "what"),
    "نزل": ("nazzala", "Dia menurunkan", "He sent down"),
    "واليه": ("wa ilayhi", "dan kepada-Nya", "and to Him"),
    "ولن": ("wa lan", "dan tidak akan", "and never"),
    "ياتي": ("ya'tī", "dia datang", "he comes"),
    "يرجعون": ("yarji'ūn", "mereka kembali", "they return"),
    "يعقلون": ("ya'qilūn", "mereka memahami", "they understand"),
    "اتخذوا": ("ittakhadhū", "mereka menjadikan", "they took"),
    "الفلك": ("al-fulk", "kapal", "the ship"),
    "ايمانكم": ("īmānukum", "iman kalian", "your faith"),
    "ايمانهم": ("īmānuhum", "iman mereka", "their faith"),
    "بالاخره": ("bil-ākhirah", "dengan akhirat", "in the Hereafter"),
    "تكن": ("takun", "kamu ada (subjungtif)", "you be (subj.)"),
    "تكونوا": ("takūnū", "kalian ada", "you be"),
    "حرم": ("ḥarrama", "Dia mengharamkan", "He forbade"),
    "خلقنا": ("khalaqnā", "Kami ciptakan", "We created"),
    "سلم": ("salām", "kedamaian; salam", "peace"),
    "سميع": ("samī'", "Maha Mendengar", "All-Hearing"),
    "عسي": ("'asā", "mudah-mudahan", "perhaps; maybe"),
    "مسمي": ("musamman", "disebut; ditentukan", "appointed; named"),
    "نشا": ("nashā'", "Kami kehendaki", "We will"),
    "وقل": ("wa qul", "dan katakanlah", "and say"),
    "وكفي": ("wa kafā", "dan cukuplah", "and sufficient is"),
    "يشعرون": ("yash'urūn", "mereka menyadari", "they perceive"),
    "يوسف": ("yūsuf", "Yusuf", "Joseph"),
    "احدا": ("aḥadan", "seorang pun", "anyone"),
    "اخاف": ("akhāfu", "aku takut", "I fear"),
    "الشمس": ("ash-shams", "matahari", "the sun"),
    "العرش": ("al-'arsh", "Arasy", "the Throne"),
    "اموالهم": ("amwāluhum", "harta mereka", "their wealth"),
    "اول": ("awwal", "pertama", "first"),
    "ايام": ("ayyām", "hari-hari", "days"),
    "بالمعروف": ("bil-ma'rūf", "dengan cara yang baik", "with kindness"),
    "بعضكم": ("ba'ḍukum", "sebagian kalian", "some of you"),
    "تدعون": ("tad'ūn", "kalian menyeru", "you call"),
    "تعبدون": ("ta'budūn", "kalian menyembah", "you worship"),
    "رحيما": ("raḥīman", "penyayang", "merciful"),
    "شهيدا": ("shahīdan", "saksi", "a witness"),
    "عملوا": ("'amilū", "mereka mengerjakan", "they did"),
    "غفورا": ("ghafūran", "pengampun", "forgiving"),
    "كريم": ("karīm", "mulia", "generous; noble"),
    "كفر": ("kafara", "dia kufur", "he disbelieved"),
    "لايه": ("la-āyah", "sungguh tanda", "surely a sign"),
    "مثلا": ("mathalan", "sebagai contoh", "as an example"),
    "نار": ("nār", "api", "fire"),
    "نجزي": ("najzī", "Kami membalas", "We recompense"),
    "والقمر": ("wal-qamar", "dan bulan", "and the moon"),
    "يبني": ("yā banī", "wahai anak-anak", "O children of"),
    "يسمعون": ("yasma'ūn", "mereka mendengar", "they hear"),
    "ينفقون": ("yunfiqūn", "mereka membelanjakan", "they spend"),
    "اكبر": ("akbar", "lebih besar", "greater"),
    "الجن": ("al-jinn", "jin", "the jinn"),
    "الذكر": ("adh-dhikr", "peringatan; Al-Qur'an", "the Reminder"),
    "السميع": ("as-samī'", "Yang Maha Mendengar", "the All-Hearing"),
    "الصلحين": ("aṣ-ṣāliḥīn", "orang-orang saleh", "the righteous"),
    "المجرمين": ("al-mujrimīn", "orang-orang berdosa", "the criminals"),
    "الينا": ("ilaynā", "kepada kami", "to us"),
    "امرا": ("amran", "suatu urusan; perintah", "a matter"),
    "انها": ("annahā", "sesungguhnya dia (perempuan)", "that it"),
    "اولي": ("awlā", "lebih berhak", "more worthy"),
    "بعده": ("ba'dahū", "sesudahnya", "after it"),
    "تتقون": ("tattaqūn", "kalian bertakwa", "you fear (Allah)"),
    "ترجعون": ("turja'ūn", "kalian dikembalikan", "you are returned"),
    "تري": ("tarā", "kamu melihat", "you see"),
    "تشكرون": ("tashkurūn", "kalian bersyukur", "you are grateful"),
    "ذي": ("dhī", "pemilik", "possessor of"),
    "عندهٗ": ("'indahū", "di sisi-Nya", "with Him"),
    "قبله": ("qiblah", "kiblat", "direction of prayer"),
    "قولا": ("qawlan", "ucapan", "a saying"),
    "قوه": ("quwwah", "kekuatan", "strength"),
    "كلمه": ("kalimah", "kalimat; perkataan", "a word"),
    "لهو": ("la-huwa", "sungguh dia", "surely he"),
    "نارا": ("nāran", "api", "a fire"),
    "والاخره": ("wal-ākhirah", "dan akhirat", "and the Hereafter"),
    "ولكم": ("wa lakum", "dan bagi kalian", "and for you"),
    "يشركون": ("yushrikūn", "mereka mempersekutukan (Allah)", "they associate (with Allah)"),
    "اتخذ": ("ittakhadha", "dia menjadikan", "he took"),
    "اتينهم": ("ātaynāhum", "Kami berikan kepada mereka", "We gave them"),
    "اراد": ("arāda", "Dia menghendaki", "He wanted"),
    "البر": ("al-birr", "kebaikan; kebajikan", "righteousness"),
    "الرسل": ("ar-rusul", "para rasul", "the messengers"),
    "جاتهم": ("jā'athum", "datang kepada mereka", "came to them"),
    "جنه": ("jannah", "surga", "a garden (of Paradise)"),
    "خلقكم": ("khalaqakum", "Dia menciptakan kalian", "He created you"),
    "سحر": ("siḥr", "sihir", "sorcery"),
    "ضل": ("ḍalla", "dia sesat", "he went astray"),
    "فقالوا": ("fa-qālū", "maka mereka berkata", "then they said"),
    "فقل": ("fa-qul", "maka katakanlah", "then say"),
    "قبلكم": ("qablakum", "sebelum kalian", "before you"),
    "للمتقين": ("lil-muttaqīn", "bagi orang-orang bertakwa", "for the God-fearing"),
    "نفسه": ("nafsahū", "dirinya", "himself"),
    "واحد": ("wāḥid", "satu", "one"),
    "واعلموا": ("wa-'lamū", "dan ketahuilah", "and know"),
    "واني": ("wa annī", "dan sesungguhnya aku", "and that I"),
    "يتقون": ("yattaqūn", "mereka bertakwa", "they fear (Allah)"),
    "يحي": ("yuḥyī", "Dia menghidupkan", "He gives life"),
    "يغفر": ("yaghfiru", "Dia mengampuni", "He forgives"),
    "يفترون": ("yaftarūn", "mereka mengada-ada", "they invent (lies)"),
    "يوحي": ("yūḥī", "Dia mewahyukan", "He reveals"),
    "اتبع": ("ittaba'a", "dia mengikuti", "he followed"),
    "اظلم": ("aẓlam", "lebih zalim", "more unjust"),
    "اعبدوا": ("u'budū", "sembahlah", "worship!"),
    "افمن": ("a-fa-man", "maka apakah orang yang", "is he who ...?"),
    "الريح": ("ar-rīḥ", "angin", "the wind"),
    "الصدقين": ("aṣ-ṣādiqīn", "orang-orang benar", "the truthful"),
    "القري": ("al-qurā", "negeri-negeri", "the towns"),
    "الكفرون": ("al-kāfirūn", "orang-orang kafir", "the disbelievers"),
    "الما": ("al-mā'", "air", "water"),
    "المسجد": ("al-masjid", "masjid", "the mosque"),
    "الهه": ("ālihah", "tuhan-tuhan", "gods"),
    "اما": ("ammā", "adapun", "as for"),
    "اين": ("ayna", "di mana", "where"),
    "بان": ("bi-anna", "bahwa sesungguhnya", "that indeed"),
    "بعدهم": ("ba'dahum", "sesudah mereka", "after them"),
    "بينت": ("bayyināt", "bukti-bukti nyata", "clear proofs"),
    "بيننا": ("baynanā", "di antara kami", "between us"),
    "تجد": ("tajid", "kamu menemukan", "you find"),
    "تذكرون": ("tadhakkarūn", "kalian mengambil pelajaran", "you take heed"),
    "حسنه": ("ḥasanah", "kebaikan", "a good deed"),
    "حقا": ("ḥaqqan", "sungguh", "truly"),
    "ذات": ("dhāt", "yang memiliki; diri", "possessor of"),
    "طايفه": ("ṭā'ifah", "segolongan", "a group"),
    "عاد": ("'ād", "kaum 'Ad", "the people of 'Ad"),
    "فاتقوا": ("fa-ttaqū", "maka bertakwalah", "then fear (Allah)"),
    "فانهٗ": ("fa-innahū", "maka sesungguhnya dia", "then indeed he"),
    "فاني": ("fa-innī", "maka sesungguhnya aku", "then indeed I"),
    "كبيرا": ("kabīran", "besar", "great"),
    "مغفره": ("maghfirah", "ampunan", "forgiveness"),
    "واتوا": ("wa ātū", "dan berikanlah", "and give"),
    "وجوههم": ("wujūhuhum", "wajah mereka", "their faces"),
    "ولد": ("walad", "anak", "a child"),
    "يبين": ("yubayyin", "Dia menerangkan", "He makes clear"),
    "يحكم": ("yaḥkumu", "Dia memutuskan", "He judges"),
    "يخرج": ("yukhrij", "Dia mengeluarkan", "He brings out"),
    "يديه": ("yadayhi", "kedua tangannya", "his hands"),
    "يضل": ("yuḍill", "Dia menyesatkan", "He leads astray"),
    "يفعل": ("yaf'al", "dia berbuat", "he does"),
    "ينزل": ("yunazzil", "Dia menurunkan", "He sends down"),
    "الالباب": ("al-albāb", "orang-orang berakal", "people of understanding"),
    "الحساب": ("al-ḥisāb", "perhitungan", "the reckoning"),
    "الخلق": ("al-khalq", "penciptaan", "creation"),
    "الصدور": ("aṣ-ṣudūr", "dada-dada", "the chests"),
    "العقاب": ("al-'iqāb", "hukuman", "the punishment"),
    "الفوز": ("al-fawz", "kemenangan", "the success"),
    "الموتي": ("al-mawtā", "orang-orang mati", "the dead"),
    "الها": ("ilāhan", "tuhan", "a god"),
    "امرنا": ("amrunā", "urusan Kami; perintah Kami", "Our command"),
    "اهلكنا": ("ahlaknā", "Kami binasakan", "We destroyed"),
    "اهلها": ("ahlahā", "penduduknya", "its people"),
    "تاتيهم": ("ta'tīhim", "datang kepada mereka", "comes to them"),
    "تتلي": ("tutlā", "dibacakan", "is recited"),
    "حكيما": ("ḥakīman", "bijaksana", "wise"),
    "ذا": ("dhā", "pemilik", "possessor of"),
    "ريب": ("rayb", "keraguan", "doubt"),
    "سمعنا": ("sami'nā", "kami mendengar", "we heard"),
    "عمل": ("'amala", "dia mengerjakan", "he did"),
    "فكيف": ("fa-kayfa", "maka bagaimana", "then how"),
    "فلم": ("fa-lam", "maka tidak", "then not"),
    "فيهم": ("fīhim", "di antara mereka", "among them"),
    "قدمت": ("qaddamat", "yang telah diperbuat", "sent forth"),
    "قضي": ("qaḍā", "Dia menetapkan; memutuskan", "He decreed"),
    "كذبا": ("kidhban", "dusta", "falsehood"),
    "كذبت": ("kudhdhibat", "didustakan", "was denied"),
    "كسبت": ("kasabat", "dia memperoleh; mengusahakan", "she earned"),
}

CURATED.update(CURATED_EXTRA)


if __name__ == "__main__":
    main()
