#!/usr/bin/env python3
"""
Kurasi arti kosa kata → isi `assets/quran/vocab.json`.

Daftar arti di bawah (kunci ternormalisasi → transliterasi, arti ID, arti EN)
ditulis manual untuk kata-kata paling sering (target ±150–200 entri; ~80%
kemunculan kata di Al-Qur'an). Entri yang belum dikurasi dibiarkan kosong
dan TIDAK tampil di aplikasi (VocabularyRepository menyaringnya).

Pakai:  python3 tools/curate_vocab.py
Setelah menambah arti baru, jalankan ulang — skrip hanya mengisi field yang
kosong, tidak menimpa yang sudah ada.
"""

import json
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
VOCAB = os.path.join(ROOT, "app", "src", "main", "assets", "quran", "vocab.json")

# key → (translit, meaningId, meaningEn)
CURATED = {
    "من": ("min", "dari", "from"),
    "الله": ("allāh", "Allah", "Allah"),
    "ان": ("inna", "sesungguhnya", "indeed"),
    "في": ("fī", "di dalam", "in"),
    "ما": ("mā", "apa; yang; tidak", "what; that; not"),
    "الذين": ("alladhīna", "orang-orang yang", "those who"),
    "لا": ("lā", "tidak", "no; not"),
    "الا": ("illā", "kecuali", "except"),
    "علي": ("'alā", "di atas", "upon; on"),
    "ولا": ("wa lā", "dan tidak", "and not"),
    "وما": ("wa mā", "dan apa; dan tidak", "and what; and not"),
    "الي": ("ilā", "ke; kepada", "to"),
    "قال": ("qāla", "dia berkata", "he said"),
    "لهم": ("lahum", "bagi mereka", "for them"),
    "ومن": ("wa min", "dan dari", "and from"),
    "ثم": ("thumma", "kemudian", "then"),
    "لكم": ("lakum", "bagi kalian", "for you"),
    "كان": ("kāna", "dia adalah", "he was"),
    "به": ("bihī", "dengannya", "with it"),
    "وان": ("wa in", "dan jika", "and if"),
    "بما": ("bimā", "dengan apa; dengan yang", "with what; with that"),
    "قل": ("qul", "katakanlah", "say!"),
    "الارض": ("al-arḍ", "bumi", "the earth"),
    "او": ("aw", "atau", "or"),
    "ذلك": ("dhālika", "itu", "that"),
    "الذي": ("alladhī", "yang", "who; which"),
    "هو": ("huwa", "dia (laki-laki)", "he; it"),
    "امنوا": ("āmanū", "mereka beriman", "they believed"),
    "هم": ("hum", "mereka", "they; them"),
    "قالوا": ("qālū", "mereka berkata", "they said"),
    "كل": ("kull", "setiap; seluruh", "every; all"),
    "لهٗ": ("lahū", "baginya", "for him"),
    "فيها": ("fīhā", "di dalamnya", "in it"),
    "والله": ("wa-llāhu", "dan Allah", "and Allah"),
    "انا": ("innā", "sesungguhnya kami", "indeed we"),
    "اذا": ("idhā", "apabila", "when"),
    "كانوا": ("kānū", "mereka adalah", "they were"),
    "عن": ("'an", "dari; tentang", "from; about"),
    "ربك": ("rabbuka", "Tuhanmu", "your Lord"),
    "يوم": ("yawm", "hari", "day"),
    "عليهم": ("'alayhim", "atas mereka", "upon them"),
    "شي": ("shay'", "sesuatu", "something"),
    "هذا": ("hādhā", "ini", "this"),
    "كفروا": ("kafarū", "mereka kafir", "they disbelieved"),
    "كنتم": ("kuntum", "kalian adalah", "you were"),
    "السموت": ("as-samāwāt", "langit-langit", "the heavens"),
    "الناس": ("an-nās", "manusia", "mankind"),
    "لم": ("lam", "tidak (lampau)", "not (past)"),
    "فان": ("fa-in", "maka jika", "then if"),
    "وهو": ("wa huwa", "dan dia", "and he"),
    "اذ": ("idh", "ketika (dulu)", "when (past)"),
    "عليكم": ("'alaykum", "atas kalian", "upon you"),
    "والذين": ("wa-lladhīna", "dan orang-orang yang", "and those who"),
    "الكتب": ("al-kitāb", "kitab", "the Book"),
    "انهٗ": ("innahū", "sesungguhnya dia", "indeed he"),
    "اني": ("innī", "sesungguhnya aku", "indeed I"),
    "والارض": ("wa-l-arḍ", "dan bumi", "and the earth"),
    "فلا": ("fa-lā", "maka tidak", "so not"),
    "منهم": ("minhum", "dari mereka", "from them"),
    "عذاب": ("'adhāb", "azab; siksaan", "punishment"),
    "بعد": ("ba'd", "sesudah", "after"),
    "عليه": ("'alayhi", "atasnya", "upon him"),
    "حتي": ("ḥattā", "sehingga; sampai", "until"),
    "يايها": ("yā ayyuhā", "wahai", "O (vocative)"),
    "بالله": ("bi-llāhi", "demi Allah", "by Allah"),
    "وهم": ("wa hum", "dan mereka", "and they"),
    "واذا": ("wa idhā", "dan apabila", "and when"),
    "اوليك": ("ulā'ika", "mereka itu", "those"),
    "انما": ("innamā", "hanyalah", "only; indeed"),
    "ام": ("am", "ataukah", "or"),
    "رب": ("rabb", "Tuhan", "Lord"),
    "ولقد": ("wa laqad", "dan sungguh", "and indeed"),
    "بل": ("bal", "bahkan; sebaliknya", "rather; nay"),
    "فيه": ("fīhi", "di dalamnya", "in it"),
    "قد": ("qad", "sungguh", "indeed (perfective)"),
    "يشا": ("yashā'", "dia menghendaki", "He wills"),
    "عند": ("'inda", "di sisi", "with; near"),
    "قبل": ("qabl", "sebelum", "before"),
    "خير": ("khayr", "lebih baik; kebaikan", "better; goodness"),
    "لله": ("li-llāhi", "bagi Allah", "for Allah"),
    "الدنيا": ("ad-dunyā", "dunia", "the world"),
    "ولكن": ("wa lākin", "akan tetapi", "but"),
    "ربهم": ("rabbuhum", "Tuhan mereka", "their Lord"),
    "ولو": ("wa law", "dan kalaulah", "and if only"),
    "مما": ("mimmā", "dari apa", "from what"),
    "الحق": ("al-ḥaqq", "kebenaran", "the truth"),
    "السما": ("as-samā'", "langit", "the sky"),
    "منكم": ("minkum", "dari kalian", "from you"),
    "ربنا": ("rabbanā", "Tuhan kami", "our Lord"),
    "عليم": ("'alīm", "Maha Mengetahui", "All-Knowing"),
    "موسي": ("mūsā", "Musa", "Moses"),
    "انهم": ("innahum", "sesungguhnya mereka", "indeed they"),
    "النار": ("an-nār", "neraka", "the Fire"),
    "ربكم": ("rabbukum", "Tuhan kalian", "your Lord"),
    "فلما": ("fa-lammā", "maka ketika", "and when"),
    "انزل": ("unzila", "diturunkan", "was revealed"),
    "ربي": ("rabbī", "Tuhanku", "my Lord"),
    "لمن": ("la-man", "sungguh bagi yang", "indeed for who"),
    "دون": ("dūn", "selain", "besides; without"),
    "فمن": ("fa-man", "maka siapa", "then who"),
    "منه": ("minhu", "darinya", "from him"),
    "سبيل": ("sabīl", "jalan", "path; way"),
    "فاذا": ("fa-idhā", "maka apabila", "then when"),
    "فما": ("fa-mā", "maka apa; maka tidak", "then what; then not"),
    "كذلك": ("ka-dhālika", "demikianlah", "thus"),
    "منها": ("minhā", "darinya", "from it"),
    "يؤمنون": ("yu'minūn", "mereka beriman", "they believe"),
    "العذاب": ("al-'adhāb", "azab", "the punishment"),
    "وقال": ("wa qāla", "dan dia berkata", "and he said"),
    "الم": ("alif lām mīm", "Alif Lam Mim", "Alif-Lam-Meem"),
    "مبين": ("mubīn", "jelas; nyata", "clear; evident"),
    "وكان": ("wa kāna", "dan dia adalah", "and he was"),
    "انتم": ("antum", "kalian", "you (pl.)"),
    "تعملون": ("ta'malūn", "kalian mengerjakan", "you do"),
    "خلق": ("khalaqa", "dia menciptakan", "He created"),
    "لنا": ("lanā", "bagi kami", "for us"),
    "يعلمون": ("ya'lamūn", "mereka mengetahui", "they know"),
    "بين": ("bayna", "antara; di antara", "between; among"),
    "للذين": ("li-lladhīna", "bagi orang-orang yang", "for those who"),
    "بها": ("bihā", "dengannya", "with it"),
    "قوم": ("qawm", "kaum", "people; nation"),
    "المؤمنين": ("al-mu'minīn", "orang-orang beriman", "the believers"),
    "لو": ("law", "kalaulah; seandainya", "if; if only"),
    "اله": ("ilāh", "tuhan; sembahan", "god"),
    "اليك": ("ilayka", "kepadamu", "to you"),
    "شيا": ("shay'an", "sesuatu", "a thing"),
    "اليه": ("ilayhi", "kepadanya", "to him"),
    "عنهم": ("'anhum", "dari mereka", "from them"),
    "بالحق": ("bil-ḥaqq", "dengan kebenaran", "with the truth"),
    "لما": ("li-mā", "untuk apa; untuk yang", "for what"),
    "انفسهم": ("anfusahum", "diri mereka", "themselves"),
    "جهنم": ("jahannam", "Jahanam; neraka", "Hell"),
    "واذ": ("wa idh", "dan ketika", "and when"),
    "الاخره": ("al-ākhirah", "akhirat", "the Hereafter"),
    "القيمه": ("al-qiyāmah", "hari kiamat", "the Resurrection"),
    "لك": ("laka", "bagimu", "for you"),
    "يعلم": ("ya'lam", "dia mengetahui", "he knows"),
    "علم": ("'ilm", "ilmu", "knowledge"),
    "غير": ("ghayr", "selain; bukan", "other than"),
    "هل": ("hal", "apakah", "is; do (question)"),
    "كتب": ("kitāb", "kitab", "a Book"),
    "التي": ("allatī", "yang (perempuan)", "which; that (fem.)"),
    "فرعون": ("fir'awn", "Firaun", "Pharaoh"),
    "قلوبهم": ("qulūbuhum", "hati mereka", "their hearts"),
    "نحن": ("naḥnu", "kami", "we"),
    "يوميذ": ("yawma-idhin", "hari itu", "that day"),
    "الظلمين": ("aẓ-ẓālimīn", "orang-orang zalim", "the wrongdoers"),
    "العزيز": ("al-'azīz", "Yang Maha Perkasa", "the Almighty"),
    "الحيوه": ("al-ḥayāh", "kehidupan", "life"),
    "الشيطن": ("ash-shayṭān", "setan", "Satan; the devil"),
    "كنا": ("kunnā", "kami adalah", "we were"),
    "لي": ("lī", "bagiku", "for me"),
    "اصحب": ("aṣḥāb", "penghuni; para sahabat", "companions; dwellers"),
    "القوم": ("al-qawm", "kaum itu", "the people"),
    "جنت": ("jannāt", "surga-surga", "gardens (of Paradise)"),
    "كيف": ("kayfa", "bagaimana", "how"),
    "الصلحت": ("aṣ-ṣāliḥāt", "amal saleh", "righteous deeds"),
    "العلمين": ("al-'ālamīn", "semesta alam", "the worlds"),
    "بعض": ("ba'ḍ", "sebagian", "some"),
    "رحيم": ("raḥīm", "Maha Penyayang", "Most Merciful"),
    "كما": ("kamā", "sebagaimana", "just as"),
    "اليم": ("alīm", "pedih", "painful"),
    "اليل": ("al-layl", "malam", "the night"),
    "لعلكم": ("la'allakum", "agar kalian", "so that you may"),
    "لن": ("lan", "tidak akan", "will never"),
    "الانسان": ("al-insān", "manusia", "mankind"),
    "الصلوه": ("aṣ-ṣalāh", "salat", "the prayer"),
    "بينهم": ("baynahum", "di antara mereka", "among them"),
    "مع": ("ma'a", "bersama", "with"),
    "انت": ("anta", "kamu (laki-laki)", "you (masc.)"),
    "جا": ("jā'a", "dia datang", "he came"),
    "عليك": ("'alayka", "atasmu", "upon you"),
    "فقد": ("fa-qad", "maka sungguh", "then indeed"),
    "الجنه": ("al-jannah", "surga", "Paradise"),
    "تعلمون": ("ta'lamūn", "kalian mengetahui", "you know"),
    "شا": ("shā'a", "dia menghendaki", "He wills"),
    "اعلم": ("a'lam", "aku lebih tahu", "I know best"),
    "انك": ("innaka", "sesungguhnya kamu", "indeed you"),
    "قليلا": ("qalīlan", "sedikit", "a little"),
    "يعملون": ("ya'malūn", "mereka mengerjakan", "they do"),
    "لقد": ("laqad", "sungguh", "indeed"),
    "وعملوا": ("wa 'amilū", "dan mereka mengerjakan", "and they did"),
    "الكفرين": ("al-kāfirīn", "orang-orang kafir", "the disbelievers"),
    "ايت": ("āyāt", "ayat-ayat; tanda-tanda", "signs; verses"),
    "رسول": ("rasūl", "rasul; utusan", "messenger"),
    "غفور": ("ghafūr", "Maha Pengampun", "Oft-Forgiving"),
    "ارسلنا": ("arsalnā", "kami mengutus", "We sent"),
    "كنت": ("kunta", "kamu adalah", "you were"),
    "امه": ("ummah", "umat", "a nation; community"),
    "ايه": ("āyah", "ayat; tanda", "a sign; verse"),
    "عظيم": ("'aẓīm", "agung; besar", "great; mighty"),
    "الدين": ("ad-dīn", "agama", "the religion; the Day of Judgement"),
    "ليس": ("laysa", "bukan; tidak ada", "is not"),
    "مثل": ("mithl", "seperti; perumpamaan", "like; example"),
    "نفس": ("nafs", "jiwa; diri", "soul; self"),
    "هي": ("hiya", "dia (perempuan)", "she; it"),
    "كثيرا": ("kathīran", "banyak", "much; many"),
    "هذه": ("hādhihi", "ini (perempuan)", "this (fem.)"),
    "الرحمن": ("ar-raḥmān", "Yang Maha Pengasih", "the Most Gracious"),
    "الرسول": ("ar-rasūl", "rasul itu", "the Messenger"),
    "جعل": ("ja'ala", "dia menjadikan", "He made"),
    "خلدين": ("khālidīn", "kekal", "abiding forever"),
}


def main():
    with open(VOCAB, encoding="utf-8") as f:
        data = json.load(f)
    filled = 0
    for e in data["entries"]:
        key = e["key"]
        if key in CURATED:
            translit, meaning_id, meaning_en = CURATED[key]
            e["translit"] = translit
            e["meaningId"] = meaning_id
            e["meaningEn"] = meaning_en
            filled += 1
    with open(VOCAB, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=1)
        f.write("\n")
    total = len(data["entries"])
    print(f"Terkurasi: {filled} / {total} entri ({filled * 100 // total}%)")


if __name__ == "__main__":
    main()
