# -*- coding: utf-8 -*-
"""
Terjemahan BAHASA INGGRIS untuk konten "Belajar Arab" (assets/lughoh).

Kunci = teks Indonesia (id) → teks Inggris. Dipakai oleh
`tools/build_lughoh.py` (inject_en): field `en`/`promptEn`/`optionsEn`/
`answerEn`/`speakerEn` disisipkan ke konten saat build, dan kelengkapan
divalidasi — SEMUA teks id WAJIB punya terjemahan EN, kalau tidak build
gagal (integritas konten).

Kunci unik per teks Indonesia: teks yang sama dipakai berulang (mis. "Apa
ini?") cukup satu entri — terjemahannya konsisten.
"""

# ---------------------------------------------------------------------------
# Level & pelajaran
# ---------------------------------------------------------------------------
LEVEL_EN = {
    "Level 1 — Perkenalan & Kehidupan Sehari-hari": "Level 1 — Introductions & Daily Life",
    "Level 2 — Pasar, Transportasi, Kesehatan, Olahraga & Rutinitas": "Level 2 — Market, Transportation, Health, Sports & Routine",
    "Level 3 — Perjalanan, Pekerjaan, Media, Interaksi & Budaya": "Level 3 — Travel, Work, Media, Social Interaction & Culture",
}

LESSON_EN = {
    "Perkenalan Diri": "Self-Introduction",
    "Keluarga": "Family",
    "Sekolah": "School",
    "Rumah": "Home",
    "Makanan": "Food",
    "Di Pasar": "At the Market",
    "Transportasi": "Transportation",
    "Kesehatan": "Health",
    "Olahraga": "Sports",
    "Rutinitas Harian": "Daily Routine",
    "Perjalanan": "Travel",
    "Pekerjaan": "Work",
    "Media": "Media",
    "Interaksi Sosial": "Social Interaction",
    "Budaya": "Culture",
}

# ---------------------------------------------------------------------------
# Nama pembicara dialog: nama orang (Ahmad, Fatimah, ...) TIDAK diterjemahkan;
# hanya label peran yang punya padanan EN.
# ---------------------------------------------------------------------------
SPEAKER_EN = {
    "Ustadz": "Ustadh",
    "Dokter": "Doctor",
    "Penjual": "Vendor",
}

# ---------------------------------------------------------------------------
# Dialog (muhadatsah), arti kosakata, contoh kalimat, dan tata bahasa (qawaid)
# ---------------------------------------------------------------------------
TEXTS = {
    # ---- L1-1 ----
    "Semoga keselamatan atas kalian": "Peace be upon you",
    "Dan semoga keselamatan atas kalian juga": "And peace be upon you too",
    "Siapa namamu?": "What is your name?",
    "Namaku Fatimah. Dan kamu?": "My name is Fatimah. And you?",
    "Aku Ahmad. Selamat datang": "I am Ahmad. Welcome",
    "Selamat datang juga": "Welcome to you too",
    "Dari mana kamu?": "Where are you from?",
    "Aku dari Indonesia. Dan kamu?": "I am from Indonesia. And you?",
    "Aku juga dari Indonesia": "I am from Indonesia too",
    "Senang berkenalan": "Nice to meet you",
    "salam sejahtera": "greetings of peace",
    "Semoga keselamatan atasmu, Ahmad": "Peace be upon you, Ahmad",
    "nama": "name",
    "Namaku Ahmad": "My name is Ahmad",
    "apa": "what",
    "Apa ini?": "What is this?",
    "saya": "I",
    "Aku seorang pelajar": "I am a student",
    "kamu (laki-laki)": "you (male)",
    "kamu (perempuan)": "you (female)",
    "dari": "from",
    "Aku dari Jakarta": "I am from Jakarta",
    "di mana": "where",
    "Di mana kamu?": "Where are you?",
    "Indonesia": "Indonesia",
    "Aku dari Indonesia": "I am from Indonesia",
    "juga": "also, too",
    "Aku juga seorang pelajar": "I am a student too",
    "Kata ganti orang (ضمائر): أَنَا، أَنْتَ، أَنْتِ": "Personal pronouns (ضمائر): أَنَا، أَنْتَ، أَنْتِ",
    "أَنَا berarti saya, أَنْتَ berarti kamu (untuk laki-laki), dan أَنْتِ berarti kamu (untuk perempuan). Perhatikan bahwa kata ganti 'kamu' berbeda jenis kelaminnya.": "أَنَا means I, أَنْتَ means you (for a male), and أَنْتِ means you (for a female). Notice that the pronoun 'you' differs by gender.",
    "Kalimat nominal (jumlah ismiyyah)": "Nominal sentence (jumlah ismiyyah)",
    "Kalimat Arab bisa tersusun tanpa kata kerja: kata pertama disebut mubtada' (subjek), kata kedua khabar (predikat). Contoh: أَنَا = mubtada', مِنْ إِنْدُونِيسِيَّا = khabar.": "An Arabic sentence can be formed without a verb: the first word is called mubtada' (subject) and the second khabar (predicate). Example: أَنَا = mubtada', مِنْ إِنْدُونِيسِيَّا = khabar.",
    "Kata tanya مَا": "The question word مَا",
    "مَا dipakai untuk menanyakan nama atau benda, artinya 'apa'. Untuk bertanya nama, gunakan مَا اسْمُكَ (kepada laki-laki) atau مَا اسْمُكِ (kepada perempuan).": "مَا is used to ask about a name or a thing; it means 'what'. To ask for a name, use مَا اسْمُكَ (to a male) or مَا اسْمُكِ (to a female).",

    # ---- L1-2 ----
    "Apa ini, Ahmad?": "What is this, Ahmad?",
    "Ini foto keluargaku": "This is a picture of my family",
    "Siapa ini?": "Who is this?",
    "Ini ayahku": "This is my father",
    "Dan siapa ini?": "And who is this?",
    "Ini ibuku": "This is my mother",
    "Apakah kamu punya saudara?": "Do you have siblings?",
    "Ya, aku punya saudara laki-laki dan saudara perempuan": "Yes, I have a brother and a sister",
    "Dan siapa ini dan ini?": "And who are this one and this one?",
    "Ini kakekku dan ini nenekku": "This is my grandfather and this is my grandmother",
    "ini (laki-laki/benda maskulin)": "this (masculine)",
    "Ini sebuah buku": "This is a book",
    "ini (perempuan/benda feminin)": "this (feminine)",
    "Ini sebuah sekolah": "This is a school",
    "foto, gambar": "picture, photo",
    "Ini foto rumahku": "This is a picture of my house",
    "keluarga": "family",
    "Keluargaku besar": "My family is big",
    "ayah": "father",
    "Ayahku seorang dokter": "My father is a doctor",
    "ibu": "mother",
    "Ibuku seorang guru": "My mother is a teacher",
    "saudara laki-laki": "brother",
    "Saudara laki-lakiku kecil": "My brother is young",
    "saudara perempuan": "sister",
    "Saudara perempuanku besar": "My sister is grown up",
    "kakek": "grandfather",
    "Kakekku tua": "My grandfather is old",
    "nenek": "grandmother",
    "Nenekku baik hati": "My grandmother is kind",
    "Kata tunjuk هٰذَا dan هٰذِهِ": "Demonstratives هٰذَا and هٰذِهِ",
    "هٰذَا berarti 'ini' untuk laki-laki atau kata benda maskulin (mis. أَبٌ، كِتَابٌ). هٰذِهِ untuk perempuan atau kata benda feminin (mis. أُمٌّ، صُورَةٌ).": "هٰذَا means 'this' for a male or a masculine noun (e.g. أَبٌ، كِتَابٌ). هٰذِهِ is for a female or a feminine noun (e.g. أُمٌّ، صُورَةٌ).",
    "Kata tanya مَنْ untuk orang": "The question word مَنْ for people",
    "مَنْ berarti 'siapa' dan dipakai untuk menanyakan orang, berbeda dengan مَا yang menanyakan benda.": "مَنْ means 'who' and is used to ask about people, unlike مَا which asks about things.",
    "Idhafah: menyambung dua kata benda": "Idhafah: joining two nouns",
    "Dua kata benda bisa dirangkai: kata pertama milik kata kedua, mis. صُورَةُ عَائِلَتِي = foto keluargaku. Kata kedua kehilangan tanwin.": "Two nouns can be joined: the first noun belongs to the second, e.g. صُورَةُ عَائِلَتِي = the picture of my family. The second noun loses its tanwin.",

    # ---- L1-3 ----
    "Selamat pagi, Fatimah": "Good morning, Fatimah",
    "Selamat pagi": "Good morning",
    "Aku di sekolah": "I am at school",
    "Apa yang kamu pelajari?": "What are you studying?",
    "Aku belajar bahasa Arab": "I am studying Arabic",
    "Ini sebuah pena": "This is a pen",
    "Ini sebuah penggaris": "This is a ruler",
    "selamat pagi": "good morning",
    "Selamat pagi, Ustadz": "Good morning, Ustadh",
    "selamat pagi (jawaban)": "good morning (reply)",
    "sekolah": "school",
    "Sekolahnya besar": "The school is big",
    "di dalam": "inside",
    "Bukunya di dalam tas": "The book is inside the bag",
    "buku": "book",
    "Ini buku baru": "This is a new book",
    "pena, pulpen": "pen",
    "Penaku merah": "My pen is red",
    "penggaris": "ruler",
    "Penggarisnya panjang": "The ruler is long",
    "apa (untuk bertanya kegiatan)": "what (for asking about an activity)",
    "Apa yang kamu baca?": "What are you reading?",
    "bahasa": "language",
    "Bahasa Arab itu indah": "Arabic is beautiful",
    "bahasa Arab": "Arabic (language)",
    "Kata tanya أَيْنَ (di mana)": "The question word أَيْنَ (where)",
    "أَيْنَ dipakai untuk menanyakan tempat. Jawabannya biasanya memakai kata depan فِي (di dalam).": "أَيْنَ is used to ask about a place. The answer usually uses the preposition فِي (in/inside).",
    "Kata depan فِي (di)": "The preposition فِي (in)",
    "فِي berarti 'di dalam' dan diikuti kata benda berakhiran kasrah (jar). Contoh: فِي الْمَدْرَسَةِ = di sekolah.": "فِي means 'in/inside' and is followed by a noun ending in kasrah (jar). Example: فِي الْمَدْرَسَةِ = at school.",
    "Kata kerja sekarang (fi'il mudhari')": "Present tense verb (fi'il mudhari')",
    "أَدْرُسُ berarti 'aku sedang belajar' dan تَدْرُسِينَ berarti 'kamu (perempuan) sedang belajar'. Kata kerja berubah mengikuti pelakunya.": "أَدْرُسُ means 'I am studying' and تَدْرُسِينَ means 'you (female) are studying'. The verb changes according to its doer.",
    "Aku belajar bahasa Arab": "I am studying Arabic",

    # ---- L1-4 ----
    "Di mana rumahmu, Ahmad?": "Where is your house, Ahmad?",
    "Rumahku di Jakarta": "My house is in Jakarta",
    "Apakah rumahmu besar?": "Is your house big?",
    "Ya, rumahku besar": "Yes, my house is big",
    "Berapa kamar di rumahmu?": "How many rooms are in your house?",
    "Di rumahku ada empat kamar": "There are four rooms in my house",
    "Dan di mana dapurnya?": "And where is the kitchen?",
    "Dapur dekat dengan kamar mandi": "The kitchen is close to the bathroom",
    "Ini pintu rumah": "This is the door of the house",
    "rumah": "house",
    "Rumahku dekat dengan masjid": "My house is close to the mosque",
    "besar": "big",
    "Rumahnya besar": "His house is big",
    "kamar, ruangan": "room",
    "Kamarku bersih": "My room is clean",
    "dapur": "kitchen",
    "Dapurnya luas": "The kitchen is spacious",
    "kamar mandi": "bathroom",
    "Kamar mandinya bersih": "The bathroom is clean",
    "pintu": "door",
    "Pintu kamarnya terbuka": "The door of the room is open",
    "ya (jawaban setuju)": "yes (agreement)",
    "Ya, ini bukuku": "Yes, this is my book",
    "berapa": "how many",
    "Berapa buku yang kamu punya?": "How many books do you have?",
    "dekat": "near, close",
    "Masjidnya dekat dengan rumah": "The mosque is close to the house",
    "empat": "four",
    "Aku punya empat buku": "I have four books",
    "Kata tanya أَيْنَ + فِي untuk tempat": "أَيْنَ + فِي for places",
    "Untuk bertanya tempat gunakan أَيْنَ (di mana). Jawabannya memakai فِي (di) atau قَرِيبٌ مِنْ (dekat dengan).": "To ask about a place use أَيْنَ (where). The answer uses فِي (in) or قَرِيبٌ مِنْ (close to).",
    "Kata tanya كَمْ (berapa)": "The question word كَمْ (how many)",
    "كَمْ dipakai untuk menanyakan jumlah. Kata benda setelahnya berakhiran -an (nasab), mis. كَمْ غُرْفَةً؟ = berapa kamar?": "كَمْ is used to ask about a quantity. The noun after it ends in -an (nasab), e.g. كَمْ غُرْفَةً؟ = how many rooms?",
    "Kalimat dengan kata sifat (na't)": "Sentences with adjectives (na't)",
    "Kata sifat mengikuti kata benda dalam jenisnya: بَيْتٌ كَبِيرٌ (rumah besar, maskulin), مَدْرَسَةٌ كَبِيرَةٌ (sekolah besar, feminin).": "The adjective follows its noun in gender: بَيْتٌ كَبِيرٌ (a big house, masculine), مَدْرَسَةٌ كَبِيرَةٌ (a big school, feminine).",

    "Aku Ahmad": "I am Ahmad",
    "Rumahku besar": "My house is big",
    "Nama ayahku Ahmad": "My father's name is Ahmad",
    "Berapa harga apel ini?": "How much is this apple?",

    # ---- L1-5 ----
    "Apa ini, Fatimah?": "What is this, Fatimah?",
    "Ini roti": "This is bread",
    "Dan apa ini?": "And what is this?",
    "Ini nasi": "This is rice",
    "Aku sangat suka nasi": "I really like rice",
    "Dan ini sup": "And this is soup",
    "Ini buah": "This is fruit",
    "Apa nama buah ini?": "What is the name of this fruit?",
    "Namanya pisang": "Its name is banana",
    "Makanannya lezat": "The food is delicious",
    "makanan": "food",
    "Makanannya ada di dapur": "The food is in the kitchen",
    "roti": "bread",
    "Rotinya segar": "The bread is fresh",
    "nasi": "rice",
    "Nasi berasal dari Indonesia": "Rice comes from Indonesia",
    "sup": "soup",
    "Supnya pedas": "The soup is spicy",
    "buah": "fruit",
    "Buahnya enak": "The fruit is tasty",
    "pisang": "banana",
    "Pisangnya berwarna kuning": "The banana is yellow",
    "saya suka": "I like",
    "Aku suka roti": "I like bread",
    "sangat, banyak": "very, a lot",
    "Aku sangat suka buah": "I really like fruit",
    "lezat, enak": "delicious, tasty",
    "Rotinya lezat": "The bread is delicious",
    "أُحِبُّ + kata benda (saya suka ...)": "أُحِبُّ + noun (I like ...)",
    "أُحِبُّ berarti 'saya suka/mencintai'. Kata benda sesudahnya berakhiran -a (nasab), contoh: أُحِبُّ الْأَرُزَّ = aku suka nasi.": "أُحِبُّ means 'I like/love'. The noun after it ends in -a (nasab), e.g. أُحِبُّ الْأَرُزَّ = I like rice.",
    "Kata sifat (na't) mengikuti kata benda": "Adjectives (na't) follow the noun",
    "Kata sifat mengikuti kata benda dalam jenisnya: الطَّعَامُ لَذِيذٌ (makanan lezat, maskulin) dan الْفَاكِهَةُ لَذِيذَةٌ (buah lezat, feminin).": "The adjective follows its noun in gender: الطَّعَامُ لَذِيذٌ (the food is delicious, masculine) and الْفَاكِهَةُ لَذِيذَةٌ (the fruit is delicious, feminine).",
    "Menanyakan nama benda: مَا اسْمُ ...؟": "Asking the name of a thing: مَا اسْمُ ...؟",
    "Untuk menanyakan nama sesuatu gunakan مَا اسْمُ ...؟ (apa nama ...?). Jawabannya: اسْمُهُ (namanya, maskulin) atau اسْمُهَا (namanya, feminin).": "To ask the name of something use مَا اسْمُ ...؟ (what is the name of ...?). The answer: اسْمُهُ (its name, masculine) or اسْمُهَا (its name, feminine).",

    # ---- L2-1 ----
    "Hari ini aku di pasar": "Today I am at the market",
    "Semoga keselamatan, silakan": "Peace be upon you, please come in",
    "Dan semoga keselamatan. Berapa harga apel ini?": "And peace be upon you too. How much is this apple?",
    "Satu kilo sepuluh ribu rupiah": "One kilo is ten thousand rupiah",
    "Ini sangat mahal": "This is very expensive",
    "Maka jeruk ini lebih murah": "Then these oranges are cheaper",
    "Berapa harga jeruk?": "How much are the oranges?",
    "Harganya delapan ribu per kilo": "They are eight thousand per kilo",
    "Bagus. Aku ambil dua kilo": "Good. I will take two kilos",
    "Baiklah, silakan": "Alright, here you go",
    "pasar": "market",
    "Pasarnya dekat dengan rumah": "The market is close to the house",
    "apel": "apple",
    "Apelnya lezat": "The apple is delicious",
    "jeruk": "orange",
    "Jeruknya berwarna kuning": "The orange is yellow",
    "harga": "price",
    "Harga bukunya mahal": "The price of the book is expensive",
    "mahal": "expensive",
    "Kemeja ini mahal": "This shirt is expensive",
    "lebih murah": "cheaper",
    "Buku ini lebih murah daripada itu": "This book is cheaper than that one",
    "kilo": "kilo",
    "Satu kilo nasi sepuluh ribu": "One kilo of rice is ten thousand",
    "rupiah": "rupiah",
    "Ini lima ribu rupiah": "This is five thousand rupiah",
    "aku mengambil": "I take",
    "Aku mengambil buku dari perpustakaan": "I take a book from the library",
    "sangat": "very",
    "Rumahnya sangat besar": "His house is very big",
    "بِكَمْ untuk bertanya harga": "بِكَمْ to ask the price",
    "بِكَمْ berarti 'berapa harganya?'. Jawaban harga memakai بِ (dengan/seharga), mis. بِعَشَرَةِ آلَافِ رُوبِيَّة = seharga sepuluh ribu rupiah.": "بِكَمْ means 'how much is it?'. The price answer uses بِ (with/for), e.g. بِعَشَرَةِ آلَافِ رُوبِيَّة = for ten thousand rupiah.",
    "Angka 3–10 + kata benda jamak": "Numbers 3–10 + plural noun",
    "Untuk angka 3 sampai 10, kata bendanya berbentuk jamak: عَشَرَةُ آلَافٍ (sepuluh ribu), ثَمَانِيَةُ آلَافٍ (delapan ribu).": "For numbers 3 to 10, the noun takes the plural form: عَشَرَةُ آلَافٍ (ten thousand), ثَمَانِيَةُ آلَافٍ (eight thousand).",
    "Bentuk perbandingan أَفْعَل": "The comparative form أَفْعَل",
    "أَرْخَصُ berarti 'lebih murah', bentuk perbandingan dari رَخِيصٌ (murah). Pola ini dipakai untuk membandingkan: أَكْبَرُ (lebih besar), أَقْرَبُ (lebih dekat).": "أَرْخَصُ means 'cheaper', the comparative form of رَخِيصٌ (cheap). This pattern is used for comparing: أَكْبَرُ (bigger), أَقْرَبُ (closer).",

    # ---- L2-2 ----
    "Bagaimana kamu pergi ke sekolah?": "How do you go to school?",
    "Aku pergi dengan mobil": "I go by car",
    "Dan bagaimana kamu pergi ke pasar?": "And how do you go to the market?",
    "Aku pergi dengan sepeda motor": "I go by motorcycle",
    "Apakah sekolahnya jauh?": "Is the school far?",
    "Tidak, sekolahnya dekat": "No, the school is near",
    "Dan di mana halte bus?": "And where is the bus stop?",
    "Halte bus di depan masjid": "The bus stop is in front of the mosque",
    "Apakah kamu naik bus?": "Do you take the bus?",
    "Ya, kadang-kadang": "Yes, sometimes",
    "bagaimana": "how",
    "Bagaimana kabarmu?": "How are you?",
    "aku pergi": "I go",
    "Aku pergi ke masjid": "I go to the mosque",
    "mobil": "car",
    "Mobilnya baru": "The car is new",
    "sepeda motor": "motorcycle",
    "Sepeda motornya cepat": "The motorcycle is fast",
    "stasiun, halte": "station, stop",
    "Stasiun keretanya jauh": "The train station is far",
    "bus": "bus",
    "Busnya besar": "The bus is big",
    "jauh": "far",
    "Sekolahnya jauh dari rumahku": "The school is far from my house",
    "di depan": "in front of",
    "Masjidnya di depan sekolah": "The mosque is in front of the school",
    "kadang-kadang": "sometimes",
    "Aku kadang-kadang pergi naik bus": "Sometimes I go by bus",
    "ke (arah)": "to (direction)",
    "Aku pergi ke pasar": "I go to the market",
    "كَيْفَ untuk bertanya cara": "كَيْفَ to ask how",
    "كَيْفَ berarti 'bagaimana' dan dipakai untuk menanyakan cara melakukan sesuatu, mis. cara pergi ke suatu tempat.": "كَيْفَ means 'how' and is used to ask about the way of doing something, e.g. how to go to a place.",
    "بِ + alat transportasi": "بِ + means of transport",
    "Untuk menyebut alat yang dipakai, gunakan بِ (dengan): بِالسَّيَّارَةِ (dengan mobil), بِالدَّرَّاجَةِ النَّارِيَّةِ (dengan sepeda motor).": "To mention the means used, use بِ (by/with): بِالسَّيَّارَةِ (by car), بِالدَّرَّاجَةِ النَّارِيَّةِ (by motorcycle).",
    "إِلَى untuk arah tujuan": "إِلَى for direction",
    "إِلَى berarti 'ke' dan menunjukkan arah/tujuan: إِلَى الْمَدْرَسَةِ (ke sekolah), إِلَى السُّوقِ (ke pasar).": "إِلَى means 'to' and shows direction/destination: إِلَى الْمَدْرَسَةِ (to school), إِلَى السُّوقِ (to the market).",

    # ---- L2-3 ----
    "Ada apa denganmu, Ahmad?": "What is wrong with you, Ahmad?",
    "Aku sakit kepala yang parah": "I have a severe headache",
    "Apakah kamu demam?": "Do you have a fever?",
    "Ya, aku juga demam": "Yes, I have a fever too",
    "Tolong buka mulutmu": "Please open your mouth",
    "Kamu terkena flu": "You have the flu",
    "Apa yang harus kulakukan, Dokter?": "What should I do, Doctor?",
    "Beristirahatlah di rumah dan minumlah air": "Rest at home and drink water",
    "Apakah aku boleh makan buah?": "May I eat fruit?",
    "Ya, makanlah buah dan minumlah air banyak-banyak": "Yes, eat fruit and drink plenty of water",
    "dokter": "doctor",
    "Dokternya ada di rumah sakit": "The doctor is at the hospital",
    "sakit kepala": "headache",
    "Hari ini aku sakit kepala": "Today I have a headache",
    "demam": "fever",
    "Demam hari ini tinggi": "The fever is high today",
    "flu, pilek": "flu",
    "Flu biasa terjadi di musim dingin": "The flu commonly occurs in winter",
    "parah, kuat": "severe, strong",
    "Dinginnya parah hari ini": "The cold is severe today",
    "air": "water",
    "Airnya dingin": "The water is cold",
    "mulut": "mouth",
    "Mulutku kecil": "My mouth is small",
    "bukalah (perintah)": "open (command)",
    "Tolong buka pintunya": "Please open the door",
    "beristirahatlah (perintah)": "rest (command)",
    "Beristirahatlah setelah bekerja": "Rest after working",
    "pada, punya": "at, have",
    "Aku punya buku yang indah": "I have a beautiful book",
    "عِنْدِي / عِنْدَكَ untuk 'punya'": "عِنْدِي / عِنْدَكَ for 'to have'",
    "عِنْدَ + akhiran menunjukkan kepemilikan: عِنْدِي (aku punya), عِنْدَكَ (kamu punya). Dipakai juga untuk keadaan: عِنْدِي صُدَاعٌ = aku sakit kepala.": "عِنْدَ + suffix shows possession: عِنْدِي (I have), عِنْدَكَ (you have). It is also used for conditions: عِنْدِي صُدَاعٌ = I have a headache.",
    "Kata perintah (fi'il amr)": "Command verb (fi'il amr)",
    "Perintah untuk satu orang laki-laki: اِفْتَحْ (bukalah), اِسْتَرِحْ (beristirahatlah), كُلْ (makanlah), اِشْرَبْ (minumlah). Sebelum kata ber-ال, huruf akhir mendapat kasrah: كُلِ الْفَاكِهَةَ.": "Command for one male: اِفْتَحْ (open), اِسْتَرِحْ (rest), كُلْ (eat), اِشْرَبْ (drink). Before a word with ال, the final letter takes kasrah: كُلِ الْفَاكِهَةَ.",
    "مَاذَا أَفْعَلُ؟ (apa yang harus kulakukan?)": "مَاذَا أَفْعَلُ؟ (what should I do?)",
    "مَاذَا أَفْعَلُ؟ berarti 'apa yang harus kulakukan?' — dipakai untuk meminta nasihat kepada dokter atau orang yang lebih tahu.": "مَاذَا أَفْعَلُ؟ means 'what should I do?' — used to ask for advice from a doctor or someone more knowledgeable.",

    # ---- L2-4 ----
    "Apakah kamu bermain sepak bola, Ahmad?": "Do you play football, Ahmad?",
    "Ya, aku bermain sepak bola setiap hari": "Yes, I play football every day",
    "Di mana kamu bermain?": "Where do you play?",
    "Aku bermain di lapangan": "I play at the field",
    "Dengan siapa kamu bermain?": "Who do you play with?",
    "Aku bermain dengan teman-temanku": "I play with my friends",
    "Apakah temanmu bermain bersamamu?": "Does your friend play with you?",
    "Ya, temanku Ahmad bermain denganku": "Yes, my friend Ahmad plays with me",
    "Dan apakah kamu berenang?": "And do you swim?",
    "Ya, aku berenang di kolam renang pada hari Jumat": "Yes, I swim in the pool on Friday",
    "Apa olahraga favoritmu?": "What is your favorite sport?",
    "Favoritku sepak bola": "My favorite is football",
    "sepak bola": "football",
    "Sepak bola populer di dunia": "Football is popular in the world",
    "aku bermain": "I play",
    "Aku bermain catur dengan saudaraku": "I play chess with my brother",
    "lapangan": "field",
    "Lapangannya luas": "The field is spacious",
    "dengan, bersama": "with",
    "Aku pergi ke pasar bersama ibuku": "I go to the market with my mother",
    "teman (laki-laki)": "friend (male)",
    "Temanku baik hati": "My friend is kind",
    "aku berenang": "I swim",
    "Aku berenang di laut": "I swim in the sea",
    "kolam renang": "swimming pool",
    "Kolam renangnya bersih": "The swimming pool is clean",
    "olahraga": "sport",
    "Olahraga itu baik untuk kesehatan": "Sport is good for health",
    "favorit": "favorite",
    "Ini makanan favoritku": "This is my favorite food",
    "setiap hari": "every day",
    "Aku membaca Al-Qur'an setiap hari": "I read the Qur'an every day",
    "Kata kerja sekarang dengan pelaku berbeda": "Present verb with different doers",
    "أَلْعَبُ (aku bermain) dan تَلْعَبُ (kamu bermain) adalah bentuk kata kerja sekarang. Awal kata berubah sesuai pelaku: أ- untuk aku, ت- untuk kamu.": "أَلْعَبُ (I play) and تَلْعَبُ (you play) are present-tense verb forms. The beginning of the word changes according to the doer: أ- for I, ت- for you.",
    "مَعَ (dengan, bersama)": "مَعَ (with)",
    "مَعَ berarti 'dengan' atau 'bersama': مَعَ أَصْدِقَائِي (bersama teman-temanku), مَعَكَ (denganmu), مَعِي (denganku).": "مَعَ means 'with': مَعَ أَصْدِقَائِي (with my friends), مَعَكَ (with you), مَعِي (with me).",
    "Keterangan waktu: كُلَّ يَوْمٍ، يَوْمَ الْجُمُعَةِ": "Time adverbs: كُلَّ يَوْمٍ، يَوْمَ الْجُمُعَةِ",
    "كُلَّ يَوْمٍ berarti 'setiap hari' dan يَوْمَ الْجُمُعَةِ berarti 'pada hari Jumat' — keduanya adalah keterangan waktu (zharf zaman).": "كُلَّ يَوْمٍ means 'every day' and يَوْمَ الْجُمُعَةِ means 'on Friday' — both are time adverbs (zharf zaman).",

    # ---- L2-5 ----
    "Kapan kamu bangun, Fatimah?": "When do you wake up, Fatimah?",
    "Aku bangun jam enam pagi": "I wake up at six in the morning",
    "Apa yang kamu lakukan setelah itu?": "What do you do after that?",
    "Aku salat lalu sarapan": "I pray, then I have breakfast",
    "Dan kapan kamu pergi bekerja?": "And when do you go to work?",
    "Aku pergi bekerja jam tujuh": "I go to work at seven",
    "Apa yang kamu makan saat makan siang?": "What do you eat at lunch?",
    "Aku makan nasi dan ikan": "I eat rice and fish",
    "Dan kapan kamu pulang ke rumah?": "And when do you return home?",
    "Aku pulang ke rumah jam sepuluh malam": "I return home at ten at night",
    "kapan": "when",
    "Kapan kamu pulang ke rumah?": "When do you return home?",
    "aku bangun": "I wake up",
    "Aku bangun pagi-pagi": "I wake up early",
    "keenam, jam enam": "sixth, six o'clock",
    "Jam enam pagi": "Six in the morning",
    "pada pagi hari": "in the morning",
    "Aku membaca setiap pagi": "I read every morning",
    "aku salat": "I pray",
    "Aku salat di masjid": "I pray at the mosque",
    "lalu, kemudian": "then, afterwards",
    "Aku makan lalu pergi": "I eat, then I go",
    "aku sarapan": "I have breakfast",
    "Aku sarapan bersama keluargaku": "I have breakfast with my family",
    "pekerjaan, kerja": "work",
    "Pekerjaan itu penting": "That work is important",
    "makan siang": "lunch",
    "Makan siangnya sudah siap": "Lunch is ready",
    "aku pulang": "I return",
    "Aku pulang kerja di sore hari": "I return from work in the afternoon",
    "pada malam hari": "at night",
    "Aku tidur di malam hari": "I sleep at night",
    "مَتَى untuk bertanya waktu": "مَتَى to ask when",
    "مَتَى berarti 'kapan' dan dipakai untuk menanyakan waktu suatu kegiatan.": "مَتَى means 'when' and is used to ask about the time of an activity.",
    "فِي + waktu untuk menyebut jam": "فِي + time to tell the clock",
    "Untuk menyebut jam, gunakan فِي + السَّاعَةُ: فِي السَّادِسَةِ (pada jam enam). Tambahkan صَبَاحًا (pagi) atau مَسَاءً (malam).": "To tell the clock, use فِي + السَّاعَةُ: فِي السَّادِسَةِ (at six o'clock). Add صَبَاحًا (morning) or مَسَاءً (evening).",
    "ثُمَّ untuk urutan kegiatan": "ثُمَّ for sequence of actions",
    "ثُمَّ berarti 'lalu/kemudian' dan menghubungkan dua kegiatan yang berurutan: أُصَلِّي ثُمَّ أَفْطُرُ (aku salat lalu sarapan).": "ثُمَّ means 'then/afterwards' and connects two consecutive actions: أُصَلِّي ثُمَّ أَفْطُرُ (I pray, then I have breakfast).",

    # ---- L3-1 ----
    "Ke mana kamu ingin bepergian, Ahmad?": "Where do you want to travel, Ahmad?",
    "Aku ingin bepergian ke Makkah": "I want to travel to Makkah",
    "Masya Allah. Kapan kamu pergi?": "Masha Allah. When are you going?",
    "Aku pergi bulan depan": "I am going next month",
    "Bagaimana kamu pergi? Naik pesawat?": "How are you going? By plane?",
    "Ya, aku pergi naik pesawat": "Yes, I am going by plane",
    "Di mana kamu tinggal di Makkah?": "Where do you stay in Makkah?",
    "Aku tinggal di hotel dekat Masjidil Haram": "I stay at a hotel near Masjidil Haram",
    "Apa yang kamu kunjungi di sana?": "What do you visit there?",
    "Aku mengunjungi Ka'bah dan salat di sana": "I visit the Ka'bah and pray there",
    "aku bepergian": "I travel",
    "Aku bepergian ke Bali setiap tahun": "I travel to Bali every year",
    "aku ingin": "I want",
    "Aku ingin buku baru": "I want a new book",
    "untuk, agar (penghubung)": "to, in order to (connector)",
    "Aku ingin belajar bahasa Arab": "I want to study Arabic",
    "Makkah": "Makkah",
    "Makkah kota yang suci": "Makkah is a sacred city",
    "bulan (penanggalan)": "month (calendar)",
    "Bulan depan adalah bulan Ramadan": "Next month is the month of Ramadan",
    "yang akan datang": "next, coming",
    "Pada minggu yang akan datang": "Next week",
    "pesawat": "plane",
    "Pesawatnya cepat": "The plane is fast",
    "aku tinggal": "I stay",
    "Aku tinggal di Jakarta": "I live in Jakarta",
    "hotel": "hotel",
    "Hotelnya dekat dengan laut": "The hotel is close to the sea",
    "aku mengunjungi": "I visit",
    "Aku mengunjungi nenekku pada hari raya": "I visit my grandmother on the holiday",
    "أُرِيدُ أَنْ + kata kerja (ingin melakukan ...)": "أُرِيدُ أَنْ + verb (want to do ...)",
    "Untuk menyatakan keinginan: أُرِيدُ (aku ingin) diikuti أَنْ lalu kata kerja. Contoh: أُرِيدُ أَنْ أُسَافِرَ = aku ingin bepergian.": "To express a wish: أُرِيدُ (I want) followed by أَنْ then a verb. Example: أُرِيدُ أَنْ أُسَافِرَ = I want to travel.",
    "بِ + alat untuk cara bepergian": "بِ + means for traveling",
    "Cara bepergian disebut dengan بِ + alat: بِالطَّائِرَةِ (naik pesawat), بِالسَّفِينَةِ (naik kapal).": "The way of traveling is expressed with بِ + means: بِالطَّائِرَةِ (by plane), بِالسَّفِينَةِ (by ship).",
    "Kata sifat ber-ال (na't ma'rifah)": "Adjective with ال (na't ma'rifah)",
    "الشَّهْرُ الْقَادِمُ = bulan yang akan datang. Kata benda dan kata sifat sama-sama ber-ال. Kata sifat juga bisa tanpa ال setelah kata tak tentu: فُنْدُقٌ قَرِيبٌ.": "الشَّهْرُ الْقَادِمُ = the coming month. Both the noun and the adjective take ال. The adjective can also come without ال after an indefinite noun: فُنْدُقٌ قَرِيبٌ.",

    # ---- L3-2 ----
    "Apa pekerjaanmu, Ahmad?": "What is your job, Ahmad?",
    "Aku seorang insinyur": "I am an engineer",
    "Di mana kamu bekerja?": "Where do you work?",
    "Aku bekerja di perusahaan besar": "I work at a big company",
    "Apa yang kamu lakukan di perusahaan?": "What do you do at the company?",
    "Aku mengelola proyek-proyek besar": "I manage big projects",
    "Dan apakah kamu suka pekerjaanmu?": "And do you like your job?",
    "Ya, aku sangat suka pekerjaanku": "Yes, I really like my job",
    "Kapan kamu mulai bekerja?": "When do you start working?",
    "Aku mulai bekerja jam delapan pagi": "I start working at eight in the morning",
    "pekerjaan": "job, work",
    "Pekerjaanku di kantor besar": "My job is at a big office",
    "insinyur": "engineer",
    "Insinyur membangun jembatan": "Engineers build bridges",
    "aku bekerja": "I work",
    "Aku bekerja dari pagi sampai sore": "I work from morning until evening",
    "perusahaan": "company",
    "Perusahaannya besar": "The company is big",
    "proyek": "project",
    "Ini proyek yang penting": "This is an important project",
    "aku mengelola": "I manage",
    "Aku mengelola kantor kecil": "I manage a small office",
    "aku mulai": "I start",
    "Aku mulai belajar pada bulan September": "I start studying in September",
    "kedelapan, jam delapan": "eighth, eight o'clock",
    "Jam delapan malam": "Eight in the evening",
    "aku suka": "I like",
    "Aku suka pekerjaanku": "I like my job",
    "Nama profesi sebagai khabar": "Profession names as khabar",
    "Untuk menyebut profesi: أَنَا + nama profesi. أَنَا مُهَنْدِسٌ = aku seorang insinyur. Profesi lain: طَبِيبٌ (dokter), مُدَرِّسٌ (guru), تَاجِرٌ (pedagang).": "To state a profession: أَنَا + profession name. أَنَا مُهَنْدِسٌ = I am an engineer. Other professions: طَبِيبٌ (doctor), مُدَرِّسٌ (teacher), تَاجِرٌ (merchant).",
    "فِي + tempat bekerja": "فِي + place of work",
    "Tempat bekerja disebut dengan فِي: أَعْمَلُ فِي شَرِكَةٍ = aku bekerja di sebuah perusahaan.": "The place of work is expressed with فِي: أَعْمَلُ فِي شَرِكَةٍ = I work at a company.",
    "مَاذَا تَفْعَلُ؟ (apa yang kamu lakukan?)": "مَاذَا تَفْعَلُ؟ (what do you do?)",
    "مَاذَا تَفْعَلُ؟ menanyakan kegiatan. Jawab dengan kata kerja: أُدِيرُ مَشْرُوعَاتٍ = aku mengelola proyek-proyek.": "مَاذَا تَفْعَلُ؟ asks about an activity. Answer with a verb: أُدِيرُ مَشْرُوعَاتٍ = I manage projects.",

    # ---- L3-3 ----
    "Apa yang kamu lakukan di malam hari, Fatimah?": "What do you do at night, Fatimah?",
    "Aku menonton televisi bersama keluargaku": "I watch television with my family",
    "Apa yang kamu tonton?": "What do you watch?",
    "Aku menonton berita lalu film": "I watch the news, then a film",
    "Apakah kamu membaca koran?": "Do you read the newspaper?",
    "Ya, aku membaca koran setiap pagi": "Yes, I read the newspaper every morning",
    "Dan apa yang kamu baca di koran?": "And what do you read in the newspaper?",
    "Aku membaca berita dan artikel-artikel": "I read news and articles",
    "Apakah kamu mendengarkan radio?": "Do you listen to the radio?",
    "Ya, aku mendengarkan radio di mobil": "Yes, I listen to the radio in the car",
    "aku menonton": "I watch",
    "Aku menonton film bersama teman-temanku": "I watch films with my friends",
    "televisi": "television",
    "Televisinya ada di ruang tamu": "The television is in the living room",
    "berita": "news",
    "Berita itu penting setiap hari": "The news is important every day",
    "film": "film",
    "Filmnya bagus": "The film is good",
    "aku membaca": "I read",
    "Aku membaca satu buku setiap minggu": "I read one book every week",
    "koran": "newspaper",
    "Korannya ada di atas meja": "The newspaper is on the table",
    "artikel": "article",
    "Aku membaca artikel yang bermanfaat": "I read a useful article",
    "aku mendengarkan": "I listen",
    "Aku sering mendengarkan Al-Qur'an": "I often listen to the Qur'an",
    "radio": "radio",
    "Radionya tua": "The radio is old",
    "pagi": "morning",
    "Setiap pagi aku minum teh": "Every morning I drink tea",
    "Kata kerja media: menonton, membaca, mendengarkan": "Media verbs: to watch, to read, to listen",
    "أُشَاهِدُ (menonton), أَقْرَأُ (membaca), أَسْتَمِعُ (mendengarkan). Bentuk perempuan: تُشَاهِدِينَ، تَقْرَئِينَ، تَسْتَمِعِينَ.": "أُشَاهِدُ (I watch), أَقْرَأُ (I read), أَسْتَمِعُ (I listen). Female forms: تُشَاهِدِينَ، تَقْرَئِينَ، تَسْتَمِعِينَ.",
    "أَسْتَمِعُ إِلَى (mendengarkan ...)": "أَسْتَمِعُ إِلَى (to listen to ...)",
    "Kata kerja 'mendengarkan' diikuti إِلَى: أَسْتَمِعُ إِلَى الرَّادْيُو = aku mendengarkan radio.": "The verb 'to listen' is followed by إِلَى: أَسْتَمِعُ إِلَى الرَّادْيُو = I listen to the radio.",
    "كُلَّ صَبَاحٍ (setiap pagi)": "كُلَّ صَبَاحٍ (every morning)",
    "كُلَّ + waktu = setiap ...: كُلَّ صَبَاحٍ (setiap pagi), كُلَّ يَوْمٍ (setiap hari), كُلَّ أُسْبُوعٍ (setiap minggu).": "كُلَّ + time = every ...: كُلَّ صَبَاحٍ (every morning), كُلَّ يَوْمٍ (every day), كُلَّ أُسْبُوعٍ (every week).",

    # ---- L3-4 ----
    "Semoga keselamatan, Ustadz": "Peace be upon you, Ustadh",
    "Dan semoga keselamatan dan rahmat Allah": "And peace and the mercy of Allah be upon you",
    "Bagaimana kabarmu hari ini?": "How are you today?",
    "Aku baik, alhamdulillah. Dan kamu?": "I am fine, alhamdulillah. And you?",
    "Aku juga baik": "I am fine too",
    "Ini hadiah untukmu, Ustadz": "This is a gift for you, Ustadh",
    "Terima kasih banyak. Hadiah apa ini?": "Thank you very much. What gift is this?",
    "Ini jam tangan yang indah": "This is a beautiful watch",
    "Alangkah indahnya! Terima kasih, Salim": "How beautiful! Thank you, Salim",
    "Sama-sama, Ustadz": "You are welcome, Ustadh",
    "ustadz, guru": "ustadh, teacher",
    "Ustadz mengajari kami bahasa Arab": "The ustadh teaches us Arabic",
    "rahmat": "mercy",
    "Rahmat Allah itu luas": "The mercy of Allah is vast",
    "keadaan, kabar": "state, news",
    "Keadaan keluargaku baik": "My family is in a good state",
    "baik-baik": "fine, well",
    "Aku baik-baik saja, alhamdulillah": "I am fine, alhamdulillah",
    "segala puji bagi Allah": "all praise be to Allah",
    "Segala puji bagi Allah dalam segala keadaan": "All praise be to Allah in every situation",
    "hadiah": "gift",
    "Hadiahnya dari temanku": "The gift is from my friend",
    "untukmu (laki-laki)": "for you (male)",
    "Buku ini untukmu": "This book is for you",
    "terima kasih": "thank you",
    "Terima kasih atas bantuannya": "Thank you for your help",
    "jam, jam tangan": "watch",
    "Jam tanganku baru": "My watch is new",
    "indah, bagus": "beautiful",
    "Kotanya indah": "The city is beautiful",
    "sama-sama (jawaban terima kasih)": "you are welcome (reply to thanks)",
    "Sama-sama, saudaraku": "You are welcome, my brother",
    "Sapaan menanyakan kabar: كَيْفَ حَالُكَ؟": "Greeting asking about one's state: كَيْفَ حَالُكَ؟",
    "كَيْفَ حَالُكَ؟ = bagaimana kabarmu? (laki-laki). Untuk perempuan: كَيْفَ حَالُكِ؟ Jawaban: أَنَا بِخَيْرٍ (aku baik-baik saja).": "كَيْفَ حَالُكَ؟ = how are you? (male). For a female: كَيْفَ حَالُكِ؟ Answer: أَنَا بِخَيْرٍ (I am fine).",
    "لَـ + kata ganti (untuk ...)": "لَـ + pronoun (for ...)",
    "لَـ berarti 'untuk' dan bisa disambung kata ganti: لَكَ (untukmu), لِي (untukku), لَهُ (untuknya).": "لَـ means 'for' and can be joined to pronouns: لَكَ (for you), لِي (for me), لَهُ (for him).",
    "Ungkapan terima kasih": "Expressions of thanks",
    "شُكْرًا (terima kasih), شُكْرًا جَزِيلًا (terima kasih banyak). Jawabannya: الْعَفْوُ (sama-sama).": "شُكْرًا (thank you), شُكْرًا جَزِيلًا (thank you very much). The reply: الْعَفْوُ (you are welcome).",

    # ---- L3-5 ----
    "Apa kebiasaan-kebiasaan di Indonesia, Ahmad?": "What are the customs in Indonesia, Ahmad?",
    "Di antara kebiasaan baik adalah memuliakan tamu": "Among the good customs is honoring guests",
    "Dan apa kebiasaan ini?": "And what is this custom?",
    "Jika tamu datang, kami menyajikan teh untuknya": "When a guest comes, we serve him tea",
    "Ini kebiasaan yang indah": "This is a beautiful custom",
    "Dan pada hari raya kami mengunjungi kerabat": "And on the holiday we visit relatives",
    "Dan apa yang kalian makan pada hari raya?": "And what do you eat on the holiday?",
    "Kami makan kue dan manisan": "We eat cakes and sweets",
    "Alangkah indahnya kebiasaan-kebiasaan Indonesia!": "How beautiful are the customs of Indonesia!",
    "Ya, alhamdulillah": "Yes, alhamdulillah",
    "kebiasaan": "custom, habit",
    "Kebiasaan berbeda dari satu negara ke negara lain": "Customs differ from one country to another",
    "memuliakan, penghormatan": "honoring",
    "Memuliakan tamu termasuk ajaran Islam": "Honoring guests is part of the teachings of Islam",
    "tamu": "guest",
    "Tamu itu datang dari jauh": "The guest came from far away",
    "hari raya": "holiday, festival",
    "Hari raya adalah hari yang bahagia": "The holiday is a happy day",
    "kerabat-kerabat": "relatives",
    "Aku mengunjungi kerabat pada hari raya": "I visit relatives on the holiday",
    "kami menyajikan": "we serve",
    "Kami menyajikan kopi untuk tamu": "We serve coffee to the guest",
    "kami makan": "we eat",
    "Kami makan makanan bersama-sama": "We eat food together",
    "kue": "cake",
    "Kuenya manis": "The cake is sweet",
    "manisan": "sweets",
    "Manisan disukai anak-anak": "Children like sweets",
    "teh": "tea",
    "Tehnya panas": "The tea is hot",
    "مَا + isim untuk bertanya budaya": "مَا + noun to ask about culture",
    "مَا الْعَادَاتُ فِي إِنْدُونِيسِيَّا؟ = apa kebiasaan-kebiasaan di Indonesia? Pola: مَا + kata benda untuk bertanya tentang sesuatu.": "مَا الْعَادَاتُ فِي إِنْدُونِيسِيَّا؟ = what are the customs in Indonesia? Pattern: مَا + noun to ask about something.",
    "إِذَا (jika) — kalimat syarat": "إِذَا (if) — conditional sentence",
    "إِذَا berarti 'jika'. Kalimat syarat: إِذَا جَاءَ الضَّيْفُ نُقَدِّمُ لَهُ الشَّايَ = jika tamu datang, kami menyajikan teh untuknya.": "إِذَا means 'if'. Conditional sentence: إِذَا جَاءَ الضَّيْفُ نُقَدِّمُ لَهُ الشَّايَ = if a guest comes, we serve him tea.",
    "Ungkapan kagum: مَا أَجْمَلَ ...!": "Exclamation of admiration: مَا أَجْمَلَ ...!",
    "مَا أَجْمَلَ ...! berarti 'alangkah indahnya ...!' — ungkapan kekaguman. Contoh: مَا أَجْمَلَ الْعَادَاتِ الْإِنْدُونِيسِيَّةَ!": "مَا أَجْمَلَ ...! means 'how beautiful ... is!' — an expression of admiration. Example: مَا أَجْمَلَ الْعَادَاتِ الْإِنْدُونِيسِيَّةَ!",
}

# ---------------------------------------------------------------------------
# Latihan (tadribat)
# ---------------------------------------------------------------------------
# fillBlank: promptId (Indonesia) → promptEn (Inggris). Opsi/jawaban = kata Arab.
FILL_PROMPT_EN = {
    "Isilah titik-titik: Siapa ___?": "Fill in the blank: What ___?",
    "Isilah titik-titik: Aku juga dari ___": "Fill in the blank: I am also from ___",
    "Isilah titik-titik: Ini ___ (ayahku)": "Fill in the blank: This is ___ (my father)",
    "Isilah titik-titik: Ini ___ (ibuku)": "Fill in the blank: This is ___ (my mother)",
    "Isilah titik-titik: Aku ___ sekolah": "Fill in the blank: I am ___ school",
    "Isilah titik-titik: Ini sebuah ___ (buku)": "Fill in the blank: This is a ___ (book)",
    "Isilah titik-titik: Di mana ___ , Ahmad?": "Fill in the blank: Where is ___ , Ahmad?",
    "Isilah titik-titik: Di rumahku ada empat ___": "Fill in the blank: In my house there are four ___",
    "Isilah titik-titik: Aku sangat suka ___": "Fill in the blank: I really like ___",
    "Isilah titik-titik: Ini ___ (buah)": "Fill in the blank: This is ___ (fruit)",
    "Isilah titik-titik: Berapa harga ___ ini?": "Fill in the blank: How much is this ___?",
    "Isilah titik-titik: Harganya delapan ___": "Fill in the blank: Its price is eight ___",
    "Isilah titik-titik: Aku pergi ___ mobil": "Fill in the blank: I go ___ car",
    "Isilah titik-titik: Bagaimana kamu pergi ___ sekolah?": "Fill in the blank: How do you go ___ school?",
    "Isilah titik-titik: Aku sakit kepala yang ___": "Fill in the blank: I have a ___ headache",
    "Isilah titik-titik: Apakah kamu ___ (demam)?": "Fill in the blank: Do you ___ (fever)?",
    "Isilah titik-titik: Aku bermain ___ setiap hari": "Fill in the blank: I play ___ every day",
    "Isilah titik-titik: Aku berenang di ___": "Fill in the blank: I swim in the ___",
    "Isilah titik-titik: Aku bangun jam ___ pagi": "Fill in the blank: I wake up at ___ in the morning",
    "Isilah titik-titik: Aku salat ___ sarapan": "Fill in the blank: I pray ___ breakfast",
    "Isilah titik-titik: Aku ingin ___ ke Makkah": "Fill in the blank: I want to ___ to Makkah",
    "Isilah titik-titik: Aku tinggal di ___ dekat masjid": "Fill in the blank: I stay at a ___ near the mosque",
    "Isilah titik-titik: Aku seorang ___": "Fill in the blank: I am a(n) ___",
    "Isilah titik-titik: Aku bekerja di ___ besar": "Fill in the blank: I work at a big ___",
    "Isilah titik-titik: Aku menonton ___ bersama keluargaku": "Fill in the blank: I watch ___ with my family",
    "Isilah titik-titik: Aku membaca koran setiap ___": "Fill in the blank: I read the newspaper every ___",
    "Isilah titik-titik: Bagaimana ___ hari ini?": "Fill in the blank: How are ___ today?",
    "Isilah titik-titik: Ini hadiah ___ , Ustadz": "Fill in the blank: This is a gift ___ , Ustadh",
    "Isilah titik-titik: Jika ___ datang, kami menyajikan teh untuknya": "Fill in the blank: If a ___ comes, we serve him tea",
    "Isilah titik-titik: Kami makan ___ dan manisan": "Fill in the blank: We eat ___ and sweets",
}

# translateArId: kunci = promptAr (Arab) → (optionsEn, answerEn)
TRANSLATE_AR_ID_EN = {
    "مَا اسْمُكِ؟": (["What is your name?", "How are you?", "Where are you from?", "Where is your house?"], "What is your name?"),
    "أَهْلًا وَسَهْلًا": (["Welcome", "Good morning", "Goodbye", "Thank you"], "Welcome"),
    "هٰذِهِ أُمِّي": (["This is my mother", "This is my father", "This is my grandfather", "This is my grandmother"], "This is my mother"),
    "هَلْ لَكَ إِخْوَةٌ؟": (["Do you have siblings?", "What is your name?", "Where are you from?", "Where is your house?"], "Do you have siblings?"),
    "مَاذَا تَدْرُسِينَ؟": (["What are you studying?", "What is your name?", "Where is your school?", "What is this?"], "What are you studying?"),
    "أَنَا فِي الْمَدْرَسَةِ": (["I am at school", "I am at home", "I am at the market", "I am at the mosque"], "I am at school"),
    "بَيْتِي فِي جَاكَرْتَا": (["My house is in Jakarta", "My house is in Bandung", "My school is in Jakarta", "Your house is in Jakarta"], "My house is in Jakarta"),
    "الْمَطْبَخُ قَرِيبٌ مِنَ الْحَمَّامِ": (["The kitchen is close to the bathroom", "The kitchen is inside the house", "The bathroom is close to the door", "The kitchen is big"], "The kitchen is close to the bathroom"),
    "أُحِبُّ الْأَرُزَّ كَثِيرًا": (["I really like rice", "I like bread", "I eat rice", "The rice is tasty"], "I really like rice"),
    "مَا اسْمُ هٰذِهِ الْفَاكِهَةِ؟": (["What is the name of this fruit?", "What is this?", "What is the name of this food?", "Where is this fruit?"], "What is the name of this fruit?"),
    "هٰذَا غَالٍ جِدًّا": (["This is very expensive", "This is very cheap", "This is very tasty", "This is very good"], "This is very expensive"),
    "آخُذُ كِيلُوَيْنِ": (["I will take two kilos", "I will take one kilo", "I like oranges", "I buy apples"], "I will take two kilos"),
    "أَذْهَبُ بِالدَّرَّاجَةِ النَّارِيَّةِ": (["I go by motorcycle", "I go by car", "I go by bus", "I go by bicycle"], "I go by motorcycle"),
    "مَحَطَّةُ الْحَافِلَةِ أَمَامَ الْمَسْجِدِ": (["The bus stop is in front of the mosque", "The bus stop is behind the mosque", "The bus stop is near the mosque", "The mosque is in front of the bus stop"], "The bus stop is in front of the mosque"),
    "عِنْدِي صُدَاعٌ شَدِيدٌ": (["I have a severe headache", "I have a fever", "I have the flu", "I am very tired"], "I have a severe headache"),
    "اِسْتَرِحْ فِي الْبَيْتِ وَاشْرَبِ الْمَاءَ": (["Rest at home and drink water", "Please open your mouth", "Eat fruit", "Go to school"], "Rest at home and drink water"),
    "أَلْعَبُ مَعَ أَصْدِقَائِي": (["I play with my friends", "I play at the field", "I swim with my friend", "I play every day"], "I play with my friends"),
    "مَا رِيَاضَتُكَ الْمُفَضَّلَةُ؟": (["What is your favorite sport?", "What is your game?", "Where do you exercise?", "When do you play?"], "What is your favorite sport?"),
    "أَسْتَيْقِظُ فِي السَّادِسَةِ صَبَاحًا": (["I wake up at six in the morning", "I wake up at seven in the morning", "I sleep at six at night", "I go at six in the morning"], "I wake up at six in the morning"),
    "آكُلُ الْأَرُزَّ وَالسَّمَكَ": (["I eat rice and fish", "I eat bread and milk", "I like rice and fish", "I eat at lunch"], "I eat rice and fish"),
    "أُرِيدُ أَنْ أُسَافِرَ إِلَى مَكَّةَ": (["I want to travel to Makkah", "I want to live in Makkah", "I go to Makkah", "I like Makkah"], "I want to travel to Makkah"),
    "أَسْكُنُ فِي فُنْدُقٍ قَرِيبٍ مِنَ الْمَسْجِدِ الْحَرَامِ": (["I stay at a hotel near Masjidil Haram", "I live in a house near the mosque", "The hotel is near Masjidil Haram", "I go to the hotel"], "I stay at a hotel near Masjidil Haram"),
    "أَنَا مُهَنْدِسٌ": (["I am an engineer", "I am a doctor", "I am a teacher", "I am a merchant"], "I am an engineer"),
    "أُحِبُّ عَمَلِي كَثِيرًا": (["I really like my job", "I like my company", "My job is big", "I work a lot"], "I really like my job"),
    "أُشَاهِدُ الْأَخْبَارَ ثُمَّ الْفِلْمَ": (["I watch the news, then the film", "I watch the film, then the news", "I read news and articles", "I listen to the radio"], "I watch the news, then the film"),
    "أَسْتَمِعُ إِلَى الرَّادْيُو فِي السَّيَّارَةِ": (["I listen to the radio in the car", "I watch TV in the car", "I listen to the radio at home", "I read the newspaper in the car"], "I listen to the radio in the car"),
    "كَيْفَ حَالُكَ الْيَوْمَ؟": (["How are you today?", "What is your name today?", "Where are you today?", "How is your family?"], "How are you today?"),
    "شُكْرًا جَزِيلًا": (["Thank you very much", "You are welcome", "Welcome", "Thank you a little"], "Thank you very much"),
    "إِذَا جَاءَ الضَّيْفُ نُقَدِّمُ لَهُ الشَّايَ": (["When a guest comes, we serve him tea", "When a guest comes, we eat cake", "The guest came bringing tea", "We serve tea to the family"], "When a guest comes, we serve him tea"),
    "هٰذِهِ عَادَةٌ جَمِيلَةٌ": (["This is a beautiful custom", "This is a bad custom", "This is a beautiful gift", "This is tasty tea"], "This is a beautiful custom"),
}

# translateIdAr: promptId (Indonesia) → promptEn (Inggris). Opsi/jawaban = kata Arab.
TRANSLATE_ID_AR_EN = {
    "Senang berkenalan.": "Nice to meet you.",
    "Dari mana kamu?": "Where are you from?",
    "Siapa ini?": "Who is this?",
    "Ini foto keluargaku.": "This is a picture of my family.",
    "Selamat pagi.": "Good morning.",
    "Ini sebuah penggaris.": "This is a ruler.",
    "Berapa kamar di rumahmu?": "How many rooms are in your house?",
    "Apakah rumahmu besar?": "Is your house big?",
    "Ini roti.": "This is bread.",
    "Makanannya lezat.": "The food is delicious.",
    "Berapa harga jeruk?": "How much are the oranges?",
    "Silakan.": "Please, go ahead.",
    "Bagaimana kamu pergi ke sekolah?": "How do you go to school?",
    "Apakah sekolahnya jauh?": "Is the school far?",
    "Apakah kamu demam?": "Do you have a fever?",
    "Apa yang harus kulakukan, Dokter?": "What should I do, Doctor?",
    "Apakah kamu bermain sepak bola?": "Do you play football?",
    "Dengan siapa kamu bermain?": "Who do you play with?",
    "Kapan kamu bangun, Fatimah?": "When do you wake up, Fatimah?",
    "Aku pulang ke rumah jam sepuluh malam.": "I return home at ten at night.",
    "Ke mana kamu ingin bepergian?": "Where do you want to travel?",
    "Kapan kamu pergi?": "When are you going?",
    "Apa pekerjaanmu, Ahmad?": "What is your job, Ahmad?",
    "Di mana kamu bekerja?": "Where do you work?",
    "Apakah kamu membaca koran?": "Do you read the newspaper?",
    "Apa yang kamu tonton?": "What do you watch?",
    "Terima kasih, Salim.": "Thank you, Salim.",
    "Ini hadiah untukmu, Ustadz.": "This is a gift for you, Ustadh.",
    "Apa yang kalian makan pada hari raya?": "What do you eat on the holiday?",
    "Dan pada hari raya kami mengunjungi kerabat.": "And on the holiday we visit relatives.",
}
