# -*- coding: utf-8 -*-
"""
Konten Level 1 — "Perkenalan & Kehidupan Sehari-hari" (5 lesson).
Konten ORISINAL: ditulis dari nol, jangan menyalin dari kitab/sumber mana pun.
Skema: tools/lughoh-schema.md. Di-generate oleh tools/build_lughoh.py.
"""

LEVELS = [
    {
        "id": 1,
        "titleId": "Level 1 — Perkenalan & Kehidupan Sehari-hari",
        "titleAr": "المُسْتَوَى الأَوَّل",
        "lessons": [
            # ------------------------------------------------------------------
            # Lesson 1-1: Perkenalan Diri
            # ------------------------------------------------------------------
            {
                "id": "1-1",
                "titleId": "Perkenalan Diri",
                "titleAr": "التَّعْرِيفُ بِالنَّفْسِ",
                "muhadatsah": [
                    {"speaker": "Ahmad", "ar": "السَّلَامُ عَلَيْكُمْ", "latin": "As-salāmu ʿalaikum", "id": "Semoga keselamatan atas kalian"},
                    {"speaker": "Fatimah", "ar": "وَعَلَيْكُمُ السَّلَامُ", "latin": "Wa ʿalaikumus-salām", "id": "Dan semoga keselamatan atas kalian juga"},
                    {"speaker": "Ahmad", "ar": "مَا اسْمُكِ؟", "latin": "Mā ismuki?", "id": "Siapa namamu?"},
                    {"speaker": "Fatimah", "ar": "اِسْمِي فَاطِمَةُ. وَأَنْتَ؟", "latin": "Ismī Fāṭimah. Wa anta?", "id": "Namaku Fatimah. Dan kamu?"},
                    {"speaker": "Ahmad", "ar": "أَنَا أَحْمَدُ. أَهْلًا وَسَهْلًا", "latin": "Anā Aḥmad. Ahlan wa sahlan", "id": "Aku Ahmad. Selamat datang"},
                    {"speaker": "Fatimah", "ar": "أَهْلًا بِكَ", "latin": "Ahlan bika", "id": "Selamat datang juga"},
                    {"speaker": "Ahmad", "ar": "مِنْ أَيْنَ أَنْتِ؟", "latin": "Min ayna anti?", "id": "Dari mana kamu?"},
                    {"speaker": "Fatimah", "ar": "أَنَا مِنْ إِنْدُونِيسِيَّا. وَأَنْتَ؟", "latin": "Anā min Indūnīsiyyā. Wa anta?", "id": "Aku dari Indonesia. Dan kamu?"},
                    {"speaker": "Ahmad", "ar": "أَنَا مِنْ إِنْدُونِيسِيَّا أَيْضًا", "latin": "Anā min Indūnīsiyyā ayḍan", "id": "Aku juga dari Indonesia"},
                    {"speaker": "Fatimah", "ar": "تَشَرَّفْنَا", "latin": "Tasharrafnā", "id": "Senang berkenalan"},
                ],
                "mufrodat": [
                    {"ar": "السَّلَامُ عَلَيْكُمْ", "latin": "as-salāmu ʿalaikum", "id": "salam sejahtera",
                     "exampleAr": "السَّلَامُ عَلَيْكُمْ يَا أَحْمَدُ", "exampleLatin": "As-salāmu ʿalaikum yā Aḥmad", "exampleId": "Semoga keselamatan atasmu, Ahmad"},
                    {"ar": "اِسْم", "latin": "ism", "id": "nama",
                     "exampleAr": "اِسْمِي أَحْمَدُ", "exampleLatin": "Ismī Aḥmad", "exampleId": "Namaku Ahmad"},
                    {"ar": "مَا", "latin": "mā", "id": "apa",
                     "exampleAr": "مَا هٰذَا؟", "exampleLatin": "Mā hādhā?", "exampleId": "Apa ini?"},
                    {"ar": "أَنَا", "latin": "anā", "id": "saya",
                     "exampleAr": "أَنَا طَالِبٌ", "exampleLatin": "Anā ṭālibun", "exampleId": "Aku seorang pelajar"},
                    {"ar": "أَنْتَ", "latin": "anta", "id": "kamu (laki-laki)",
                     "exampleAr": "مَا اسْمُكَ؟", "exampleLatin": "Mā ismuka?", "exampleId": "Siapa namamu?"},
                    {"ar": "أَنْتِ", "latin": "anti", "id": "kamu (perempuan)",
                     "exampleAr": "مِنْ أَيْنَ أَنْتِ؟", "exampleLatin": "Min ayna anti?", "exampleId": "Dari mana kamu?"},
                    {"ar": "مِنْ", "latin": "min", "id": "dari",
                     "exampleAr": "أَنَا مِنْ جَاكَرْتَا", "exampleLatin": "Anā min Jākartā", "exampleId": "Aku dari Jakarta"},
                    {"ar": "أَيْنَ", "latin": "ayna", "id": "di mana",
                     "exampleAr": "أَيْنَ أَنْتَ؟", "exampleLatin": "Ayna anta?", "exampleId": "Di mana kamu?"},
                    {"ar": "إِنْدُونِيسِيَّا", "latin": "Indūnīsiyyā", "id": "Indonesia",
                     "exampleAr": "أَنَا مِنْ إِنْدُونِيسِيَّا", "exampleLatin": "Anā min Indūnīsiyyā", "exampleId": "Aku dari Indonesia"},
                    {"ar": "أَيْضًا", "latin": "ayḍan", "id": "juga",
                     "exampleAr": "أَنَا طَالِبٌ أَيْضًا", "exampleLatin": "Anā ṭālibun ayḍan", "exampleId": "Aku juga seorang pelajar"},
                ],
                "qawaid": [
                    {"titleId": "Kata ganti orang (ضمائر): أَنَا، أَنْتَ، أَنْتِ",
                     "id": "أَنَا berarti saya, أَنْتَ berarti kamu (untuk laki-laki), dan أَنْتِ berarti kamu (untuk perempuan). Perhatikan bahwa kata ganti 'kamu' berbeda jenis kelaminnya.",
                     "exampleAr": "أَنَا أَحْمَدُ", "exampleLatin": "Anā Aḥmad", "exampleId": "Aku Ahmad"},
                    {"titleId": "Kalimat nominal (jumlah ismiyyah)",
                     "id": "Kalimat Arab bisa tersusun tanpa kata kerja: kata pertama disebut mubtada' (subjek), kata kedua khabar (predikat). Contoh: أَنَا = mubtada', مِنْ إِنْدُونِيسِيَّا = khabar.",
                     "exampleAr": "أَنَا مِنْ إِنْدُونِيسِيَّا أَيْضًا", "exampleLatin": "Anā min Indūnīsiyyā ayḍan", "exampleId": "Aku juga dari Indonesia"},
                    {"titleId": "Kata tanya مَا",
                     "id": "مَا dipakai untuk menanyakan nama atau benda, artinya 'apa'. Untuk bertanya nama, gunakan مَا اسْمُكَ (kepada laki-laki) atau مَا اسْمُكِ (kepada perempuan).",
                     "exampleAr": "مَا اسْمُكِ؟", "exampleLatin": "Mā ismuki?", "exampleId": "Siapa namamu?"},
                ],
                "tadribat": [
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Siapa ___?", "promptAr": "مَا ____؟", "promptLatin": "Mā ____?",
                     "options": ["اسْمُكِ", "بَيْتُكِ", "كِتَابُكِ", "قَلَمُكِ"], "answer": "اسْمُكِ"},
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Aku juga dari ___", "promptAr": "أَنَا مِنْ ____ أَيْضًا", "promptLatin": "Anā min ____ ayḍan",
                     "options": ["إِنْدُونِيسِيَّا", "مِصْرَ", "الْمَغْرِبِ", "تُونِسَ"], "answer": "إِنْدُونِيسِيَّا"},
                    {"type": "translateArId", "promptAr": "مَا اسْمُكِ؟", "promptLatin": "Mā ismuki?",
                     "options": ["Siapa namamu?", "Apa kabarmu?", "Dari mana kamu?", "Di mana rumahmu?"], "answer": "Siapa namamu?"},
                    {"type": "translateArId", "promptAr": "أَهْلًا وَسَهْلًا", "promptLatin": "Ahlan wa sahlan",
                     "options": ["Selamat datang", "Selamat pagi", "Sampai jumpa", "Terima kasih"], "answer": "Selamat datang"},
                    {"type": "translateIdAr", "promptId": "Senang berkenalan.",
                     "options": ["تَشَرَّفْنَا", "أَهْلًا وَسَهْلًا", "مَعَ السَّلَامَةِ", "صَبَاحَ الْخَيْرِ"], "answer": "تَشَرَّفْنَا"},
                    {"type": "translateIdAr", "promptId": "Dari mana kamu?",
                     "options": ["مِنْ أَيْنَ أَنْتِ؟", "مَا اسْمُكِ؟", "كَيْفَ حَالُكِ؟", "أَيْنَ بَيْتُكِ؟"], "answer": "مِنْ أَيْنَ أَنْتِ؟"},
                    {"type": "rearrange",
                     "words": [{"ar": "أَنَا", "latin": "anā"}, {"ar": "مِنْ", "latin": "min"},
                               {"ar": "إِنْدُونِيسِيَّا", "latin": "Indūnīsiyyā"}, {"ar": "أَيْضًا", "latin": "ayḍan"}],
                     "answer": ["أَنَا", "مِنْ", "إِنْدُونِيسِيَّا", "أَيْضًا"]},
                    {"type": "rearrange",
                     "words": [{"ar": "مِنْ", "latin": "min"}, {"ar": "أَيْنَ", "latin": "ayna"}, {"ar": "أَنْتِ", "latin": "anti"}],
                     "answer": ["مِنْ", "أَيْنَ", "أَنْتِ"]},
                ],
            },

            # ------------------------------------------------------------------
            # Lesson 1-2: Keluarga
            # ------------------------------------------------------------------
            {
                "id": "1-2",
                "titleId": "Keluarga",
                "titleAr": "العَائِلَةُ",
                "muhadatsah": [
                    {"speaker": "Salim", "ar": "مَا هٰذَا يَا أَحْمَدُ؟", "latin": "Mā hādhā yā Aḥmad?", "id": "Apa ini, Ahmad?"},
                    {"speaker": "Ahmad", "ar": "هٰذِهِ صُورَةُ عَائِلَتِي", "latin": "Hādhihi ṣūratu ʿā'ilatī", "id": "Ini foto keluargaku"},
                    {"speaker": "Salim", "ar": "مَنْ هٰذَا؟", "latin": "Man hādhā?", "id": "Siapa ini?"},
                    {"speaker": "Ahmad", "ar": "هٰذَا أَبِي", "latin": "Hādhā abī", "id": "Ini ayahku"},
                    {"speaker": "Salim", "ar": "وَمَنْ هٰذِهِ؟", "latin": "Wa man hādhihi?", "id": "Dan siapa ini?"},
                    {"speaker": "Ahmad", "ar": "هٰذِهِ أُمِّي", "latin": "Hādhihi ummī", "id": "Ini ibuku"},
                    {"speaker": "Salim", "ar": "هَلْ لَكَ إِخْوَةٌ؟", "latin": "Hal laka ikhwatun?", "id": "Apakah kamu punya saudara?"},
                    {"speaker": "Ahmad", "ar": "نَعَمْ، لِي أَخٌ وَأُخْتٌ", "latin": "Naʿam, lī akhun wa ukhtun", "id": "Ya, aku punya saudara laki-laki dan saudara perempuan"},
                    {"speaker": "Salim", "ar": "وَمَنْ هٰذَا وَهٰذِهِ؟", "latin": "Wa man hādhā wa hādhihi?", "id": "Dan siapa ini dan ini?"},
                    {"speaker": "Ahmad", "ar": "هٰذَا جَدِّي وَهٰذِهِ جَدَّتِي", "latin": "Hādhā jaddī wa hādhihi jaddatī", "id": "Ini kakekku dan ini nenekku"},
                ],
                "mufrodat": [
                    {"ar": "هٰذَا", "latin": "hādhā", "id": "ini (laki-laki/benda maskulin)",
                     "exampleAr": "هٰذَا كِتَابٌ", "exampleLatin": "Hādhā kitābun", "exampleId": "Ini sebuah buku"},
                    {"ar": "هٰذِهِ", "latin": "hādhihi", "id": "ini (perempuan/benda feminin)",
                     "exampleAr": "هٰذِهِ مَدْرَسَةٌ", "exampleLatin": "Hādhihi madrasatun", "exampleId": "Ini sebuah sekolah"},
                    {"ar": "صُورَة", "latin": "ṣūrah", "id": "foto, gambar",
                     "exampleAr": "هٰذِهِ صُورَةُ بَيْتِي", "exampleLatin": "Hādhihi ṣūratu baytī", "exampleId": "Ini foto rumahku"},
                    {"ar": "عَائِلَة", "latin": "ʿā'ilah", "id": "keluarga",
                     "exampleAr": "عَائِلَتِي كَبِيرَةٌ", "exampleLatin": "ʿā'ilatī kabīrah", "exampleId": "Keluargaku besar"},
                    {"ar": "أَب", "latin": "ab", "id": "ayah",
                     "exampleAr": "أَبِي طَبِيبٌ", "exampleLatin": "Abī ṭabībun", "exampleId": "Ayahku seorang dokter"},
                    {"ar": "أُمّ", "latin": "umm", "id": "ibu",
                     "exampleAr": "أُمِّي مُدَرِّسَةٌ", "exampleLatin": "Ummī mudarrisah", "exampleId": "Ibuku seorang guru"},
                    {"ar": "أَخ", "latin": "akh", "id": "saudara laki-laki",
                     "exampleAr": "أَخِي صَغِيرٌ", "exampleLatin": "Akhī ṣaghīrun", "exampleId": "Saudara laki-lakiku kecil"},
                    {"ar": "أُخْت", "latin": "ukht", "id": "saudara perempuan",
                     "exampleAr": "أُخْتِي كَبِيرَةٌ", "exampleLatin": "Ukhtī kabīrah", "exampleId": "Saudara perempuanku besar"},
                    {"ar": "جَدّ", "latin": "jadd", "id": "kakek",
                     "exampleAr": "جَدِّي كَبِيرٌ", "exampleLatin": "Jaddī kabīrun", "exampleId": "Kakekku tua"},
                    {"ar": "جَدَّة", "latin": "jaddah", "id": "nenek",
                     "exampleAr": "جَدَّتِي طَيِّبَةٌ", "exampleLatin": "Jaddatī ṭayyibah", "exampleId": "Nenekku baik hati"},
                ],
                "qawaid": [
                    {"titleId": "Kata tunjuk هٰذَا dan هٰذِهِ",
                     "id": "هٰذَا berarti 'ini' untuk laki-laki atau kata benda maskulin (mis. أَبٌ، كِتَابٌ). هٰذِهِ untuk perempuan atau kata benda feminin (mis. أُمٌّ، صُورَةٌ).",
                     "exampleAr": "هٰذَا أَبِي", "exampleLatin": "Hādhā abī", "exampleId": "Ini ayahku"},
                    {"titleId": "Kata tanya مَنْ untuk orang",
                     "id": "مَنْ berarti 'siapa' dan dipakai untuk menanyakan orang, berbeda dengan مَا yang menanyakan benda.",
                     "exampleAr": "مَنْ هٰذَا؟", "exampleLatin": "Man hādhā?", "exampleId": "Siapa ini?"},
                    {"titleId": "Idhafah: menyambung dua kata benda",
                     "id": "Dua kata benda bisa dirangkai: kata pertama milik kata kedua, mis. صُورَةُ عَائِلَتِي = foto keluargaku. Kata kedua kehilangan tanwin.",
                     "exampleAr": "هٰذِهِ صُورَةُ عَائِلَتِي", "exampleLatin": "Hādhihi ṣūratu ʿā'ilatī", "exampleId": "Ini foto keluargaku"},
                ],
                "tadribat": [
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Ini ___ (ayahku)", "promptAr": "هٰذَا ____", "promptLatin": "Hādhā ____",
                     "options": ["أَبِي", "أُمِّي", "جَدَّتِي", "أُخْتِي"], "answer": "أَبِي"},
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Ini ___ (ibuku)", "promptAr": "هٰذِهِ ____", "promptLatin": "Hādhihi ____",
                     "options": ["أُمِّي", "أَبِي", "أَخِي", "جَدِّي"], "answer": "أُمِّي"},
                    {"type": "translateArId", "promptAr": "هٰذِهِ أُمِّي", "promptLatin": "Hādhihi ummī",
                     "options": ["Ini ibuku", "Ini ayahku", "Ini kakekku", "Ini nenekku"], "answer": "Ini ibuku"},
                    {"type": "translateArId", "promptAr": "هَلْ لَكَ إِخْوَةٌ؟", "promptLatin": "Hal laka ikhwatun?",
                     "options": ["Apakah kamu punya saudara?", "Apa namamu?", "Dari mana kamu?", "Di mana rumahmu?"], "answer": "Apakah kamu punya saudara?"},
                    {"type": "translateIdAr", "promptId": "Siapa ini?",
                     "options": ["مَنْ هٰذَا؟", "مَا هٰذَا؟", "أَيْنَ هٰذَا؟", "كَيْفَ هٰذَا؟"], "answer": "مَنْ هٰذَا؟"},
                    {"type": "translateIdAr", "promptId": "Ini foto keluargaku.",
                     "options": ["هٰذِهِ صُورَةُ عَائِلَتِي", "هٰذَا بَيْتُ عَائِلَتِي", "هٰذِهِ أُمِّي", "هٰذَا جَدِّي"], "answer": "هٰذِهِ صُورَةُ عَائِلَتِي"},
                    {"type": "rearrange",
                     "words": [{"ar": "هٰذِهِ", "latin": "hādhihi"}, {"ar": "صُورَةُ", "latin": "ṣūratu"}, {"ar": "عَائِلَتِي", "latin": "ʿā'ilatī"}],
                     "answer": ["هٰذِهِ", "صُورَةُ", "عَائِلَتِي"]},
                    {"type": "rearrange",
                     "words": [{"ar": "لِي", "latin": "lī"}, {"ar": "أَخٌ", "latin": "akhun"}, {"ar": "وَأُخْتٌ", "latin": "wa ukhtun"}],
                     "answer": ["لِي", "أَخٌ", "وَأُخْتٌ"]},
                ],
            },

            # ------------------------------------------------------------------
            # Lesson 1-3: Sekolah
            # ------------------------------------------------------------------
            {
                "id": "1-3",
                "titleId": "Sekolah",
                "titleAr": "المَدْرَسَةُ",
                "muhadatsah": [
                    {"speaker": "Ustadz", "ar": "صَبَاحَ الْخَيْرِ يَا فَاطِمَةُ", "latin": "Ṣabāḥa l-khayr yā Fāṭimah", "id": "Selamat pagi, Fatimah"},
                    {"speaker": "Fatimah", "ar": "صَبَاحَ النُّورِ", "latin": "Ṣabāḥa n-nūr", "id": "Selamat pagi"},
                    {"speaker": "Ustadz", "ar": "أَيْنَ أَنْتِ؟", "latin": "Ayna anti?", "id": "Di mana kamu?"},
                    {"speaker": "Fatimah", "ar": "أَنَا فِي الْمَدْرَسَةِ", "latin": "Anā fī l-madrasah", "id": "Aku di sekolah"},
                    {"speaker": "Ustadz", "ar": "مَاذَا تَدْرُسِينَ؟", "latin": "Mādhā tadrusīna?", "id": "Apa yang kamu pelajari?"},
                    {"speaker": "Fatimah", "ar": "أَدْرُسُ اللُّغَةَ الْعَرَبِيَّةَ", "latin": "Adrusu l-lughata l-ʿarabiyyah", "id": "Aku belajar bahasa Arab"},
                    {"speaker": "Ustadz", "ar": "مَا هٰذَا؟", "latin": "Mā hādhā?", "id": "Apa ini?"},
                    {"speaker": "Fatimah", "ar": "هٰذَا كِتَابٌ", "latin": "Hādhā kitābun", "id": "Ini sebuah buku"},
                    {"speaker": "Ustadz", "ar": "وَمَا هٰذَا؟", "latin": "Wa mā hādhā?", "id": "Dan apa ini?"},
                    {"speaker": "Fatimah", "ar": "هٰذَا قَلَمٌ", "latin": "Hādhā qalamun", "id": "Ini sebuah pena"},
                    {"speaker": "Ustadz", "ar": "وَمَا هٰذِهِ؟", "latin": "Wa mā hādhihi?", "id": "Dan apa ini?"},
                    {"speaker": "Fatimah", "ar": "هٰذِهِ مِسْطَرَةٌ", "latin": "Hādhihi misṭarah", "id": "Ini sebuah penggaris"},
                ],
                "mufrodat": [
                    {"ar": "صَبَاحَ الْخَيْرِ", "latin": "ṣabāḥa l-khayr", "id": "selamat pagi",
                     "exampleAr": "صَبَاحَ الْخَيْرِ يَا أُسْتَاذُ", "exampleLatin": "Ṣabāḥa l-khayr yā ustādh", "exampleId": "Selamat pagi, Ustadz"},
                    {"ar": "صَبَاحَ النُّورِ", "latin": "ṣabāḥa n-nūr", "id": "selamat pagi (jawaban)",
                     "exampleAr": "صَبَاحَ النُّورِ يَا فَاطِمَةُ", "exampleLatin": "Ṣabāḥa n-nūr yā Fāṭimah", "exampleId": "Selamat pagi, Fatimah"},
                    {"ar": "الْمَدْرَسَة", "latin": "al-madrasah", "id": "sekolah",
                     "exampleAr": "الْمَدْرَسَةُ كَبِيرَةٌ", "exampleLatin": "Al-madrasatu kabīrah", "exampleId": "Sekolahnya besar"},
                    {"ar": "فِي", "latin": "fī", "id": "di dalam",
                     "exampleAr": "الْكِتَابُ فِي الْحَقِيبَةِ", "exampleLatin": "Al-kitābu fī l-ḥaqībah", "exampleId": "Bukunya di dalam tas"},
                    {"ar": "كِتَاب", "latin": "kitāb", "id": "buku",
                     "exampleAr": "هٰذَا كِتَابٌ جَدِيدٌ", "exampleLatin": "Hādhā kitābun jadīdun", "exampleId": "Ini buku baru"},
                    {"ar": "قَلَم", "latin": "qalam", "id": "pena, pulpen",
                     "exampleAr": "قَلَمِي أَحْمَرُ", "exampleLatin": "Qalamī aḥmaru", "exampleId": "Penaku merah"},
                    {"ar": "مِسْطَرَة", "latin": "misṭarah", "id": "penggaris",
                     "exampleAr": "الْمِسْطَرَةُ طَوِيلَةٌ", "exampleLatin": "Al-misṭaratu ṭawīlah", "exampleId": "Penggarisnya panjang"},
                    {"ar": "مَاذَا", "latin": "mādhā", "id": "apa (untuk bertanya kegiatan)",
                     "exampleAr": "مَاذَا تَقْرَأُ؟", "exampleLatin": "Mādhā taqra'?", "exampleId": "Apa yang kamu baca?"},
                    {"ar": "اللُّغَة", "latin": "al-lughah", "id": "bahasa",
                     "exampleAr": "اللُّغَةُ الْعَرَبِيَّةُ جَمِيلَةٌ", "exampleLatin": "Al-lughatu l-ʿarabiyyatu jamīlah", "exampleId": "Bahasa Arab itu indah"},
                    {"ar": "الْعَرَبِيَّة", "latin": "al-ʿarabiyyah", "id": "bahasa Arab",
                     "exampleAr": "أَتَعَلَّمُ الْعَرَبِيَّةَ", "exampleLatin": "Ataʿallamu l-ʿarabiyyah", "exampleId": "Aku belajar bahasa Arab"},
                ],
                "qawaid": [
                    {"titleId": "Kata tanya أَيْنَ (di mana)",
                     "id": "أَيْنَ dipakai untuk menanyakan tempat. Jawabannya biasanya memakai kata depan فِي (di dalam).",
                     "exampleAr": "أَيْنَ أَنْتِ؟", "exampleLatin": "Ayna anti?", "exampleId": "Di mana kamu?"},
                    {"titleId": "Kata depan فِي (di)",
                     "id": "فِي berarti 'di dalam' dan diikuti kata benda berakhiran kasrah (jar). Contoh: فِي الْمَدْرَسَةِ = di sekolah.",
                     "exampleAr": "أَنَا فِي الْمَدْرَسَةِ", "exampleLatin": "Anā fī l-madrasah", "exampleId": "Aku di sekolah"},
                    {"titleId": "Kata kerja sekarang (fi'il mudhari')",
                     "id": "أَدْرُسُ berarti 'aku sedang belajar' dan تَدْرُسِينَ berarti 'kamu (perempuan) sedang belajar'. Kata kerja berubah mengikuti pelakunya.",
                     "exampleAr": "أَدْرُسُ اللُّغَةَ الْعَرَبِيَّةَ", "exampleLatin": "Adrusu l-lughata l-ʿarabiyyah", "exampleId": "Aku belajar bahasa Arab"},
                ],
                "tadribat": [
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Aku ___ sekolah", "promptAr": "أَنَا ____ الْمَدْرَسَةِ", "promptLatin": "Anā ____ l-madrasah",
                     "options": ["فِي", "مِنْ", "عَلَى", "إِلَى"], "answer": "فِي"},
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Ini sebuah ___ (buku)", "promptAr": "هٰذَا ____", "promptLatin": "Hādhā ____",
                     "options": ["كِتَابٌ", "مِسْطَرَةٌ", "مَدْرَسَةٌ", "حَقِيبَةٌ"], "answer": "كِتَابٌ"},
                    {"type": "translateArId", "promptAr": "مَاذَا تَدْرُسِينَ؟", "promptLatin": "Mādhā tadrusīna?",
                     "options": ["Apa yang kamu pelajari?", "Apa namamu?", "Di mana sekolahmu?", "Apa ini?"], "answer": "Apa yang kamu pelajari?"},
                    {"type": "translateArId", "promptAr": "أَنَا فِي الْمَدْرَسَةِ", "promptLatin": "Anā fī l-madrasah",
                     "options": ["Aku di sekolah", "Aku di rumah", "Aku di pasar", "Aku di masjid"], "answer": "Aku di sekolah"},
                    {"type": "translateIdAr", "promptId": "Selamat pagi.",
                     "options": ["صَبَاحَ الْخَيْرِ", "مَسَاءَ الْخَيْرِ", "أَهْلًا وَسَهْلًا", "تَشَرَّفْنَا"], "answer": "صَبَاحَ الْخَيْرِ"},
                    {"type": "translateIdAr", "promptId": "Ini sebuah penggaris.",
                     "options": ["هٰذِهِ مِسْطَرَةٌ", "هٰذَا قَلَمٌ", "هٰذَا كِتَابٌ", "هٰذِهِ مَدْرَسَةٌ"], "answer": "هٰذِهِ مِسْطَرَةٌ"},
                    {"type": "rearrange",
                     "words": [{"ar": "أَنَا", "latin": "anā"}, {"ar": "فِي", "latin": "fī"}, {"ar": "الْمَدْرَسَةِ", "latin": "al-madrasah"}],
                     "answer": ["أَنَا", "فِي", "الْمَدْرَسَةِ"]},
                    {"type": "rearrange",
                     "words": [{"ar": "أَدْرُسُ", "latin": "adrusu"}, {"ar": "اللُّغَةَ", "latin": "al-lughata"}, {"ar": "الْعَرَبِيَّةَ", "latin": "al-ʿarabiyyah"}],
                     "answer": ["أَدْرُسُ", "اللُّغَةَ", "الْعَرَبِيَّةَ"]},
                ],
            },

            # ------------------------------------------------------------------
            # Lesson 1-4: Rumah
            # ------------------------------------------------------------------
            {
                "id": "1-4",
                "titleId": "Rumah",
                "titleAr": "البَيْتُ",
                "muhadatsah": [
                    {"speaker": "Salim", "ar": "أَيْنَ بَيْتُكَ يَا أَحْمَدُ؟", "latin": "Ayna baytuka yā Aḥmad?", "id": "Di mana rumahmu, Ahmad?"},
                    {"speaker": "Ahmad", "ar": "بَيْتِي فِي جَاكَرْتَا", "latin": "Baytī fī Jākartā", "id": "Rumahku di Jakarta"},
                    {"speaker": "Salim", "ar": "هَلْ بَيْتُكَ كَبِيرٌ؟", "latin": "Hal baytuka kabīrun?", "id": "Apakah rumahmu besar?"},
                    {"speaker": "Ahmad", "ar": "نَعَمْ، بَيْتِي كَبِيرٌ", "latin": "Naʿam, baytī kabīrun", "id": "Ya, rumahku besar"},
                    {"speaker": "Salim", "ar": "كَمْ غُرْفَةً فِي بَيْتِكَ؟", "latin": "Kam ghurfatan fī baytika?", "id": "Berapa kamar di rumahmu?"},
                    {"speaker": "Ahmad", "ar": "فِي بَيْتِي أَرْبَعُ غُرَفٍ", "latin": "Fī baytī arbaʿu ghurafin", "id": "Di rumahku ada empat kamar"},
                    {"speaker": "Salim", "ar": "وَأَيْنَ الْمَطْبَخُ؟", "latin": "Wa ayna l-maṭbakh?", "id": "Dan di mana dapurnya?"},
                    {"speaker": "Ahmad", "ar": "الْمَطْبَخُ قَرِيبٌ مِنَ الْحَمَّامِ", "latin": "Al-maṭbakhu qarībun mina l-ḥammām", "id": "Dapur dekat dengan kamar mandi"},
                    {"speaker": "Salim", "ar": "مَا هٰذَا؟", "latin": "Mā hādhā?", "id": "Apa ini?"},
                    {"speaker": "Ahmad", "ar": "هٰذَا بَابُ الْبَيْتِ", "latin": "Hādhā bābu l-bayt", "id": "Ini pintu rumah"},
                ],
                "mufrodat": [
                    {"ar": "بَيْت", "latin": "bayt", "id": "rumah",
                     "exampleAr": "بَيْتِي قَرِيبٌ مِنَ الْمَسْجِدِ", "exampleLatin": "Baytī qarībun mina l-masjid", "exampleId": "Rumahku dekat dengan masjid"},
                    {"ar": "كَبِير", "latin": "kabīr", "id": "besar",
                     "exampleAr": "الْبَيْتُ كَبِيرٌ", "exampleLatin": "Al-baytu kabīrun", "exampleId": "Rumahnya besar"},
                    {"ar": "غُرْفَة", "latin": "ghurfah", "id": "kamar, ruangan",
                     "exampleAr": "غُرْفَتِي نَظِيفَةٌ", "exampleLatin": "Ghurfatī naẓīfah", "exampleId": "Kamarku bersih"},
                    {"ar": "مَطْبَخ", "latin": "maṭbakh", "id": "dapur",
                     "exampleAr": "الْمَطْبَخُ وَاسِعٌ", "exampleLatin": "Al-maṭbakhu wāsiʿun", "exampleId": "Dapurnya luas"},
                    {"ar": "حَمَّام", "latin": "ḥammām", "id": "kamar mandi",
                     "exampleAr": "الْحَمَّامُ نَظِيفٌ", "exampleLatin": "Al-ḥammāmu naẓīfun", "exampleId": "Kamar mandinya bersih"},
                    {"ar": "بَاب", "latin": "bāb", "id": "pintu",
                     "exampleAr": "بَابُ الْغُرْفَةِ مَفْتُوحٌ", "exampleLatin": "Bābu l-ghurfati maftūḥun", "exampleId": "Pintu kamarnya terbuka"},
                    {"ar": "نَعَم", "latin": "naʿam", "id": "ya (jawaban setuju)",
                     "exampleAr": "نَعَمْ، هٰذَا كِتَابِي", "exampleLatin": "Naʿam, hādhā kitābī", "exampleId": "Ya, ini bukuku"},
                    {"ar": "كَمْ", "latin": "kam", "id": "berapa",
                     "exampleAr": "كَمْ كِتَابًا عِنْدَكَ؟", "exampleLatin": "Kam kitāban ʿindaka?", "exampleId": "Berapa buku yang kamu punya?"},
                    {"ar": "قَرِيب", "latin": "qarīb", "id": "dekat",
                     "exampleAr": "الْمَسْجِدُ قَرِيبٌ مِنَ الْبَيْتِ", "exampleLatin": "Al-masjidu qarībun mina l-bayt", "exampleId": "Masjidnya dekat dengan rumah"},
                    {"ar": "أَرْبَع", "latin": "arbaʿ", "id": "empat",
                     "exampleAr": "عِنْدِي أَرْبَعَةُ كُتُبٍ", "exampleLatin": "ʿindī arbaʿatu kutubin", "exampleId": "Aku punya empat buku"},
                ],
                "qawaid": [
                    {"titleId": "Kata tanya أَيْنَ + فِي untuk tempat",
                     "id": "Untuk bertanya tempat gunakan أَيْنَ (di mana). Jawabannya memakai فِي (di) atau قَرِيبٌ مِنْ (dekat dengan).",
                     "exampleAr": "أَيْنَ بَيْتُكَ يَا أَحْمَدُ؟", "exampleLatin": "Ayna baytuka yā Aḥmad?", "exampleId": "Di mana rumahmu, Ahmad?"},
                    {"titleId": "Kata tanya كَمْ (berapa)",
                     "id": "كَمْ dipakai untuk menanyakan jumlah. Kata benda setelahnya berakhiran -an (nasab), mis. كَمْ غُرْفَةً؟ = berapa kamar?",
                     "exampleAr": "كَمْ غُرْفَةً فِي بَيْتِكَ؟", "exampleLatin": "Kam ghurfatan fī baytika?", "exampleId": "Berapa kamar di rumahmu?"},
                    {"titleId": "Kalimat dengan kata sifat (na't)",
                     "id": "Kata sifat mengikuti kata benda dalam jenisnya: بَيْتٌ كَبِيرٌ (rumah besar, maskulin), مَدْرَسَةٌ كَبِيرَةٌ (sekolah besar, feminin).",
                     "exampleAr": "بَيْتِي كَبِيرٌ", "exampleLatin": "Baytī kabīrun", "exampleId": "Rumahku besar"},
                ],
                "tadribat": [
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Di mana ___ , Ahmad?", "promptAr": "أَيْنَ ____ يَا أَحْمَدُ؟", "promptLatin": "Ayna ____ yā Aḥmad?",
                     "options": ["بَيْتُكَ", "كِتَابُكَ", "قَلَمُكَ", "مَدْرَسَتُكَ"], "answer": "بَيْتُكَ"},
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Di rumahku ada empat ___", "promptAr": "فِي بَيْتِي أَرْبَعُ ____", "promptLatin": "Fī baytī arbaʿu ____",
                     "options": ["غُرَفٍ", "كُتُبٍ", "أَقْلَامٍ", "مَسَاجِدَ"], "answer": "غُرَفٍ"},
                    {"type": "translateArId", "promptAr": "بَيْتِي فِي جَاكَرْتَا", "promptLatin": "Baytī fī Jākartā",
                     "options": ["Rumahku di Jakarta", "Rumahku di Bandung", "Sekolahku di Jakarta", "Rumahmu di Jakarta"], "answer": "Rumahku di Jakarta"},
                    {"type": "translateArId", "promptAr": "الْمَطْبَخُ قَرِيبٌ مِنَ الْحَمَّامِ", "promptLatin": "Al-maṭbakhu qarībun mina l-ḥammām",
                     "options": ["Dapur dekat dengan kamar mandi", "Dapur ada di dalam rumah", "Kamar mandi dekat dengan pintu", "Dapurnya besar"], "answer": "Dapur dekat dengan kamar mandi"},
                    {"type": "translateIdAr", "promptId": "Berapa kamar di rumahmu?",
                     "options": ["كَمْ غُرْفَةً فِي بَيْتِكَ؟", "كَمْ كِتَابًا عِنْدَكَ؟", "أَيْنَ غُرْفَتُكَ؟", "هَلْ بَيْتُكَ كَبِيرٌ؟"], "answer": "كَمْ غُرْفَةً فِي بَيْتِكَ؟"},
                    {"type": "translateIdAr", "promptId": "Apakah rumahmu besar?",
                     "options": ["هَلْ بَيْتُكَ كَبِيرٌ؟", "هَلْ بَيْتُكَ قَرِيبٌ؟", "أَيْنَ بَيْتُكَ؟", "كَمْ بَيْتًا لَكَ؟"], "answer": "هَلْ بَيْتُكَ كَبِيرٌ؟"},
                    {"type": "rearrange",
                     "words": [{"ar": "بَيْتِي", "latin": "baytī"}, {"ar": "فِي", "latin": "fī"}, {"ar": "جَاكَرْتَا", "latin": "Jākartā"}],
                     "answer": ["بَيْتِي", "فِي", "جَاكَرْتَا"]},
                    {"type": "rearrange",
                     "words": [{"ar": "الْمَطْبَخُ", "latin": "al-maṭbakh"}, {"ar": "قَرِيبٌ", "latin": "qarībun"}, {"ar": "مِنَ", "latin": "mina"}, {"ar": "الْحَمَّامِ", "latin": "al-ḥammām"}],
                     "answer": ["الْمَطْبَخُ", "قَرِيبٌ", "مِنَ", "الْحَمَّامِ"]},
                ],
            },

            # ------------------------------------------------------------------
            # Lesson 1-5: Makanan
            # ------------------------------------------------------------------
            {
                "id": "1-5",
                "titleId": "Makanan",
                "titleAr": "الطَّعَامُ",
                "muhadatsah": [
                    {"speaker": "Ahmad", "ar": "مَا هٰذَا يَا فَاطِمَةُ؟", "latin": "Mā hādhā yā Fāṭimah?", "id": "Apa ini, Fatimah?"},
                    {"speaker": "Fatimah", "ar": "هٰذَا خُبْزٌ", "latin": "Hādhā khubzun", "id": "Ini roti"},
                    {"speaker": "Ahmad", "ar": "وَمَا هٰذَا؟", "latin": "Wa mā hādhā?", "id": "Dan apa ini?"},
                    {"speaker": "Fatimah", "ar": "هٰذَا أَرُزٌّ", "latin": "Hādhā aruzzun", "id": "Ini nasi"},
                    {"speaker": "Ahmad", "ar": "أُحِبُّ الْأَرُزَّ كَثِيرًا", "latin": "Uḥibbu l-aruzza kathīran", "id": "Aku sangat suka nasi"},
                    {"speaker": "Fatimah", "ar": "وَهٰذَا حَسَاءٌ", "latin": "Wa hādhā ḥasā'un", "id": "Dan ini sup"},
                    {"speaker": "Ahmad", "ar": "مَا هٰذِهِ؟", "latin": "Mā hādhihi?", "id": "Apa ini?"},
                    {"speaker": "Fatimah", "ar": "هٰذِهِ فَاكِهَةٌ", "latin": "Hādhihi fākihah", "id": "Ini buah"},
                    {"speaker": "Ahmad", "ar": "مَا اسْمُ هٰذِهِ الْفَاكِهَةِ؟", "latin": "Mā smu hādhihi l-fākihah?", "id": "Apa nama buah ini?"},
                    {"speaker": "Fatimah", "ar": "اسْمُهَا مَوْزٌ", "latin": "Ismuhā mawzun", "id": "Namanya pisang"},
                    {"speaker": "Ahmad", "ar": "الطَّعَامُ لَذِيذٌ", "latin": "Aṭ-ṭaʿāmu ladhdhīdhun", "id": "Makanannya lezat"},
                ],
                "mufrodat": [
                    {"ar": "الطَّعَام", "latin": "aṭ-ṭaʿām", "id": "makanan",
                     "exampleAr": "الطَّعَامُ فِي الْمَطْبَخِ", "exampleLatin": "Aṭ-ṭaʿāmu fī l-maṭbakh", "exampleId": "Makanannya ada di dapur"},
                    {"ar": "خُبْز", "latin": "khubz", "id": "roti",
                     "exampleAr": "الْخُبْزُ طَازَجٌ", "exampleLatin": "Al-khubzu ṭāzijun", "exampleId": "Rotinya segar"},
                    {"ar": "أَرُزّ", "latin": "aruzz", "id": "nasi",
                     "exampleAr": "الْأَرُزُّ مِنْ إِنْدُونِيسِيَّا", "exampleLatin": "Al-aruzzu min Indūnīsiyyā", "exampleId": "Nasi berasal dari Indonesia"},
                    {"ar": "حَسَاء", "latin": "ḥasā'", "id": "sup",
                     "exampleAr": "الْحَسَاءُ حَارٌّ", "exampleLatin": "Al-ḥasā'u ḥārr", "exampleId": "Supnya pedas"},
                    {"ar": "فَاكِهَة", "latin": "fākihah", "id": "buah",
                     "exampleAr": "الْفَاكِهَةُ طَيِّبَةٌ", "exampleLatin": "Al-fākihatu ṭayyibah", "exampleId": "Buahnya enak"},
                    {"ar": "مَوْز", "latin": "mawz", "id": "pisang",
                     "exampleAr": "الْمَوْزُ أَصْفَرُ", "exampleLatin": "Al-mawzu aṣfaru", "exampleId": "Pisangnya berwarna kuning"},
                    {"ar": "أُحِبُّ", "latin": "uḥibbu", "id": "saya suka",
                     "exampleAr": "أُحِبُّ الْخُبْزَ", "exampleLatin": "Uḥibbu l-khubz", "exampleId": "Aku suka roti"},
                    {"ar": "كَثِيرًا", "latin": "kathīran", "id": "sangat, banyak",
                     "exampleAr": "أُحِبُّ الْفَاكِهَةَ كَثِيرًا", "exampleLatin": "Uḥibbu l-fākihata kathīran", "exampleId": "Aku sangat suka buah"},
                    {"ar": "اسْم", "latin": "ism", "id": "nama",
                     "exampleAr": "اسْمُ أَبِي أَحْمَدُ", "exampleLatin": "Ismu abī Aḥmad", "exampleId": "Nama ayahku Ahmad"},
                    {"ar": "لَذِيذ", "latin": "ladhdhīdh", "id": "lezat, enak",
                     "exampleAr": "الْخُبْزُ لَذِيذٌ", "exampleLatin": "Al-khubzu ladhdhīdhun", "exampleId": "Rotinya lezat"},
                ],
                "qawaid": [
                    {"titleId": "أُحِبُّ + kata benda (saya suka ...)",
                     "id": "أُحِبُّ berarti 'saya suka/mencintai'. Kata benda sesudahnya berakhiran -a (nasab), contoh: أُحِبُّ الْأَرُزَّ = aku suka nasi.",
                     "exampleAr": "أُحِبُّ الْأَرُزَّ كَثِيرًا", "exampleLatin": "Uḥibbu l-aruzza kathīran", "exampleId": "Aku sangat suka nasi"},
                    {"titleId": "Kata sifat (na't) mengikuti kata benda",
                     "id": "Kata sifat mengikuti kata benda dalam jenisnya: الطَّعَامُ لَذِيذٌ (makanan lezat, maskulin) dan الْفَاكِهَةُ لَذِيذَةٌ (buah lezat, feminin).",
                     "exampleAr": "الطَّعَامُ لَذِيذٌ", "exampleLatin": "Aṭ-ṭaʿāmu ladhdhīdhun", "exampleId": "Makanannya lezat"},
                    {"titleId": "Menanyakan nama benda: مَا اسْمُ ...؟",
                     "id": "Untuk menanyakan nama sesuatu gunakan مَا اسْمُ ...؟ (apa nama ...?). Jawabannya: اسْمُهُ (namanya, maskulin) atau اسْمُهَا (namanya, feminin).",
                     "exampleAr": "مَا اسْمُ هٰذِهِ الْفَاكِهَةِ؟", "exampleLatin": "Mā smu hādhihi l-fākihah?", "exampleId": "Apa nama buah ini?"},
                ],
                "tadribat": [
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Aku sangat suka ___", "promptAr": "أُحِبُّ ____ كَثِيرًا", "promptLatin": "Uḥibbu ____ kathīran",
                     "options": ["الْأَرُزَّ", "الْخُبْزَ", "الْحَسَاءَ", "الْفَاكِهَةَ"], "answer": "الْأَرُزَّ"},
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Ini ___ (buah)", "promptAr": "هٰذِهِ ____", "promptLatin": "Hādhihi ____",
                     "options": ["فَاكِهَةٌ", "خُبْزٌ", "أَرُزٌّ", "حَسَاءٌ"], "answer": "فَاكِهَةٌ"},
                    {"type": "translateArId", "promptAr": "أُحِبُّ الْأَرُزَّ كَثِيرًا", "promptLatin": "Uḥibbu l-aruzza kathīran",
                     "options": ["Aku sangat suka nasi", "Aku suka roti", "Aku makan nasi", "Nasi itu enak"], "answer": "Aku sangat suka nasi"},
                    {"type": "translateArId", "promptAr": "مَا اسْمُ هٰذِهِ الْفَاكِهَةِ؟", "promptLatin": "Mā smu hādhihi l-fākihah?",
                     "options": ["Apa nama buah ini?", "Apa ini?", "Apa nama makanan ini?", "Di mana buah ini?"], "answer": "Apa nama buah ini?"},
                    {"type": "translateIdAr", "promptId": "Ini roti.",
                     "options": ["هٰذَا خُبْزٌ", "هٰذَا أَرُزٌّ", "هٰذَا حَسَاءٌ", "هٰذِهِ فَاكِهَةٌ"], "answer": "هٰذَا خُبْزٌ"},
                    {"type": "translateIdAr", "promptId": "Makanannya lezat.",
                     "options": ["الطَّعَامُ لَذِيذٌ", "الطَّعَامُ كَبِيرٌ", "الْفَاكِهَةُ لَذِيذَةٌ", "الْخُبْزُ حَارٌّ"], "answer": "الطَّعَامُ لَذِيذٌ"},
                    {"type": "rearrange",
                     "words": [{"ar": "أُحِبُّ", "latin": "uḥibbu"}, {"ar": "الْأَرُزَّ", "latin": "al-aruzz"}, {"ar": "كَثِيرًا", "latin": "kathīran"}],
                     "answer": ["أُحِبُّ", "الْأَرُزَّ", "كَثِيرًا"]},
                    {"type": "rearrange",
                     "words": [{"ar": "مَا", "latin": "mā"}, {"ar": "اسْمُ", "latin": "smu"}, {"ar": "هٰذِهِ", "latin": "hādhihi"}, {"ar": "الْفَاكِهَةِ", "latin": "al-fākihah"}],
                     "answer": ["مَا", "اسْمُ", "هٰذِهِ", "الْفَاكِهَةِ"]},
                ],
            },
        ],
    }
]
