# -*- coding: utf-8 -*-
"""
Konten Level 2 — "Aktivitas & Kehidupan Sehari-hari" (5 lesson).
Konten ORISINAL: ditulis dari nol, jangan menyalin dari kitab/sumber mana pun.
Skema: tools/lughoh-schema.md. Di-generate oleh tools/build_lughoh.py.
"""

LEVELS = [
    {
        "id": 2,
        "titleId": "Level 2 — Pasar, Transportasi, Kesehatan, Olahraga & Rutinitas",
        "titleAr": "المُسْتَوَى الثَّانِي",
        "lessons": [
            # ------------------------------------------------------------------
            # Lesson 2-1: Di Pasar
            # ------------------------------------------------------------------
            {
                "id": "2-1",
                "titleId": "Di Pasar",
                "titleAr": "فِي السُّوقِ",
                "muhadatsah": [
                    {"speaker": "Fatimah", "ar": "أَنَا فِي السُّوقِ الْيَوْمَ", "latin": "Anā fī s-sūqi l-yawm", "id": "Hari ini aku di pasar"},
                    {"speaker": "Penjual", "ar": "السَّلَامُ عَلَيْكُمْ، تَفَضَّلِي", "latin": "As-salāmu ʿalaikum, tafaḍḍalī", "id": "Semoga keselamatan, silakan"},
                    {"speaker": "Fatimah", "ar": "وَعَلَيْكُمُ السَّلَامُ. بِكَمْ هٰذَا التُّفَّاحُ؟", "latin": "Wa ʿalaikumus-salām. Bikam hādhā t-tuffāḥ?", "id": "Dan semoga keselamatan. Berapa harga apel ini?"},
                    {"speaker": "Penjual", "ar": "الْكِيلُو بِعَشَرَةِ آلَافِ رُوبِيَّة", "latin": "Al-kīlū biʿasharati ālāfi rūbiyyah", "id": "Satu kilo sepuluh ribu rupiah"},
                    {"speaker": "Fatimah", "ar": "هٰذَا غَالٍ جِدًّا", "latin": "Hādhā ghālin jiddan", "id": "Ini sangat mahal"},
                    {"speaker": "Penjual", "ar": "فَهٰذَا الْبُرْتُقَالُ أَرْخَصُ", "latin": "Fa-hādhā l-burtuqāl arkhaṣ", "id": "Maka jeruk ini lebih murah"},
                    {"speaker": "Fatimah", "ar": "كَمْ ثَمَنُ الْبُرْتُقَالِ؟", "latin": "Kam thamanu l-burtuqāl?", "id": "Berapa harga jeruk?"},
                    {"speaker": "Penjual", "ar": "ثَمَنُهُ ثَمَانِيَةُ آلَافٍ لِلْكِيلُو", "latin": "Thamanuhu thamāniyatu ālāfin lil-kīlū", "id": "Harganya delapan ribu per kilo"},
                    {"speaker": "Fatimah", "ar": "جَيِّدٌ. آخُذُ كِيلُوَيْنِ", "latin": "Jayyid. Ākhudhu kīlawayni", "id": "Bagus. Aku ambil dua kilo"},
                    {"speaker": "Penjual", "ar": "حَسَنًا، تَفَضَّلِي", "latin": "Ḥasanan, tafaḍḍalī", "id": "Baiklah, silakan"},
                ],
                "mufrodat": [
                    {"ar": "السُّوق", "latin": "as-sūq", "id": "pasar",
                     "exampleAr": "السُّوقُ قَرِيبٌ مِنَ الْبَيْتِ", "exampleLatin": "As-sūqu qarībun mina l-bayt", "exampleId": "Pasarnya dekat dengan rumah"},
                    {"ar": "تُفَّاح", "latin": "tuffāḥ", "id": "apel",
                     "exampleAr": "التُّفَّاحُ لَذِيذٌ", "exampleLatin": "At-tuffāḥu ladhdhīdhun", "exampleId": "Apelnya lezat"},
                    {"ar": "بُرْتُقَال", "latin": "burtuqāl", "id": "jeruk",
                     "exampleAr": "الْبُرْتُقَالُ أَصْفَرُ", "exampleLatin": "Al-burtuqālu aṣfaru", "exampleId": "Jeruknya berwarna kuning"},
                    {"ar": "ثَمَن", "latin": "thaman", "id": "harga",
                     "exampleAr": "ثَمَنُ الْكِتَابِ غَالٍ", "exampleLatin": "Thamanu l-kitābi ghālin", "exampleId": "Harga bukunya mahal"},
                    {"ar": "غَالٍ", "latin": "ghālin", "id": "mahal",
                     "exampleAr": "هٰذَا الْقَمِيصُ غَالٍ", "exampleLatin": "Hādhā l-qamīṣu ghālin", "exampleId": "Kemeja ini mahal"},
                    {"ar": "أَرْخَص", "latin": "arkhaṣ", "id": "lebih murah",
                     "exampleAr": "هٰذَا الْكِتَابُ أَرْخَصُ مِنْ ذٰلِكَ", "exampleLatin": "Hādhā l-kitābu arkhaṣu min dhālika", "exampleId": "Buku ini lebih murah daripada itu"},
                    {"ar": "كِيلُو", "latin": "kīlū", "id": "kilo",
                     "exampleAr": "كِيلُو الْأَرُزِّ بِعَشَرَةِ آلَافٍ", "exampleLatin": "Kīlū l-aruzzi biʿasharati ālāfin", "exampleId": "Satu kilo nasi sepuluh ribu"},
                    {"ar": "رُوبِيَّة", "latin": "rūbiyyah", "id": "rupiah",
                     "exampleAr": "هٰذَا بِخَمْسَةِ آلَافِ رُوبِيَّة", "exampleLatin": "Hādhā bikhamsati ālāfi rūbiyyah", "exampleId": "Ini lima ribu rupiah"},
                    {"ar": "آخُذُ", "latin": "ākhudhu", "id": "aku mengambil",
                     "exampleAr": "آخُذُ الْكِتَابَ مِنَ الْمَكْتَبَةِ", "exampleLatin": "Ākhudhu l-kitāba mina l-maktabah", "exampleId": "Aku mengambil buku dari perpustakaan"},
                    {"ar": "جِدًّا", "latin": "jiddan", "id": "sangat",
                     "exampleAr": "الْبَيْتُ كَبِيرٌ جِدًّا", "exampleLatin": "Al-baytu kabīrun jiddan", "exampleId": "Rumahnya sangat besar"},
                ],
                "qawaid": [
                    {"titleId": "بِكَمْ untuk bertanya harga",
                     "id": "بِكَمْ berarti 'berapa harganya?'. Jawaban harga memakai بِ (dengan/seharga), mis. بِعَشَرَةِ آلَافِ رُوبِيَّة = seharga sepuluh ribu rupiah.",
                     "exampleAr": "بِكَمْ هٰذَا التُّفَّاحُ؟", "exampleLatin": "Bikam hādhā t-tuffāḥ?", "exampleId": "Berapa harga apel ini?"},
                    {"titleId": "Angka 3–10 + kata benda jamak",
                     "id": "Untuk angka 3 sampai 10, kata bendanya berbentuk jamak: عَشَرَةُ آلَافٍ (sepuluh ribu), ثَمَانِيَةُ آلَافٍ (delapan ribu).",
                     "exampleAr": "الْكِيلُو بِعَشَرَةِ آلَافِ رُوبِيَّة", "exampleLatin": "Al-kīlū biʿasharati ālāfi rūbiyyah", "exampleId": "Satu kilo sepuluh ribu rupiah"},
                    {"titleId": "Bentuk perbandingan أَفْعَل",
                     "id": "أَرْخَصُ berarti 'lebih murah', bentuk perbandingan dari رَخِيصٌ (murah). Pola ini dipakai untuk membandingkan: أَكْبَرُ (lebih besar), أَقْرَبُ (lebih dekat).",
                     "exampleAr": "فَهٰذَا الْبُرْتُقَالُ أَرْخَصُ", "exampleLatin": "Fa-hādhā l-burtuqāl arkhaṣ", "exampleId": "Maka jeruk ini lebih murah"},
                ],
                "tadribat": [
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Berapa harga ___ ini?", "promptAr": "بِكَمْ هٰذَا ____؟", "promptLatin": "Bikam hādhā ____?",
                     "options": ["التُّفَّاحُ", "الْبُرْتُقَالُ", "الْخُبْزُ", "الْأَرُزُّ"], "answer": "التُّفَّاحُ"},
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Harganya delapan ___", "promptAr": "ثَمَنُهُ ثَمَانِيَةُ ____", "promptLatin": "Thamanuhu thamāniyatu ____",
                     "options": ["آلَافٍ", "غُرَفٍ", "كُتُبٍ", "أَقْلَامٍ"], "answer": "آلَافٍ"},
                    {"type": "translateArId", "promptAr": "هٰذَا غَالٍ جِدًّا", "promptLatin": "Hādhā ghālin jiddan",
                     "options": ["Ini sangat mahal", "Ini sangat murah", "Ini sangat enak", "Ini sangat bagus"], "answer": "Ini sangat mahal"},
                    {"type": "translateArId", "promptAr": "آخُذُ كِيلُوَيْنِ", "promptLatin": "Ākhudhu kīlawayni",
                     "options": ["Aku ambil dua kilo", "Aku ambil satu kilo", "Aku suka jeruk", "Aku beli apel"], "answer": "Aku ambil dua kilo"},
                    {"type": "translateIdAr", "promptId": "Berapa harga jeruk?",
                     "options": ["كَمْ ثَمَنُ الْبُرْتُقَالِ؟", "بِكَمْ هٰذَا التُّفَّاحُ؟", "كَمْ كِيلُو عِنْدَكَ؟", "أَيْنَ السُّوقُ؟"], "answer": "كَمْ ثَمَنُ الْبُرْتُقَالِ؟"},
                    {"type": "translateIdAr", "promptId": "Silakan.",
                     "options": ["تَفَضَّلِي", "تَشَرَّفْنَا", "أَهْلًا وَسَهْلًا", "مَعَ السَّلَامَةِ"], "answer": "تَفَضَّلِي"},
                    {"type": "rearrange",
                     "words": [{"ar": "أَنَا", "latin": "anā"}, {"ar": "فِي", "latin": "fī"}, {"ar": "السُّوقِ", "latin": "as-sūq"}, {"ar": "الْيَوْمَ", "latin": "al-yawm"}],
                     "answer": ["أَنَا", "فِي", "السُّوقِ", "الْيَوْمَ"]},
                    {"type": "rearrange",
                     "words": [{"ar": "ثَمَنُهُ", "latin": "thamanuhu"}, {"ar": "ثَمَانِيَةُ", "latin": "thamāniyatu"}, {"ar": "آلَافٍ", "latin": "ālāfin"}],
                     "answer": ["ثَمَنُهُ", "ثَمَانِيَةُ", "آلَافٍ"]},
                ],
            },

            # ------------------------------------------------------------------
            # Lesson 2-2: Transportasi
            # ------------------------------------------------------------------
            {
                "id": "2-2",
                "titleId": "Transportasi",
                "titleAr": "المُوَاصَلَاتُ",
                "muhadatsah": [
                    {"speaker": "Salim", "ar": "كَيْفَ تَذْهَبُ إِلَى الْمَدْرَسَةِ؟", "latin": "Kayfa tadhhabu ilā l-madrasah?", "id": "Bagaimana kamu pergi ke sekolah?"},
                    {"speaker": "Ahmad", "ar": "أَذْهَبُ بِالسَّيَّارَةِ", "latin": "Adhhabu bis-sayyārah", "id": "Aku pergi dengan mobil"},
                    {"speaker": "Salim", "ar": "وَكَيْفَ تَذْهَبُ إِلَى السُّوقِ؟", "latin": "Wa kayfa tadhhabu ilā s-sūq?", "id": "Dan bagaimana kamu pergi ke pasar?"},
                    {"speaker": "Ahmad", "ar": "أَذْهَبُ بِالدَّرَّاجَةِ النَّارِيَّةِ", "latin": "Adhhabu bid-darrājati n-nāriyyah", "id": "Aku pergi dengan sepeda motor"},
                    {"speaker": "Salim", "ar": "هَلْ الْمَدْرَسَةُ بَعِيدَةٌ؟", "latin": "Hal al-madrasatu baʿīdah?", "id": "Apakah sekolahnya jauh?"},
                    {"speaker": "Ahmad", "ar": "لَا، الْمَدْرَسَةُ قَرِيبَةٌ", "latin": "Lā, al-madrasatu qarībah", "id": "Tidak, sekolahnya dekat"},
                    {"speaker": "Salim", "ar": "وَأَيْنَ مَحَطَّةُ الْحَافِلَةِ؟", "latin": "Wa ayna maḥaṭṭatu l-ḥāfilah?", "id": "Dan di mana halte bus?"},
                    {"speaker": "Ahmad", "ar": "مَحَطَّةُ الْحَافِلَةِ أَمَامَ الْمَسْجِدِ", "latin": "Maḥaṭṭatu l-ḥāfilah amāma l-masjid", "id": "Halte bus di depan masjid"},
                    {"speaker": "Salim", "ar": "هَلْ تَرْكَبُ الْحَافِلَةَ؟", "latin": "Hal tarkabu l-ḥāfilah?", "id": "Apakah kamu naik bus?"},
                    {"speaker": "Ahmad", "ar": "نَعَمْ، أَحْيَانًا", "latin": "Naʿam, aḥyānan", "id": "Ya, kadang-kadang"},
                ],
                "mufrodat": [
                    {"ar": "كَيْفَ", "latin": "kayfa", "id": "bagaimana",
                     "exampleAr": "كَيْفَ حَالُكَ؟", "exampleLatin": "Kayfa ḥāluka?", "exampleId": "Bagaimana kabarmu?"},
                    {"ar": "أَذْهَبُ", "latin": "adhhabu", "id": "aku pergi",
                     "exampleAr": "أَذْهَبُ إِلَى الْمَسْجِدِ", "exampleLatin": "Adhhabu ilā l-masjid", "exampleId": "Aku pergi ke masjid"},
                    {"ar": "سَيَّارَة", "latin": "sayyārah", "id": "mobil",
                     "exampleAr": "السَّيَّارَةُ جَدِيدَةٌ", "exampleLatin": "As-sayyāratu jadīdah", "exampleId": "Mobilnya baru"},
                    {"ar": "دَرَّاجَة نَارِيَّة", "latin": "darrājah nāriyyah", "id": "sepeda motor",
                     "exampleAr": "الدَّرَّاجَةُ النَّارِيَّةُ سَرِيعَةٌ", "exampleLatin": "Ad-darrājatu n-nāriyyatu sarīʿah", "exampleId": "Sepeda motornya cepat"},
                    {"ar": "مَحَطَّة", "latin": "maḥaṭṭah", "id": "stasiun, halte",
                     "exampleAr": "مَحَطَّةُ الْقِطَارِ بَعِيدَةٌ", "exampleLatin": "Maḥaṭṭatu l-qiṭāri baʿīdah", "exampleId": "Stasiun keretanya jauh"},
                    {"ar": "حَافِلَة", "latin": "ḥāfilah", "id": "bus",
                     "exampleAr": "الْحَافِلَةُ كَبِيرَةٌ", "exampleLatin": "Al-ḥāfilatu kabīrah", "exampleId": "Busnya besar"},
                    {"ar": "بَعِيد", "latin": "baʿīd", "id": "jauh",
                     "exampleAr": "الْمَدْرَسَةُ بَعِيدَةٌ مِنْ بَيْتِي", "exampleLatin": "Al-madrasatu baʿīdah min baytī", "exampleId": "Sekolahnya jauh dari rumahku"},
                    {"ar": "أَمَامَ", "latin": "amāma", "id": "di depan",
                     "exampleAr": "الْمَسْجِدُ أَمَامَ الْمَدْرَسَةِ", "exampleLatin": "Al-masjidu amāma l-madrasah", "exampleId": "Masjidnya di depan sekolah"},
                    {"ar": "أَحْيَانًا", "latin": "aḥyānan", "id": "kadang-kadang",
                     "exampleAr": "أَذْهَبُ بِالْحَافِلَةِ أَحْيَانًا", "exampleLatin": "Adhhabu bil-ḥāfilah aḥyānan", "exampleId": "Aku kadang-kadang pergi naik bus"},
                    {"ar": "إِلَى", "latin": "ilā", "id": "ke (arah)",
                     "exampleAr": "أَذْهَبُ إِلَى السُّوقِ", "exampleLatin": "Adhhabu ilā s-sūq", "exampleId": "Aku pergi ke pasar"},
                ],
                "qawaid": [
                    {"titleId": "كَيْفَ untuk bertanya cara",
                     "id": "كَيْفَ berarti 'bagaimana' dan dipakai untuk menanyakan cara melakukan sesuatu, mis. cara pergi ke suatu tempat.",
                     "exampleAr": "كَيْفَ تَذْهَبُ إِلَى الْمَدْرَسَةِ؟", "exampleLatin": "Kayfa tadhhabu ilā l-madrasah?", "exampleId": "Bagaimana kamu pergi ke sekolah?"},
                    {"titleId": "بِ + alat transportasi",
                     "id": "Untuk menyebut alat yang dipakai, gunakan بِ (dengan): بِالسَّيَّارَةِ (dengan mobil), بِالدَّرَّاجَةِ النَّارِيَّةِ (dengan sepeda motor).",
                     "exampleAr": "أَذْهَبُ بِالسَّيَّارَةِ", "exampleLatin": "Adhhabu bis-sayyārah", "exampleId": "Aku pergi dengan mobil"},
                    {"titleId": "إِلَى untuk arah tujuan",
                     "id": "إِلَى berarti 'ke' dan menunjukkan arah/tujuan: إِلَى الْمَدْرَسَةِ (ke sekolah), إِلَى السُّوقِ (ke pasar).",
                     "exampleAr": "كَيْفَ تَذْهَبُ إِلَى السُّوقِ؟", "exampleLatin": "Wa kayfa tadhhabu ilā s-sūq?", "exampleId": "Dan bagaimana kamu pergi ke pasar?"},
                ],
                "tadribat": [
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Aku pergi ___ mobil", "promptAr": "أَذْهَبُ ____ السَّيَّارَةِ", "promptLatin": "Adhhabu ____ s-sayyārah",
                     "options": ["بِ", "فِي", "مِنْ", "إِلَى"], "answer": "بِ"},
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Bagaimana kamu pergi ___ sekolah?", "promptAr": "كَيْفَ تَذْهَبُ ____ الْمَدْرَسَةِ؟", "promptLatin": "Kayfa tadhhabu ____ l-madrasah?",
                     "options": ["إِلَى", "مِنْ", "بِ", "عَنْ"], "answer": "إِلَى"},
                    {"type": "translateArId", "promptAr": "أَذْهَبُ بِالدَّرَّاجَةِ النَّارِيَّةِ", "promptLatin": "Adhhabu bid-darrājati n-nāriyyah",
                     "options": ["Aku pergi dengan sepeda motor", "Aku pergi dengan mobil", "Aku pergi dengan bus", "Aku pergi dengan sepeda"], "answer": "Aku pergi dengan sepeda motor"},
                    {"type": "translateArId", "promptAr": "مَحَطَّةُ الْحَافِلَةِ أَمَامَ الْمَسْجِدِ", "promptLatin": "Maḥaṭṭatu l-ḥāfilah amāma l-masjid",
                     "options": ["Halte bus di depan masjid", "Halte bus di belakang masjid", "Halte bus dekat masjid", "Masjid di depan halte bus"], "answer": "Halte bus di depan masjid"},
                    {"type": "translateIdAr", "promptId": "Bagaimana kamu pergi ke sekolah?",
                     "options": ["كَيْفَ تَذْهَبُ إِلَى الْمَدْرَسَةِ؟", "أَيْنَ تَذْهَبُ؟", "مَاذَا تَذْهَبُ؟", "كَمْ تَذْهَبُ؟"], "answer": "كَيْفَ تَذْهَبُ إِلَى الْمَدْرَسَةِ؟"},
                    {"type": "translateIdAr", "promptId": "Apakah sekolahnya jauh?",
                     "options": ["هَلْ الْمَدْرَسَةُ بَعِيدَةٌ؟", "هَلْ الْمَدْرَسَةُ قَرِيبَةٌ؟", "أَيْنَ الْمَدْرَسَةُ؟", "كَيْفَ الْمَدْرَسَةُ؟"], "answer": "هَلْ الْمَدْرَسَةُ بَعِيدَةٌ؟"},
                    {"type": "rearrange",
                     "words": [{"ar": "أَذْهَبُ", "latin": "adhhabu"}, {"ar": "إِلَى", "latin": "ilā"}, {"ar": "السُّوقِ", "latin": "as-sūq"}, {"ar": "بِالسَّيَّارَةِ", "latin": "bis-sayyārah"}],
                     "answer": ["أَذْهَبُ", "إِلَى", "السُّوقِ", "بِالسَّيَّارَةِ"]},
                    {"type": "rearrange",
                     "words": [{"ar": "مَحَطَّةُ", "latin": "maḥaṭṭatu"}, {"ar": "الْحَافِلَةِ", "latin": "al-ḥāfilah"}, {"ar": "أَمَامَ", "latin": "amāma"}, {"ar": "الْمَسْجِدِ", "latin": "al-masjid"}],
                     "answer": ["مَحَطَّةُ", "الْحَافِلَةِ", "أَمَامَ", "الْمَسْجِدِ"]},
                ],
            },

            # ------------------------------------------------------------------
            # Lesson 2-3: Kesehatan
            # ------------------------------------------------------------------
            {
                "id": "2-3",
                "titleId": "Kesehatan",
                "titleAr": "الصِّحَّةُ",
                "muhadatsah": [
                    {"speaker": "Dokter", "ar": "مَا بِكَ يَا أَحْمَدُ؟", "latin": "Mā bika yā Aḥmad?", "id": "Ada apa denganmu, Ahmad?"},
                    {"speaker": "Ahmad", "ar": "عِنْدِي صُدَاعٌ شَدِيدٌ", "latin": "ʿindī ṣudāʿun shadīd", "id": "Aku sakit kepala yang parah"},
                    {"speaker": "Dokter", "ar": "هَلْ عِنْدَكَ حُمَّى؟", "latin": "Hal ʿindaka ḥummā?", "id": "Apakah kamu demam?"},
                    {"speaker": "Ahmad", "ar": "نَعَمْ، عِنْدِي حُمَّى أَيْضًا", "latin": "Naʿam, ʿindī ḥummā ayḍan", "id": "Ya, aku juga demam"},
                    {"speaker": "Dokter", "ar": "اِفْتَحْ فَمَكَ مِنْ فَضْلِكَ", "latin": "Iftaḥ famaka min faḍlika", "id": "Tolong buka mulutmu"},
                    {"speaker": "Dokter", "ar": "عِنْدَكَ زُكَامٌ", "latin": "ʿindaka zukām", "id": "Kamu terkena flu"},
                    {"speaker": "Ahmad", "ar": "مَاذَا أَفْعَلُ يَا طَبِيبُ؟", "latin": "Mādhā afʿalu yā ṭabīb?", "id": "Apa yang harus kulakukan, Dokter?"},
                    {"speaker": "Dokter", "ar": "اِسْتَرِحْ فِي الْبَيْتِ وَاشْرَبِ الْمَاءَ", "latin": "Istariḥ fī l-bayt wa-shrabi l-mā'", "id": "Beristirahatlah di rumah dan minumlah air"},
                    {"speaker": "Ahmad", "ar": "هَلْ آكُلُ الْفَاكِهَةَ؟", "latin": "Hal ākulu l-fākihah?", "id": "Apakah aku boleh makan buah?"},
                    {"speaker": "Dokter", "ar": "نَعَمْ، كُلِ الْفَاكِهَةَ وَاشْرَبِ الْمَاءَ كَثِيرًا", "latin": "Naʿam, kuli l-fākihah wa-shrabi l-mā'a kathīran", "id": "Ya, makanlah buah dan minumlah air banyak-banyak"},
                ],
                "mufrodat": [
                    {"ar": "طَبِيب", "latin": "ṭabīb", "id": "dokter",
                     "exampleAr": "الطَّبِيبُ فِي الْمُسْتَشْفَى", "exampleLatin": "Aṭ-ṭabību fī l-mustashfā", "exampleId": "Dokternya ada di rumah sakit"},
                    {"ar": "صُدَاع", "latin": "ṣudāʿ", "id": "sakit kepala",
                     "exampleAr": "عِنْدِي صُدَاعٌ الْيَوْمَ", "exampleLatin": "ʿindī ṣudāʿun al-yawm", "exampleId": "Hari ini aku sakit kepala"},
                    {"ar": "حُمَّى", "latin": "ḥummā", "id": "demam",
                     "exampleAr": "حُمَّى الْيَوْمِ عَالِيَةٌ", "exampleLatin": "Ḥummā l-yawmi ʿāliyah", "exampleId": "Demam hari ini tinggi"},
                    {"ar": "زُكَام", "latin": "zukām", "id": "flu, pilek",
                     "exampleAr": "الزُّكَامُ شَائِعٌ فِي الشِّتَاءِ", "exampleLatin": "Az-zukāmu shā'iʿun fī sh-shitā'", "exampleId": "Flu biasa terjadi di musim dingin"},
                    {"ar": "شَدِيد", "latin": "shadīd", "id": "parah, kuat",
                     "exampleAr": "الْبَرْدُ شَدِيدٌ الْيَوْمَ", "exampleLatin": "Al-bardu shadīdun al-yawm", "exampleId": "Dinginnya parah hari ini"},
                    {"ar": "مَاء", "latin": "mā'", "id": "air",
                     "exampleAr": "الْمَاءُ بَارِدٌ", "exampleLatin": "Al-mā'u bāridun", "exampleId": "Airnya dingin"},
                    {"ar": "فَم", "latin": "fam", "id": "mulut",
                     "exampleAr": "فَمِي صَغِيرٌ", "exampleLatin": "Famī ṣaghīrun", "exampleId": "Mulutku kecil"},
                    {"ar": "اِفْتَحْ", "latin": "iftaḥ", "id": "bukalah (perintah)",
                     "exampleAr": "اِفْتَحِ الْبَابَ مِنْ فَضْلِكَ", "exampleLatin": "Iftaḥi l-bāba min faḍlika", "exampleId": "Tolong buka pintunya"},
                    {"ar": "اِسْتَرِحْ", "latin": "istariḥ", "id": "beristirahatlah (perintah)",
                     "exampleAr": "اِسْتَرِحْ بَعْدَ الْعَمَلِ", "exampleLatin": "Istariḥ baʿda l-ʿamal", "exampleId": "Beristirahatlah setelah bekerja"},
                    {"ar": "عِنْدَ", "latin": "ʿinda", "id": "pada, punya",
                     "exampleAr": "عِنْدِي كِتَابٌ جَمِيلٌ", "exampleLatin": "ʿindī kitābun jamīlun", "exampleId": "Aku punya buku yang indah"},
                ],
                "qawaid": [
                    {"titleId": "عِنْدِي / عِنْدَكَ untuk 'punya'",
                     "id": "عِنْدَ + akhiran menunjukkan kepemilikan: عِنْدِي (aku punya), عِنْدَكَ (kamu punya). Dipakai juga untuk keadaan: عِنْدِي صُدَاعٌ = aku sakit kepala.",
                     "exampleAr": "عِنْدِي صُدَاعٌ شَدِيدٌ", "exampleLatin": "ʿindī ṣudāʿun shadīd", "exampleId": "Aku sakit kepala yang parah"},
                    {"titleId": "Kata perintah (fi'il amr)",
                     "id": "Perintah untuk satu orang laki-laki: اِفْتَحْ (bukalah), اِسْتَرِحْ (beristirahatlah), كُلْ (makanlah), اِشْرَبْ (minumlah). Sebelum kata ber-ال, huruf akhir mendapat kasrah: كُلِ الْفَاكِهَةَ.",
                     "exampleAr": "اِسْتَرِحْ فِي الْبَيْتِ وَاشْرَبِ الْمَاءَ", "exampleLatin": "Istariḥ fī l-bayt wa-shrabi l-mā'", "exampleId": "Beristirahatlah di rumah dan minumlah air"},
                    {"titleId": "مَاذَا أَفْعَلُ؟ (apa yang harus kulakukan?)",
                     "id": "مَاذَا أَفْعَلُ؟ berarti 'apa yang harus kulakukan?' — dipakai untuk meminta nasihat kepada dokter atau orang yang lebih tahu.",
                     "exampleAr": "مَاذَا أَفْعَلُ يَا طَبِيبُ؟", "exampleLatin": "Mādhā afʿalu yā ṭabīb?", "exampleId": "Apa yang harus kulakukan, Dokter?"},
                ],
                "tadribat": [
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Aku sakit kepala yang ___", "promptAr": "عِنْدِي صُدَاعٌ ____", "promptLatin": "ʿindī ṣudāʿun ____",
                     "options": ["شَدِيدٌ", "حُمَّى", "زُكَامٌ", "مَاءٌ"], "answer": "شَدِيدٌ"},
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Apakah kamu ___ (demam)?", "promptAr": "هَلْ عِنْدَكَ ____؟", "promptLatin": "Hal ʿindaka ____?",
                     "options": ["حُمَّى", "بَيْتٌ", "كِتَابٌ", "سَيَّارَةٌ"], "answer": "حُمَّى"},
                    {"type": "translateArId", "promptAr": "عِنْدِي صُدَاعٌ شَدِيدٌ", "promptLatin": "ʿindī ṣudāʿun shadīd",
                     "options": ["Aku sakit kepala yang parah", "Aku demam", "Aku terkena flu", "Aku sangat lelah"], "answer": "Aku sakit kepala yang parah"},
                    {"type": "translateArId", "promptAr": "اِسْتَرِحْ فِي الْبَيْتِ وَاشْرَبِ الْمَاءَ", "promptLatin": "Istariḥ fī l-bayt wa-shrabi l-mā'",
                     "options": ["Beristirahatlah di rumah dan minumlah air", "Tolong buka mulutmu", "Makanlah buah", "Pergilah ke sekolah"], "answer": "Beristirahatlah di rumah dan minumlah air"},
                    {"type": "translateIdAr", "promptId": "Apakah kamu demam?",
                     "options": ["هَلْ عِنْدَكَ حُمَّى؟", "هَلْ عِنْدَكَ صُدَاعٌ؟", "مَا بِكَ؟", "أَيْنَ الطَّبِيبُ؟"], "answer": "هَلْ عِنْدَكَ حُمَّى؟"},
                    {"type": "translateIdAr", "promptId": "Apa yang harus kulakukan, Dokter?",
                     "options": ["مَاذَا أَفْعَلُ يَا طَبِيبُ؟", "مَاذَا تَدْرُسُ؟", "كَيْفَ أَفْعَلُ؟", "أَيْنَ أَذْهَبُ؟"], "answer": "مَاذَا أَفْعَلُ يَا طَبِيبُ؟"},
                    {"type": "rearrange",
                     "words": [{"ar": "عِنْدِي", "latin": "ʿindī"}, {"ar": "صُدَاعٌ", "latin": "ṣudāʿun"}, {"ar": "شَدِيدٌ", "latin": "shadīd"}],
                     "answer": ["عِنْدِي", "صُدَاعٌ", "شَدِيدٌ"]},
                    {"type": "rearrange",
                     "words": [{"ar": "اِشْرَبِ", "latin": "ishrabi"}, {"ar": "الْمَاءَ", "latin": "al-mā'"}, {"ar": "كَثِيرًا", "latin": "kathīran"}],
                     "answer": ["اِشْرَبِ", "الْمَاءَ", "كَثِيرًا"]},
                ],
            },

            # ------------------------------------------------------------------
            # Lesson 2-4: Olahraga
            # ------------------------------------------------------------------
            {
                "id": "2-4",
                "titleId": "Olahraga",
                "titleAr": "الرِّيَاضَةُ",
                "muhadatsah": [
                    {"speaker": "Salim", "ar": "هَلْ تَلْعَبُ كُرَةَ الْقَدَمِ يَا أَحْمَدُ؟", "latin": "Hal talʿabu kurata l-qadam yā Aḥmad?", "id": "Apakah kamu bermain sepak bola, Ahmad?"},
                    {"speaker": "Ahmad", "ar": "نَعَمْ، أَلْعَبُ كُرَةَ الْقَدَمِ كُلَّ يَوْمٍ", "latin": "Naʿam, alʿabu kurata l-qadam kulla yawm", "id": "Ya, aku bermain sepak bola setiap hari"},
                    {"speaker": "Salim", "ar": "أَيْنَ تَلْعَبُ؟", "latin": "Ayna talʿabu?", "id": "Di mana kamu bermain?"},
                    {"speaker": "Ahmad", "ar": "أَلْعَبُ فِي الْمَلْعَبِ", "latin": "Alʿabu fī l-malʿab", "id": "Aku bermain di lapangan"},
                    {"speaker": "Salim", "ar": "مَعَ مَنْ تَلْعَبُ؟", "latin": "Maʿa man talʿabu?", "id": "Dengan siapa kamu bermain?"},
                    {"speaker": "Ahmad", "ar": "أَلْعَبُ مَعَ أَصْدِقَائِي", "latin": "Alʿabu maʿa aṣdiqā'ī", "id": "Aku bermain dengan teman-temanku"},
                    {"speaker": "Salim", "ar": "هَلْ صَدِيقُكَ يَلْعَبُ مَعَكَ؟", "latin": "Hal ṣadīquka yalʿabu maʿaka?", "id": "Apakah temanmu bermain bersamamu?"},
                    {"speaker": "Ahmad", "ar": "نَعَمْ، صَدِيقِي أَحْمَدُ يَلْعَبُ مَعِي", "latin": "Naʿam, ṣadīqī Aḥmad yalʿabu maʿī", "id": "Ya, temanku Ahmad bermain denganku"},
                    {"speaker": "Salim", "ar": "وَهَلْ تَسْبَحُ؟", "latin": "Wa hal tasbaḥu?", "id": "Dan apakah kamu berenang?"},
                    {"speaker": "Ahmad", "ar": "نَعَمْ، أَسْبَحُ فِي الْمَسْبَحِ يَوْمَ الْجُمُعَةِ", "latin": "Naʿam, asbaḥu fī l-masbaḥ yawma l-jumuʿah", "id": "Ya, aku berenang di kolam renang pada hari Jumat"},
                    {"speaker": "Salim", "ar": "مَا رِيَاضَتُكَ الْمُفَضَّلَةُ؟", "latin": "Mā riyāḍatuka l-mufaḍḍalah?", "id": "Apa olahraga favoritmu?"},
                    {"speaker": "Ahmad", "ar": "الْمُفَضَّلَةُ عِنْدِي كُرَةُ الْقَدَمِ", "latin": "Al-mufaḍḍalah ʿindī kuratu l-qadam", "id": "Favoritku sepak bola"},
                ],
                "mufrodat": [
                    {"ar": "كُرَةُ الْقَدَم", "latin": "kuratu l-qadam", "id": "sepak bola",
                     "exampleAr": "كُرَةُ الْقَدَمِ شَائِعَةٌ فِي الْعَالَمِ", "exampleLatin": "Kuratu l-qadami shā'iʿah fī l-ʿālam", "exampleId": "Sepak bola populer di dunia"},
                    {"ar": "أَلْعَبُ", "latin": "alʿabu", "id": "aku bermain",
                     "exampleAr": "أَلْعَبُ الشِّطْرَنْجَ مَعَ أَخِي", "exampleLatin": "Alʿabu sh-shṭranj maʿa akhī", "exampleId": "Aku bermain catur dengan saudaraku"},
                    {"ar": "مَلْعَب", "latin": "malʿab", "id": "lapangan",
                     "exampleAr": "الْمَلْعَبُ وَاسِعٌ", "exampleLatin": "Al-malʿabu wāsiʿun", "exampleId": "Lapangannya luas"},
                    {"ar": "مَعَ", "latin": "maʿa", "id": "dengan, bersama",
                     "exampleAr": "أَذْهَبُ إِلَى السُّوقِ مَعَ أُمِّي", "exampleLatin": "Adhhabu ilā s-sūq maʿa ummī", "exampleId": "Aku pergi ke pasar bersama ibuku"},
                    {"ar": "صَدِيق", "latin": "ṣadīq", "id": "teman (laki-laki)",
                     "exampleAr": "صَدِيقِي طَيِّبٌ", "exampleLatin": "Ṣadīqī ṭayyibun", "exampleId": "Temanku baik hati"},
                    {"ar": "أَسْبَحُ", "latin": "asbaḥu", "id": "aku berenang",
                     "exampleAr": "أَسْبَحُ فِي الْبَحْرِ", "exampleLatin": "Asbaḥu fī l-baḥr", "exampleId": "Aku berenang di laut"},
                    {"ar": "مَسْبَح", "latin": "masbaḥ", "id": "kolam renang",
                     "exampleAr": "الْمَسْبَحُ نَظِيفٌ", "exampleLatin": "Al-masbaḥu naẓīfun", "exampleId": "Kolam renangnya bersih"},
                    {"ar": "رِيَاضَة", "latin": "riyāḍah", "id": "olahraga",
                     "exampleAr": "الرِّيَاضَةُ مُفِيدَةٌ لِلصِّحَّةِ", "exampleLatin": "Ar-riyāḍatu mufīdah liṣ-ṣiḥḥah", "exampleId": "Olahraga itu baik untuk kesehatan"},
                    {"ar": "مُفَضَّل", "latin": "mufaḍḍal", "id": "favorit",
                     "exampleAr": "هٰذَا طَعَامِي الْمُفَضَّلُ", "exampleLatin": "Hādhā ṭaʿāmī l-mufaḍḍal", "exampleId": "Ini makanan favoritku"},
                    {"ar": "كُلَّ يَوْمٍ", "latin": "kulla yawm", "id": "setiap hari",
                     "exampleAr": "أَقْرَأُ الْقُرْآنَ كُلَّ يَوْمٍ", "exampleLatin": "Aqra'u l-Qur'āna kulla yawm", "exampleId": "Aku membaca Al-Qur'an setiap hari"},
                ],
                "qawaid": [
                    {"titleId": "Kata kerja sekarang dengan pelaku berbeda",
                     "id": "أَلْعَبُ (aku bermain) dan تَلْعَبُ (kamu bermain) adalah bentuk kata kerja sekarang. Awal kata berubah sesuai pelaku: أ- untuk aku, ت- untuk kamu.",
                     "exampleAr": "أَلْعَبُ كُرَةَ الْقَدَمِ كُلَّ يَوْمٍ", "exampleLatin": "Naʿam, alʿabu kurata l-qadam kulla yawm", "exampleId": "Ya, aku bermain sepak bola setiap hari"},
                    {"titleId": "مَعَ (dengan, bersama)",
                     "id": "مَعَ berarti 'dengan' atau 'bersama': مَعَ أَصْدِقَائِي (bersama teman-temanku), مَعَكَ (denganmu), مَعِي (denganku).",
                     "exampleAr": "أَلْعَبُ مَعَ أَصْدِقَائِي", "exampleLatin": "Alʿabu maʿa aṣdiqā'ī", "exampleId": "Aku bermain dengan teman-temanku"},
                    {"titleId": "Keterangan waktu: كُلَّ يَوْمٍ، يَوْمَ الْجُمُعَةِ",
                     "id": "كُلَّ يَوْمٍ berarti 'setiap hari' dan يَوْمَ الْجُمُعَةِ berarti 'pada hari Jumat' — keduanya adalah keterangan waktu (zharf zaman).",
                     "exampleAr": "أَسْبَحُ فِي الْمَسْبَحِ يَوْمَ الْجُمُعَةِ", "exampleLatin": "Naʿam, asbaḥu fī l-masbaḥ yawma l-jumuʿah", "exampleId": "Ya, aku berenang di kolam renang pada hari Jumat"},
                ],
                "tadribat": [
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Aku bermain ___ setiap hari", "promptAr": "أَلْعَبُ ____ كُلَّ يَوْمٍ", "promptLatin": "Alʿabu ____ kulla yawm",
                     "options": ["كُرَةَ الْقَدَمِ", "الْمَلْعَبَ", "الْحَافِلَةَ", "الْمَاءَ"], "answer": "كُرَةَ الْقَدَمِ"},
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Aku berenang di ___", "promptAr": "أَسْبَحُ فِي ____", "promptLatin": "Asbaḥu fī ____",
                     "options": ["الْمَسْبَحِ", "الْمَلْعَبِ", "الْمَدْرَسَةِ", "السُّوقِ"], "answer": "الْمَسْبَحِ"},
                    {"type": "translateArId", "promptAr": "أَلْعَبُ مَعَ أَصْدِقَائِي", "promptLatin": "Alʿabu maʿa aṣdiqā'ī",
                     "options": ["Aku bermain dengan teman-temanku", "Aku bermain di lapangan", "Aku berenang dengan temanku", "Aku bermain setiap hari"], "answer": "Aku bermain dengan teman-temanku"},
                    {"type": "translateArId", "promptAr": "مَا رِيَاضَتُكَ الْمُفَضَّلَةُ؟", "promptLatin": "Mā riyāḍatuka l-mufaḍḍalah?",
                     "options": ["Apa olahraga favoritmu?", "Apa permainanmu?", "Di mana kamu berolahraga?", "Kapan kamu bermain?"], "answer": "Apa olahraga favoritmu?"},
                    {"type": "translateIdAr", "promptId": "Apakah kamu bermain sepak bola?",
                     "options": ["هَلْ تَلْعَبُ كُرَةَ الْقَدَمِ؟", "هَلْ تَسْبَحُ؟", "هَلْ تَلْعَبُ فِي الْمَلْعَبِ؟", "أَيْنَ تَلْعَبُ؟"], "answer": "هَلْ تَلْعَبُ كُرَةَ الْقَدَمِ؟"},
                    {"type": "translateIdAr", "promptId": "Dengan siapa kamu bermain?",
                     "options": ["مَعَ مَنْ تَلْعَبُ؟", "أَيْنَ تَلْعَبُ؟", "مَاذَا تَلْعَبُ؟", "مَنْ مَعَكَ؟"], "answer": "مَعَ مَنْ تَلْعَبُ؟"},
                    {"type": "rearrange",
                     "words": [{"ar": "أَلْعَبُ", "latin": "alʿabu"}, {"ar": "كُرَةَ", "latin": "kurata"}, {"ar": "الْقَدَمِ", "latin": "al-qadam"}, {"ar": "كُلَّ", "latin": "kulla"}, {"ar": "يَوْمٍ", "latin": "yawm"}],
                     "answer": ["أَلْعَبُ", "كُرَةَ", "الْقَدَمِ", "كُلَّ", "يَوْمٍ"]},
                    {"type": "rearrange",
                     "words": [{"ar": "أَسْبَحُ", "latin": "asbaḥu"}, {"ar": "فِي", "latin": "fī"}, {"ar": "الْمَسْبَحِ", "latin": "al-masbaḥ"}, {"ar": "يَوْمَ", "latin": "yawma"}, {"ar": "الْجُمُعَةِ", "latin": "al-jumuʿah"}],
                     "answer": ["أَسْبَحُ", "فِي", "الْمَسْبَحِ", "يَوْمَ", "الْجُمُعَةِ"]},
                ],
            },

            # ------------------------------------------------------------------
            # Lesson 2-5: Rutinitas Harian
            # ------------------------------------------------------------------
            {
                "id": "2-5",
                "titleId": "Rutinitas Harian",
                "titleAr": "الرُّوتِينُ الْيَوْمِيُّ",
                "muhadatsah": [
                    {"speaker": "Khadijah", "ar": "مَتَى تَسْتَيْقِظِينَ يَا فَاطِمَةُ؟", "latin": "Matā tastaqīẓīna yā Fāṭimah?", "id": "Kapan kamu bangun, Fatimah?"},
                    {"speaker": "Fatimah", "ar": "أَسْتَيْقِظُ فِي السَّادِسَةِ صَبَاحًا", "latin": "Astaqīẓu fī s-sādisati ṣabāḥan", "id": "Aku bangun jam enam pagi"},
                    {"speaker": "Khadijah", "ar": "مَاذَا تَفْعَلِينَ بَعْدَ ذٰلِكَ؟", "latin": "Mādhā tafʿalīna baʿda dhālika?", "id": "Apa yang kamu lakukan setelah itu?"},
                    {"speaker": "Fatimah", "ar": "أُصَلِّي ثُمَّ أَفْطُرُ", "latin": "Uṣallī thumma afṭuru", "id": "Aku salat lalu sarapan"},
                    {"speaker": "Khadijah", "ar": "وَمَتَى تَذْهَبِينَ إِلَى الْعَمَلِ؟", "latin": "Wa matā tadhhabīna ilā l-ʿamal?", "id": "Dan kapan kamu pergi bekerja?"},
                    {"speaker": "Fatimah", "ar": "أَذْهَبُ إِلَى الْعَمَلِ فِي السَّابِعَةِ", "latin": "Adhhabu ilā l-ʿamal fī s-sābiʿah", "id": "Aku pergi bekerja jam tujuh"},
                    {"speaker": "Khadijah", "ar": "مَاذَا تَأْكُلِينَ فِي الْغَدَاءِ؟", "latin": "Mādhā ta'kulīna fī l-ghadā'?", "id": "Apa yang kamu makan saat makan siang?"},
                    {"speaker": "Fatimah", "ar": "آكُلُ الْأَرُزَّ وَالسَّمَكَ", "latin": "Ākulu l-aruzza was-samak", "id": "Aku makan nasi dan ikan"},
                    {"speaker": "Khadijah", "ar": "وَمَتَى تَرْجِعِينَ إِلَى الْبَيْتِ؟", "latin": "Wa matā tarjiʿīna ilā l-bayt?", "id": "Dan kapan kamu pulang ke rumah?"},
                    {"speaker": "Fatimah", "ar": "أَرْجِعُ إِلَى الْبَيْتِ فِي الْعَاشِرَةِ مَسَاءً", "latin": "Arjiʿu ilā l-bayt fī l-ʿāshirah masā'an", "id": "Aku pulang ke rumah jam sepuluh malam"},
                ],
                "mufrodat": [
                    {"ar": "مَتَى", "latin": "matā", "id": "kapan",
                     "exampleAr": "مَتَى تَرْجِعُ إِلَى الْبَيْتِ؟", "exampleLatin": "Matā tarjiʿu ilā l-bayt?", "exampleId": "Kapan kamu pulang ke rumah?"},
                    {"ar": "أَسْتَيْقِظُ", "latin": "astaqīẓu", "id": "aku bangun",
                     "exampleAr": "أَسْتَيْقِظُ مُبَكِّرًا", "exampleLatin": "Astaqīẓu mubakkiran", "exampleId": "Aku bangun pagi-pagi"},
                    {"ar": "السَّادِسَة", "latin": "as-sādisah", "id": "keenam, jam enam",
                     "exampleAr": "السَّاعَةُ السَّادِسَةُ صَبَاحًا", "exampleLatin": "As-sāʿatu s-sādisatu ṣabāḥan", "exampleId": "Jam enam pagi"},
                    {"ar": "صَبَاحًا", "latin": "ṣabāḥan", "id": "pada pagi hari",
                     "exampleAr": "أَقْرَأُ كُلَّ صَبَاحٍ", "exampleLatin": "Aqra'u kulla ṣabāḥin", "exampleId": "Aku membaca setiap pagi"},
                    {"ar": "أُصَلِّي", "latin": "uṣallī", "id": "aku salat",
                     "exampleAr": "أُصَلِّي فِي الْمَسْجِدِ", "exampleLatin": "Uṣallī fī l-masjid", "exampleId": "Aku salat di masjid"},
                    {"ar": "ثُمَّ", "latin": "thumma", "id": "lalu, kemudian",
                     "exampleAr": "آكُلُ ثُمَّ أَذْهَبُ", "exampleLatin": "Ākulu thumma adhhabu", "exampleId": "Aku makan lalu pergi"},
                    {"ar": "أَفْطُرُ", "latin": "afṭuru", "id": "aku sarapan",
                     "exampleAr": "أَفْطُرُ مَعَ عَائِلَتِي", "exampleLatin": "Afṭuru maʿa ʿā'ilatī", "exampleId": "Aku sarapan bersama keluargaku"},
                    {"ar": "الْعَمَل", "latin": "al-ʿamal", "id": "pekerjaan, kerja",
                     "exampleAr": "الْعَمَلُ مُهِمٌّ", "exampleLatin": "Al-ʿamalu muhimmun", "exampleId": "Pekerjaan itu penting"},
                    {"ar": "الْغَدَاء", "latin": "al-ghadā'", "id": "makan siang",
                     "exampleAr": "الْغَدَاءُ جَاهِزٌ", "exampleLatin": "Al-ghadā'u jāhizun", "exampleId": "Makan siangnya sudah siap"},
                    {"ar": "أَرْجِعُ", "latin": "arjiʿu", "id": "aku pulang",
                     "exampleAr": "أَرْجِعُ مِنَ الْعَمَلِ فِي الْمَسَاءِ", "exampleLatin": "Arjiʿu mina l-ʿamal fī l-masā'", "exampleId": "Aku pulang kerja di sore hari"},
                    {"ar": "مَسَاءً", "latin": "masā'an", "id": "pada malam hari",
                     "exampleAr": "أَنَامُ مَسَاءً", "exampleLatin": "Anāmu masā'an", "exampleId": "Aku tidur di malam hari"},
                ],
                "qawaid": [
                    {"titleId": "مَتَى untuk bertanya waktu",
                     "id": "مَتَى berarti 'kapan' dan dipakai untuk menanyakan waktu suatu kegiatan.",
                     "exampleAr": "مَتَى تَسْتَيْقِظِينَ يَا فَاطِمَةُ؟", "exampleLatin": "Matā tastaqīẓīna yā Fāṭimah?", "exampleId": "Kapan kamu bangun, Fatimah?"},
                    {"titleId": "فِي + waktu untuk menyebut jam",
                     "id": "Untuk menyebut jam, gunakan فِي + السَّاعَةُ: فِي السَّادِسَةِ (pada jam enam). Tambahkan صَبَاحًا (pagi) atau مَسَاءً (malam).",
                     "exampleAr": "أَسْتَيْقِظُ فِي السَّادِسَةِ صَبَاحًا", "exampleLatin": "Astaqīẓu fī s-sādisati ṣabāḥan", "exampleId": "Aku bangun jam enam pagi"},
                    {"titleId": "ثُمَّ untuk urutan kegiatan",
                     "id": "ثُمَّ berarti 'lalu/kemudian' dan menghubungkan dua kegiatan yang berurutan: أُصَلِّي ثُمَّ أَفْطُرُ (aku salat lalu sarapan).",
                     "exampleAr": "أُصَلِّي ثُمَّ أَفْطُرُ", "exampleLatin": "Uṣallī thumma afṭuru", "exampleId": "Aku salat lalu sarapan"},
                ],
                "tadribat": [
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Aku bangun jam ___ pagi", "promptAr": "أَسْتَيْقِظُ فِي ____ صَبَاحًا", "promptLatin": "Astaqīẓu fī ____ ṣabāḥan",
                     "options": ["السَّادِسَةِ", "الْعَاشِرَةِ", "الْمَسْجِدِ", "السُّوقِ"], "answer": "السَّادِسَةِ"},
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Aku salat ___ sarapan", "promptAr": "أُصَلِّي ____ أَفْطُرُ", "promptLatin": "Uṣallī ____ afṭuru",
                     "options": ["ثُمَّ", "فِي", "مِنْ", "عِنْدَ"], "answer": "ثُمَّ"},
                    {"type": "translateArId", "promptAr": "أَسْتَيْقِظُ فِي السَّادِسَةِ صَبَاحًا", "promptLatin": "Astaqīẓu fī s-sādisati ṣabāḥan",
                     "options": ["Aku bangun jam enam pagi", "Aku bangun jam tujuh pagi", "Aku tidur jam enam malam", "Aku pergi jam enam pagi"], "answer": "Aku bangun jam enam pagi"},
                    {"type": "translateArId", "promptAr": "آكُلُ الْأَرُزَّ وَالسَّمَكَ", "promptLatin": "Ākulu l-aruzza was-samak",
                     "options": ["Aku makan nasi dan ikan", "Aku makan roti dan susu", "Aku suka nasi dan ikan", "Aku makan saat makan siang"], "answer": "Aku makan nasi dan ikan"},
                    {"type": "translateIdAr", "promptId": "Kapan kamu bangun, Fatimah?",
                     "options": ["مَتَى تَسْتَيْقِظِينَ يَا فَاطِمَةُ؟", "أَيْنَ تَسْتَيْقِظِينَ؟", "مَاذَا تَفْعَلِينَ؟", "كَمْ تَسْتَيْقِظِينَ؟"], "answer": "مَتَى تَسْتَيْقِظِينَ يَا فَاطِمَةُ؟"},
                    {"type": "translateIdAr", "promptId": "Aku pulang ke rumah jam sepuluh malam.",
                     "options": ["أَرْجِعُ إِلَى الْبَيْتِ فِي الْعَاشِرَةِ مَسَاءً", "أَذْهَبُ إِلَى الْبَيْتِ فِي الْعَاشِرَةِ صَبَاحًا", "أَرْجِعُ إِلَى الْعَمَلِ فِي السَّابِعَةِ", "أَسْتَيْقِظُ فِي السَّادِسَةِ صَبَاحًا"], "answer": "أَرْجِعُ إِلَى الْبَيْتِ فِي الْعَاشِرَةِ مَسَاءً"},
                    {"type": "rearrange",
                     "words": [{"ar": "أُصَلِّي", "latin": "uṣallī"}, {"ar": "ثُمَّ", "latin": "thumma"}, {"ar": "أَفْطُرُ", "latin": "afṭuru"}],
                     "answer": ["أُصَلِّي", "ثُمَّ", "أَفْطُرُ"]},
                    {"type": "rearrange",
                     "words": [{"ar": "أَذْهَبُ", "latin": "adhhabu"}, {"ar": "إِلَى", "latin": "ilā"}, {"ar": "الْعَمَلِ", "latin": "al-ʿamal"}, {"ar": "فِي", "latin": "fī"}, {"ar": "السَّابِعَةِ", "latin": "as-sābiʿah"}],
                     "answer": ["أَذْهَبُ", "إِلَى", "الْعَمَلِ", "فِي", "السَّابِعَةِ"]},
                ],
            },
        ],
    }
]
