# -*- coding: utf-8 -*-
"""
Konten Level 3 — "Kehidupan Sosial & Profesional" (5 lesson).
Konten ORISINAL: ditulis dari nol, jangan menyalin dari kitab/sumber mana pun.
Skema: tools/lughoh-schema.md. Di-generate oleh tools/build_lughoh.py.
"""

LEVELS = [
    {
        "id": 3,
        "titleId": "Level 3 — Perjalanan, Pekerjaan, Media, Interaksi & Budaya",
        "titleAr": "المُسْتَوَى الثَّالِثُ",
        "lessons": [
            # ------------------------------------------------------------------
            # Lesson 3-1: Perjalanan
            # ------------------------------------------------------------------
            {
                "id": "3-1",
                "titleId": "Perjalanan",
                "titleAr": "السَّفَرُ",
                "muhadatsah": [
                    {"speaker": "Salim", "ar": "إِلَى أَيْنَ تُرِيدُ أَنْ تُسَافِرَ يَا أَحْمَدُ؟", "latin": "Ilā ayna turīdu an tusāfira yā Aḥmad?", "id": "Ke mana kamu ingin bepergian, Ahmad?"},
                    {"speaker": "Ahmad", "ar": "أُرِيدُ أَنْ أُسَافِرَ إِلَى مَكَّةَ", "latin": "Urīdu an usāfira ilā Makkah", "id": "Aku ingin bepergian ke Makkah"},
                    {"speaker": "Salim", "ar": "مَا شَاءَ اللهُ. مَتَى تُسَافِرُ؟", "latin": "Mā shā' Allāh. Matā tusāfiru?", "id": "Masya Allah. Kapan kamu pergi?"},
                    {"speaker": "Ahmad", "ar": "أُسَافِرُ فِي الشَّهْرِ الْقَادِمِ", "latin": "Usāfiru fī sh-shahri l-qādim", "id": "Aku pergi bulan depan"},
                    {"speaker": "Salim", "ar": "كَيْفَ تُسَافِرُ؟ بِالطَّائِرَةِ؟", "latin": "Kayfa tusāfiru? Biṭ-ṭā'irah?", "id": "Bagaimana kamu pergi? Naik pesawat?"},
                    {"speaker": "Ahmad", "ar": "نَعَمْ، أُسَافِرُ بِالطَّائِرَةِ", "latin": "Naʿam, usāfiru biṭ-ṭā'irah", "id": "Ya, aku pergi naik pesawat"},
                    {"speaker": "Salim", "ar": "أَيْنَ تَسْكُنُ فِي مَكَّةَ؟", "latin": "Ayna taskunu fī Makkah?", "id": "Di mana kamu tinggal di Makkah?"},
                    {"speaker": "Ahmad", "ar": "أَسْكُنُ فِي فُنْدُقٍ قَرِيبٍ مِنَ الْمَسْجِدِ الْحَرَامِ", "latin": "Askunu fī funduqin qarībin mina l-masjidi l-ḥarām", "id": "Aku tinggal di hotel dekat Masjidil Haram"},
                    {"speaker": "Salim", "ar": "مَاذَا تَزُورُ هُنَاكَ؟", "latin": "Mādhā tazūru hunāka?", "id": "Apa yang kamu kunjungi di sana?"},
                    {"speaker": "Ahmad", "ar": "أَزُورُ الْكَعْبَةَ وَأُصَلِّي فِيهَا", "latin": "Azūru l-kaʿbah wa-uṣallī fīhā", "id": "Aku mengunjungi Ka'bah dan salat di sana"},
                ],
                "mufrodat": [
                    {"ar": "أُسَافِرُ", "latin": "usāfiru", "id": "aku bepergian",
                     "exampleAr": "أُسَافِرُ إِلَى بَالِي كُلَّ سَنَةٍ", "exampleLatin": "Usāfiru ilā Bālī kulla sanah", "exampleId": "Aku bepergian ke Bali setiap tahun"},
                    {"ar": "أُرِيدُ", "latin": "urīdu", "id": "aku ingin",
                     "exampleAr": "أُرِيدُ كِتَابًا جَدِيدًا", "exampleLatin": "Urīdu kitāban jadīdan", "exampleId": "Aku ingin buku baru"},
                    {"ar": "أَنْ", "latin": "an", "id": "untuk, agar (penghubung)",
                     "exampleAr": "أُرِيدُ أَنْ أَتَعَلَّمَ الْعَرَبِيَّةَ", "exampleLatin": "Urīdu an ataʿallama l-ʿarabiyyah", "exampleId": "Aku ingin belajar bahasa Arab"},
                    {"ar": "مَكَّة", "latin": "Makkah", "id": "Makkah",
                     "exampleAr": "مَكَّةُ مَدِينَةٌ مُقَدَّسَةٌ", "exampleLatin": "Makkatu madīnatun muqaddasah", "exampleId": "Makkah kota yang suci"},
                    {"ar": "الشَّهْر", "latin": "ash-shahr", "id": "bulan (penanggalan)",
                     "exampleAr": "الشَّهْرُ الْقَادِمُ شَهْرُ رَمَضَانَ", "exampleLatin": "Ash-shahru l-qādimu shahru Ramaḍān", "exampleId": "Bulan depan adalah bulan Ramadan"},
                    {"ar": "قَادِم", "latin": "qādim", "id": "yang akan datang",
                     "exampleAr": "فِي الْأُسْبُوعِ الْقَادِمِ", "exampleLatin": "Fī l-usbūʿi l-qādim", "exampleId": "Pada minggu yang akan datang"},
                    {"ar": "طَائِرَة", "latin": "ṭā'irah", "id": "pesawat",
                     "exampleAr": "الطَّائِرَةُ سَرِيعَةٌ", "exampleLatin": "Aṭ-ṭā'iratu sarīʿah", "exampleId": "Pesawatnya cepat"},
                    {"ar": "أَسْكُنُ", "latin": "askunu", "id": "aku tinggal",
                     "exampleAr": "أَسْكُنُ فِي جَاكَرْتَا", "exampleLatin": "Askunu fī Jākartā", "exampleId": "Aku tinggal di Jakarta"},
                    {"ar": "فُنْدُق", "latin": "funduq", "id": "hotel",
                     "exampleAr": "الْفُنْدُقُ قَرِيبٌ مِنَ الْبَحْرِ", "exampleLatin": "Al-funduqu qarībun mina l-baḥr", "exampleId": "Hotelnya dekat dengan laut"},
                    {"ar": "أَزُورُ", "latin": "azūru", "id": "aku mengunjungi",
                     "exampleAr": "أَزُورُ جَدَّتِي فِي الْعِيدِ", "exampleLatin": "Azūru jaddatī fī l-ʿīd", "exampleId": "Aku mengunjungi nenekku pada hari raya"},
                ],
                "qawaid": [
                    {"titleId": "أُرِيدُ أَنْ + kata kerja (ingin melakukan ...)",
                     "id": "Untuk menyatakan keinginan: أُرِيدُ (aku ingin) diikuti أَنْ lalu kata kerja. Contoh: أُرِيدُ أَنْ أُسَافِرَ = aku ingin bepergian.",
                     "exampleAr": "أُرِيدُ أَنْ أُسَافِرَ إِلَى مَكَّةَ", "exampleLatin": "Urīdu an usāfira ilā Makkah", "exampleId": "Aku ingin bepergian ke Makkah"},
                    {"titleId": "بِ + alat untuk cara bepergian",
                     "id": "Cara bepergian disebut dengan بِ + alat: بِالطَّائِرَةِ (naik pesawat), بِالسَّفِينَةِ (naik kapal).",
                     "exampleAr": "أُسَافِرُ بِالطَّائِرَةِ", "exampleLatin": "Naʿam, usāfiru biṭ-ṭā'irah", "exampleId": "Ya, aku pergi naik pesawat"},
                    {"titleId": "Kata sifat ber-ال (na't ma'rifah)",
                     "id": "الشَّهْرُ الْقَادِمُ = bulan yang akan datang. Kata benda dan kata sifat sama-sama ber-ال. Kata sifat juga bisa tanpa ال setelah kata tak tentu: فُنْدُقٌ قَرِيبٌ.",
                     "exampleAr": "أُسَافِرُ فِي الشَّهْرِ الْقَادِمِ", "exampleLatin": "Usāfiru fī sh-shahri l-qādim", "exampleId": "Aku pergi bulan depan"},
                ],
                "tadribat": [
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Aku ingin ___ ke Makkah", "promptAr": "أُرِيدُ أَنْ ____ إِلَى مَكَّةَ", "promptLatin": "Urīdu an ____ ilā Makkah",
                     "options": ["أُسَافِرَ", "أَسْكُنَ", "آكُلَ", "أَذْهَبَ"], "answer": "أُسَافِرَ"},
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Aku tinggal di ___ dekat masjid", "promptAr": "أَسْكُنُ فِي ____ قَرِيبٍ مِنَ الْمَسْجِدِ", "promptLatin": "Askunu fī ____ qarībin mina l-masjid",
                     "options": ["فُنْدُقٍ", "بَيْتٍ", "مَكْتَبٍ", "مَلْعَبٍ"], "answer": "فُنْدُقٍ"},
                    {"type": "translateArId", "promptAr": "أُرِيدُ أَنْ أُسَافِرَ إِلَى مَكَّةَ", "promptLatin": "Urīdu an usāfira ilā Makkah",
                     "options": ["Aku ingin bepergian ke Makkah", "Aku ingin tinggal di Makkah", "Aku pergi ke Makkah", "Aku suka Makkah"], "answer": "Aku ingin bepergian ke Makkah"},
                    {"type": "translateArId", "promptAr": "أَسْكُنُ فِي فُنْدُقٍ قَرِيبٍ مِنَ الْمَسْجِدِ الْحَرَامِ", "promptLatin": "Askunu fī funduqin qarībin mina l-masjidi l-ḥarām",
                     "options": ["Aku tinggal di hotel dekat Masjidil Haram", "Aku tinggal di rumah dekat masjid", "Hotelnya dekat Masjidil Haram", "Aku pergi ke hotel"], "answer": "Aku tinggal di hotel dekat Masjidil Haram"},
                    {"type": "translateIdAr", "promptId": "Ke mana kamu ingin bepergian?",
                     "options": ["إِلَى أَيْنَ تُرِيدُ أَنْ تُسَافِرَ؟", "مَتَى تُسَافِرُ؟", "كَيْفَ تُسَافِرُ؟", "أَيْنَ تَسْكُنُ؟"], "answer": "إِلَى أَيْنَ تُرِيدُ أَنْ تُسَافِرَ؟"},
                    {"type": "translateIdAr", "promptId": "Kapan kamu pergi?",
                     "options": ["مَتَى تُسَافِرُ؟", "أَيْنَ تُسَافِرُ؟", "كَمْ تُسَافِرُ؟", "مَاذَا تُسَافِرُ؟"], "answer": "مَتَى تُسَافِرُ؟"},
                    {"type": "rearrange",
                     "words": [{"ar": "أُرِيدُ", "latin": "urīdu"}, {"ar": "أَنْ", "latin": "an"}, {"ar": "أُسَافِرَ", "latin": "usāfira"}, {"ar": "إِلَى", "latin": "ilā"}, {"ar": "مَكَّةَ", "latin": "Makkah"}],
                     "answer": ["أُرِيدُ", "أَنْ", "أُسَافِرَ", "إِلَى", "مَكَّةَ"]},
                    {"type": "rearrange",
                     "words": [{"ar": "أُسَافِرُ", "latin": "usāfiru"}, {"ar": "فِي", "latin": "fī"}, {"ar": "الشَّهْرِ", "latin": "ash-shahr"}, {"ar": "الْقَادِمِ", "latin": "al-qādim"}],
                     "answer": ["أُسَافِرُ", "فِي", "الشَّهْرِ", "الْقَادِمِ"]},
                ],
            },

            # ------------------------------------------------------------------
            # Lesson 3-2: Pekerjaan
            # ------------------------------------------------------------------
            {
                "id": "3-2",
                "titleId": "Pekerjaan",
                "titleAr": "العَمَلُ",
                "muhadatsah": [
                    {"speaker": "Salim", "ar": "مَا عَمَلُكَ يَا أَحْمَدُ؟", "latin": "Mā ʿamaluka yā Aḥmad?", "id": "Apa pekerjaanmu, Ahmad?"},
                    {"speaker": "Ahmad", "ar": "أَنَا مُهَنْدِسٌ", "latin": "Anā muhandis", "id": "Aku seorang insinyur"},
                    {"speaker": "Salim", "ar": "أَيْنَ تَعْمَلُ؟", "latin": "Ayna taʿmalu?", "id": "Di mana kamu bekerja?"},
                    {"speaker": "Ahmad", "ar": "أَعْمَلُ فِي شَرِكَةٍ كَبِيرَةٍ", "latin": "Aʿmalu fī sharikatin kabīrah", "id": "Aku bekerja di perusahaan besar"},
                    {"speaker": "Salim", "ar": "مَاذَا تَفْعَلُ فِي الشَّرِكَةِ؟", "latin": "Mādhā tafʿalu fī sh-sharikah?", "id": "Apa yang kamu lakukan di perusahaan?"},
                    {"speaker": "Ahmad", "ar": "أُدِيرُ مَشْرُوعَاتٍ كَبِيرَةً", "latin": "Udīru mashrūʿātin kabīrah", "id": "Aku mengelola proyek-proyek besar"},
                    {"speaker": "Salim", "ar": "وَهَلْ تُحِبُّ عَمَلَكَ؟", "latin": "Wa hal tuḥibbu ʿamalaka?", "id": "Dan apakah kamu suka pekerjaanmu?"},
                    {"speaker": "Ahmad", "ar": "نَعَمْ، أُحِبُّ عَمَلِي كَثِيرًا", "latin": "Naʿam, uḥibbu ʿamalī kathīran", "id": "Ya, aku sangat suka pekerjaanku"},
                    {"speaker": "Salim", "ar": "مَتَى تَبْدَأُ الْعَمَلَ؟", "latin": "Matā tabda'u l-ʿamal?", "id": "Kapan kamu mulai bekerja?"},
                    {"speaker": "Ahmad", "ar": "أَبْدَأُ الْعَمَلَ فِي الثَّامِنَةِ صَبَاحًا", "latin": "Abda'u l-ʿamal fī th-thāminah ṣabāḥan", "id": "Aku mulai bekerja jam delapan pagi"},
                ],
                "mufrodat": [
                    {"ar": "عَمَل", "latin": "ʿamal", "id": "pekerjaan",
                     "exampleAr": "عَمَلِي فِي مَكْتَبٍ كَبِيرٍ", "exampleLatin": "ʿamalī fī maktabin kabīr", "exampleId": "Pekerjaanku di kantor besar"},
                    {"ar": "مُهَنْدِس", "latin": "muhandis", "id": "insinyur",
                     "exampleAr": "الْمُهَنْدِسُ يَبْنِي الْجُسُورَ", "exampleLatin": "Al-muhandisu yabnī l-jusūr", "exampleId": "Insinyur membangun jembatan"},
                    {"ar": "أَعْمَلُ", "latin": "aʿmalu", "id": "aku bekerja",
                     "exampleAr": "أَعْمَلُ مِنَ الصَّبَاحِ إِلَى الْمَسَاءِ", "exampleLatin": "Aʿmalu mina ṣ-ṣabāḥ ilā l-masā'", "exampleId": "Aku bekerja dari pagi sampai sore"},
                    {"ar": "شَرِكَة", "latin": "sharikah", "id": "perusahaan",
                     "exampleAr": "الشَّرِكَةُ كَبِيرَةٌ", "exampleLatin": "Ash-sharikatu kabīrah", "exampleId": "Perusahaannya besar"},
                    {"ar": "مَشْرُوع", "latin": "mashrūʿ", "id": "proyek",
                     "exampleAr": "هٰذَا مَشْرُوعٌ مُهِمٌّ", "exampleLatin": "Hādhā mashrūʿun muhimmun", "exampleId": "Ini proyek yang penting"},
                    {"ar": "أُدِيرُ", "latin": "udīru", "id": "aku mengelola",
                     "exampleAr": "أُدِيرُ مَكْتَبًا صَغِيرًا", "exampleLatin": "Udīru maktaban ṣaghīran", "exampleId": "Aku mengelola kantor kecil"},
                    {"ar": "أَبْدَأُ", "latin": "abda'u", "id": "aku mulai",
                     "exampleAr": "أَبْدَأُ الدِّرَاسَةَ فِي السَّبْتَمْبَر", "exampleLatin": "Abda'u d-dirāsah fī s-sabtambar", "exampleId": "Aku mulai belajar pada bulan September"},
                    {"ar": "الثَّامِنَة", "latin": "ath-thāminah", "id": "kedelapan, jam delapan",
                     "exampleAr": "السَّاعَةُ الثَّامِنَةُ مَسَاءً", "exampleLatin": "As-sāʿatu th-thāminatu masā'an", "exampleId": "Jam delapan malam"},
                    {"ar": "أُحِبُّ", "latin": "uḥibbu", "id": "aku suka",
                     "exampleAr": "أُحِبُّ عَمَلِي", "exampleLatin": "Uḥibbu ʿamalī", "exampleId": "Aku suka pekerjaanku"},
                ],
                "qawaid": [
                    {"titleId": "Nama profesi sebagai khabar",
                     "id": "Untuk menyebut profesi: أَنَا + nama profesi. أَنَا مُهَنْدِسٌ = aku seorang insinyur. Profesi lain: طَبِيبٌ (dokter), مُدَرِّسٌ (guru), تَاجِرٌ (pedagang).",
                     "exampleAr": "أَنَا مُهَنْدِسٌ", "exampleLatin": "Anā muhandis", "exampleId": "Aku seorang insinyur"},
                    {"titleId": "فِي + tempat bekerja",
                     "id": "Tempat bekerja disebut dengan فِي: أَعْمَلُ فِي شَرِكَةٍ = aku bekerja di sebuah perusahaan.",
                     "exampleAr": "أَعْمَلُ فِي شَرِكَةٍ كَبِيرَةٍ", "exampleLatin": "Aʿmalu fī sharikatin kabīrah", "exampleId": "Aku bekerja di perusahaan besar"},
                    {"titleId": "مَاذَا تَفْعَلُ؟ (apa yang kamu lakukan?)",
                     "id": "مَاذَا تَفْعَلُ؟ menanyakan kegiatan. Jawab dengan kata kerja: أُدِيرُ مَشْرُوعَاتٍ = aku mengelola proyek-proyek.",
                     "exampleAr": "مَاذَا تَفْعَلُ فِي الشَّرِكَةِ؟", "exampleLatin": "Mādhā tafʿalu fī sh-sharikah?", "exampleId": "Apa yang kamu lakukan di perusahaan?"},
                ],
                "tadribat": [
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Aku seorang ___", "promptAr": "أَنَا ____", "promptLatin": "Anā ____",
                     "options": ["مُهَنْدِسٌ", "شَرِكَةٌ", "عَمَلٌ", "مَشْرُوعٌ"], "answer": "مُهَنْدِسٌ"},
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Aku bekerja di ___ besar", "promptAr": "أَعْمَلُ فِي ____ كَبِيرَةٍ", "promptLatin": "Aʿmalu fī ____ kabīrah",
                     "options": ["شَرِكَةٍ", "بَيْتٍ", "مَدْرَسَةٍ", "مَلْعَبٍ"], "answer": "شَرِكَةٍ"},
                    {"type": "translateArId", "promptAr": "أَنَا مُهَنْدِسٌ", "promptLatin": "Anā muhandis",
                     "options": ["Aku seorang insinyur", "Aku seorang dokter", "Aku seorang guru", "Aku seorang pedagang"], "answer": "Aku seorang insinyur"},
                    {"type": "translateArId", "promptAr": "أُحِبُّ عَمَلِي كَثِيرًا", "promptLatin": "Uḥibbu ʿamalī kathīran",
                     "options": ["Aku sangat suka pekerjaanku", "Aku suka perusahaanku", "Pekerjaanku besar", "Aku bekerja sangat banyak"], "answer": "Aku sangat suka pekerjaanku"},
                    {"type": "translateIdAr", "promptId": "Apa pekerjaanmu, Ahmad?",
                     "options": ["مَا عَمَلُكَ يَا أَحْمَدُ؟", "مَا اسْمُكَ؟", "أَيْنَ تَعْمَلُ؟", "مَتَى تَبْدَأُ الْعَمَلَ؟"], "answer": "مَا عَمَلُكَ يَا أَحْمَدُ؟"},
                    {"type": "translateIdAr", "promptId": "Di mana kamu bekerja?",
                     "options": ["أَيْنَ تَعْمَلُ؟", "كَيْفَ تَعْمَلُ؟", "مَاذَا تَعْمَلُ؟", "مَنْ يَعْمَلُ؟"], "answer": "أَيْنَ تَعْمَلُ؟"},
                    {"type": "rearrange",
                     "words": [{"ar": "أَعْمَلُ", "latin": "aʿmalu"}, {"ar": "فِي", "latin": "fī"}, {"ar": "شَرِكَةٍ", "latin": "sharikah"}, {"ar": "كَبِيرَةٍ", "latin": "kabīrah"}],
                     "answer": ["أَعْمَلُ", "فِي", "شَرِكَةٍ", "كَبِيرَةٍ"]},
                    {"type": "rearrange",
                     "words": [{"ar": "أَبْدَأُ", "latin": "abda'u"}, {"ar": "الْعَمَلَ", "latin": "al-ʿamal"}, {"ar": "فِي", "latin": "fī"}, {"ar": "الثَّامِنَةِ", "latin": "ath-thāminah"}, {"ar": "صَبَاحًا", "latin": "ṣabāḥan"}],
                     "answer": ["أَبْدَأُ", "الْعَمَلَ", "فِي", "الثَّامِنَةِ", "صَبَاحًا"]},
                ],
            },

            # ------------------------------------------------------------------
            # Lesson 3-3: Media
            # ------------------------------------------------------------------
            {
                "id": "3-3",
                "titleId": "Media",
                "titleAr": "الوَسَائِطُ",
                "muhadatsah": [
                    {"speaker": "Khadijah", "ar": "مَاذَا تَفْعَلِينَ فِي الْمَسَاءِ يَا فَاطِمَةُ؟", "latin": "Mādhā tafʿalīna fī l-masā' yā Fāṭimah?", "id": "Apa yang kamu lakukan di malam hari, Fatimah?"},
                    {"speaker": "Fatimah", "ar": "أُشَاهِدُ التِّلْفَازَ مَعَ عَائِلَتِي", "latin": "Ushāhidu t-tilfāz maʿa ʿā'ilatī", "id": "Aku menonton televisi bersama keluargaku"},
                    {"speaker": "Khadijah", "ar": "مَاذَا تُشَاهِدِينَ؟", "latin": "Mādhā tushāhidīna?", "id": "Apa yang kamu tonton?"},
                    {"speaker": "Fatimah", "ar": "أُشَاهِدُ الْأَخْبَارَ ثُمَّ الْفِلْمَ", "latin": "Ushāhidu l-akhbār thumma l-film", "id": "Aku menonton berita lalu film"},
                    {"speaker": "Khadijah", "ar": "هَلْ تَقْرَئِينَ الْجَرِيدَةَ؟", "latin": "Hal taqra'īna l-jarīdah?", "id": "Apakah kamu membaca koran?"},
                    {"speaker": "Fatimah", "ar": "نَعَمْ، أَقْرَأُ الْجَرِيدَةَ كُلَّ صَبَاحٍ", "latin": "Naʿam, aqra'u l-jarīdah kulla ṣabāḥ", "id": "Ya, aku membaca koran setiap pagi"},
                    {"speaker": "Khadijah", "ar": "وَمَاذَا تَقْرَئِينَ فِي الْجَرِيدَةِ؟", "latin": "Wa mādhā taqra'īna fī l-jarīdah?", "id": "Dan apa yang kamu baca di koran?"},
                    {"speaker": "Fatimah", "ar": "أَقْرَأُ الْأَخْبَارَ وَالْمَقَالَاتِ", "latin": "Aqra'u l-akhbār wal-maqālāt", "id": "Aku membaca berita dan artikel-artikel"},
                    {"speaker": "Khadijah", "ar": "هَلْ تَسْتَمِعِينَ إِلَى الرَّادْيُو؟", "latin": "Hal tastamiʿīna ilā r-rādyū?", "id": "Apakah kamu mendengarkan radio?"},
                    {"speaker": "Fatimah", "ar": "نَعَمْ، أَسْتَمِعُ إِلَى الرَّادْيُو فِي السَّيَّارَةِ", "latin": "Naʿam, astamiʿu ilā r-rādyū fī s-sayyārah", "id": "Ya, aku mendengarkan radio di mobil"},
                ],
                "mufrodat": [
                    {"ar": "أُشَاهِدُ", "latin": "ushāhidu", "id": "aku menonton",
                     "exampleAr": "أُشَاهِدُ الْفِلْمَ مَعَ أَصْدِقَائِي", "exampleLatin": "Ushāhidu l-filma maʿa aṣdiqā'ī", "exampleId": "Aku menonton film bersama teman-temanku"},
                    {"ar": "التِّلْفَاز", "latin": "at-tilfāz", "id": "televisi",
                     "exampleAr": "التِّلْفَازُ فِي غُرْفَةِ الْجُلُوسِ", "exampleLatin": "At-tilfāzu fī ghurfati l-julūs", "exampleId": "Televisinya ada di ruang tamu"},
                    {"ar": "الْأَخْبَار", "latin": "al-akhbār", "id": "berita",
                     "exampleAr": "الْأَخْبَارُ مُهِمَّةٌ كُلَّ يَوْمٍ", "exampleLatin": "Al-akhbāru muhimmah kulla yawm", "exampleId": "Berita itu penting setiap hari"},
                    {"ar": "فِلْم", "latin": "film", "id": "film",
                     "exampleAr": "الْفِلْمُ جَمِيلٌ", "exampleLatin": "Al-filmu jamīlun", "exampleId": "Filmnya bagus"},
                    {"ar": "أَقْرَأُ", "latin": "aqra'u", "id": "aku membaca",
                     "exampleAr": "أَقْرَأُ كِتَابًا كُلَّ أُسْبُوعٍ", "exampleLatin": "Aqra'u kitāban kulla usbūʿ", "exampleId": "Aku membaca satu buku setiap minggu"},
                    {"ar": "الْجَرِيدَة", "latin": "al-jarīdah", "id": "koran",
                     "exampleAr": "الْجَرِيدَةُ عَلَى الطَّاوِلَةِ", "exampleLatin": "Al-jarīdatu ʿalā ṭ-ṭāwilah", "exampleId": "Korannya ada di atas meja"},
                    {"ar": "مَقَال", "latin": "maqāl", "id": "artikel",
                     "exampleAr": "قَرَأْتُ مَقَالًا مُفِيدًا", "exampleLatin": "Qara'tu maqālan mufīdan", "exampleId": "Aku membaca artikel yang bermanfaat"},
                    {"ar": "أَسْتَمِعُ", "latin": "astamiʿu", "id": "aku mendengarkan",
                     "exampleAr": "أَسْتَمِعُ إِلَى الْقُرْآنِ كَثِيرًا", "exampleLatin": "Astamiʿu ilā l-Qur'āni kathīran", "exampleId": "Aku sering mendengarkan Al-Qur'an"},
                    {"ar": "الرَّادْيُو", "latin": "ar-rādyū", "id": "radio",
                     "exampleAr": "الرَّادْيُو قَدِيمٌ", "exampleLatin": "Ar-rādyū qadīmun", "exampleId": "Radionya tua"},
                    {"ar": "صَبَاح", "latin": "ṣabāḥ", "id": "pagi",
                     "exampleAr": "كُلَّ صَبَاحٍ أَشْرَبُ الشَّايَ", "exampleLatin": "Kulla ṣabāḥin ashrabu sh-shāy", "exampleId": "Setiap pagi aku minum teh"},
                ],
                "qawaid": [
                    {"titleId": "Kata kerja media: menonton, membaca, mendengarkan",
                     "id": "أُشَاهِدُ (menonton), أَقْرَأُ (membaca), أَسْتَمِعُ (mendengarkan). Bentuk perempuan: تُشَاهِدِينَ، تَقْرَئِينَ، تَسْتَمِعِينَ.",
                     "exampleAr": "أُشَاهِدُ الْأَخْبَارَ ثُمَّ الْفِلْمَ", "exampleLatin": "Ushāhidu l-akhbār thumma l-film", "exampleId": "Aku menonton berita lalu film"},
                    {"titleId": "أَسْتَمِعُ إِلَى (mendengarkan ...)",
                     "id": "Kata kerja 'mendengarkan' diikuti إِلَى: أَسْتَمِعُ إِلَى الرَّادْيُو = aku mendengarkan radio.",
                     "exampleAr": "أَسْتَمِعُ إِلَى الرَّادْيُو فِي السَّيَّارَةِ", "exampleLatin": "Naʿam, astamiʿu ilā r-rādyū fī s-sayyārah", "exampleId": "Ya, aku mendengarkan radio di mobil"},
                    {"titleId": "كُلَّ صَبَاحٍ (setiap pagi)",
                     "id": "كُلَّ + waktu = setiap ...: كُلَّ صَبَاحٍ (setiap pagi), كُلَّ يَوْمٍ (setiap hari), كُلَّ أُسْبُوعٍ (setiap minggu).",
                     "exampleAr": "أَقْرَأُ الْجَرِيدَةَ كُلَّ صَبَاحٍ", "exampleLatin": "Naʿam, aqra'u l-jarīdah kulla ṣabāḥ", "exampleId": "Ya, aku membaca koran setiap pagi"},
                ],
                "tadribat": [
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Aku menonton ___ bersama keluargaku", "promptAr": "أُشَاهِدُ ____ مَعَ عَائِلَتِي", "promptLatin": "Ushāhidu ____ maʿa ʿā'ilatī",
                     "options": ["التِّلْفَازَ", "الْجَرِيدَةَ", "الرَّادْيُو", "الْمَقَالَاتِ"], "answer": "التِّلْفَازَ"},
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Aku membaca koran setiap ___", "promptAr": "أَقْرَأُ الْجَرِيدَةَ كُلَّ ____", "promptLatin": "Aqra'u l-jarīdah kulla ____",
                     "options": ["صَبَاحٍ", "مَسَاءٍ", "يَوْمٍ", "شَهْرٍ"], "answer": "صَبَاحٍ"},
                    {"type": "translateArId", "promptAr": "أُشَاهِدُ الْأَخْبَارَ ثُمَّ الْفِلْمَ", "promptLatin": "Ushāhidu l-akhbār thumma l-film",
                     "options": ["Aku menonton berita lalu film", "Aku menonton film lalu berita", "Aku membaca berita dan artikel", "Aku mendengarkan radio"], "answer": "Aku menonton berita lalu film"},
                    {"type": "translateArId", "promptAr": "أَسْتَمِعُ إِلَى الرَّادْيُو فِي السَّيَّارَةِ", "promptLatin": "Astamiʿu ilā r-rādyū fī s-sayyārah",
                     "options": ["Aku mendengarkan radio di mobil", "Aku menonton TV di mobil", "Aku mendengarkan radio di rumah", "Aku membaca koran di mobil"], "answer": "Aku mendengarkan radio di mobil"},
                    {"type": "translateIdAr", "promptId": "Apakah kamu membaca koran?",
                     "options": ["هَلْ تَقْرَئِينَ الْجَرِيدَةَ؟", "هَلْ تَسْتَمِعِينَ إِلَى الرَّادْيُو؟", "مَاذَا تَقْرَئِينَ؟", "أَيْنَ الْجَرِيدَةُ؟"], "answer": "هَلْ تَقْرَئِينَ الْجَرِيدَةَ؟"},
                    {"type": "translateIdAr", "promptId": "Apa yang kamu tonton?",
                     "options": ["مَاذَا تُشَاهِدِينَ؟", "مَاذَا تَقْرَئِينَ؟", "مَاذَا تَسْتَمِعِينَ؟", "مَاذَا تَفْعَلِينَ؟"], "answer": "مَاذَا تُشَاهِدِينَ؟"},
                    {"type": "rearrange",
                     "words": [{"ar": "أُشَاهِدُ", "latin": "ushāhidu"}, {"ar": "التِّلْفَازَ", "latin": "at-tilfāz"}, {"ar": "مَعَ", "latin": "maʿa"}, {"ar": "عَائِلَتِي", "latin": "ʿā'ilatī"}],
                     "answer": ["أُشَاهِدُ", "التِّلْفَازَ", "مَعَ", "عَائِلَتِي"]},
                    {"type": "rearrange",
                     "words": [{"ar": "أَقْرَأُ", "latin": "aqra'u"}, {"ar": "الْجَرِيدَةَ", "latin": "al-jarīdah"}, {"ar": "كُلَّ", "latin": "kulla"}, {"ar": "صَبَاحٍ", "latin": "ṣabāḥ"}],
                     "answer": ["أَقْرَأُ", "الْجَرِيدَةَ", "كُلَّ", "صَبَاحٍ"]},
                ],
            },

            # ------------------------------------------------------------------
            # Lesson 3-4: Interaksi Sosial
            # ------------------------------------------------------------------
            {
                "id": "3-4",
                "titleId": "Interaksi Sosial",
                "titleAr": "التَّوَاصُلُ الِاجْتِمَاعِيُّ",
                "muhadatsah": [
                    {"speaker": "Salim", "ar": "السَّلَامُ عَلَيْكُمْ يَا أُسْتَاذُ", "latin": "As-salāmu ʿalaikum yā ustādh", "id": "Semoga keselamatan, Ustadz"},
                    {"speaker": "Ustadz", "ar": "وَعَلَيْكُمُ السَّلَامُ وَرَحْمَةُ اللهِ", "latin": "Wa ʿalaikumus-salāmu wa-raḥmatu llāh", "id": "Dan semoga keselamatan dan rahmat Allah"},
                    {"speaker": "Salim", "ar": "كَيْفَ حَالُكَ الْيَوْمَ؟", "latin": "Kayfa ḥāluka l-yawm?", "id": "Bagaimana kabarmu hari ini?"},
                    {"speaker": "Ustadz", "ar": "أَنَا بِخَيْرٍ، وَالْحَمْدُ لِلَّهِ. وَأَنْتَ؟", "latin": "Anā bikhayrin, wal-ḥamdu lillāh. Wa anta?", "id": "Aku baik, alhamdulillah. Dan kamu?"},
                    {"speaker": "Salim", "ar": "أَنَا بِخَيْرٍ أَيْضًا", "latin": "Anā bikhayrin ayḍan", "id": "Aku juga baik"},
                    {"speaker": "Salim", "ar": "هٰذِهِ هَدِيَّةٌ لَكَ يَا أُسْتَاذُ", "latin": "Hādhihi hadiyyatun laka yā ustādh", "id": "Ini hadiah untukmu, Ustadz"},
                    {"speaker": "Ustadz", "ar": "شُكْرًا جَزِيلًا. مَا هٰذِهِ الْهَدِيَّةُ؟", "latin": "Shukran jazīlan. Mā hādhihi l-hadiyyah?", "id": "Terima kasih banyak. Hadiah apa ini?"},
                    {"speaker": "Salim", "ar": "هٰذِهِ سَاعَةٌ جَمِيلَةٌ", "latin": "Hādhihi sāʿatun jamīlah", "id": "Ini jam tangan yang indah"},
                    {"speaker": "Ustadz", "ar": "مَا أَجْمَلَهَا! شُكْرًا يَا سَالِمُ", "latin": "Mā ajmalahā! Shukran yā Sālim", "id": "Alangkah indahnya! Terima kasih, Salim"},
                    {"speaker": "Salim", "ar": "الْعَفْوُ يَا أُسْتَاذُ", "latin": "Al-ʿafwu yā ustādh", "id": "Sama-sama, Ustadz"},
                ],
                "mufrodat": [
                    {"ar": "أُسْتَاذ", "latin": "ustādh", "id": "ustadz, guru",
                     "exampleAr": "الْأُسْتَاذُ يُعَلِّمُنَا الْعَرَبِيَّةَ", "exampleLatin": "Al-ustādhu yuʿallimunā l-ʿarabiyyah", "exampleId": "Ustadz mengajari kami bahasa Arab"},
                    {"ar": "رَحْمَة", "latin": "raḥmah", "id": "rahmat",
                     "exampleAr": "رَحْمَةُ اللهِ وَاسِعَةٌ", "exampleLatin": "Raḥmatu llāhi wāsiʿah", "exampleId": "Rahmat Allah itu luas"},
                    {"ar": "حَال", "latin": "ḥāl", "id": "keadaan, kabar",
                     "exampleAr": "حَالُ عَائِلَتِي جَيِّدٌ", "exampleLatin": "Ḥālu ʿā'ilatī jayyid", "exampleId": "Keadaan keluargaku baik"},
                    {"ar": "بِخَيْر", "latin": "bikhayr", "id": "baik-baik",
                     "exampleAr": "أَنَا بِخَيْرٍ وَالْحَمْدُ لِلَّهِ", "exampleLatin": "Anā bikhayrin wal-ḥamdu lillāh", "exampleId": "Aku baik-baik saja, alhamdulillah"},
                    {"ar": "الْحَمْدُ لِلَّهِ", "latin": "al-ḥamdu lillāh", "id": "segala puji bagi Allah",
                     "exampleAr": "الْحَمْدُ لِلَّهِ عَلَى كُلِّ حَالٍ", "exampleLatin": "Al-ḥamdu lillāh ʿalā kulli ḥāl", "exampleId": "Segala puji bagi Allah dalam segala keadaan"},
                    {"ar": "هَدِيَّة", "latin": "hadiyyah", "id": "hadiah",
                     "exampleAr": "الْهَدِيَّةُ مِنْ صَدِيقِي", "exampleLatin": "Al-hadiyyatu min ṣadīqī", "exampleId": "Hadiahnya dari temanku"},
                    {"ar": "لَكَ", "latin": "laka", "id": "untukmu (laki-laki)",
                     "exampleAr": "هٰذَا الْكِتَابُ لَكَ", "exampleLatin": "Hādhā l-kitābu laka", "exampleId": "Buku ini untukmu"},
                    {"ar": "شُكْرًا", "latin": "shukran", "id": "terima kasih",
                     "exampleAr": "شُكْرًا عَلَى الْمُسَاعَدَةِ", "exampleLatin": "Shukran ʿalā l-musāʿadah", "exampleId": "Terima kasih atas bantuannya"},
                    {"ar": "سَاعَة", "latin": "sāʿah", "id": "jam, jam tangan",
                     "exampleAr": "سَاعَتِي جَدِيدَةٌ", "exampleLatin": "Sāʿatī jadīdah", "exampleId": "Jam tanganku baru"},
                    {"ar": "جَمِيل", "latin": "jamīl", "id": "indah, bagus",
                     "exampleAr": "الْمَدِينَةُ جَمِيلَةٌ", "exampleLatin": "Al-madīnatu jamīlah", "exampleId": "Kotanya indah"},
                    {"ar": "الْعَفْو", "latin": "al-ʿafw", "id": "sama-sama (jawaban terima kasih)",
                     "exampleAr": "الْعَفْوُ يَا أُخِي", "exampleLatin": "Al-ʿafwu yā ukhiyy", "exampleId": "Sama-sama, saudaraku"},
                ],
                "qawaid": [
                    {"titleId": "Sapaan menanyakan kabar: كَيْفَ حَالُكَ؟",
                     "id": "كَيْفَ حَالُكَ؟ = bagaimana kabarmu? (laki-laki). Untuk perempuan: كَيْفَ حَالُكِ؟ Jawaban: أَنَا بِخَيْرٍ (aku baik-baik saja).",
                     "exampleAr": "كَيْفَ حَالُكَ الْيَوْمَ؟", "exampleLatin": "Kayfa ḥāluka l-yawm?", "exampleId": "Bagaimana kabarmu hari ini?"},
                    {"titleId": "لَـ + kata ganti (untuk ...)",
                     "id": "لَـ berarti 'untuk' dan bisa disambung kata ganti: لَكَ (untukmu), لِي (untukku), لَهُ (untuknya).",
                     "exampleAr": "هٰذِهِ هَدِيَّةٌ لَكَ يَا أُسْتَاذُ", "exampleLatin": "Hādhihi hadiyyatun laka yā ustādh", "exampleId": "Ini hadiah untukmu, Ustadz"},
                    {"titleId": "Ungkapan terima kasih",
                     "id": "شُكْرًا (terima kasih), شُكْرًا جَزِيلًا (terima kasih banyak). Jawabannya: الْعَفْوُ (sama-sama).",
                     "exampleAr": "شُكْرًا جَزِيلًا. مَا هٰذِهِ الْهَدِيَّةُ؟", "exampleLatin": "Shukran jazīlan. Mā hādhihi l-hadiyyah?", "exampleId": "Terima kasih banyak. Hadiah apa ini?"},
                ],
                "tadribat": [
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Bagaimana ___ hari ini?", "promptAr": "كَيْفَ ____ الْيَوْمَ؟", "promptLatin": "Kayfa ____ l-yawm?",
                     "options": ["حَالُكَ", "اسْمُكَ", "بَيْتُكَ", "عَمَلُكَ"], "answer": "حَالُكَ"},
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Ini hadiah ___ , Ustadz", "promptAr": "هٰذِهِ هَدِيَّةٌ ____ يَا أُسْتَاذُ", "promptLatin": "Hādhihi hadiyyatun ____ yā ustādh",
                     "options": ["لَكَ", "لِي", "لَهَا", "لَنَا"], "answer": "لَكَ"},
                    {"type": "translateArId", "promptAr": "كَيْفَ حَالُكَ الْيَوْمَ؟", "promptLatin": "Kayfa ḥāluka l-yawm?",
                     "options": ["Bagaimana kabarmu hari ini?", "Siapa namamu hari ini?", "Di mana kamu hari ini?", "Apa kabar keluargamu?"], "answer": "Bagaimana kabarmu hari ini?"},
                    {"type": "translateArId", "promptAr": "شُكْرًا جَزِيلًا", "promptLatin": "Shukran jazīlan",
                     "options": ["Terima kasih banyak", "Sama-sama", "Selamat datang", "Terima kasih sedikit"], "answer": "Terima kasih banyak"},
                    {"type": "translateIdAr", "promptId": "Terima kasih, Salim.",
                     "options": ["شُكْرًا يَا سَالِمُ", "الْعَفْوُ يَا سَالِمُ", "أَهْلًا يَا سَالِمُ", "تَفَضَّلْ يَا سَالِمُ"], "answer": "شُكْرًا يَا سَالِمُ"},
                    {"type": "translateIdAr", "promptId": "Ini hadiah untukmu, Ustadz.",
                     "options": ["هٰذِهِ هَدِيَّةٌ لَكَ يَا أُسْتَاذُ", "هٰذِهِ سَاعَةٌ لَكَ يَا أُسْتَاذُ", "هٰذَا هَدِيَّةٌ لَكَ", "هٰذِهِ هَدِيَّةٌ مِنْكَ"], "answer": "هٰذِهِ هَدِيَّةٌ لَكَ يَا أُسْتَاذُ"},
                    {"type": "rearrange",
                     "words": [{"ar": "كَيْفَ", "latin": "kayfa"}, {"ar": "حَالُكَ", "latin": "ḥāluka"}, {"ar": "الْيَوْمَ", "latin": "al-yawm"}],
                     "answer": ["كَيْفَ", "حَالُكَ", "الْيَوْمَ"]},
                    {"type": "rearrange",
                     "words": [{"ar": "هٰذِهِ", "latin": "hādhihi"}, {"ar": "هَدِيَّةٌ", "latin": "hadiyyah"}, {"ar": "لَكَ", "latin": "laka"}],
                     "answer": ["هٰذِهِ", "هَدِيَّةٌ", "لَكَ"]},
                ],
            },

            # ------------------------------------------------------------------
            # Lesson 3-5: Budaya
            # ------------------------------------------------------------------
            {
                "id": "3-5",
                "titleId": "Budaya",
                "titleAr": "الثَّقَافَةُ",
                "muhadatsah": [
                    {"speaker": "Khadijah", "ar": "مَا الْعَادَاتُ فِي إِنْدُونِيسِيَّا يَا أَحْمَدُ؟", "latin": "Mā l-ʿādātu fī Indūnīsiyyā yā Aḥmad?", "id": "Apa kebiasaan-kebiasaan di Indonesia, Ahmad?"},
                    {"speaker": "Ahmad", "ar": "مِنَ الْعَادَاتِ الْحَسَنَةِ إِكْرَامُ الضَّيْفِ", "latin": "Mina l-ʿādāti l-ḥasanati ikrāmu ḍ-ḍayf", "id": "Di antara kebiasaan baik adalah memuliakan tamu"},
                    {"speaker": "Khadijah", "ar": "وَمَا هٰذِهِ الْعَادَةُ؟", "latin": "Wa mā hādhihi l-ʿādah?", "id": "Dan apa kebiasaan ini?"},
                    {"speaker": "Ahmad", "ar": "إِذَا جَاءَ الضَّيْفُ نُقَدِّمُ لَهُ الشَّايَ", "latin": "Idhā jā'a ḍ-ḍayfu nuqaddimu lahu sh-shāy", "id": "Jika tamu datang, kami menyajikan teh untuknya"},
                    {"speaker": "Khadijah", "ar": "هٰذِهِ عَادَةٌ جَمِيلَةٌ", "latin": "Hādhihi ʿādah jamīlah", "id": "Ini kebiasaan yang indah"},
                    {"speaker": "Ahmad", "ar": "وَفِي الْعِيدِ نَزُورُ الْأَقَارِبَ", "latin": "Wa fī l-ʿīdi nazūru l-aqārib", "id": "Dan pada hari raya kami mengunjungi kerabat"},
                    {"speaker": "Khadijah", "ar": "وَمَاذَا تَأْكُلُونَ فِي الْعِيدِ؟", "latin": "Wa mādhā ta'kulūna fī l-ʿīd?", "id": "Dan apa yang kalian makan pada hari raya?"},
                    {"speaker": "Ahmad", "ar": "نَأْكُلُ الْكَعْكَةَ وَالْحَلْوَى", "latin": "Na'kulu l-kaʿkah wal-ḥalwā", "id": "Kami makan kue dan manisan"},
                    {"speaker": "Khadijah", "ar": "مَا أَجْمَلَ الْعَادَاتِ الْإِنْدُونِيسِيَّةَ!", "latin": "Mā ajmala l-ʿādāti l-indūnīsiyyah!", "id": "Alangkah indahnya kebiasaan-kebiasaan Indonesia!"},
                    {"speaker": "Ahmad", "ar": "نَعَمْ، وَالْحَمْدُ لِلَّهِ", "latin": "Naʿam, wal-ḥamdu lillāh", "id": "Ya, alhamdulillah"},
                ],
                "mufrodat": [
                    {"ar": "عَادَة", "latin": "ʿādah", "id": "kebiasaan",
                     "exampleAr": "الْعَادَاتُ تَخْتَلِفُ مِنْ بَلَدٍ إِلَى بَلَدٍ", "exampleLatin": "Al-ʿādātu takhtalifu min baladin ilā balad", "exampleId": "Kebiasaan berbeda dari satu negara ke negara lain"},
                    {"ar": "إِكْرَام", "latin": "ikrām", "id": "memuliakan, penghormatan",
                     "exampleAr": "إِكْرَامُ الضَّيْفِ مِنَ الْإِسْلَامِ", "exampleLatin": "Ikrāmu ḍ-ḍayfi mina l-Islām", "exampleId": "Memuliakan tamu termasuk ajaran Islam"},
                    {"ar": "ضَيْف", "latin": "ḍayf", "id": "tamu",
                     "exampleAr": "الضَّيْفُ جَاءَ مِنْ بَعِيدٍ", "exampleLatin": "Aḍ-ḍayfu jā'a min baʿīd", "exampleId": "Tamu itu datang dari jauh"},
                    {"ar": "عِيد", "latin": "ʿīd", "id": "hari raya",
                     "exampleAr": "الْعِيدُ يَوْمٌ سَعِيدٌ", "exampleLatin": "Al-ʿīdu yawmun saʿīd", "exampleId": "Hari raya adalah hari yang bahagia"},
                    {"ar": "أَقَارِب", "latin": "aqārib", "id": "kerabat-kerabat",
                     "exampleAr": "أَزُورُ الْأَقَارِبَ فِي الْعِيدِ", "exampleLatin": "Azūru l-aqāriba fī l-ʿīd", "exampleId": "Aku mengunjungi kerabat pada hari raya"},
                    {"ar": "نُقَدِّمُ", "latin": "nuqaddimu", "id": "kami menyajikan",
                     "exampleAr": "نُقَدِّمُ الْقَهْوَةَ لِلضَّيْفِ", "exampleLatin": "Nuqaddimu l-qahwah liḍ-ḍayf", "exampleId": "Kami menyajikan kopi untuk tamu"},
                    {"ar": "نَأْكُلُ", "latin": "na'kulu", "id": "kami makan",
                     "exampleAr": "نَأْكُلُ الطَّعَامَ مَعًا", "exampleLatin": "Na'kulu ṭ-ṭaʿāma maʿan", "exampleId": "Kami makan makanan bersama-sama"},
                    {"ar": "كَعْكَة", "latin": "kaʿkah", "id": "kue",
                     "exampleAr": "الْكَعْكَةُ حُلْوَةٌ", "exampleLatin": "Al-kaʿkatu ḥulwah", "exampleId": "Kuenya manis"},
                    {"ar": "حَلْوَى", "latin": "ḥalwā", "id": "manisan",
                     "exampleAr": "الْحَلْوَى مُفَضَّلَةٌ عِنْدَ الْأَطْفَالِ", "exampleLatin": "Al-ḥalwā mufaḍḍalah ʿinda l-aṭfāl", "exampleId": "Manisan disukai anak-anak"},
                    {"ar": "الشَّاي", "latin": "ash-shāy", "id": "teh",
                     "exampleAr": "الشَّايُ حَارٌّ", "exampleLatin": "Ash-shāyu ḥārr", "exampleId": "Tehnya panas"},
                ],
                "qawaid": [
                    {"titleId": "مَا + isim untuk bertanya budaya",
                     "id": "مَا الْعَادَاتُ فِي إِنْدُونِيسِيَّا؟ = apa kebiasaan-kebiasaan di Indonesia? Pola: مَا + kata benda untuk bertanya tentang sesuatu.",
                     "exampleAr": "مَا الْعَادَاتُ فِي إِنْدُونِيسِيَّا يَا أَحْمَدُ؟", "exampleLatin": "Mā l-ʿādātu fī Indūnīsiyyā yā Aḥmad?", "exampleId": "Apa kebiasaan-kebiasaan di Indonesia, Ahmad?"},
                    {"titleId": "إِذَا (jika) — kalimat syarat",
                     "id": "إِذَا berarti 'jika'. Kalimat syarat: إِذَا جَاءَ الضَّيْفُ نُقَدِّمُ لَهُ الشَّايَ = jika tamu datang, kami menyajikan teh untuknya.",
                     "exampleAr": "إِذَا جَاءَ الضَّيْفُ نُقَدِّمُ لَهُ الشَّايَ", "exampleLatin": "Idhā jā'a ḍ-ḍayfu nuqaddimu lahu sh-shāy", "exampleId": "Jika tamu datang, kami menyajikan teh untuknya"},
                    {"titleId": "Ungkapan kagum: مَا أَجْمَلَ ...!",
                     "id": "مَا أَجْمَلَ ...! berarti 'alangkah indahnya ...!' — ungkapan kekaguman. Contoh: مَا أَجْمَلَ الْعَادَاتِ الْإِنْدُونِيسِيَّةَ!",
                     "exampleAr": "مَا أَجْمَلَ الْعَادَاتِ الْإِنْدُونِيسِيَّةَ!", "exampleLatin": "Mā ajmala l-ʿādāti l-indūnīsiyyah!", "exampleId": "Alangkah indahnya kebiasaan-kebiasaan Indonesia!"},
                ],
                "tadribat": [
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Jika ___ datang, kami menyajikan teh untuknya", "promptAr": "إِذَا جَاءَ ____ نُقَدِّمُ لَهُ الشَّايَ", "promptLatin": "Idhā jā'a ____ nuqaddimu lahu sh-shāy",
                     "options": ["الضَّيْفُ", "الْعِيدُ", "الْكَعْكَةُ", "الْحَلْوَى"], "answer": "الضَّيْفُ"},
                    {"type": "fillBlank", "promptId": "Isilah titik-titik: Kami makan ___ dan manisan", "promptAr": "نَأْكُلُ ____ وَالْحَلْوَى", "promptLatin": "Na'kulu ____ wal-ḥalwā",
                     "options": ["الْكَعْكَةَ", "الضَّيْفَ", "الشَّايَ", "الْعِيدَ"], "answer": "الْكَعْكَةَ"},
                    {"type": "translateArId", "promptAr": "إِذَا جَاءَ الضَّيْفُ نُقَدِّمُ لَهُ الشَّايَ", "promptLatin": "Idhā jā'a ḍ-ḍayfu nuqaddimu lahu sh-shāy",
                     "options": ["Jika tamu datang, kami menyajikan teh untuknya", "Jika tamu datang, kami makan kue", "Tamu datang membawa teh", "Kami menyajikan teh untuk keluarga"], "answer": "Jika tamu datang, kami menyajikan teh untuknya"},
                    {"type": "translateArId", "promptAr": "هٰذِهِ عَادَةٌ جَمِيلَةٌ", "promptLatin": "Hādhihi ʿādah jamīlah",
                     "options": ["Ini kebiasaan yang indah", "Ini kebiasaan yang buruk", "Ini hadiah yang indah", "Ini teh yang enak"], "answer": "Ini kebiasaan yang indah"},
                    {"type": "translateIdAr", "promptId": "Apa yang kalian makan pada hari raya?",
                     "options": ["مَاذَا تَأْكُلُونَ فِي الْعِيدِ؟", "مَاذَا تَشْرَبُونَ فِي الْعِيدِ؟", "مَاذَا تَأْكُلُونَ فِي الْبَيْتِ؟", "أَيْنَ تَأْكُلُونَ؟"], "answer": "مَاذَا تَأْكُلُونَ فِي الْعِيدِ؟"},
                    {"type": "translateIdAr", "promptId": "Dan pada hari raya kami mengunjungi kerabat.",
                     "options": ["وَفِي الْعِيدِ نَزُورُ الْأَقَارِبَ", "وَفِي الْعِيدِ نَأْكُلُ الْحَلْوَى", "وَفِي الْعِيدِ نُقَدِّمُ الشَّايَ", "وَفِي الْعِيدِ نَزُورُ الضَّيْفَ"], "answer": "وَفِي الْعِيدِ نَزُورُ الْأَقَارِبَ"},
                    {"type": "rearrange",
                     "words": [{"ar": "هٰذِهِ", "latin": "hādhihi"}, {"ar": "عَادَةٌ", "latin": "ʿādah"}, {"ar": "جَمِيلَةٌ", "latin": "jamīlah"}],
                     "answer": ["هٰذِهِ", "عَادَةٌ", "جَمِيلَةٌ"]},
                    {"type": "rearrange",
                     "words": [{"ar": "نَأْكُلُ", "latin": "na'kulu"}, {"ar": "الْكَعْكَةَ", "latin": "al-kaʿkah"}, {"ar": "وَالْحَلْوَى", "latin": "wal-ḥalwā"}],
                     "answer": ["نَأْكُلُ", "الْكَعْكَةَ", "وَالْحَلْوَى"]},
                ],
            },
        ],
    }
]
