#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Perluasan kurasi gelombang ketiga (top-1200, freq >= 8).
Format sama dengan CURATED_EXTRA: key -> (translit, meaningId, meaningEn).
Digabung dengan CURATED/CURATED_EXTRA oleh `curate_vocab.main()`.
"""

VOCAB_EXTRA = {
    # ---- freq 61..40 ----
    "وقالوا": ("wa-qālū", "dan mereka berkata", "and they said"),
    "وانا": ("wa-innā", "dan sesungguhnya kami", "and indeed we"),
    "بايتنا": ("bi-āyātinā", "dengan ayat-ayat Kami", "with Our signs"),
    "قبلهم": ("qablahum", "sebelum mereka", "before them"),
    "للناس": ("li-n-nās", "bagi manusia", "for mankind"),
    "لقوم": ("li-qawm", "bagi kaum", "for a people"),
    "يقولون": ("yaqūlūn", "mereka berkata", "they say"),
    "علينا": ("'alaynā", "atas kami", "upon us"),
    "جميعا": ("jamī'an", "semuanya", "all together"),
    "تجري": ("tajrī", "mengalir", "flows"),
    "الرحيم": ("ar-raḥīm", "Yang Maha Penyayang", "the Most Merciful"),
    # ---- freq 39..25 ----
    "متاع": ("matā'", "kesenangan; perbekalan", "enjoyment; provision"),
    "وهدي": ("wa-hady", "dan hadyu (hewan kurban)", "and the offering"),
    "وانهم": ("wa-annahum", "dan sesungguhnya mereka", "and indeed they"),
    "نعمه": ("ni'matahū", "nikmat-Nya", "His favor"),
    "يوما": ("yawman", "suatu hari", "a day"),
    "وكنا": ("wa-kunnā", "dan kami adalah", "and we were"),
    "افتري": ("iftarā", "dia mengada-ada", "he fabricated"),
    "رسلنا": ("rusulunā", "rasul-rasul Kami", "Our messengers"),
    "كسبوا": ("kasabū", "mereka mengusahakan", "they earned"),
    "للمؤمنين": ("li-l-mu'minīn", "bagi orang-orang beriman", "for the believers"),
    "خوف": ("khawf", "rasa takut", "fear"),
    "قلوب": ("qulūb", "hati-hati", "hearts"),
    "شك": ("shakk", "keraguan", "doubt"),
    "يجعل": ("yaj'al", "Dia menjadikan", "He makes"),
    "ليقولن": ("la-yaqūlunna", "sungguh mereka akan berkata", "they will surely say"),
    "ياتيهم": ("ya'tīhim", "datang kepada mereka", "comes to them"),
    "بينه": ("baynahū", "antaranya", "between it"),
    "يكفر": ("yakfur", "dia mengingkari", "he disbelieves"),
    "كفرون": ("kafarūn", "mereka kafir", "they disbelieve"),
    "يستطيعون": ("yastaṭī'ūn", "mereka mampu", "they are able"),
    "الملا": ("al-mala'", "para pemuka", "the chiefs"),
    "وقيل": ("wa-qīla", "dan dikatakan", "and it was said"),
    "لوط": ("lūṭ", "Luth", "Lot"),
    "وهذا": ("wa-hādhā", "dan ini", "and this"),
    "رزقا": ("rizqan", "rezeki", "provision"),
    "وبئس": ("wa-bi'sa", "dan seburuk-buruknya", "and how bad"),
    "شر": ("sharr", "kejahatan; keburukan", "evil"),
    "ونحن": ("wa-naḥnu", "dan kami", "and we"),
    "فوق": ("fawqa", "di atas", "above"),
    "بصيرا": ("baṣīran", "Maha Melihat", "All-Seeing"),
    "والذي": ("wa-lladhī", "dan yang", "and the one who"),
    "خلت": ("khalat", "telah berlalu", "have passed"),
    "ملكت": ("malakat", "yang dimiliki", "possessed"),
    "تقولوا": ("taqūlū", "kalian berkata", "you say"),
    "اخري": ("ukhrā", "yang lain", "another"),
    "ادم": ("ādam", "Adam", "Adam"),
    "واذكر": ("wa-dhkur", "dan ingatlah", "and remember"),
    "كلوا": ("kulū", "makanlah", "eat"),
    "ببعض": ("bi-ba'ḍ", "dengan sebagian", "with some"),
    "ابرهم": ("ibrāhīm", "Ibrahim", "Abraham"),
    "المنفقين": ("al-munfiqīn", "orang-orang yang berinfak", "those who spend"),
    "التوريه": ("at-tawrāh", "Taurat", "the Torah"),
    "اوحينا": ("awḥaynā", "Kami wahyukan", "We revealed"),
    "بالقسط": ("bi-l-qisṭ", "dengan adil", "with justice"),
    "يكسبون": ("yaksibūn", "mereka berusaha", "they earn"),
    "سبحنهٗ": ("subḥānahū", "Maha Suci Dia", "glory be to Him"),
    "مكان": ("makān", "tempat", "place"),
    "انزلنه": ("anzalnāhu", "Kami turunkan", "We sent it down"),
    "السيات": ("as-sayyi'āt", "keburukan-keburukan", "evil deeds"),
    "الكذب": ("al-kadhib", "dusta", "falsehood"),
    "بهذا": ("bi-hādhā", "dengan ini", "with this"),
    "عندنا": ("'indanā", "di sisi Kami", "with Us"),
    "ويل": ("wayl", "celakalah", "woe"),
    "دابه": ("dābbah", "binatang melata", "creature"),
    "يستهزون": ("yastahzi'ūn", "mereka memperolok-olok", "they mock"),
    "مسلمون": ("muslimūn", "orang-orang muslim", "Muslims"),
    "قلنا": ("qulnā", "Kami berfirman", "We said"),
    "وانت": ("wa-anta", "dan engkau", "and you"),
    "قريب": ("qarīb", "dekat", "near"),
    "اتيهم": ("atāhum", "datang kepada mereka", "came to them"),
    "السو": ("as-sū'", "keburukan", "evil"),
    "المدينه": ("al-madīnah", "kota", "the city"),
    "سبع": ("sab'", "tujuh", "seven"),
    "ادخلوا": ("udkhulū", "masuklah", "enter"),
    "معرضون": ("mu'riḍūn", "berpaling", "turning away"),
    "يرد": ("yarudd", "menolak; membalas", "repels; returns"),
    "وكل": ("wa-kull", "dan setiap", "and every"),
    "والمليكه": ("wa-l-malā'ikah", "dan para malaikat", "and the angels"),
    "الظلمت": ("aẓ-ẓulumāt", "kegelapan-kegelapan", "darknesses"),
    "ازواجا": ("azwājan", "pasangan-pasangan", "pairs; spouses"),
    "بعيد": ("ba'īd", "jauh", "far"),
    "سنه": ("sanah", "tahun", "year"),
    "يخلق": ("yakhluq", "Dia menciptakan", "He creates"),
    "الانعام": ("al-an'ām", "binatang ternak", "the cattle"),
    "مره": ("marrah", "sekali", "a time"),
    "اليما": ("alīman", "yang pedih", "painful"),
    "اوتي": ("ūtiya", "diberi", "was given"),
    "نفسا": ("nafsan", "diri; jiwa", "a soul"),
    "قلوبكم": ("qulūbukum", "hati kalian", "your hearts"),
    "معهم": ("ma'ahum", "bersama mereka", "with them"),
    "الفضل": ("al-faḍl", "karunia", "the bounty"),
    "الاولي": ("al-ūlā", "yang pertama", "the first"),
    "واطيعوا": ("wa-aṭī'ū", "dan taatlah", "and obey"),
    "اسم": ("ism", "nama", "name"),
    "رجل": ("rajul", "seorang laki-laki", "a man"),
    "المجرمون": ("al-mujrimūn", "para penjahat", "the criminals"),
    "الحسني": ("al-ḥusnā", "yang terbaik", "the best"),
    "يفعلون": ("yaf'alūn", "mereka berbuat", "they do"),
    "فانظر": ("fa-nẓur", "maka lihatlah", "then look"),
    "اريتم": ("ara'aytum", "tahukah kalian", "have you seen"),
    "اتيكم": ("atākum", "datang kepada kalian", "came to you"),
    "امنتم": ("āmantum", "kalian beriman", "you believed"),
    "اذن": ("idhan", "kalau begitu", "then"),
    "يحزنون": ("yaḥzanūn", "mereka bersedih", "they grieve"),
    "ولدا": ("waladan", "anak", "a child"),
    "لقومه": ("li-qawmihī", "bagi kaumnya", "for his people"),
    "وجدنا": ("wajadnā", "kami mendapati", "we found"),
    "كره": ("kurh", "keterpaksaan; kebencian", "reluctance"),
    "الخسرين": ("al-khāsirīn", "orang-orang yang rugi", "the losers"),
    "فلولا": ("fa-lawlā", "maka mengapa tidak", "then why not"),
    "يكونوا": ("yakūnū", "mereka menjadi", "they are"),
    "اعبد": ("a'bud", "aku menyembah", "I worship"),
    "ادريك": ("adrāka", "mengetahui", "makes known"),
    "صبروا": ("ṣabarū", "mereka bersabar", "they were patient"),
    "اخذ": ("akhadha", "dia mengambil", "he took"),
    "واتبعوا": ("wa-ttaba'ū", "dan mereka mengikuti", "and they followed"),
    "اليس": ("a-laysa", "bukankah", "is it not"),
    "وذلك": ("wa-dhālika", "dan itu", "and that"),
    "بلغ": ("balagha", "sampai", "reached"),
    "وقالت": ("wa-qālat", "dan dia (perempuan) berkata", "and she said"),
    "لهن": ("la-hunna", "bagi mereka (perempuan)", "for them (f)"),
    "للعلمين": ("li-l-'ālamīn", "bagi semesta alam", "for the worlds"),
    "بغته": ("baghtatan", "secara tiba-tiba", "suddenly"),
    "الدار": ("ad-dār", "negeri; rumah", "the abode"),
    "الرزق": ("ar-rizq", "rezeki", "provision"),
    "الكفر": ("al-kufr", "kekufuran", "disbelief"),
    "فيقول": ("fa-yaqūl", "maka dia berkata", "then he says"),
    "فوقهم": ("fawqahum", "di atas mereka", "above them"),
    "تتخذوا": ("tattakhidhū", "kalian menjadikan", "you take"),
    "فريق": ("farīq", "segolongan", "a group"),
    "وكيلا": ("wakīlan", "pelindung; wakil", "a guardian; trustee"),
    "الشيطين": ("ash-shayāṭīn", "setan-setan", "the devils"),
    "قتل": ("qutila", "dibunuh", "was killed"),
    "مبينا": ("mubīnan", "yang jelas", "clear"),
    "داوٗد": ("dāwūd", "Daud", "David"),
    "كلما": ("kullamā", "setiap kali", "whenever"),
    "رحمته": ("raḥmatuhū", "rahmat-Nya", "His mercy"),
    "وليا": ("waliyyan", "pelindung", "a protector"),
    "يريدون": ("yurīdūn", "mereka menghendaki", "they want"),
    "يفقهون": ("yafqahūn", "mereka memahami", "they understand"),
    "كمثل": ("ka-mathal", "seperti perumpamaan", "like the example"),
    "ينصرون": ("yanṣurūn", "mereka menolong", "they help"),
    "واذكروا": ("wa-dhkurū", "dan ingatlah", "and remember"),
    "الامور": ("al-umūr", "urusan-urusan", "the affairs"),
    "بعذاب": ("bi-'adhāb", "dengan azab", "with punishment"),
    "توعدون": ("tū'idūn", "yang dijanjikan", "you are promised"),
    "حرج": ("ḥaraj", "kesempitan; keberatan", "difficulty"),
    "الاخرين": ("al-ākharīn", "yang lain", "the others"),
    "ياهل": ("yā ahl", "wahai penduduk", "O people of"),
    "يكفرون": ("yakfurūn", "mereka mengingkari", "they disbelieve"),
    "ضرا": ("ḍurran", "bahaya; mudarat", "harm"),
    "سيئه": ("sayyi'ah", "keburukan", "an evil deed"),
    "اشركوا": ("ashrakū", "mereka mempersekutukan", "they associated partners"),
    "الحي": ("al-ḥayy", "Yang Maha Hidup", "the Ever-Living"),
    "تسمع": ("tasma'", "engkau mendengar", "you hear"),
    "شهيد": ("shahīd", "saksi", "a witness"),
    "سلطن": ("sulṭān", "kekuasaan; bukti", "authority; proof"),
    "يؤمنوا": ("yu'minū", "mereka beriman", "they believe"),
    "البيت": ("al-bayt", "rumah (Ka'bah)", "the House"),
    "كبير": ("kabīr", "besar", "great"),
    "بذات": ("bi-dhāt", "dengan zat", "by the essence"),
    "ويعلم": ("wa-ya'lam", "dan Dia mengetahui", "and He knows"),
    "بشرا": ("basharan", "manusia", "a human"),
    "ثمود": ("thamūd", "Tsamud", "Thamud"),
    "ورا": ("warā'", "di belakang", "behind"),
    "تاب": ("tāba", "dia bertobat", "he repented"),
    "اولوا": ("ulū", "pemilik; orang-orang yang", "those with"),
    "اخرج": ("akhraja", "mengeluarkan", "brought out"),
    "بالغيب": ("bi-l-ghayb", "dengan yang gaib", "in the unseen"),
    "امين": ("amīn", "dapat dipercaya", "trustworthy"),
    "امرهم": ("amruhum", "urusan mereka", "their affair"),
    "درجت": ("darajāt", "derajat-derajat", "degrees"),
    "بي": ("bī", "denganku", "with me"),
    "افلم": ("a-fa-lam", "maka tidakkah", "did they not"),
    "يستوي": ("yastawī", "sama", "are equal"),
    "ارسلنك": ("arsalnāka", "Kami mengutusmu", "We sent you"),
    "يضلل": ("yuḍlil", "Dia menyesatkan", "He lets stray"),
    "اهواهم": ("ahwā'uhum", "hawa nafsu mereka", "their desires"),
    "بايه": ("bi-āyah", "dengan sebuah ayat/tanda", "with a sign"),
    "وانزل": ("wa-anzala", "dan Dia menurunkan", "and He sent down"),
    "بامره": ("bi-amrihī", "dengan perintah-Nya", "by His command"),
    "وتري": ("wa-tarā", "dan engkau melihat", "and you see"),
    "اخر": ("ākhar", "yang lain", "another"),
    "وانزلنا": ("wa-anzalnā", "dan Kami turunkan", "and We sent down"),
    "اليمين": ("al-yamīn", "sumpah; tangan kanan", "the oath; right hand"),
    "ولهٗ": ("wa-lahū", "dan baginya", "and for him"),
    "ترك": ("taraka", "dia meninggalkan", "he left"),
    "القربي": ("al-qurbā", "kerabat", "the relatives"),
    "اجرهم": ("ajruhum", "pahala mereka", "their reward"),
    "سبحن": ("subḥāna", "Maha Suci", "glory be to"),
    "كتبا": ("kutuban", "kitab-kitab", "books"),
    "خبيرا": ("khabīran", "Maha Mengetahui", "All-Aware"),
    "اوحي": ("awḥā", "Dia mewahyukan", "He revealed"),
    "نصيرا": ("naṣīran", "penolong", "a helper"),
    "كم": ("kam", "berapa banyak", "how many"),
    "عيسي": ("'īsā", "Isa", "Jesus"),
    "قول": ("qawl", "perkataan", "word; saying"),
    "المفلحون": ("al-mufliḥūn", "orang-orang yang beruntung", "the successful"),
    "مرض": ("maraḍ", "penyakit", "disease"),
    "تكفرون": ("takfurūn", "kalian mengingkari", "you disbelieve"),
    "اخذنا": ("akhadhnā", "Kami mengambil; menghukum", "We seized"),
    "مهين": ("muhīn", "yang menghinakan", "humiliating"),
    "شهدا": ("shuhadā'", "para saksi", "witnesses"),
    "اتبعوا": ("ittaba'ū", "mereka mengikuti", "they followed"),
    "حدود": ("ḥudūd", "batas-batas", "limits"),
    "خلفهم": ("khalfahum", "di belakang mereka", "behind them"),
    "الكفار": ("al-kuffār", "orang-orang kafir", "the disbelievers"),
    "للمكذبين": ("li-l-mukadhdhibīn", "bagi orang-orang yang mendustakan", "for the deniers"),
    "وبشر": ("wa-bashshir", "dan sampaikan kabar gembira", "and give glad tidings"),
    "صدق": ("ṣidq", "kebenaran", "truthfulness"),
    "مرجعكم": ("marji'ukum", "tempat kembali kalian", "your return"),
    "حميم": ("ḥamīm", "air mendidih; teman akrab", "boiling water; close friend"),
    "يرجون": ("yarjūn", "mereka mengharap", "they hope"),
    "زين": ("zayyana", "menghiasi", "adorned"),
    "رسلهم": ("rusuluhum", "rasul-rasul mereka", "their messengers"),
    "فيكم": ("fīkum", "di antara kalian", "among you"),
    "السلم": ("as-silm", "perdamaian", "peace"),
    "السمع": ("as-sam'", "pendengaran", "hearing"),
    "احق": ("aḥaqq", "lebih berhak", "more deserving"),
    "فاتوا": ("fa'tū", "maka datangkanlah", "then bring"),
    "وربك": ("wa-rabbuka", "dan Tuhanmu", "and your Lord"),
    "يبصرون": ("yubṣirūn", "mereka melihat", "they see"),
    "ظلمت": ("ẓulmat", "kegelapan", "darkness"),
    "شركا": ("shurakā'", "sekutu-sekutu", "partners"),
    "المسلمين": ("al-muslimīn", "orang-orang muslim", "the Muslims"),
    "ابانا": ("ābā'anā", "nenek moyang kami", "our forefathers"),
    "واقيموا": ("wa-aqīmū", "dan dirikanlah", "and establish"),
    "الغفور": ("al-ghafūr", "Yang Maha Pengampun", "the Oft-Forgiving"),
    "طعام": ("ṭa'ām", "makanan", "food"),
    "دين": ("dīn", "agama", "religion"),
    "ذهب": ("dhahaba", "pergi", "went"),
    "يقولوا": ("yaqūlū", "mereka berkata", "they say"),
    "ويقول": ("wa-yaqūl", "dan dia berkata", "and he says"),
    "اسلكم": ("uslukū", "masukkanlah", "enter"),
    "فانا": ("fa-innā", "maka sesungguhnya kami", "then indeed we"),
    "معك": ("ma'aka", "bersamamu", "with you"),
    "فاصبر": ("fa-ṣbir", "maka bersabarlah", "then be patient"),
    "غيرهٗ": ("ghayrahū", "selain-Nya", "other than Him"),
    "وتلك": ("wa-tilka", "dan itu", "and those"),
    "ثلثه": ("thuluthah", "sepertiganya", "a third of it"),
    "رسل": ("rusul", "rasul-rasul", "messengers"),
    "تقول": ("taqūl", "dia berkata", "she says"),
    "فمنهم": ("fa-minhum", "maka di antara mereka", "then among them"),
    "ذكري": ("dhikrā", "peringatan", "reminder"),
    "عليهن": ("'alayhinna", "atas mereka (perempuan)", "upon them (f)"),
    "ويعقوب": ("wa-ya'qūb", "dan Yakub", "and Jacob"),
    "تاكلون": ("ta'kulūn", "kalian makan", "you eat"),
    "سجدا": ("sujjadan", "bersujud", "prostrating"),
    "بيني": ("baynī", "antara aku", "between me"),
    "ادعوا": ("ud'ū", "berdoalah; serulah", "call; invoke"),
    "وسخر": ("wa-sakhkhara", "dan menundukkan", "and subjected"),
    "الثمرت": ("ath-thamarāt", "buah-buahan", "fruits"),
    "ومما": ("wa-mimmā", "dan dari apa", "and from what"),
    "ابتغا": ("ibtaghā", "dia mencari", "he sought"),
    "عدن": ("'adn", "Adn (surga)", "Eden"),
    "البلغ": ("al-balāgh", "penyampaian", "the delivery"),
    "استكبروا": ("istakbarū", "mereka menyombongkan diri", "they were arrogant"),
    "عنا": ("'annā", "dari kami", "from us"),
    "سبيله": ("sabīlahū", "jalan-Nya", "His way"),
    "مني": ("minnī", "dari aku", "from me"),
    "نطفه": ("nuṭfah", "air mani; setetes", "a drop of fluid"),
    "يذكرون": ("yadhkurūn", "mereka mengingat", "they remember"),
    "سا": ("sā'", "buruklah", "evil is"),
    "كن": ("kun", "jadilah", "be"),
    "وله": ("wa-lahū", "dan baginya", "and to him"),
    "موتها": ("mawtuhā", "kematiannya", "its death"),
    "مؤمن": ("mu'min", "orang beriman", "a believer"),
    "الخسرون": ("al-khāsirūn", "orang-orang yang rugi", "the losers"),
    "انظر": ("unẓur", "lihatlah", "look"),
    "والمسكين": ("wa-l-miskīn", "dan orang miskin", "and the needy"),
    "سلطنا": ("sallaṭnā", "Kami kuasakan", "We gave power"),
    "عدوا": ("'aduwwan", "musuh", "an enemy"),
    "شديدا": ("shadīdan", "yang keras", "severe"),
    "بالذي": ("bi-lladhī", "dengan yang", "with that which"),
    "يتخذ": ("yattakhidh", "dia menjadikan", "he takes"),
    "للظلمين": ("li-ẓ-ẓālimīn", "bagi orang-orang zalim", "for the wrongdoers"),
    "هزوا": ("huzuwan", "olok-olokan", "mockery"),
    "معي": ("ma'ī", "bersamaku", "with me"),
    "وعمل": ("wa-'amal", "dan amal", "and deed"),
    "هرون": ("hārūn", "Harun", "Aaron"),
    "يوقنون": ("yūqinūn", "mereka yakin", "they are certain"),
    "الفسقين": ("al-fāsiqīn", "orang-orang fasik", "the defiant"),
    "مصدقا": ("muṣaddiqan", "membenarkan", "confirming"),
    "البينت": ("al-bayyināt", "bukti-bukti yang jelas", "clear proofs"),
    "ورسله": ("wa-rusulihī", "dan rasul-rasul-Nya", "and His messengers"),
    "كانهم": ("ka-annahum", "seakan-akan mereka", "as if they"),
    "والحكمه": ("wa-l-ḥikmah", "dan hikmah", "and wisdom"),
    "اموالكم": ("amwālukum", "harta kalian", "your wealth"),
    "تفلحون": ("tufliḥūn", "kalian beruntung", "you succeed"),
    "كثيره": ("kathīrah", "banyak", "much"),
    "انفقوا": ("anfiqū", "berinfaklah", "spend"),
    "واصحب": ("wa-aṣḥāb", "dan penghuni", "and the companions of"),
    "والمؤمنت": ("wa-l-mu'mināt", "dan perempuan-perempuan beriman", "and the believing women"),
    "اضل": ("aḍalla", "menyesatkan", "led astray"),
    "واطيعون": ("wa-aṭī'ūn", "dan taatilah aku", "and obey me"),
    "تقوم": ("taqūm", "berdiri", "stands"),
    "فذوقوا": ("fa-dhūqū", "maka rasakanlah", "then taste"),
    "النعيم": ("an-na'īm", "kenikmatan", "delight"),
    "القرون": ("al-qurūn", "generasi-generasi", "generations"),
    "يختلفون": ("yakhtalifūn", "mereka berselisih", "they differ"),
    "دعوا": ("da'aw", "mereka menyeru; berdoa", "they called"),
    "يتفكرون": ("yatafakkarūn", "mereka berpikir", "they reflect"),
    "وبينكم": ("wa-baynakum", "dan di antara kalian", "and between you"),
    "الظن": ("aẓ-ẓann", "persangkaan", "conjecture"),
    "يغني": ("yughnī", "memperkaya; mencukupi", "enriches; suffices"),
    "راوا": ("ra'aw", "mereka melihat", "they saw"),
    "مجرمين": ("mujrimīn", "orang-orang yang berbuat dosa", "sinners"),
    "المفسدين": ("al-mufsidīn", "orang-orang yang berbuat kerusakan", "the corrupters"),
    "ذريه": ("dhurriyyah", "keturunan", "offspring"),
    "الطيبت": ("aṭ-ṭayyibāt", "hal-hal yang baik", "good things"),
    "جاك": ("jā'aka", "datang kepadamu", "came to you"),
    "حنيفا": ("ḥanīfan", "lurus (hanif)", "upright"),
    "لنفسه": ("li-nafsihī", "bagi dirinya", "for himself"),
    "عين": ("'ayn", "mata; sumber air", "eye; spring"),
    "دينكم": ("dīnukum", "agama kalian", "your religion"),
    "صدورهم": ("ṣudūruhum", "dada mereka", "their chests"),
    "الاحزاب": ("al-aḥzāb", "golongan-golongan", "the confederates"),
    "اثنين": ("ithnayn", "dua", "two"),
    "قليل": ("qalīl", "sedikit", "little"),
    "وهي": ("wa-hiya", "dan dia (perempuan)", "and she"),
    "بك": ("bika", "denganmu", "with you"),
    "يرسل": ("yursil", "Dia mengutus", "He sends"),
    "وربكم": ("wa-rabbukum", "dan Tuhan kalian", "and your Lord"),
    "جات": ("jā'at", "telah datang", "came"),
    "را": ("ra'ā", "dia melihat", "he saw"),
    "تخف": ("takhaf", "engkau takut", "you fear"),
    "يات": ("ya'ti", "datang", "comes"),
    "وكلا": ("wa-kullā", "dan keduanya", "and both"),
    "بحمد": ("bi-ḥamd", "dengan pujian", "with praise"),
    "اغني": ("aghnā", "memperkaya", "enriched"),
    "وجه": ("wajh", "wajah", "face"),
    "حكما": ("ḥakaman", "hakim; pemutus", "a judge"),
    "عبادنا": ("'ibādanā", "hamba-hamba Kami", "Our servants"),
    "الكذبين": ("al-kādhibīn", "orang-orang pendusta", "the liars"),
    "الطير": ("aṭ-ṭayr", "burung", "the birds"),
    "منهما": ("minhumā", "dari keduanya", "from both"),
    "لعلي": ("la-'allī", "agar aku", "so that I"),
    "نصيب": ("naṣīb", "bagian", "share"),
    "وجا": ("wa-jā'a", "dan datang", "and came"),
    "اخيه": ("akhīhi", "saudaranya", "his brother"),
    "القريه": ("al-qaryah", "negeri; kampung", "the town"),
    "باسنا": ("ba'sunā", "azab Kami", "Our punishment"),
    "والشهاده": ("wa-sh-shahādah", "dan kesaksian", "and the testimony"),
    "دعا": ("da'ā", "dia berdoa; menyeru", "he called"),
    "يملكون": ("yamlikūn", "mereka memiliki", "they possess"),
    "الامثال": ("al-amthāl", "perumpamaan-perumpamaan", "the examples"),
    "رزقنهم": ("razaqnāhum", "Kami beri rezeki", "We provided them"),
    "عهد": ("'ahd", "perjanjian", "covenant"),
    "النور": ("an-nūr", "cahaya", "the light"),
    "الحميد": ("al-ḥamīd", "Yang Maha Terpuji", "the Praiseworthy"),
    "يعمل": ("ya'mal", "dia berbuat", "he does"),
    "فاخذتهم": ("fa-akhadhathum", "maka azab menimpa mereka", "then seized them"),
    "يهتدون": ("yahtadūn", "mereka mendapat petunjuk", "they are guided"),
    "فالذين": ("fa-lladhīna", "maka orang-orang yang", "then those who"),
    "فيكون": ("fa-yakūn", "maka jadilah", "then it is"),
    "ثمنا": ("thamanan", "harga", "price"),
    "هادوا": ("hādū", "orang-orang Yahudi", "the Jews"),
    "تابوا": ("tābū", "mereka bertobat", "they repented"),
    "بمن": ("bi-man", "dengan orang yang", "with whom"),
    "لهما": ("lahumā", "bagi keduanya", "for both"),
    "الباطل": ("al-bāṭil", "kebatilan", "falsehood"),
    "نؤمن": ("nu'min", "kami beriman", "we believe"),
    "ايتي": ("āyātī", "ayat-ayat-Ku", "My verses"),
    "ذكرا": ("dhikran", "peringatan; zikir", "a reminder"),
    "الصور": ("aṣ-ṣūr", "sangkakala", "the trumpet"),
    "يوعدون": ("yū'adūn", "mereka dijanjikan", "they are promised"),
    "وكذبوا": ("wa-kadhdhabū", "dan mereka mendustakan", "and they denied"),
    "فريقا": ("farīqan", "segolongan", "a group"),
    "سليمن": ("sulaymān", "Sulaiman", "Solomon"),
    "تبين": ("tabayyana", "menjadi jelas", "became clear"),
    "الصبرين": ("aṣ-ṣābirīn", "orang-orang yang sabar", "the patient"),
    "مصيبه": ("muṣībah", "musibah", "calamity"),
    "وجاهدوا": ("wa-jāhidū", "dan berjihadlah", "and strive"),
    "حليم": ("ḥalīm", "Maha Penyantun", "Forbearing"),
    "حديث": ("ḥadīth", "perkataan; pembicaraan", "speech; narration"),
    "القي": ("alqā", "melemparkan", "cast"),
    "ايديكم": ("aydīkum", "tangan kalian", "your hands"),
    "ارسل": ("arsala", "mengutus", "sent"),
    "عباد": ("'ibād", "hamba-hamba", "servants"),
    "المنكر": ("al-munkar", "kemungkaran", "the evil"),
    "فانهم": ("fa-innahum", "maka sesungguhnya mereka", "then indeed they"),
    "تكذبون": ("tukadhdhibūn", "kalian mendustakan", "you deny"),
    "دينهم": ("dīnuhum", "agama mereka", "their religion"),
    "يجدون": ("yajidūn", "mereka mendapati", "they find"),
    "بيوت": ("buyūt", "rumah-rumah", "houses"),
    "يدي": ("yaday", "dua tangan", "two hands"),
    "ويغفر": ("wa-yaghfir", "dan Dia mengampuni", "and He forgives"),
    "المسيح": ("al-masīḥ", "Al-Masih", "the Messiah"),
    "تنزيل": ("tanzīl", "penurunan (wahyu)", "the revelation"),
    "وانفسهم": ("wa-anfusihim", "dan diri mereka", "and themselves"),
    "الاعراب": ("al-a'rāb", "orang-orang Arab Badui", "the Bedouins"),
    "رسوله": ("rasūluhū", "rasul-Nya", "His Messenger"),
    "استوي": ("istawā", "bersemayam; tegak", "settled; rose"),
    "نورا": ("nūran", "cahaya", "a light"),
    "سبحنك": ("subḥānaka", "Maha Suci Engkau", "glory be to You"),
    "نفسي": ("nafsī", "diriku", "myself"),
    "يفلح": ("yufliḥ", "beruntung", "succeeds"),
    "والبحر": ("wa-l-baḥr", "dan laut", "and the sea"),
    "طيبه": ("ṭayyibah", "yang baik", "good"),
    "ويهدي": ("wa-yahdī", "dan Dia memberi petunjuk", "and He guides"),
    "هنالك": ("hunālika", "di sana", "there"),
    "يملك": ("yamlik", "memiliki", "possesses"),
    "بري": ("barī'", "bebas; berlepas diri", "free; innocent"),
    "متي": ("matā", "kapan", "when"),
    "الوعد": ("al-wa'd", "janji", "the promise"),
    "نفعا": ("naf'an", "manfaat", "benefit"),
    "الن": ("al-āna", "sekarang", "now"),
    "تجزون": ("tujzawn", "kalian dibalas", "you are recompensed"),
    "ويميت": ("wa-yumīt", "dan Dia mematikan", "and He gives death"),
    "يشكرون": ("yashkurūn", "mereka bersyukur", "they are grateful"),
    "يتبعون": ("yattabi'ūn", "mereka mengikuti", "they follow"),
    "اجري": ("ajrī", "pahala-ku", "my reward"),
    "اكون": ("akūn", "aku menjadi", "I be"),
    "مسلمين": ("muslimīn", "orang-orang muslim", "Muslims"),
    "بيوتا": ("buyūtan", "rumah-rumah", "houses"),
    "اختلفوا": ("ikhtalafū", "mereka berselisih", "they differed"),
    "تكونن": ("takūnan", "engkau menjadi", "you become"),
    "فانك": ("fa-innaka", "maka sesungguhnya engkau", "then indeed you"),
    "واتبع": ("wa-ttaba'", "dan ikutilah", "and follow"),
    "الخير": ("al-khayr", "kebaikan", "the good"),
    "فعل": ("fa'ala", "dia berbuat", "he did"),
    "فويل": ("fa-wayl", "maka celakalah", "then woe"),
    "لعنه": ("la'nah", "laknat", "curse"),
    "ويقوم": ("wa-yaqūm", "dan berdiri", "and stands"),
    "اقول": ("aqūl", "aku berkata", "I say"),
    "قومك": ("qawmuka", "kaummu", "your people"),
    "امم": ("umam", "umat-umat", "nations"),
    "فاصبحوا": ("fa-aṣbaḥū", "maka mereka menjadi", "then they became"),
    "ديارهم": ("diyāruhum", "negeri mereka", "their homes"),
    "سلما": ("silman", "perdamaian", "peace"),
    "قومهٗ": ("qawmuhū", "kaumnya", "his people"),
    "مدين": ("madyan", "Madyan", "Midian"),
    "باذنه": ("bi-idhnihī", "dengan izin-Nya", "by His permission"),
    "يعبدون": ("ya'budūn", "mereka menyembah", "they worship"),
    "بغافل": ("bi-ghāfil", "lengah", "unmindful"),
    "قرانا": ("qur'ānan", "Al-Qur'an", "a Qur'an"),
    "لابيه": ("li-abīhi", "kepada ayahnya", "to his father"),
    "والشمس": ("wa-sh-shams", "dan matahari", "and the sun"),
    "واسحق": ("wa-isḥāq", "dan Ishaq", "and Isaac"),
    "مله": ("millah", "agama", "religion"),
    "سنين": ("sinīn", "tahun-tahun", "years"),
    "فليتوكل": ("fa-l-yatawakkal", "maka hendaklah bertawakal", "then let him rely"),
    "دخلوا": ("dakhalū", "mereka masuk", "they entered"),
    "مكانا": ("makānan", "tempat", "a place"),
    "وبين": ("wa-bayna", "dan antara", "and between"),
    "لاولي": ("li-ulī", "bagi orang-orang yang", "for those with"),
    "رواسي": ("rawāsī", "gunung-gunung", "mountains"),
    "بربهم": ("bi-rabbihim", "dengan Tuhan mereka", "with their Lord"),
    "كمن": ("ka-man", "seperti orang yang", "like one who"),
    "يبسط": ("yabsuṭ", "melapangkan", "extends"),
    "ويقدر": ("wa-yaqdir", "dan menyempitkan", "and restricts"),
    "قريبا": ("qarīban", "dekat", "near"),
    "سريع": ("sarī'", "cepat", "swift"),
    "اذكروا": ("udhkurū", "ingatlah", "remember"),
    "عذابي": ("'adhābī", "azab-Ku", "My punishment"),
    "وثمود": ("wa-thamūd", "dan (kaum) Tsamud", "and Thamud"),
    "تعلم": ("ta'lam", "engkau mengetahui", "you know"),
    "الابصار": ("al-abṣār", "penglihatan", "the sights"),
    "معلوم": ("ma'lūm", "diketahui", "known"),
    "للمليكه": ("li-l-malā'ikah", "bagi para malaikat", "for the angels"),
    "ابليس": ("iblīs", "Iblis", "Iblis"),
    "عبادي": ("'ibādī", "hamba-hamba-Ku", "My servants"),
    "ولعلكم": ("wa-la'allakum", "dan agar kalian", "and so that you"),
    "اساطير": ("asāṭīr", "dongeng-dongeng", "legends"),
    "مثوي": ("mathwā", "tempat tinggal", "abode"),
    "الاعلي": ("al-a'lā", "Yang Maha Tinggi", "the Most High"),
    "اقرب": ("aqrab", "lebih dekat", "nearer"),
    "لكذبون": ("la-kādhibūn", "sungguh pendusta", "surely liars"),
    "الايمان": ("al-īmān", "keimanan", "faith"),
    "فاخذهم": ("fa-akhadhahum", "maka azab menimpa mereka", "then seized them"),
    "واتينه": ("wa-ātaynāhu", "dan Kami berikan kepadanya", "and We gave him"),
    "فضلا": ("faḍlan", "karunia", "favor"),
    "وكم": ("wa-kam", "dan betapa banyak", "and how many"),
    "عندك": ("'indaka", "di sisimu", "with you"),
    "فيهن": ("fīhinna", "di dalamnya (perempuan)", "in them (f)"),
    "كونوا": ("kūnū", "jadilah", "be"),
    "النبين": ("an-nabiyyīn", "para nabi", "the prophets"),
    "كثير": ("kathīr", "banyak", "many"),
    "لبعض": ("li-ba'ḍ", "bagi sebagian", "for some"),
    "تؤمنوا": ("tu'minū", "kalian beriman", "you believe"),
    "تخرج": ("takhruj", "keluar", "goes out"),
    "نفسك": ("nafsaka", "dirimu", "yourself"),
    "يشرك": ("yushrik", "dia mempersekutukan", "he associates"),
    "نعم": ("ni'am", "nikmat-nikmat", "favors"),
    "نجعل": ("naj'al", "Kami jadikan", "We make"),
    "بالباطل": ("bi-l-bāṭil", "dengan kebatilan", "with falsehood"),
    "علما": ("'ilman", "ilmu", "knowledge"),
    "فلهٗ": ("fa-lahū", "maka baginya", "then for him"),
    "للرحمن": ("li-r-raḥmān", "bagi Yang Maha Pemurah", "for the Most Merciful"),
    "يذكر": ("yadhkur", "dia mengingat", "he remembers"),
    "ابصارهم": ("abṣāruhum", "penglihatan mereka", "their eyes"),
    "والسما": ("wa-s-samā'", "dan langit", "and the sky"),
    "تفعلوا": ("taf'alū", "kalian berbuat", "you do"),
    "انزلت": ("unzilat", "diturunkan", "was sent down"),
    "قلتم": ("qultum", "kalian berkata", "you said"),
    "ادني": ("adnā", "lebih dekat", "nearer"),
    "ميثاق": ("mīthāq", "perjanjian", "covenant"),
    "الفسقون": ("al-fāsiqūn", "orang-orang fasik", "the defiant"),
    "نصير": ("naṣīr", "penolong", "helper"),
    "واسمعيل": ("wa-ismā'īl", "dan Ismail", "and Ishmael"),
    "اعمالكم": ("a'mālukum", "amal kalian", "your deeds"),
    "يسلونك": ("yas'alūnaka", "mereka bertanya kepadamu", "they ask you"),
    "تولي": ("tawallā", "berpaling", "turned away"),
    "اهله": ("ahluhū", "keluarganya", "his family"),
    "الخبيث": ("al-khabīth", "yang buruk", "the evil"),
    "بعضا": ("ba'ḍan", "sebagian", "some"),
    "اتيك": ("ātīka", "datang kepadamu", "come to you"),
    "ضلوا": ("ḍallū", "mereka sesat", "they went astray"),
    "تبصرون": ("tubṣirūn", "kalian melihat", "you see"),
    "ظلمين": ("ẓālimīn", "orang-orang zalim", "wrongdoers"),
    "يتوب": ("yatūb", "Dia menerima tobat", "He accepts repentance"),
    "والانس": ("wa-l-ins", "dan manusia", "and mankind"),
    "تشا": ("tashā'", "engkau menghendaki", "you will"),
    "والرسول": ("wa-r-rasūl", "dan rasul", "and the Messenger"),
    "كالذين": ("ka-lladhīna", "seperti orang-orang yang", "like those who"),
    "لقضي": ("la-quḍiya", "sungguh ditetapkan", "surely it would have been decided"),
    "يدعوا": ("yad'ū", "dia menyeru", "he calls"),
    "دار": ("dār", "negeri; rumah", "abode"),
    "نقول": ("naqūl", "kami berkata", "we say"),
    "وضل": ("wa-ḍalla", "dan sesat", "and strayed"),
    "الميت": ("al-mayyit", "yang mati", "the dead"),
    "ساعه": ("sā'ah", "saat (kiamat)", "the Hour"),
    "ولكل": ("wa-li-kull", "dan bagi setiap", "and for each"),
    "اثم": ("ithm", "dosa", "sin"),
    "ذوقوا": ("dhūqū", "rasakanlah", "taste"),
    "ظن": ("ẓann", "sangkaan", "assumption"),
    "لذو": ("la-dhū", "sungguh pemilik", "surely possessor of"),
    "مثقال": ("mithqāl", "seberat", "the weight"),
    "قولهم": ("qawluhum", "perkataan mereka", "their saying"),
    "العزه": ("al-'izzah", "kemuliaan; kekuatan", "honor; might"),
    "الغني": ("al-ghanī", "Yang Maha Kaya", "the Self-Sufficient"),
    "توليتم": ("tawallaytum", "kalian berpaling", "you turned away"),
    "فكذبوه": ("fa-kadhdhabūhu", "maka mereka mendustakannya", "then they denied him"),
    "رسلا": ("rusulan", "rasul-rasul", "messengers"),
    "وهرون": ("wa-hārūn", "dan Harun", "and Aaron"),
    "السحره": ("as-saḥarah", "para penyihir", "the sorcerers"),
    "القوا": ("alqaw", "mereka melemparkan", "they cast"),
    "واوحينا": ("wa-awḥaynā", "dan Kami wahyukan", "and We revealed"),
    "بغيا": ("baghyan", "secara zalim", "wrongfully"),
    "فاليوم": ("fa-l-yawma", "maka pada hari ini", "then today"),
    "ويجعل": ("wa-yaj'al", "dan Dia menjadikan", "and He makes"),
    "عملا": ("'amalan", "amal", "a deed"),
    "انه": ("innahū", "sesungguhnya dia", "indeed he"),
    "خسروا": ("khasirū", "mereka rugi", "they lost"),
    "ياتيكم": ("ya'tīkum", "datang kepada kalian", "comes to you"),
    "مقيم": ("muqīm", "tegak; kekal", "standing; lasting"),
    "لغفور": ("la-ghafūr", "sungguh Maha Pengampun", "surely Oft-Forgiving"),
    "فكان": ("fa-kāna", "maka jadilah", "then it was"),
    "اخاهم": ("akhāhum", "saudara mereka", "their brother"),
    "يعبد": ("ya'bud", "dia menyembah", "he worships"),
    "اعرض": ("a'raḍ", "berpaling", "turned away"),
    "علمت": ("'alimtu", "aku mengetahui", "I knew"),
    "اريد": ("urīd", "aku menghendaki", "I want"),
    "برب": ("bi-rabb", "dengan Tuhan", "with the Lord"),
    "عربيا": ("'arabiyyan", "berbahasa Arab", "Arabic"),
    "يابت": ("yā abati", "wahai ayahku", "O my father"),
    "المخلصين": ("al-mukhliṣīn", "orang-orang yang ikhlas", "the sincere"),
    "اياه": ("iyyāhu", "hanya Dia", "Him alone"),
    "ايها": ("ayyuhā", "wahai", "O"),
    "يسير": ("yasīr", "mudah", "easy"),
    "ابواب": ("abwāb", "pintu-pintu", "gates"),
    "تالله": ("ta-llāhi", "demi Allah", "by Allah"),
    "رجالا": ("rijālan", "laki-laki; orang-orang", "men"),
    "يغشي": ("yughshī", "menutup", "covers"),
    "انثي": ("unthā", "perempuan", "female"),
    "الكبير": ("al-kabīr", "Yang Maha Besar", "the Most Great"),
    "ينفع": ("yanfa'", "bermanfaat", "benefits"),
    "واقاموا": ("wa-aqāmū", "dan mereka mendirikan", "and they establish"),
    "وانفقوا": ("wa-anfaqū", "dan mereka berinfak", "and they spend"),
    "وجعلوا": ("wa-ja'alū", "dan mereka menjadikan", "and they made"),
    "شكور": ("shakūr", "Maha Mensyukuri", "Most Appreciative"),
    "بسلطن": ("bi-sulṭān", "dengan kekuasaan/bukti", "with authority"),
    "هدينا": ("hadaynā", "Kami beri petunjuk", "We guided"),
    "ضرب": ("ḍaraba", "membuat perumpamaan", "struck; set forth"),
    "نعمت": ("ni'mat", "nikmat", "favor"),
    "كفار": ("kuffār", "orang-orang kafir", "disbelievers"),
    "اجعل": ("aj'al", "aku jadikan", "I make"),
    "ليوم": ("li-yawm", "bagi hari", "for the day"),
    "بقدر": ("bi-qadar", "dengan ukuran", "in due measure"),
    "يبعثون": ("yub'athūn", "mereka dibangkitkan", "they are raised"),
    "وعيون": ("wa-'uyūn", "dan mata air", "and springs"),
    "ومنها": ("wa-minhā", "dan darinya", "and from it"),
    "يخافون": ("yakhāfūn", "mereka takut", "they fear"),
    "نصيبا": ("naṣīban", "bagian", "a share"),
    "وجههٗ": ("wajhahū", "wajahnya", "his face"),
    "غضب": ("ghaḍab", "kemurkaan", "anger"),
    "رزقكم": ("rizqukum", "rezeki kalian", "your provision"),
    "يك": ("yaka", "menjadi", "be"),
    "وابن": ("wa-bni", "dan anak", "and son"),
    "مال": ("māl", "harta", "wealth"),
    "لبثتم": ("labithtum", "kalian tinggal", "you stayed"),
    "يهد": ("yahdī", "memberi petunjuk", "guides"),
    "ونذيرا": ("wa-nadhīran", "dan pemberi peringatan", "and a warner"),
    "مائه": ("mi'ah", "seratus", "a hundred"),
    "تطع": ("tuṭi'", "engkau menaati", "you obey"),
    "خلقنكم": ("khalaqnākum", "Kami ciptakan kalian", "We created you"),
    "صبرا": ("ṣabran", "kesabaran", "patience"),
    "امري": ("amrī", "urusanku", "my affair"),
    "لقا": ("liqā'", "pertemuan", "meeting"),
    "نبيا": ("nabiyyan", "seorang nabi", "a prophet"),
    "عنك": ("'anka", "darimu", "from you"),
    "ووهبنا": ("wa-wahabnā", "dan Kami anugerahkan", "and We granted"),
    "ونذر": ("wa-nudhir", "dan aku memperingatkan", "and I warn"),
    "وكنتم": ("wa-kuntum", "dan kalian adalah", "and you were"),
    "ليله": ("laylah", "malam", "night"),
    "وقولوا": ("wa-qūlū", "dan katakanlah", "and say"),
    "الف": ("alf", "seribu", "a thousand"),
    "يدخل": ("yadkhul", "masuk", "enters"),
    "اليهود": ("al-yahūd", "orang-orang Yahudi", "the Jews"),
    "واسع": ("wāsi'", "Maha Luas", "All-Encompassing"),

    "اثما": ["ithmā", "dosa", "sin"],
    "اخرين": ["ākharīn", "yang lain-lain", "others"],
    "اقسم": ["aqsama", "dia bersumpah", "he swore"],
    "الاثم": ["al-ithm", "dosa", "the sin"],
    "الخيرت": ["al-khayrāt", "kebaikan-kebaikan", "good deeds"],
    "السعير": ["as-sa'īr", "api yang menyala-nyala", "the blazing fire"],
    "العلي": ["al-'alī", "Yang Maha Tinggi", "the Most High"],
    "القتال": ["al-qitāl", "peperangan", "fighting"],
    "اولو": ["ulū", "pemilik; orang-orang yang", "those with"],
    "باموالهم": ["bi-amwālihim", "dengan harta mereka", "with their wealth"],
    "تاكلوا": ["ta'kulū", "kalian makan", "you eat"],
    "تتبع": ["tattabi'", "engkau mengikuti", "you follow"],
    "تتبعوا": ["tattabi'ū", "kalian mengikuti", "you follow"],
    "تحشرون": ["tuḥsharūn", "kalian dikumpulkan", "you are gathered"],
    "ترحمون": ["turḥamūn", "kalian dirahmati", "you receive mercy"],
    "تنفقوا": ["tunfiqū", "kalian berinfak", "you spend"],
    "ذكروا": ["dhakarū", "mereka menyebut", "they mentioned"],
    "طين": ["ṭīn", "tanah liat", "clay"],
    "عليهما": ["'alayhimā", "atas keduanya", "upon both"],
    "فيهما": ["fīhimā", "di dalam keduanya", "in both"],
    "كفرين": ["kāfirīn", "orang-orang kafir", "disbelievers"],
    "نفسهٗ": ["nafsahū", "dirinya", "himself"],
    "نور": ["nūr", "cahaya", "light"],
    "واصلح": ["wa-aṣliḥ", "dan perbaikilah", "and set things right"],
    "والانجيل": ["wa-l-injīl", "dan Injil", "and the Gospel"],
    "والكتب": ["wa-l-kutub", "dan kitab-kitab", "and the Books"],
}
